### ISSUE TITLE
Problem with static[int] in return type

### ISSUE THREAD

**Issue by Henry** [nim-lang/Nim#3309] opened 2015-09-08 20:33 UTC
```
type
  OdArray*[As: static[int], T] = object
    l: int

proc initOdArray*[As: static[int], T](len: int): OdArray[As, T] =
  result.l = len

var test = initOdArray[10, int](100)
```

generates `Error: type expected`

See also forum discussion http://forum.nim-lang.org/t/1618

**Comment by gmpreussner** [comment] 2016-03-02 13:47
This is still broken. Workaround:

```nim
type
  OdArray*[As: static[int], T] = object
    l: int

proc initOdArray*(As: static[int], T: typedesc, len: int): OdArray[As, T] =
  result.l = len

var test = initOdArray(10, int, 100)
```

**Comment by gmpreussner** [comment] 2016-03-02 14:02
The workaround does not work if the generic parameters need to be pass through to other types/procs/constructors:

```nim
type
  Foo[N: static[int], T] = object
    a: array[N, T]

  Bar[N: static[int], T] = object
    f: ref Foo[N, T]

proc initBar(N: static[int], T: typedesc): Bar[N, T] =
  result.f = Foo[N, T]()    ## Error: object constructor needs an object type

when isMainModule:
  var f = initBar(16, int)
```

**Comment by mratsim** [comment] 2017-03-31 15:11
Seems like a duplicate of https://github.com/nim-lang/Nim/issues/1017

**Closed** 2017-06-20 09:29 UTC
Labels: Static[T]
