### ISSUE TITLE
--out and --nimcache wrong paths

### ISSUE THREAD

**Issue by yglukhov** [nim-lang/Nim#3871] opened 2016-02-16 09:55 UTC
```sh
cd NIMBLE_PROJ_DIR
nim c -r -o:nimble123 src/nimble
...
Hint: operation successful (93010 lines compiled; 4.572 sec total; 334.342MB; Debug Build) [SuccessX]
sh: ./nimble123: No such file or directory
Error: execution of an external program failed: './nimble123 '
```
nimble123 is created in src dir instead of current dir.

**Comment by dom96** [comment] 2016-02-16 10:35
Possible duplicate of (or just related to) #3358

**Closed** 2016-02-16 18:42 UTC
Labels: Path Handling
