### ISSUE TITLE
"ordinal type expected" caused by default value for static[set[T]]

### ISSUE THREAD

**Issue by GULPF** [nim-lang/Nim#8448] opened 2018-07-26 05:11 UTC
```nim
proc foo*(y: static[set[bool]] = { true }) = discard # Error: ordinal type expected
foo()
```

**Comment by mratsim** [comment] 2018-07-26 10:40
Seems like duplicate of https://github.com/nim-lang/Nim/issues/7546

**Comment by bung87** [comment] 2022-12-23 05:18
it compiles fine in 1.6.10 https://play.nim-lang.org/#ix=4jkh

**Closed** 2022-12-23 05:53 UTC
Labels: Static[T]
