### ISSUE TITLE
Redefinition error hinges on first characters of identifiers

### ISSUE THREAD

**Issue by LChris314** [nim-lang/Nim#6370] opened 2017-09-12 13:26 UTC
This
```nim
type
  Color = enum BLUE, RED
  Red = object
```
triggers `Error: redefinition of 'RED'`.
But both
```nim
type
  Color = enum BLUE, RED
  red = object
```
and
```nim
type
  Color = enum BLUE, RED
  rED = object
```
compile.

**Comment by andreaferretti** [comment] 2017-09-12 13:44
This actually applies to all identifiers in Nim: they are case insensitive except for the first letter https://nim-lang.org/docs/manual.html#lexical-analysis-identifier-equality

**Comment by GULPF** [comment] 2017-09-12 13:44
This is expected behavior due to case insensitive identifiers. `Red` and `RED` always refer to the same identifier. See https://nim-lang.org/docs/manual.html#lexical-analysis-identifier-equality.

For enums, the naming convention is to either use a prefix (e.g `clBlue`, `clRed`), or mark the enum as pure, which means that the values can only be referred to like `Color.blue`, `Color.red` (https://nim-lang.org/docs/manual.html#types-enumeration-types).

**Comment by LChris314** [comment] 2017-09-12 14:09
Oh wow I never read that part of the manual, what a surprise. Sorry for taking up your time. Also should I close the issue myself? I'm not used to how github issues usually operate.

**Comment by Yardanico** [comment] 2017-09-12 14:38
@LChris314 yeah, you can close it yourself

**Closed** 2017-09-12 15:24 UTC
