### ISSUE TITLE
[Request] Add high(uint) and low(uint)

### ISSUE THREAD

**Issue by kaushalmodi** [nim-lang/Nim#11557] opened 2019-06-21 12:08 UTC
The `low(uint)` and `high(uint)` would be helpful just as `low(int)` and `high(int)` are.

This came up while discussing https://github.com/nim-lang/Nim/issues/11551 and https://github.com/nim-lang/Nim/issues/11552 on IRC: https://irclogs.nim-lang.org/21-06-2019.html#11:48:42.

---

`high(uint)` was easily derived using https://play.nim-lang.org/index.html#ix=1MnO.

```nim
const
  highUint = high(int).uint + high(int).uint + 1
echo highUint  # -> 18446744073709551615
```

/cc @narimiran

**Comment by narimiran** [comment] 2019-06-21 12:14
Duplicate of:

* https://github.com/nim-lang/Nim/issues/725
* https://github.com/nim-lang/Nim/issues/6620

**Closed by narimiran** 2019-06-21 12:14 UTC
