### ISSUE TITLE
[times.nim] LocalTime timezone offset incorrect when in DST

### ISSUE THREAD

**Issue by jonathonf** [nim-lang/Nim#3199] opened 2015-08-09 21:13 UTC
## Summary

There is an inconsistency between timezone name and offset provided by `getLocalTime()`. While the timezone name is adjusted for DST, the offset is not. This is the case for all variants of `format("z")`.

See also #3200.
## nim test code

``` nim
import times

echo getTzname()
echo getTime().getLocalTime.format("ZZZ")
echo getTime().getLocalTime.format("zzz")
```
## Output, BST

http://www.timeanddate.com/time/zones/bst

| Code | Actual | Expected |
| --- | --- | --- |
| `getTzname()` | (nonDST: GMT, DST: BST) | (nonDST: GMT, DST: BST) |
| `getTime().getLocalTime.format("ZZZ")` | BST | BST |
| `getTime().getLocalTime.format("zzz")` | 00:00 | +01:00 |
## Output, EDT

http://www.timeanddate.com/time/zones/edt

| Code | Actual | Expected |
| --- | --- | --- |
| `getTzname()` | (nonDST: EST, DST: EDT) | (nonDST: EST, DST: EDT) |
| `getTime().getLocalTime.format("ZZZ")` | EDT | EDT |
| `getTime().getLocalTime.format("zzz")` | 05:00 | -04:00 |

**Comment by GULPF** [comment] 2017-10-03 14:33
Looks like this is fixed. BST now gives +01:00 and EDT -04:00.

**Comment by andreaferretti** [comment] 2017-10-03 15:36
I am not sure how to test this (how to temporarily change the timezone on the command line). If it is confirmed to be fixed, I can close it

**Comment by GULPF** [comment] 2017-10-03 17:59
On linux you can set the `TZ` environment variable to the timezone. To find out which value you should use you can run `tzselect`. E.g for testing with BST and EDT (only works right now since DST is currently active in these time zones, I don't know how to force BST/EDT):
```
TZ=America/New_York ./testprogram
TZ=Europe/London ./testprogram 
```

**Closed** 2017-10-09 23:05 UTC
Labels: Medium Priority, Stdlib, Times
