### ISSUE TITLE
Windows 10 "threat" Win32/Uwamson.A!ml "potentially unwanted behavior" on finish.exe

### ISSUE THREAD

**Issue by terremoth** [nim-lang/Nim#19340] opened 2022-01-07 21:54 UTC
Probably there is a way to fix that in the binary, so it won't warn people

![image](https://user-images.githubusercontent.com/11032344/148612056-76f9f9a1-d475-4e28-98ba-f87268e89b1a.png)

**Comment by ghost** [comment] 2022-01-07 22:02
Sorry to hear that, but it's already being discussed, so closing as a duplicate of https://github.com/nim-lang/Nim/issues/17820

**Closed as completed by ghost** 2022-01-07 22:02 UTC

**Comment by terremoth** [comment] 2022-01-07 22:08
@Yardanico sorry, no problem, I just felt the responsability to report. Hope you guys can solve. Thanks, ☺
