### ISSUE TITLE
5 bugs with importcpp exceptions

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/Nim#14369] opened 2020-05-16 12:41 UTC
* this shows 5 bugs with importcpp exceptions
* I finally got the last example to work, we should add it to manual to replace / enhance https://nim-lang.github.io/Nim/manual.html#exception-handling-imported-exceptions as it's more comprehensive (otherwise requires a lot of trial+error)

### Examples
```nim
when defined case1: # D20200516T052028:here
  #[
  nim default constructor for importcpp type doesn't work
  error: no member named 'm_type' in 'std::exception'
  ]#
  type
    std_exception {.importcpp: "std::exception", header: "<exception>".} = object of RootObj
    runtime_error {.importcpp: "std::runtime_error", header: "<stdexcept>".} = object of std_exception
  proc initStdException(): std_exception {.importcpp: "std::exception()", constructor.}

  try: raise initStdException() # works
  except std_exception as ex: discard

  try: raise std_exception() # bug; note that `std_exception()` (instead of initStdException()) was example given in https://nim-lang.github.io/Nim/manual.html#exception-handling-imported-exceptions (but without ` of RootObj`)
  except std_exception as ex: discard

when defined case2: # D20200516T044839:here gitissue
  #[
  dead code elimination false positive: removed a header causes codegen error
  error: no member named 'runtime_error' in namespace 'std'
  ]#
  type RuntimeError {.importcpp: "std::runtime_error", header: "<stdexcept>".} = object
  proc initRuntimeError(a: cstring): RuntimeError {.importcpp: "std::runtime_error(@)", constructor.}
  proc fun() =
    var a = initRuntimeError("foo")
  # fun() # uncomment makes bug disappear
  try: raise initRuntimeError("foo2")
  except: discard

when defined case3a: # D20200516T045925:here gitissue
  #[
  `except Exception` doesn't catch C++ exceptions; do we need a common root?
  Error: unhandled cpp exception: std::exception
  ]#
  type
    std_exception {.importcpp: "std::exception", header: "<exception>".} = object
  proc what(s: std_exception): cstring {.importcpp: "((char *)#.what())".}
  try: raise std_exception()
  except Exception as e: # bug
  # except Exception: # ditto
    discard

when defined case3b: # D20200516T052550:here gitissue
  # getCurrentException buggy with importcpp exceptions
  type
    std_exception {.importcpp: "std::exception", header: "<exception>".} = object
  try: raise std_exception()
  except: # works
    let e = getCurrentException() # works but should it? isn't type wrong (ref Exception instead of std_exception)
    doAssert e != nil # fails

when defined case3c: # D20200516T045949:here gitissue
  #[
   error: no matching constructor for initialization of 'std::runtime_error'
N_LIB_PRIVATE std::runtime_error a__u49bz4qduTkSaq6kyRgi9cbA;
  ]#
  type RuntimeError {.importcpp: "std::runtime_error", header: "<stdexcept>".} = object
  proc initRuntimeError(a: cstring): RuntimeError {.importcpp: "std::runtime_error(@)", constructor.}

  proc fun() =
    var a = initRuntimeError("foo") # ok
  # var a = initRuntimeError("foo") # bug
  # var a: RuntimeError # bug
  var a {.noinit.}: RuntimeError # bug

when defined case4: # D20200516T050951:here gitissue
  #[
  example that works
  ]#
  type
    std_exception {.importcpp: "std::exception", header: "<exception>".} = object of RootObj
    RuntimeError {.importcpp: "std::runtime_error", header: "<stdexcept>".} = object of std_exception
  proc what(s: std_exception): cstring {.importcpp: "((char *)#.what())".}
  proc initRuntimeError(a: cstring): RuntimeError {.importcpp: "std::runtime_error(@)", constructor.}
  proc initStdException(): std_exception {.importcpp: "std::exception()", constructor.}

  proc fun() =
    let a = initRuntimeError("foo")
    doAssert $a.what == "foo"
    var b: cstring
    try: raise initRuntimeError("foo2")
    except std_exception as e:
      b = e.what()
    doAssert $b == "foo2"

    try: raise initStdException()
    except std_exception as ex: discard

    try: raise initRuntimeError("foo3")
    except RuntimeError as e:
      b = e.what()
    except std_exception as e:
      doAssert false
    doAssert $b == "foo3"

  fun()
```

### Current Output
these fail
nim r -b:cpp -d:case1 $timn_D/tests/nim/all/t10759.nim
nim r -b:cpp -d:case2 $timn_D/tests/nim/all/t10759.nim
nim r -b:cpp -d:case3a $timn_D/tests/nim/all/t10759.nim
nim r -b:cpp -d:case3b $timn_D/tests/nim/all/t10759.nim
nim r -b:cpp -d:case3c $timn_D/tests/nim/all/t10759.nim

this works
nim r -b:cpp -d:case4 $timn_D/tests/nim/all/t10759.nim

### Expected Output
all should work

### Additional Information

* c777f2fb608e1f42daf31d314dda0050f6354acd 1.3.5
* somewhat related: https://github.com/nim-lang/RFCs/issues/89#issuecomment-418408142

**Comment by cooldome** [comment] 2020-05-16 14:31
This line in wrong in your example:
```nim
std_exception {.importcpp: "std::exception", header: "<exception>".} = object of RootObj
```
std_exception doesn't inherit from RootObj, it must be:
```nim
std_exception {.importcpp: "std::exception", header: "<exception>".}  = objet
```

[EDIT from timothee: that doesnt' work but your next post works, using inheritable]

**Comment by cooldome** [comment] 2020-05-16 16:55
case1 not bug, should be written in the following way
```nim
type
    std_exception {.importcpp: "std::exception", header: "<exception>", inheritable.} = object
    runtime_error {.importcpp: "std::runtime_error", header: "<stdexcept>".} = object of std_exception

try: raise std_exception() 
except std_exception as ex: discard
```

**Comment by cooldome** [comment] 2020-05-16 17:45
case 3a: not a bug works as expected. It is simply impossible for Nim Exception and C++ exceptions to have common root as cpp exceptions do not have root, any type can be thrown in cpp including `int`, `char`, `void *`.
case 3b:  getCurrentException() is for Nim Exceptions only, possibly it should be better clarified the doc. 

case3c: misuse of imported object. Cpp object is not default constructable, correct usage of imported object in the reposibility of the user. This can somewhat help:
```nim
  type RuntimeError {.requiresInit, importcpp: "std::runtime_error", header: "<stdexcept>".} = object
```

**Comment by cooldome** [comment] 2020-05-16 17:45
Summary: case2 the only bug I can confirm

**Comment by timotheecour** [comment] 2020-05-17 00:00
https://github.com/nim-lang/Nim/issues/14369#issuecomment-629655041
> This line in wrong in your example:
> std_exception doesn't inherit from RootObj, it must be: [...]

that doesn't work, you'll get: `Error: inheritance only works with non-final objects; for std_exception to be inheritable it must be 'object of RootObj' instead of 'object'`

**Comment by timotheecour** [comment] 2020-05-17 02:02
great, I forgot about inheritable thanks!!

> case 3b: getCurrentException() is for Nim Exceptions only, possibly it should be better clarified the doc.

ideally this would give CT errors in some contexts (see https://github.com/nim-lang/RFCs/issues/89#issuecomment-629643195)

maybe we could still have `getCurrentExceptionMsg()` that would work with nim exceptions + C++ exceptions inheriting from std::exception (via `what`) ?

> This can somewhat help:

`requiresInit` doesn't change anything somehow

> case3c: misuse of imported object.

but it's the same problem with this at module level:
```nim
var a = initRuntimeError("foo") # bug
```

here's a reduced example without exceptions:
```nim
{.emit:"""
#include <stdio.h>
struct A{
  A(int a){ printf("ctor\n"); }
  ~A(){ printf("dtor\n"); }
};
""".}
type A {.importcpp: "A".} = object
proc initA(a: cint): A {.importcpp: "A(@)", constructor.}
var a = initA(12)
```

```
@mt10759e.nim.cpp:44:17: error: no matching constructor for initialization of 'A'
```

cgen should instead use implicit pointers for global importcpp variables:

instead of generating:
```c++
/* section: NIM_merge_VARS */
N_LIB_PRIVATE A a__kEcttXN5qSDQ71dflcCVww;
N_LIB_PRIVATE N_NIMCALL(void, NimMainModule)(void) {{
  a__kEcttXN5qSDQ71dflcCVww = A(((int) 12));
}}
```
the compiler should generate:
```c++
/* section: NIM_merge_VARS */
N_LIB_PRIVATE A* a__kEcttXN5qSDQ71dflcCVww;
N_LIB_PRIVATE N_NIMCALL(void, NimMainModule)(void) {{
  *a__kEcttXN5qSDQ71dflcCVww = A(((int) 12));
}}
```

also, we should update manual discussing foreign exceptions with a more comprehensive example (eg like my case4 but fixed to use inheritable)

**Comment by cooldome** [comment] 2020-05-17 20:53
Global cpp imported variables without default constructor is the bug. IMO. compiler should take advantage of requiresInit flag for global variables that should be provided. I suggest you submit it as separate issue since not exception related. I plan to close this issue as everything else is documentation related.

**Comment by cooldome** [comment] 2020-05-17 21:02
getCurrentException() can be used outside of try/except blocks and it is useful outside of these blocks.
No changes on this front, it can't be CT error.

**Closed as completed** 2020-05-18 07:38 UTC
Labels: C++ Code Generation
