### ISSUE TITLE
js: uint64.high == -1

### ISSUE THREAD

**Issue by juancarlospaco** [nim-lang/Nim#16411] opened 2020-12-20 09:29 UTC
# JavaScript

```nim
echo uint64.high
```

# Current Output

```nim
-1
```

# Expected Output

```nim
18446744073709551615
```

# Additional Information

```console
$ nim --eval:"echo uint64.high"
18446744073709551615

$ nim js -r example.nim
-1

$
```

# System Information

<details>

```json

{
  "compiled": "2020-04-12T10:45:59",
  "NimVersion": "1.5.1",
  "hostCPU": "amd64",
  "hostOS": "linux",
  "cpuEndian": "littleEndian",
  "getTempDir": "/tmp/",
  "now": "2020-12-20T06:19:50-03:00",
  "getCurrentEncoding": "UTF-8",
  "getFreeMem": 397312,
  "getTotalMem": 528384,
  "getOccupiedMem": 72496,
  "countProcessors": 6,
  "arch": "x86_64",
  "FileSystemCaseSensitive": true,
  "nimcacheDir": "",
  "ccompilerPath": "",
  "currentCompilerExe": "/home/juan/.choosenim/toolchains/nim-1.5.1/bin/nim",
  "nimpretty": "0.2",
  "nimble": "nimble v0.12.0 compiled at 2020-12-17 00:46:16\ngit hash: couldn't determine git hash",
  "nimgrep": "1.6.0",
  "nimsuggest": "Nim Compiler Version 1.5.1 [Linux: amd64]\nCompiled at 2020-12-17\nCopyright (c) 2006-2020 by Andreas Rumpf\n\ngit hash: 3b963a8150e3c541859931a1ef9ecb338e46907f\nactive boot switches: -d:release -d:danger --gc:markAndSweep",
  "choosenim": "choosenim v0.7.4 (2020-10-20 17:30:52) [linux/amd64]",
  "gcc": "gcc (GCC) 10.2.0",
  "clang": "clang version 11.0.0",
  "git": "2.29.2",
  "node": "v15.4.0",
  "python": "3.9.1",
  "ssd": true
}
```

</details>

# Proposed Labels

```csv
javascript
```

**Comment by metagn** [comment] 2020-12-20 11:19
duplicate of #4714

**Comment by timotheecour** [comment] 2021-07-08 05:43
I'm re-opening because I think we can fix this issue (which is pretty blatant and affects things like std/random, refs disabled js tests in https://github.com/nim-lang/Nim/pull/18456) without fixing the much harder https://github.com/nim-lang/Nim/issues/4714

**Closed as completed** 2023-04-11 19:20 UTC
Labels: Javascript
