### ISSUE TITLE
IOError while compiling on windows

### ISSUE THREAD

**Issue by abijahm** [nim-lang/Nim#7389] opened 2018-03-21 10:38 UTC
I get this error when compiling on windows
```log
Error: unhandled exception: Unknown IO Error [IOError]
```
it happens randomly on any program i try to compile
```
Nim Compiler Version 0.18.0 [Windows: amd64]
Copyright (c) 2006-2018 by Andreas Rumpf

git hash: 5ee9e86c87d831d32441db658046fc989a197ac9
active boot switches: -d:release
```

**Comment by Yardanico** [comment] 2018-03-21 10:59
Closing as a duplicate of https://github.com/nim-lang/Nim/issues/7111

**Closed by Yardanico** 2018-03-21 10:59 UTC
