### ISSUE TITLE
Problem with .isNil for string inside of macro

### ISSUE THREAD

**Issue by StefanSalewski** [nim-lang/Nim#8520] opened 2018-08-03 05:10 UTC
https://forum.nim-lang.org/t/4096

I am still not sure if it is a bug -- the Hlaaftana reply was not that helpful.

**Comment by dom96** [comment] 2018-08-03 14:00
It will be removed AFAIK. But I wouldn't be surprised if we keep it for backwards compat so I guess the macro problem should be fixed.

**Comment by jangko** [comment] 2018-08-05 00:59
duplicate of #7859? looks similar

**Comment by dom96** [comment] 2018-08-05 12:55
Yeah, looks like it.

**Closed by dom96** 2018-08-05 12:55 UTC
Labels: VM
