### ISSUE TITLE
Strange error messages including "andreasrumpf-mac/..."

### ISSUE THREAD

**Issue by mratsim** [nim-lang/Nim#9489] opened 2018-10-24 10:20 UTC
Here is a collection of error messages I got while playing with `setupForeignThreadGc`

I can get the expected ```Error: setupForeignThreadGc is available only when ``--threads:on`` and ``--tlsEmulation:off`` are used```

but also: ```Error: unhandled exception: /Users/andreasrumpf-mac/projects/build_nim_xz/build/Nim/compiler/suggest.nim(462, 12) `result == nil or result.kind == nkPragma`  [AssertionError]```

and the non-helpful ```# Error: usage of 'foo2' is a user-defined error```

```Nim
proc foo(x: var int) =
  setupForeignThreadGc()
  x += 1

template bar() =
  setupForeignThreadGc()

var x = 0

# bar()  # Error: setupForeignThreadGc is available only when ``--threads:on`` and ``--tlsEmulation:off`` are used
# foo(x) # Error: unhandled exception: /Users/andreasrumpf-mac/projects/build_nim_xz/build/Nim/compiler/suggest.nim(462, 12) `result == nil or result.kind == nkPragma`  [AssertionError]


proc foo2(x: var int) {.noInline.}= # notice the noinline
  setupForeignThreadGc()
  x += 1

foo2(x) # Error: usage of 'foo2' is a user-defined error
```

**Comment by timotheecour** [comment] 2018-10-24 21:00
well my original plan in https://github.com/nim-lang/Nim/pull/8466 was to allow user to choose whether to use rel or abs path; and you suggested [here](https://github.com/nim-lang/Nim/pull/8466#issuecomment-408781276) the following:
> The proper fix is to use toFullPath here. I think.

and I think it's a lesser evil to have `doAssert` return an absolute path as you had suggested in that comment (before that PR `--listFullPaths` would not be honored; and abs paths makes things easier to debug where things come from, incuding in this odd case)

what's happening here is uncovering another bug, which needs to be investigated more;

for now, here's the stacktrace with debug info:
```
/Users/timothee/git_clone/nim/Nim/compiler/nim.nim(108) nim
/Users/timothee/git_clone/nim/Nim/compiler/nim.nim(72) handleCmdLine
/Users/timothee/git_clone/nim/Nim/compiler/cmdlinehelper.nim(91) loadConfigsAndRunMainCommand
/Users/timothee/git_clone/nim/Nim/compiler/main.nim(163) mainCommand
/Users/timothee/git_clone/nim/Nim/compiler/main.nim(74) commandCompileToC
/Users/timothee/git_clone/nim/Nim/compiler/modules.nim(126) compileProject
/Users/timothee/git_clone/nim/Nim/compiler/modules.nim(71) compileModule
/Users/timothee/git_clone/nim/Nim/compiler/passes.nim(194) processModule
/Users/timothee/git_clone/nim/Nim/compiler/passes.nim(86) processTopLevelStmt
/Users/timothee/git_clone/nim/Nim/compiler/sem.nim(600) myProcess
/Users/timothee/git_clone/nim/Nim/compiler/sem.nim(568) semStmtAndGenerateGenerics
/Users/timothee/git_clone/nim/Nim/compiler/semstmts.nim(1967) semStmt
/Users/timothee/git_clone/nim/Nim/compiler/semexprs.nim(913) semExprNoType
/Users/timothee/git_clone/nim/Nim/compiler/semexprs.nim(2531) semExpr
/Users/timothee/git_clone/nim/Nim/compiler/semstmts.nim(1908) semStmtList
/Users/timothee/git_clone/nim/Nim/compiler/semexprs.nim(2438) semExpr
/Users/timothee/git_clone/nim/Nim/compiler/semexprs.nim(894) semDirectOp
/Users/timothee/git_clone/nim/Nim/compiler/semexprs.nim(744) semOverloadedCallAnalyseEffects
/Users/timothee/git_clone/nim/Nim/compiler/semcall.nim(506) semOverloadedCall
/Users/timothee/git_clone/nim/Nim/compiler/semcall.nim(452) semResolvedCall
/Users/timothee/git_clone/nim/Nim/compiler/suggest.nim(491) markUsed
/Users/timothee/git_clone/nim/Nim/compiler/suggest.nim(475) userError
/Users/timothee/.choosenim/toolchains/nim-0.19.0/lib/suggest.nim(462) extractPragma
/Users/timothee/.choosenim/toolchains/nim-0.19.0/lib/system.nim(3790) failedAssertImpl
/Users/timothee/.choosenim/toolchains/nim-0.19.0/lib/system.nim(3783) raiseAssert
/Users/timothee/.choosenim/toolchains/nim-0.19.0/lib/system.nim(2830) sysFatal
Error: unhandled exception: /Users/timothee/git_clone/nim/Nim/compiler/suggest.nim(462, 12) `result == nil or result.kind == nkPragma`  [AssertionError]
```

2 things to note:

* /Users/timothee/.choosenim/toolchains/nim-0.19.0/lib/suggest.nim doesn't exist; the file is under:
  /Users/timothee/.choosenim/toolchains/nim-0.19.0/compiler/suggest.nim

* I'm guessing araq had compiled nim in /Users/andreasrumpf-mac/projects/build_nim_xz/build/Nim/ and that path got baked in the binary as I'm showing below:

```
strings /Users/timothee/.choosenim/toolchains/nim-0.19.0/bin/nim | grep andreasrumpf
@/Users/andreasrumpf-mac/projects/build_nim_xz/build/Nim/compiler/commands.nim(732, 13) `
@/Users/andreasrumpf-mac/projects/build_nim_xz/build/Nim/compiler/suggest.nim(462, 12) `result == nil or result.kind == nkPragma`
@/Users/andreasrumpf-mac/projects/nim/lib/packages/docutils/rstgen.nim(1084, 14) `false` renderRstToOut
```
etc...

in an ideal world, there'd be a way to specify whether doAssert/assert returns an absolute or relative path (presumably depending on `--listFullPaths`); and compiler releases would be released with `--listFullPaths:off`

**Comment by timotheecour** [comment] 2018-10-24 21:36
so in conclusion it depends on your PATH, eg if which nim points to `/Users/timothee/.nimble//bin/nim`, it'll depend on what you set for choosenim; if choosenim is set to `0.19.0` (path of /Users/timothee/.choosenim/toolchains/nim-0.19.0), it'll be using the binary distributed (instead of source distributed) version of nim which has (currently) absolute paths baked in.

* either we make choosenim use source distribution (instead of binary)
* or we change the build process for our binary distribution, using `--listFullPaths:off` (and make it generate relative paths in lineInfoObj when `--listFullPaths:off` is set)

**Comment by skilchen** [comment] 2018-10-24 22:45
this is the same problem as reported in issue #9358, quote @araq from there:
>That's a compiler bug, the .error statement must not be treated as an .error proc annotation.

**Comment by timotheecour** [comment] 2018-10-25 00:01
it's related but I wouldn't call it a duplicate issue, there are other issues being raised/diagnosed here

**Comment by skilchen** [comment] 2018-10-27 05:43
I think this issue is also fixed via https://github.com/nim-lang/Nim/commit/0c3e6735ac10c5ea77d0d63899528a819683431f

**Comment by narimiran** [comment] 2019-01-30 14:23
I cannot reproduce this, so it might be already fixed, as @skilchen mentions.

If this isn't the case, reopen it.

**Closed by narimiran** 2019-01-30 14:23 UTC
Labels: Error messages
