### ISSUE TITLE
[dynlib] Nim doesn't use default dynamic library loader, we need a replacement for standard tools, eg: ldd, otool, LD_PRELOAD, rpath

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/Nim#9203] opened 2018-10-05 06:00 UTC
* what were the reasons why Nim chose to not use the default (platform specific) dynamic library loader?
was that to ease portability and provide same interface across platforms (especially on windows)?
was that to allow more flexibility?
IIRC there was a forum post about it but couldn't find it because of https://github.com/nim-lang/nimforum/issues/180

* in any case, maybe these are valid reasons, but because of that, we can't use existing infrastructure built around default dynamic library loader, eg:

- [ ] `otool -L` (OSX) or `ldd` (linux) are very useful to list the library dependencies of a binary/shared library, eg:
```
otool -L someBinary
/pathto/app:
        /System/Library/Frameworks/OpenGL.framework/Versions/A/OpenGL (compatibility version 1.0.0, current version 1.0.0)
        /Users/timothee/homebrew/opt/cairo/lib/libcairo.2.dylib (compatibility version 11403.0.0, current version 11403.12.0)
        /Users/timothee/homebrew/opt/ffmpeg/lib/libavutil.56.dylib (compatibility version 56.0.0, current version 56.14.100)
        /Users/timothee/homebrew/opt/ffmpeg/lib/libavfilter.7.dylib (compatibility version 7.0.0, current version 7.16.100)
        ...
        /usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 400.9.0)
        /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1252.50.4)
```

this won't work in a Nim binary as it'll only list `/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1252.50.4)` , omitting all the other libraries that are needed to run a Nim program (mentioned via `dynlib` eg:
`proc myExtFunc*() {.importc: "myExtFunc", dynlib: "libfoo.dylib", cdecl.}`

we need a replacement for that in Nim: a Nim program (say `nimldd`) that can obtain the same information from a Nim binary/shared library.
The information could be saved in a file section of the Nim binary/shared library.

- [ ] LD_PRELOAD
see https://rafalcieslak.wordpress.com/2013/04/02/dynamic-linker-tricks-using-ld_preload-to-cheat-inject-features-and-investigate-programs/

- [ ] rpath
eg, allows specifying library paths that are relative to a library search path; or other similar features (eg relative to a binary)

## note
in discussion above I'm referring to fact that in Nim, instead of `-lfoo` to link against `libfoo`, Nim uses `{.dynlib:  "libfoo.dylib"}` which causes genereted C code to call `dlopen` at program start

**Comment by alaviss** [comment] 2018-10-05 07:31
You can just use `--dynlibOverrideAll` then pass the link flags yourself. I don't see why nim have to provides these information.

See also https://github.com/nim-lang/Nim/issues/8655

**Comment by Araq** [comment] 2018-10-09 13:55
Duplicate of #8655 and all of your tooling is already broken anyway, ``dlopen`` is the standard mechanism used by all dynamic languages out there.

**Closed by Araq** 2018-10-09 13:55 UTC

**Comment by timotheecour** [comment] 2019-01-12 08:33
EDIT: was moved to https://github.com/nim-lang/RFCs/issues/58
