### ISSUE TITLE
nim jsondoc -o:doc.json filename.nim fails when sequences without a type are used

### ISSUE THREAD

**Issue by faulander** [nim-lang/Nim#14066] opened 2020-04-22 09:55 UTC
Running "nim jsondoc -o:doc.json filename.nim" results in:
Error: unhandled exception: index out of bounds, the container is empty [IndexError]

### Example
```nim
proc hashesToStr(hashes: seq): string = 
  var h:string
  if hashes.len == 0:
      result = ""
  else:
    for hash in hashes:
      h = h & hash & "|"
    h = h[0 .. len(h)-2] # cuts of the last |
    result = h
```

### Additional Information
Already discussed and found a workaround with PMunch on IRC.

```
$ nim -v
Nim Compiler Version 1.2.0
```

**Comment by metagn** [comment] 2020-04-22 10:06
Unrelated to the issue, and not a workaround, can be marked as offtopic, just an FYI: instead of doing `str = str & ...` (creates a new string) you should do `str &= ...` which is actually an alias for `str.add(...)` (modifies the existing string), and instead of doing `str = str[0.. newlen - 1]` (creates a copy) you should do `str.setLen(newlen)` (doesn't create a copy).

**Comment by PMunch** [comment] 2020-04-22 10:33
The issue is that it assumes that `seq` in the signature has a type and fails when it doesn't. Should be a simple fix in `compiler/types.nim:598` and it should be fixed similarly for the other types with the same behaviour. I'll fix it, just wanted to have an issue so I didn't forget.

By the way, what is the `tyOpt` type that can be found next to `seq` in the code?

**Comment by Araq** [comment] 2020-04-27 08:39
> By the way, what is the tyOpt type that can be found next to seq in the code?

It is a builtin "opt[T]" type, it's dead code.

**Comment by PMunch** [comment] 2020-04-27 11:42
Right, should I just make that into an `assert false` or something then?

**Closed as completed** 2020-04-27 16:43 UTC
