### ISSUE TITLE
`seq`s are not properly updated in loop with ARC/ORC

### ISSUE THREAD

**Issue by konsumlamm** [nim-lang/Nim#19457] opened 2022-01-26 10:14 UTC
### Example
This is the standard euclidean algorithm for calculating the GCD, but stores the values in single-element `seq`s.
```nim
proc gcd(x, y: seq[int]): seq[int] =
    var
      a = x
      b = y
    while b[0] > 0:
      let c = @[a[0] mod b[0]]
      a = b
      b = c
    return a

echo gcd(@[1], @[2])
```

### Current Output
```
Error: unhandled exception: division by zero [DivByZeroDefect]
```

### Expected Output
```
1
```

### Additional Information
This only happens for `arc`/`orc`, it works fine with `refc`.

It also works if you
* `echo b` at the end of the loop (this leads me to the conclusion that `b` is somehow not properly updated)
* create the `seq`s inside the proc
* just use `int`s instead of `seq[int]`s

This is a reduced example of https://github.com/nim-lang/bigints/issues/88.

```
$ nim -v
Nim Compiler Version 1.7.1 [Linux: amd64]
Compiled at 2022-01-21
Copyright (c) 2006-2022 by Andreas Rumpf

git hash: 2bd1aa186e09565b2103394bd281478fa1b10ef1
active boot switches: -d:release
```

**Comment by PMunch** [comment] 2022-01-27 11:30
This seems to be caused by `b` incorrectly being interpreted as a cursor. By adding `--expandArc:gcd` we get this:
```
var
  a
  b_cursor
try:
  `=copy`(a, x)
  b_cursor = y
  block :tmp:
    while (
      0 < b_cursor[0]):
      var c
      c = @[a[0] mod b_cursor[0]]
      `=copy`(a, b_cursor)
      b_cursor = c
      `=destroy`(c)
  return
    result = a
    wasMoved(a)
finally:
  `=destroy`(a)
```
So 'b' is set to point to 'c', and 'c' is then promptly destroyed for going out of scope. 'b' should here behave the same as 'a' by copying 'c' into itself.

If we move the declaration of 'c' out of the 'while' loop it works fine:
```nim
proc gcd(x, y: seq[int]): seq[int] =
  var
    a = x
    b = y
    c: seq[int]
  while b[0] > 0:
    c = @[a[0] mod b[0]]
    a = b
    b = c
  return a

echo gcd(@[1], @[2])
```
This expands to this:
```
var
  a
  b
  c
try:
  `=copy`(a, x)
  `=copy`(b, y)
  block :tmp:
    while (
      0 < b[0]):
      `=sink`(c, @[a[0] mod b[0]])
      `=sink`(a, b)
      wasMoved(b)
      `=sink`(b, c)
      wasMoved(c)
  return
    result = a
    wasMoved(a)
finally:
  `=destroy`(c)
  `=destroy`(b)
  `=destroy`(a)
```

**Comment by DomoSokrat** [comment] 2022-01-30 18:12
It also works if we leave the declaration of `c` inside the loop:
```nim
proc gcd(x, y: seq[int]): seq[int] =
  var
    a = x
    b = y
  while b[0] > 0:
    var c: seq[int]
    c = @[a[0] mod b[0]]
    a = b
    b = c
  return a

echo gcd(@[1], @[2])
```
expands to
```
var
  a
  b
try:
  `=copy`(a, x)
  `=copy`(b, y)
  block :tmp:
    while (
      0 < b[0]):
      var c
      c = default()
      `=sink`(c, @[a[0] mod b[0]])
      `=sink`(a, b)
      wasMoved(b)
      `=sink`(b, c)
  return
    result = a
    wasMoved(a)
finally:
  `=destroy`(b)
  `=destroy`(a)
```

**Comment by ringabout** [comment] 2022-06-21 10:42
> This seems to be caused by b incorrectly being interpreted as a cursor. By adding --expandArc:gcd we get this:

Indeed, it works with `--cursorinference:off`.

prints > @[1]

**Closed as completed** 2022-09-28 11:12 UTC
Labels: Severe, ARC/ORC Memory Management
