### ISSUE TITLE
compiler segfault when calling function incorrectly with a generic proc as first parameter

### ISSUE THREAD

**Issue by barcharcraz** [nim-lang/Nim#6305] opened 2017-08-31 23:36 UTC
```
type tests {.bycopy.} = object 
  field1: int

proc lol*(h: pointer, t: ptr tests) = 
  discard

proc defo[T](a: T): T = a

lol(defo, nil)
```

**Comment by Araq** [comment] 2017-09-01 14:22
Duplicate of  #6304.

**Closed by Araq** 2017-09-01 14:22 UTC

**Comment by barcharcraz** [comment] 2017-09-01 18:16
#6304 produces an ICE this produces a segfault, probably the same root cause
