### ISSUE TITLE
Concept issue 

### ISSUE THREAD

**Issue by Bennyelg** [nim-lang/Nim#6521] opened 2017-10-16 18:48 UTC
This is the example of concepts (from Nim in Action book).
It doesn't work on devel for some reason:
```nim
type
  Comparable = concept a
    (a < a) is bool

proc myMax(a, b: Comparable): Comparable =
  if a < b:
    return b
  else:
    return a

echo myMax(1, 2)
```
Error is
```
ffa.nim(10, 12) Error: type mismatch: got (Comparable) but expected 'Comparable = int literal(1)'
```

However it works this way:
```nim
type
  Comparable = concept a
    (a < a) is bool

proc myMax[T: Comparable](a, b: T): Comparable =
  if a < b:
    return b
  else:
    return a

echo myMax(1, 2)
```

**Comment by zah** [comment] 2017-10-17 05:00
This is a duplicate of https://github.com/nim-lang/Nim/issues/6108, which is already fixed, but not yet merged in devel.

**Closed by zah** 2017-10-17 05:00 UTC
Labels: Concept[T]
