### ISSUE TITLE
Unsigned type class accepts integer literals as int type

### ISSUE THREAD

**Issue by planetis-m** [nim-lang/Nim#20079] opened 2022-07-24 16:16 UTC
The type of x is int, it should be unsigned or rejected by the compiler.

### Example
```nim
proc foo[T: SomeUnsignedInt](x: T) =
  static: echo typeof(x) # reports int
  #var x = x %% 2 # `%%` is only defined for signed ints
  var x = x

foo(1)
foo(1'u)
```

### Current Output
```
int
```

### Expected Output
??

```
$ nim -v
Nim Compiler Version 1.6.6
```

**Comment by ringabout** [comment] 2022-07-24 16:25
Duplicate of https://github.com/nim-lang/Nim/issues/1214

**Closed as completed** 2022-07-26 07:16 UTC
