### ISSUE TITLE
Snap package, compiler can't find std libraries

### ISSUE THREAD

**Issue by izznogooood** [nim-lang/Nim#15630] opened 2020-10-18 23:14 UTC
Can't import std libraries in nim when "snap installed".

### Example
```nim
from strutils import parseInt

echo "A number please: "
let n = parseInt(readLine(stdin))
case n
of 0..2, 4..7: echo "The number is in the set: {0, 1, 2, 4, 5, 6, 7}"
of 3, 8: echo "The number is 3 or 8"
else: discard
```

### Current Output
```
Error: cannot open file: strutils
```

### Expected Output
```
text....
```

### Possible Solution

Wher's the snapcraft.yaml and I'll look in to it :).

### Additional Information
Ubuntu 20.04

**Comment by ghost** [comment] 2020-10-19 06:51
This Snap package is not official, so I think you will have more luck asking in https://github.com/sirredbeard/nim_lang_snap

**Comment by narimiran** [comment] 2020-10-19 07:29
It seems it is a well-known problem with snap, not a 1.4 regression: https://github.com/sirredbeard/nim_lang_snap/issues/11

**Comment by izznogooood** [comment] 2020-10-19 09:56
Oh, i assumed since you have it in your "install" options.
I suggest you / me close this then, as it's not officially supported.

**Comment by Clyybber** [comment] 2020-10-19 12:35
Since its reported in https://github.com/sirredbeard/nim_lang_snap/issues/11 I'll close this one.

**Closed as completed by Clyybber** 2020-10-19 12:35 UTC
Labels: OS/Architecture Specific
