### ISSUE TITLE
Consts that call templates cannot evaluate whilst in procedure bodies

### ISSUE THREAD

**Issue by awr1** [nim-lang/Nim#13795] opened 2020-03-28 22:59 UTC
```nim
import std / sequtils
type SomeEnum = enum
  Foo = "foo", Bar, Baz
proc someProc() =
  const y = SomeEnum.toSeq
```
fails with:
```
sequtils.nim(623, 9) Error: cannot evaluate at compile time: result`gensym144407
```
However, the following passes compilation:
```nim
import std / sequtils
type SomeEnum = enum
  Foo = "foo", Bar, Baz
const x = SomeEnum.toSeq 
```

**Comment by juancarlospaco** [comment] 2020-03-29 03:58
Can repro.

**Comment by timotheecour** [comment] 2020-05-09 04:52
@awr1 the title needs to be changed, see reduced example below:
```nim
when true: # D20200508T215154:here gitissue
  template fun(): untyped =
    var c = 0
    c

  proc main() =
    const c = fun()

  main()

```

**Comment by awr1** [comment] 2020-05-09 18:19
@timotheecour Done

**Comment by timotheecour** [comment] 2020-10-23 19:10
this sounds like an exact duplicate of https://github.com/nim-lang/Nim/issues/12172, see https://github.com/nim-lang/Nim/issues/12172#issuecomment-530518808

**Closed as completed by timotheecour** 2020-10-23 19:10 UTC
