### ISSUE TITLE
forward declaration prevents `raises: []` or similar effect inference

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/Nim#17462] opened 2021-03-22 20:59 UTC
here's the root cause for https://github.com/nim-lang/Nim/issues/17454 (i'm fixing this issue in https://github.com/nim-lang/Nim/pull/17461 but root cause remains)
/cc @arnetheduck

### Example
```nim
when true:
  proc fn1()
  proc fn2() = fn1()
  proc fn1() = discard
  proc fn3() {.raises: [].} = fn2() # Error: can raise an unlisted exception: Exception
```
see https://github.com/nim-lang/Nim/issues/17462#issuecomment-804461618 for a slightly more complex example where fwd decl are actually needed.

### Current Output
Error: can raise an unlisted exception: Exception

### Expected Output
works

### Possible Solution
once mutual fwd declarations are all resolved with a body, effects, raises etc should be re-computed

This can be done using a fixed point algorithm on the tracked effects, removing need for most pragmas on fwd declarations.

### Additional Information
1.5.1 c8dda867f2a2607d4049759d09593a66b1697d02

**Comment by arnetheduck** [comment] 2021-03-22 21:58
fwiw, the same happens to `method` and closures and all cases can be resolved by annotating the patients explicitly - based on the number of leaks, bugs and refactoring issues we've had with exceptions, we consider explicit annotations superior in every possible way - in particular the standard library _should_ annotate all functions explicitly because they're a fixed part of the API and ABI - raising an extra exception type is a backwards-incompatible change, and when everything relies on inference, bugs are introduced that _could_ have been detected at compile-time.

**Comment by timotheecour** [comment] 2021-03-22 22:15
> in particular the standard library should annotate all functions explicitly

this would be a bad design and we're not doing that for good reasons. See for example https://www.artima.com/articles/the-trouble-with-checked-exceptions.

In any case, #17462 is a separate issue tackling effect inference in presence of forward declaration.

**Comment by arnetheduck** [comment] 2021-03-22 22:36
> separate issue

The issue proposes to make more inference more automatic - the counterproposal is to make less inference and type it out, to prevent introducing _new_ exceptions, such as for example new Defect:s in json - like the linked article points out, this is a version-breaking change - checked exceptions are a part of Nim already, that ship has sailed - mostly we're using to to _avoid_ exceptions entirely, which would be a more interesting default for forward declarations, proc's etc - ie that the inference was that they raised nothing and if they actually did, they'd have to declare it with `raises: [CatchableError]` (if they want the "let's-not-be-pecific" version).

**Comment by arnetheduck** [comment] 2021-03-22 22:39
Also, the example cheats a bit - this is the more difficult case for which forward declarations are typically used, ie to resolve circular dependencies:

```nim
when true:
  proc fn1()
  proc fn2() = fn1()
  proc fn1() = if continueRandomly(): fn2()
  proc fn3() {.raises: [].} = fn2() # Error: can raise an unlisted exception: Exception
```

**Comment by timotheecour** [comment] 2021-03-22 23:27
> to prevent introducing new exceptions, such as for example new Defect:s in json

Defects are not tracked in recent enough nim (also for good reasons), so raising new Defects in json would be transparent to raises effects.

> checked exceptions are a part of Nim already, that ship has sailed

there's a big difference between having to annotate raises effects on each proc and what we're doing in nim.

> Also, the example cheats a bit 

that was the simplest example showing the issue, but here's one where you actually need fwd declaration:

```nim
when defined case4:
  proc fn1(i: int)
  proc fn2(i: int) = 
    if i > 0: fn1(i-1)
  proc fn1(i: int) =
    if i > 0: fn2(i-1)
  proc fn3() {.raises: [].} = fn2(3) # Error: can raise an unlisted exception: Exception
```

I claim it's possible to do effect inference with mutually recursive procs, removing need for most forward declaration pragmas, for example using some form of fixed point algorithms on the tracked effects.

**Comment by arnetheduck** [comment] 2021-03-23 07:51
Well, the more useful improvement would be to avoid forward declarations altogether, ie https://github.com/nim-lang/Nim/issues/5287 - they're quite the blast from the past ;)

**Comment by saem** [comment] 2021-03-23 08:33
A forward declaration is the interface, the declaration is the implementation, if the decl alters the interface it is a non-conformance.

Not all effects may result in non-conformance, it's a worthwhile debate, that is to say they're not a meaningful part of any interface. Anyhow, any non-conformity should be an error.

**Comment by Araq** [comment] 2021-03-23 08:36
> I claim it's possible to do effect inference with mutually recursive procs, removing need for most forward declaration pragmas, for example using some form of fixed point algorithms on the tracked effects.

It's possible indeed but the costs are unclear and before we make the compiler slower or make it take up more memory, we should focus on IC as it changes these costs.

**Comment by timotheecour** [comment] 2021-03-23 08:54
> A forward declaration is the interface, the declaration is the implementation, if the decl alters the interface it is a non-conformance.

There would be no non-conformance, the effects would be inferred instead of hard-coded, when absent from the forward declaration:

case 1: raises effect for `fn1` are hard-coded, they're checked but not inferred
```nim
proc fn1(i: int) {.raises: [Foo].}
proc fn2(i: int) = impl()
```

case 2: raises effect for `fn1` are not specified, they're inferred
```nim
proc fn1(i: int)
proc fn2(i: int) = impl()
```

> It's possible indeed but the costs are unclear and before we make the compiler slower or make it take up more memory, we should focus on IC as it changes these costs.

yes, a candidate implementation would have to provide benchmarks (possibly both real and synthetic) showing there is no performance regression; given that the number of symbols involved is small (this only concerns 1 module at a time), I'd expect this to hold.

**Comment by arnetheduck** [comment] 2021-03-23 11:16
> bad design

I'd also generally consider it bad design to show a dialog box with an exception trace to the user, as the article about Java from 2003 suggests people should do in a top-level exception handler - but in general what is good and bad design often depends on the use case - the article agrees however that changing the exceptions that are raised is a version-changing event - as such it would be good to have _some_ mechanism to prevent such changes in the standard library (that claims to maintain backwards compatibility), and since effects are there and _can_ solve this problem, it stands to reason that they'll do better than relying on human diligence. 

This is a problem for the step _after_ you've written the initial version of code, and now have to maintain it.

> also for good reasons

Good reasons for one are bad reasons for another - for Nimbus in particular, these `Defect` and panic dialects of the language present challenges, because we have many libraries trying to cooperate and they all need to follow the same dialect to do that well - de facto, the distinction between `Defect` and `not Defect` becomes moot, and the inability to track and enforce it with the compiler's help is unfortunate - the `json` change would not have been possible had https://github.com/nim-lang/Nim/issues/12862 been implemented - it is precisely this reason explicit and deliberate exception specifiers in the standard library would be a feature, Defect or not - there would be fewer buggy point releases of Nim that require downstream projects to crash before the issues are discovered with backporting and more point releases.

**Comment by Araq** [comment] 2021-03-23 16:34
From https://nim-lang.org/docs/manual.html

> Every call to a proc q which has an unknown body (due to a forward declaration or an importc pragma) is assumed to raise system.Exception unless q has an explicit raises list.

It works as designed. Yes, yes, I know you don't like the design. This is clearly the domain of the RFC process though.

**Closed as completed by Araq** 2021-03-23 16:34 UTC
Labels: Effect Tracking
