### ISSUE TITLE
Object (ref) name vs module name name resolution bug

### ISSUE THREAD

**Issue by tobimensch** [nim-lang/Nim#14310] opened 2020-05-11 21:37 UTC
I've commented the following code with the relevant information about the bug.
It's not working when you import sample from a module, yet it is working if you include
the module or have the sample code copy+pasted.
The bug can also be worked around by renaming the sample ref to start with a big letter.
It looks like there's a bug related to the name resolution between module names and
object/object ref names.
The error you get is:
```
Error: internal error: getTypeDescAux(tyProxy)
```

Code:
```
### put this in its own module like sample.nim
type
  sample* = ref object
    test: string
### this code goes in another module: main.nim
#import sample # remove the comment when the sample is its own module to trigger the error

type
  TestTypeKind = enum
    typeOne
    typeTwo
  TestType = ref object
    children: seq[TestType]
    text: string
    case kind: TestTypeKind
    of typeOne:
      num: int
    of typeTwo:
      text2: string
  TheThang*[T] = object
    path: seq[int]
    node: T
    base: T
    tree: T

proc init[T](tw: var TheThang[T]) =
  tw.path = @[]
  tw.node = T.default
  tw.base = T.default
  tw.tree = T.default

proc initTheThang*[T](): TheThang[T] =
  return result

var t1 = initTheThang[sample]() # does not work (but also does work, if included instead of imported)
var t2 = initTheThang[TestType]() # does work!
```
```
$ nim -v
Nim Compiler Version 1.2.0
```

**Comment by narimiran** [comment] 2021-01-21 17:04
Duplicate of https://github.com/nim-lang/Nim/issues/12213

**Closed as completed by narimiran** 2021-01-21 17:04 UTC
