### ISSUE TITLE
Object variants cannot reuse field names

### ISSUE THREAD

**Issue by johnnovak** [nim-lang/Nim#4786] opened 2016-09-17 00:31 UTC
This is more like a feature request I guess. Currently, attempting to reuse field names in object variants will generate a redefinition errors. I don't see any point in this restriction; it makes use cases like the one presented below difficult:

```
type
  AntialiasKind* = enum
    akNone, akGrid, akJittered, akMultiJittered

  Antialias* = ref AntialiasObj
  AntialiasObj = object
    case kind*: AntialiasKind
    of akNone: discard
    of akGrid: m, n*: Natural
    of akJittered: m, n*: Natural
    of akMultiJittered: m, n*: Natural
```

For now, the workaround is to rename field names (e.g. jm, jn, mjm, mjn), but that's ugly...

**Comment by dom96** [comment] 2016-09-17 17:52
Duplicate of #3629

**Closed by dom96** 2016-09-17 17:52 UTC
