### ISSUE TITLE
Compiler breaks on float64 casting

### ISSUE THREAD

**Issue by Abrasax-** [nim-lang/Nim#3031] opened 2015-07-01 08:26 UTC
```Nim
echo float64(1 shl 33)
```
Produces
```Nim
Traceback (most recent call last)
nim.nim(97)              nim
nim.nim(61)              handleCmdLine
main.nim(330)            mainCommand
main.nim(46)             commandCheck
modules.nim(206)         compileProject
modules.nim(154)         compileModule
passes.nim(193)          processModule
passes.nim(137)          processTopLevelStmt
sem.nim(455)             myProcess
sem.nim(436)             semStmtAndGenerateGenerics
transf.nim(804)          transformStmt
transf.nim(775)          processTransf
transf.nim(720)          transform
transf.nim(632)          transformCall
transf.nim(104)          transformSons
transf.nim(726)          transform
transf.nim(381)          transformConv
transf.nim(763)          transform
transf.nim(104)          transformSons
transf.nim(720)          transform
transf.nim(632)          transformCall
transf.nim(104)          transformSons
transf.nim(764)          transform
semfold.nim(785)         getConstExpr
semfold.nim(546)         foldConv
system.nim(2358)         sysFatal
Error: unhandled exception: value out of range: 8589934592 [RangeError]
```
On the other hand
```Nim
let v = 1 shl 33
echo float64(v)
```
Outputs: `0.0`
And
```Nim
let v: int64 = 1 shl 33
echo float64(v)
```
Yields: `8589934592.0`

Somewhat related to #3028
* * *
nim -v
```Nim
Nim Compiler Version 0.11.3 (2015-07-01) [Windows: i386]
Copyright (c) 2006-2015 by Andreas Rumpf

git hash: 5ec42038f9280ffafc6be5f0b50b677a244e071a
```
git branch:`* devel`
command: `nim check test.nim` and `nim c -r test.nim`

**Comment by Araq** [comment] 2015-07-01 09:38
Duplicate of #1463.

**Closed by Araq** 2015-07-01 09:38 UTC
