### ISSUE TITLE
fix c2nim link in Tools page

### ISSUE THREAD

**Issue by gour** [nim-lang/Nim#3522] opened 2015-11-07 08:48 UTC
[tools.txt](https://github.com/nim-lang/Nim/blob/devel/doc/tools.txt) file has dead link to [c2nim](https://github.com/nim-lang/c2nim) tool which is now a separate package, so the doc should be rearranged somehow...

**Comment by Araq** [comment] 2016-05-31 11:10
Duplicate of #3929.

**Closed by Araq** 2016-05-31 11:10 UTC
Labels: Documentation
