### ISSUE TITLE
[1.0.0] Unused import checker reporting exported but renamed imports

### ISSUE THREAD

**Issue by Wazubaba** [nim-lang/Nim#12259] opened 2019-09-25 08:10 UTC
The unused import checker is warning of unused imports when exporting an import that has been renamed. I didn't note any issue on exported modules that were not renamed, however.

### Example

```nim
# file ex1.nim
let examplevar* = 5

# file ex2.nim
import ex1 as renamed
export renamed

# file main.nim
import ex2
echo examplevar
```

### Current Output
```
ex2.nim(1, 12) Warning: imported and not used: 'ex1' [UnusedImport]
```

### Expected Output

```
No reported unused import.
```

### Additional Information

```
$ nim -v
Nim Compiler Version 1.0.0 [Linux: amd64]
(via choosenim)
```

**Comment by Bennyelg** [comment] 2019-09-25 10:43
seems like on `devel` its not produce this error

**Comment by timotheecour** [comment] 2020-09-17 22:18
duplicate of https://github.com/nim-lang/Nim/issues/14246 (closing this despite being older, the other one has more information)

**Closed by timotheecour** 2020-09-17 22:18 UTC
