### ISSUE TITLE
Concepts regression (generics in concept do not work)

### ISSUE THREAD

**Issue by aikidos** [nim-lang/Nim#12527] opened 2019-10-26 15:18 UTC
Documentation link: https://nim-lang.org/docs/manual_experimental.html#concepts-generic-concepts-and-type-binding-rules

Playground: https://play.nim-lang.org/#ix=1ZTy

![image](https://user-images.githubusercontent.com/37471511/67621856-955a3300-f81c-11e9-92b0-e8af9bec2d2b.png)

**Comment by kapehh-karen** [comment] 2019-10-26 20:42
:(

**Comment by andreaferretti** [comment] 2019-10-28 09:21
Duplicate of https://github.com/nim-lang/Nim/issues/5650

In any case, that example of functor is wrong and [does not make sense](https://github.com/nim-lang/Nim/issues/5650#issuecomment-291418854)

**Closed** 2019-10-28 09:21 UTC
