### ISSUE TITLE
can we create a "duplicate" github label, and add it to closed issues that are duplicates

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/Nim#8507] opened 2018-08-01 22:15 UTC
(I could do it myself if I had the proper priviledge)
rationale:
* when looking at closed issues, we can can filter out based on presence / absence of "duplicate" label
* less confusing when one sees a long standing (but unresolved) issue as closed, even though it's just closed as duplicate

NOTE: alternatives suggested [here](https://github.com/nim-lang/Nim/issues/8486#issuecomment-409533636) based on keyword search for duplicate (eg https://github.com/nim-lang/Nim/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed+duplicate, or using "NOT duplicate") are brittle:

* eg: https://github.com/nim-lang/Nim/issues/8440 mentions `nvm, closing as dupe of` (false negative)
* eg: https://github.com/nim-lang/Nim/issues/8362 mentions `duplicate the rich interface` (false positive)

it's a feature used in issue trackers, eg bugzilla, or other github projects, eg https://github.com/Linuxbrew/homebrew-core/issues?q=label%3Aduplicate+is%3Aclosed

**Comment by andreaferretti** [comment] 2018-08-02 08:27
More work than it is worth

**Comment by mratsim** [comment] 2018-08-02 10:02
I think it's fine to tag duplicate going forward and not retag past issues.

**Comment by andreaferretti** [comment] 2018-08-02 10:25
I have created a "duplicate" label and added to a couple of issues (sorry, in the process I accidentally tagged this very issue). Not going to retag everything though

**Comment by dom96** [comment] 2018-08-02 12:11
> when looking at closed issues, we can can filter out based on presence / absence of "duplicate" label

I have never in my life needed to do this.

> less confusing when one sees a long standing (but unresolved) issue as closed, even though it's just closed as duplicate

Every issue that is closed as a duplicate is accompanied by a message stating "Duplicate of #x". There is absolutely no need for a label as well.

I'm closing this because I think it's a waste of time.

**Closed by dom96** 2018-08-02 12:11 UTC
