### ISSUE TITLE
newString(len) has off-by-one error

### ISSUE THREAD

**Issue by luked99** [nim-lang/Nim#6991] opened 2017-12-29 14:59 UTC
I think newString() might have an off-by-one error.

```
var s = newString(0)
s[0] = 'a'   # this works fine!
s[1] = 'b'   # this fails as you might expect
```

And so-on for larger values. I'm not sure to what extent this is a bug, or by design.

**Comment by Yardanico** [comment] 2017-12-29 15:04
@luked99 Strings in Nim are null-terminated

**Comment by Araq** [comment] 2017-12-29 15:10
It's by design but there is already an RFC to change that. Closing.

**Closed by Araq** 2017-12-29 15:10 UTC

**Comment by yglukhov** [comment] 2017-12-29 15:23
#5596
