### ISSUE TITLE
Assigning to var array parameter produces wrong code (compiles but doesn't work)

### ISSUE THREAD

**Issue by yglukhov** [nim-lang/Nim#3083] opened 2015-07-08 09:06 UTC
```nim
type MyArr = array[3, int]

proc changeArr(a: var MyArr) =
    a = [1, 2, 3]

var a: MyArr
changeArr(a)
echo (@a)
```
output:
```
@[0, 0, 0]
```
Related C code:
```c
N_NIMCALL(void, changearr_91009)(NI* a) {
	a = TMP127;
}
```

**Comment by Araq** [comment] 2015-07-08 09:35
Duplicate of #2963.

**Closed by Araq** 2015-07-08 09:35 UTC
