### ISSUE TITLE
`.uint8` : error at compile-time , no error at execution-time

### ISSUE THREAD

**Issue by dreamflow** [nim-lang/Nim#23132] opened 2023-12-27 03:43 UTC
### Description
this runs fine
```nim
block :
    let test_u64 : uint64 = 0xFFFFFFFFFFFF03.uint64
    let test_u8  : uint8  = test_u64.uint8
    echo test_u8
```
and shows the value of the lowest byte : 3

but the same code at compile-time
```nim
static :
    let test_u64 : uint64 = 0xFFFFFFFFFFFF03.uint64
    let test_u8  : uint8  = test_u64.uint8
    echo test_u8
```
breaks with
`Error: illegal conversion from '72057594037927683' to '[0..255]'`
in the line

```nim
let test_u8  : uint8  = test_u64.uint8
```

### Expected Output
to be the same as at execution-time :
3 , the value of the lowest byte

### Possible Solution
in the nimvm implementation adding
before the conversion
```nim
and 0xFF
```
to extract the lowest byte and have it in range [0..255] ,
identical to the behaviour at execution-time .

### Nim Version
nim -v
```
Nim Compiler Version 2.1.1 [Windows: amd64]
Compiled at 2023-12-26
```

### Additional Information

compiled with the cmdLine
`nim compile test.nim`
on the gcc version :
`winlibs-x86_64-posix-seh-gcc-13.2.0-mingw-w64ucrt-11.0.1-r3`

**Comment by ringabout** [comment] 2023-12-27 04:18
Duplicate of https://github.com/nim-lang/Nim/issues/22085 https://github.com/nim-lang/Nim/issues/12700

**Closed as completed** 2024-08-11 11:10 UTC
