### ISSUE TITLE
Using MSVC based compiler fails with error: No Target Architecture

### ISSUE THREAD

**Issue by Keithcat1** [nim-lang/Nim#16519] opened 2020-12-30 21:19 UTC
Using Nim 1.4.2
When compiling with either --cc:vcc or --cc:clang_cl, I get an error like this (below error is from clang_cl):
C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um\winnt.h(173,2): error: "No Target Architecture"
From some internet searches, it seems the answer is to #include <windows.h> at some point.

**Comment by rockcavera** [comment] 2020-12-31 15:56
> Using Nim 1.4.2
> When compiling with either --cc:vcc or --cc:clang_cl, I get an error like this (below error is from clang_cl):
> C:\Program Files (x86)\Windows Kits\10\include\10.0.18362.0\um\winnt.h(173,2): error: "No Target Architecture"
> From some internet searches, it seems the answer is to #include <windows.h> at some point.

If I'm not mistaken, this error has already been fixed in the devel. Look if it's related to this: [PR](https://github.com/nim-lang/Nim/pull/16322)

**Comment by ringabout** [comment] 2021-03-28 06:44
can't reproduce with latest devel.

Feel free to reopen, if something is still wrong.

**Closed as completed** 2021-03-28 06:45 UTC
Labels: Waiting on Author
