### ISSUE TITLE
`0xFF000000_0000000000000` should error with value out of range; instead treated as 0

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/Nim#14529] opened 2020-06-01 00:24 UTC
`0xFF000000_0000000000000` should error with value out of range; instead treated as 0

### Example
```nim
block:
  echo 0xFF000000_0000000
  echo 0xFF000000_00000000
  echo 0xFF000000_000000000
  echo 0xFF000000_0000000000
  echo 0xFF000000_00000000000
  echo 0xFF000000_000000000000
  echo 0xFF000000_0000000000000

```

### Current Output
```
1148417904979476480
-72057594037927936
-1152921504606846976
0
0
0
0
```

### Expected Output
```
echo 0xFF000000_0000000000
```
this should give error: value out of range

### Additional Information
found that while working on https://github.com/nim-lang/Nim/issues/14522
177c7f96e93c6b8d9d206cd13f22c0d0d7d4192e 1.3.5

the fact that `0xFF000000_0000000` is treated as signed instead of unsigned is a separate issue, to be discussed sepately

**Comment by alaviss** [comment] 2020-06-01 04:51
> the fact that `0xFF000000_0000000` is treated as signed instead of unsigned is a separate issue, to be discussed sepately

IIRC there were proposals to make this `uint` but was met with enough resistance that it didn't take off.

Maybe now we should re-propose this as an RFC?

**Comment by timotheecour** [comment] 2020-06-01 05:02
> IIRC there were proposals 

do you have a link?
current behavior causes absurdities such as https://github.com/nim-lang/Nim/issues/14522

**Comment by alaviss** [comment] 2020-06-01 05:13
I can't find it, though @Araq has said on record many times that hex as int is intentional, so maybe he can expand on the topic.

**Comment by Araq** [comment] 2020-06-01 07:05
``0xFF000000_00000000.uint64`` should be ``0xFF000000_00000000'u64``. Hex numbers should have suffixes anyway that's why I rejected the proposal.

**Comment by ringabout** [comment] 2021-03-29 16:36
Duplicate of https://github.com/nim-lang/Nim/issues/4350

**Closed as completed by ringabout** 2021-03-29 16:36 UTC
Labels: unsigned
