### ISSUE TITLE
Error: pragmas are only allowed in the header of a proc

### ISSUE THREAD

**Issue by StefanSalewski** [nim-lang/Nim#4204] opened 2016-05-22 21:06 UTC
Of course we can fix that easily by removing the pragma in the proc definition. But that is really bad, because when we only look at the proc definition we will not know which pragmas are really applied. For my case, the declaration with pragma is hidden in a macro. And generally that messages confuse people, I had to ask in the forum one year ago, before that my feeling was that pragmas may not work at all when forward declaration is used.

$ cat rr.nim 

proc test(i: int): int {.cdecl.}

proc test(i: int): int {.cdecl.} =
  2 * i

stefan@AMD64X2 ~ $ nim c rr.nim 
Hint: system [Processing]
Hint: rr [Processing]
rr.nim(4, 24) Error: pragmas are only allowed in the header of a proc

**Comment by dom96** [comment] 2016-05-23 12:51
Duplicate of https://github.com/nim-lang/Nim/issues/1970

**Closed by dom96** 2016-05-23 12:51 UTC
