### ISSUE TITLE
[RFC] Error for exported procs that take or return private types

### ISSUE THREAD

**Issue by hlaaftana** [nim-lang/Nim#7786] opened 2018-05-06 14:12 UTC
The following compiles and can be imported from another module:

```nim
type Obj = object
  x, y: int

proc a*(obj: Obj) = discard
proc a*: Obj = Obj(x: 3, y: 4)
```

In my opinion, this should not be allowed in either case. You could argue for the second proc to give a warning and the first one to give an error however. [Real world case related to this](https://forum.nim-lang.org/t/3802)

**Comment by andreaferretti** [comment] 2018-05-06 17:42
Actually, I think this is good. The return type becomes an opaque type, on which you can only act through the interface exposed by the module. I think this can actually be useful and intentional

**Comment by Araq** [comment] 2018-05-08 05:35
Useful or not, the compiler is consistent with the spec here and the problem is minor, only affecting insufficiently tested library code. Closing.

**Closed by Araq** 2018-05-08 05:35 UTC
