### ISSUE TITLE
Nim vm issues on 32-bit platforms

### ISSUE THREAD

**Issue by couven92** [nim-lang/Nim#6197] opened 2017-08-07 14:09 UTC
The nim virtual machine is having issues on 32-bit platforms 

Because of this some of the tests in the Nim repo fail when running the nim tester on 32-bit systems (or when running a cross-compiled 32-bit version of the nim tester)

The following tests from the Nim testsuite are affected:

#### [`tbitops.nim`](https://github.com/nim-lang/Nim/tree/devel/tests/stdlib/tbitops.nim) and [`tbitops2.nim`](https://github.com/nim-lang/Nim/tree/devel/tests/stdlib/tbitops2.nim) from [Category `stdlib`](https://github.com/nim-lang/Nim/tree/devel/tests/stdlib)
> unhandled exception: parityBits(0b00110010'u8) == 1

#### [`tconsttable.nim`](https://github.com/nim-lang/Nim/tree/devel/tests/vm/tconsttable.nim) from [Category `vm`](https://github.com/nim-lang/Nim/tree/devel/tests/vm)
<pre>exitcode: 1

Output:
Traceback (most recent call last)
tables.nim(317)          tconsttable
tables.nim(151)          []
Error: unhandled exception: key not found: this [KeyError]</pre>

#### [`trgba.nim`](https://github.com/nim-lang/Nim/tree/devel/tests/vm/trgba.nim) from [Category `vm`](https://github.com/nim-lang/Nim/tree/devel/tests/vm)
<table class="table table-condensed">
                                    <thead>
                                        <tr>
                                            <th>Expected</th>
                                            <th>Actual</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <tr>
                                            <td><pre>[127, 127, 0, 255]
[127, 127, 0, 255]</pre></td>
                                            <td><pre>[127, 127, 0, 255]
[0, 0, 0, 0]</pre></td>
                                        </tr>
                                    </tbody>
                                </table>

**Comment by yglukhov** [comment] 2017-08-07 14:34
Oh, my favorite :)
#4588, #4962, #5010, #5774.

**Comment by Parashurama** [comment] 2017-08-08 16:42
Weirdly I can only reproduce the issue in tconsttable.nim, not in others.
steps on Linux x64:
* latest nim devel.
* installed gcc multilib
* compiled a nim with "./koch temp --cpu:i386 --passc: -m32 --passL: -m32" 
to make to a 32 bits nim compiler 

runing testfile with:
```alias_to_nim_i386 -r c --cpu:i386 --passc: -m32 --passL: -m32 path/to/testfile.nim```

"--cpu:i386 --passc: -m32 --passL: -m32" is needed since otherwise I get a "Nim_and_C_compiler_disagree_on_target_architecture" error in the C compiling step.

**Comment by couven92** [comment] 2017-08-08 17:00
@Parashurama huh, that's very interesting... I am using `vcc` and running on Windows and I just confirmed that those turn up on Windows... I also get these errors using `clang` on 32-bit ARM on Android.

**Comment by Parashurama** [comment] 2017-08-08 17:44
I will try with clang 32bits (still Linux x64) and will report results.

**Comment by couven92** [comment] 2017-08-08 18:11
@Parashurama `testament` invokes the nim compiler... Are you sure you ran testament with  
`--cpu:i386 --passc: -m32 --passL: -m32`

**Comment by Parashurama** [comment] 2017-08-08 18:21
I ran the files individually with nim_temp  -r c path/to/file.nim
testament always runs  ```nim```

**Comment by couven92** [comment] 2017-08-08 18:26
@Parashurama regardless, as far as I know: if no `--cpu` option is passed to `nim` it will choose the architecture of the **host** not the architecture of the compiler.

So you'll need to run `nim_temp --cpu:i386 --passc: -m32 --passL: -m32 -r c path/to/file.nim`

**Comment by Parashurama** [comment] 2017-08-08 18:56
That's how I ran the tests. (see 2nd above post)
So I'm not sure what's going on.
I have an old xp VM i could run tomorrow and install the whole nim compiler toolchain on it, but it might take some time before I get back to you on that.

**Comment by Parashurama** [comment] 2017-08-19 10:56
the hashing problem between VM and compiletime (tconsttable.nim) on 32bits OS is now fixed with latest devel. 
But I can't reproduce the other two issues reported (on Linux or XP vm).
@couven92 Can you check that those issues are still present?

**Comment by couven92** [comment] 2017-08-20 10:23
@Parashurama yes, the consttable.nim does actually pass now, but the bitops and rgba tests still fail at my end

#### `nim --version`
```
Nim Compiler Version 0.17.1 (2017-08-20) [Windows: i386]
Copyright (c) 2006-2017 by Andreas Rumpf

git hash: 837b77b0a1383379ea052ff8e763d634d6a4549f
active boot switches:
```
#### `cl.exe /?`
```
**********************************************************************
** Visual Studio 2017 Developer Command Prompt v15.0.26730.3
** Copyright (c) 2017 Microsoft Corporation
**********************************************************************
[vcvarsall.bat] Environment initialized for: 'x86'

Microsoft (R) C/C++ Optimizing Compiler Version 19.11.25506 for x86
Copyright (C) Microsoft Corporation.  All rights reserved.
```

**Comment by Parashurama** [comment] 2017-08-20 12:54
Since Mingw x86 works just fine, it's seems to be an issue with VCC x86 then, but I don't have a way to check. (really not a windows guy). 
If you want you can try to debug ``trgba``
by seeing which variable is zero-ed out in
```proc ABGR* (val: int| int64): TAggRgba8 ```

**Comment by couven92** [comment] 2017-08-21 15:10
@Parashurama I will try, let me just find the time to test this in more detail first :P

Here's a link to the Visual C++ Standalone Build Tools: http://landinghub.visualstudio.com/visual-cpp-build-tools

**Comment by Parashurama** [comment] 2017-08-21 19:49
Okay, weird thing.
I managed to roll-up an XP VM, with Visual Studio C++ 2010 express installed.
and I ran the tests with no issues.
Here is a log. (same result in debug or release mode)
```
Setting environment for using Microsoft Visual Studio 2010 x86 tools.

C:\Program Files\Microsoft Visual Studio 10.0\VC>cl.exe
Microsoft (R) 32-bit C/C++ Optimizing Compiler Version 16.00.30319.01 for 80x86
Copyright (C) Microsoft Corporation.  All rights reserved.

usage: cl [ option... ] filename... [ /link linkoption... ]

C:\Nim\nim-0.17.0\tests\vm>nim -r c --cc:vcc -d:release trgba
Hint: used config file 'C:\Nim\nim-0.17.0\config\nim.cfg' [Conf]
Hint: system [Processing]
Hint: trgba [Processing]
Hint: vccexe.exe /c --platform:x86 /nologo /O2  /IC:\Nim\nim-0.17.0\lib /Fotests\vm\nimcache\compiler_trgba.obj tests\vm\nimcache\compiler_trgba.c [Exec]
"C:\WINDOWS\system32\cmd.exe" /C ""C:\Program Files\Microsoft Visual Studio 10.0\VC\vcvarsall" x86 && SET"
cl.exe /c /nologo /O2 /IC:\Nim\nim-0.17.0\lib /Fotests\vm\nimcache\compiler_trgba.obj tests\vm\nimcache\compiler_trgba.c compiler_trgba.c
Hint: vccexe.exe /c --platform:x86 /nologo /O2  /IC:\Nim\nim-0.17.0\lib /Fotests\vm\nimcache\stdlib_system.obj tests\vm\nimcache\stdlib_system.c [Exec]
"C:\WINDOWS\system32\cmd.exe" /C ""C:\Program Files\Microsoft Visual Studio 10.0\VC\vcvarsall" x86 && SET"
cl.exe /c /nologo /O2 /IC:\Nim\nim-0.17.0\lib /Fotests\vm\nimcache\stdlib_system.obj tests\vm\nimcache\stdlib_system.c stdlib_system.c
Hint:  [Link]
"C:\WINDOWS\system32\cmd.exe" /C ""C:\Program Files\Microsoft Visual Studio 10.0\VC\vcvarsall" x86 && SET"
cl.exe /nologo /DEBUG /Zi /F33554432 /FeC:\Nim\nim-0.17.0\tests\vm\trgba.exe tests\vm\nimcache\compiler_trgba.obj tests\vm\nimcache\stdlib_system.obj
Hint: operation successful (10876 lines compiled; 1.612 sec total; 9.18MiB peakm
em; Release Build) [SuccessX]
Hint: C:\Nim\nim-0.17.0\tests\vm\trgba.exe  [Exec]
[127, 127, 0, 255]
[127, 127, 0, 255]

```

**Comment by Araq** [comment] 2017-09-01 19:17
Is this still an issue?

**Comment by couven92** [comment] 2017-09-06 11:55
@Araq Just confirmed: `tbitops`, `tbitops2` and `trgba` are still failing with the same error as described.

`tconsttable` is fixed

**Comment by jangko** [comment] 2018-08-07 09:28
after #8556 merged, I build the compiler using msvc 2010 cross compiling from 64bits nim compiler, and then rebuild it once again using compiler from first iteration.

debug mode compiler i386:
* all #4588, #4962, #5010, #5774. no problem
* tbitops, tbitops2, trgba, and tconsttable also no problem anymore
tests are build both debug mode and release mode

release mode compiler i386:
* all #4588, #4962, #5010, #5774. no problem
* tbitops, tbitops2, trgba, and tconsttable also no problem anymore
tests are build both debug mode and release mode

my machine is windows 10 64bits
first iteration command: `nim_c c --cpu:i386 --passc: -m32 --passL: -m32 compiler/nim`
second iteration: `nim_b c compiler/nim` and `nim_b c -d:release compiler/nim`

test with mingw 32bits:
Thread model: posix
gcc version 7.3.0 (i686-posix-dwarf-rev0, Built by MinGW-W64 project)
using the same procedures as above
result no problem found on both release mode and debug mode compiler
tests are build both debug mode and release mode

**Closed** 2019-05-28 23:10 UTC
Labels: OS/Arch specific, VM
