### ISSUE TITLE
can't build a tuple with `static int` element

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/Nim#10073] opened 2018-12-22 01:03 UTC
can't build a tuple with `static int` element

### Example
```nim
block:
  proc foo[N: static int](dims: array[N, int])=
    const N1 = N
    let temp = N # works
    let temp2 = (a:N) # Error: invalid type: 'static[int](2)' in this context: 'tuple[a: static[int](2)]' for let
    # let temp3 = (N, N) # ditto

  foo([1, 2])
```

### Current Output
```
Error: invalid type: 'static[int](2)' in this context: 'tuple[a: static[int](2)]' for let
```

### Expected Output
compiles because `let temp = N` works

**Comment by Araq** [comment] 2018-12-22 08:42
But ``let temp = N`` strips away the static'ness. This is not a bug but ``static T`` has a fair share of terrible design choices.

**Comment by timotheecour** [comment] 2018-12-23 09:49
reopening because I really don't understand your analysis.
here's another example:

why would
* `let temp1 = N `  work
* ` let temp2 = Foo(age: N)` work
* but `let temp3 = (age:N)` not work?

```nim
when true:
  type Foo = object
    age: int
  proc foo[N: static int](dims: array[N, int])=
    const N1 = N
    let temp1 = N # works
    let temp2 = Foo(age: N)
    # let temp3 = (age:N) # uncomment gives: Error: invalid type: 'static[int](2)' in this context: 'tuple[age: static[int](2)]' for let
  foo([1, 2])
```

**Comment by zah** [comment] 2019-01-06 18:17
A more proper fix has been pushed here: https://github.com/nim-lang/Nim/pull/10218

**Closed** 2019-01-07 11:11 UTC
Labels: Static[T], fix_in_progress, tuple
