### ISSUE TITLE
No link to std/enumerate in the stdlib docs

### ISSUE THREAD

**Issue by Benjamin-Lee** [nim-lang/Nim#15694] opened 2020-10-23 16:18 UTC
Is this intentional? If not, I'm happy to PR it. I took a look at the discussion (https://github.com/nim-lang/Nim/pull/15297#issuecomment-696124868) surrounding the inclusion of `enumerate` not in `sugar` but in `std/enumerate` and wasn't sure if it was a temporary solution or not.

**Comment by timotheecour** [comment] 2020-10-23 16:39
https://nim-lang.github.io/Nim/enumerate.html ?

**Comment by Benjamin-Lee** [comment] 2020-10-23 17:00
Looking here to be specific: https://nim-lang.github.io/Nim/lib.html

**Comment by timotheecour** [comment] 2020-10-23 17:02
kochdocs could add some logic to check that all docgen'd stdlib modules are mentioned in lib.rst, that way, it'd always stay in sync.

I'm sure other modules are missing.

**Comment by timotheecour** [comment] 2020-11-19 07:37
duplicate of https://github.com/nim-lang/Nim/issues/16046

**Closed as completed by timotheecour** 2020-11-19 07:37 UTC
Labels: Documentation
