### ISSUE TITLE
`echo typeof(data[0 .. 1])` is `byte`? No, is `seq[byte]`

### ISSUE THREAD

**Issue by haoyu234** [nim-lang/Nim#22616] opened 2023-09-01 07:07 UTC
### Description

Problems found during print debugging, maybe not so important.

https://play.nim-lang.org/#ix=4F4Z

```nim
var data: array[4, byte] = [1, 2, 3, 4]
# var data = @[byte(1), 2, 3, 4]

echo "data[0 .. 1] is seq[byte]? ", data[0 .. 1] is seq[byte]
echo "data[0 .. 1] is byte? ", data[0 .. 1] is byte
echo "typeof(data[0 .. 1]) is ", typeof(data[0 .. 1])
```

output:
```
data[0 .. 1] is seq[byte]? true
data[0 .. 1] is byte? false
typeof(data[0 .. 1]) is byte   # ??????
```

### Nim Version

Nim Compiler Version 2.1.1 [Linux: amd64]
Compiled at 2023-08-23
Copyright (c) 2006-2023 by Andreas Rumpf

git hash: 6b04d0395ab1d6d8efa7d287c73da2c7230800c9
active boot switches: -d:release

### Current Output

```text
data[0 .. 1] is seq[byte]? true
data[0 .. 1] is byte? false
typeof(data[0 .. 1]) is byte
```

### Expected Output

```text
data[0 .. 1] is seq[byte]? true
data[0 .. 1] is byte? false
typeof(data[0 .. 1]) is seq[byte]
```

**Comment by ringabout** [comment] 2023-09-01 07:16
Duplicate of https://github.com/nim-lang/Nim/issues/12383

And work around: `echo "typeof(data[0 .. 1]) is ", typeof(data[0 .. 1], typeOfProc)`

**Closed as completed by ringabout** 2023-09-01 07:16 UTC
