### ISSUE TITLE
`type(int).name` should be `type int`, not `int`, to avoid confusion with `int`

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/Nim#8705] opened 2018-08-21 00:13 UTC
```nim
import typetraits

let x=1
type T = type(x)
type T2 = type(T)

doAssert T is int
doAssert int is T

doAssert: T2 isnot int
doAssert int isnot T2

echo T.name # int
echo T2.name # int, should be something like `type int` or `type[int]`
```

**Comment by jangko** [comment] 2018-08-22 01:58
looks very similar with #1674, except the `typetraits.name` part

**Comment by dom96** [comment] 2018-08-22 14:31
Yeah, looks like a duplicate of #1674 to me.

**Closed by dom96** 2018-08-22 14:31 UTC
Labels: typedesc[T]
