### ISSUE TITLE
Valid uint64 literal says -72057594037927936 can't be converted to uint64.

### ISSUE THREAD

**Issue by treeform** [nim-lang/Nim#14522] opened 2020-05-31 19:47 UTC
```nim
echo 0xFF000000_00000000.uint64
```
```
Error: -72057594037927936 can't be converted to uint64
```
https://play.nim-lang.org/#ix=2nY6

I think its treating all hex literals as signed int64, so it can't accept one that has a negative bit set. Some where in some conversions this happens?

My compiler:
```
Nim Compiler Version 1.2.0 [Windows: amd64]
Compiled at 2020-04-03
Copyright (c) 2006-2020 by Andreas Rumpf

git hash: 7e83adff84be5d0c401a213eccb61e321a3fb1ff
active boot switches: -d:release
```

**Comment by treeform** [comment] 2020-05-31 19:53
Hmm Recruit_main707, pointed out that cast works
```nim
echo cast[uint64](0xFF00000000000000)
```

Very strange!

**Comment by treeform** [comment] 2020-05-31 19:57
Hmm leorize, points out that:
```nim
echo 0xFF00000000000000u64
```
Also works!

**Comment by timotheecour** [comment] 2021-07-02 05:56
update as of 3ceaf5c1309ac8d4d68e6f39c13b021bcc1b15f4
```nim
when true:
  # echo 0xFF000000_00000000.uint64 # Error: -72057594037927936 can't be converted to uint64
  echo 0xFF000000_00000000'u64 # ok
  const a = 0xFF000000_00000000
  # echo a.uint64 # Error: -72057594037927936 can't be converted to uint64
  # var b: uint64 = a # Error: type mismatch:
```

**Comment by ringabout** [comment] 2024-08-08 13:41
Duplicate of https://github.com/nim-lang/Nim/issues/12700
```nim
let x = 0xFF000000_00000000
echo uint64(x)
```
works

**Closed as completed** 2024-08-11 11:10 UTC
Labels: unsigned

**Comment by treeform** [comment] 2024-08-11 17:37
Thank you! Great fix.
