### ISSUE TITLE
$ on recursive variant object crashes the compiler

### ISSUE THREAD

**Issue by StasRuinsEverything** [nim-lang/Nim#7255] opened 2018-02-24 23:15 UTC
Hello! The title pretty much says it all. Here's a reproduction:
```nim
type
  Node = object
    case leaf: bool
    of true:
      val: int
    of false:
      nodes: seq[Node]

let node = Node(leaf: true, val: 1)
let x = $node
```
It happens in 0.17.2 and the devel version. Note that when changing **nodes: seq[Node]** into **nodes: seq[string]** or something similar, the problem disappears, even though that field is inactive. Manually overloading $ for this type as follows also fixed the problem:
```nim
proc `$`(node: Node): string =
  if node.leaf:
    $node.val
  else:
    $node.nodes
```

**Comment by nc-x** [comment] 2018-02-25 03:43
Duplicate of https://github.com/nim-lang/Nim/issues/6943?

**Comment by mratsim** [comment] 2018-02-28 10:20
Works for me on devel

**Comment by mratsim** [comment] 2018-02-28 10:22
Edit: it doesn't crash but actually the rest of the code is not executed, strange (tested by adding an `echo` at the end)

**Comment by dom96** [comment] 2018-06-12 18:18
Closing as duplicate of #6943

**Closed by dom96** 2018-06-12 18:18 UTC
Labels: Crash
