### ISSUE TITLE
[BLOCKER] sizeof should be available at compile time, but gives: `Error: cannot run in the VM: sizeof`

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/Nim#8522] opened 2018-08-03 06:44 UTC
```
type A=object
  a:int

block:
  # ok
  let s = sizeof(A)
block:
  # Error: cannot run in the VM: sizeof(A)
  const s = sizeof(A)
```

D (and even C++ ) support it at CT

**Comment by GULPF** [comment] 2018-08-03 06:47
See #5664

**Comment by dom96** [comment] 2018-08-03 13:59
Duplicate of #5493

**Closed by dom96** 2018-08-03 13:59 UTC
Labels: VM

**Comment by Yardanico** [comment] 2018-08-03 14:28
@dom96 are you sure that this issue is a duplicate of #5493?

**Comment by dom96** [comment] 2018-08-03 14:37
[yes](https://github.com/nim-lang/Nim/issues/5493#issuecomment-289931924)

**Comment by timotheecour** [comment] 2018-10-14 21:49
now works thanks to @krux02 's work in https://github.com/nim-lang/Nim/pull/5664 which has been merged
