### ISSUE TITLE
ICE When incorrectly calling a procedure with another procedure

### ISSUE THREAD

**Issue by barcharcraz** [nim-lang/Nim#6304] opened 2017-08-31 23:35 UTC
```import os

import os

type tests {.bycopy.} = object 
  field1: int

proc lol*(h: pointer, t: ptr tests) = 
  discard

lol(handle, nil)
```
compile with --threads:on

**Comment by Araq** [comment] 2018-02-04 06:31
Duplicate of all the other ``getTypeDescAux`` bugs.

**Closed by Araq** 2018-02-04 06:31 UTC
Labels: Crash, Medium Priority, Semcheck
