### ISSUE TITLE
[TODO] allow optional params after varargs, but require them to always be passed with keyword

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/Nim#9036] opened 2018-09-22 16:22 UTC
Note: this is related to https://github.com/nim-lang/Nim/issues/5855, but https://github.com/nim-lang/Nim/issues/5855 relates to non-optional parameters after varargs[untyped], whereas this issue relates to optional parameters after `varargs[anything]` (T, typed, untyped)

the proposal is to allow optional params after varargs, but require them to always be passed with keyword if they're being passed; it thus removes any ambiguity (eg `varargs[typed]` would otherwise be ambiguous)

In this proposal, I'm also requiring `template foo(a:varargs[int], b = ",")` to be called with keyword (`foo(1,2,3,b=".")`) even though this particular case would not be ambiguous, as it's simpler to implement and also to read resulting code.
```nim
foo(1,2,3, ".") # currently valid but becomes invalid under this proposal
foo(1,2,3, b=".") # currently valid and stays valid under this proposal
foo(1,2,3) # currently invalid but becomes valid under this proposal
```

```nim
import std/macros
macro fooAux(a:untyped):untyped=
  result = newCall(bindSym"echo")
  for ai in a: result.add ai

when defined(case12):
  template foo(a:varargs[typed], b = ",")=
    fooAux(a)
    echo b
  foo(1,2,3, ".") # works but shouldn't under this proposal
  foo(1,2,3, b = ".") # ok

when defined(case12b):
  # Error: type mismatch: got <int literal(1), int literal(2), int literal(3)>
  template foo(a:varargs[typed], b = ",")=
    fooAux(a)
    echo b
  foo(1,2,3) # doesn't work but should work under this proposal

## ditto with varargs[int]
when defined(case13):
  template foo(a:varargs[int], b = ",")=
    fooAux(a)
    echo b
  foo(1,2,3, ".")
  foo(1,2,3, b = ".")

when defined(case13b):
  # Error: type mismatch: got <int literal(1), int literal(2), int literal(3)>
  template foo(a:varargs[int], b = ",")=
    fooAux(a)
    echo b
  foo(1,2,3)

## ditto with varargs[untyped]
```

## eg use case:
`strAppend(1+1, 2 == 3, sep = ",")` (many other use cases obviously)

**Comment by krux02** [comment] 2018-11-07 18:12
Please, if you have an idea to an existing issue, make a comment in that existing issue, don't create a new issue and call it an "RFC". This is very annoying.

I am closing this as duplicate of https://github.com/nim-lang/Nim/issues/5855

**Closed as completed by krux02** 2018-11-07 18:12 UTC
Labels: RFC

**Comment by timotheecour** [comment] 2018-11-07 18:39
I don't see how it's a duplicate of  #5855 ;#5855 deals with `varargs[untyped]` (it's right there in the title), whereas this deals with `optional parameters after varargs[anything] (T, typed, untyped)` ; as I explained in the very 1st line

**Comment by krux02** [comment] 2018-11-07 20:46
one issue about remaining arguments after varargs should be enough. You can put your two cents in the comment section and explain how it can be solved with named arguments.  But really this isn't a different issue.
