### ISSUE TITLE
recursive distinct object: compiler frozen at 100% CPU

### ISSUE THREAD

**Issue by mratsim** [nim-lang/Nim#16393] opened 2020-12-18 14:30 UTC
The following code snippet will stuck the compiler at 100% CPU for 1.2.6, 1.4.2 and devel

```Nim
type
  TrustedSig = distinct TrustedSig
```

**Comment by timotheecour** [comment] 2020-12-18 21:49
side note:
should be easy to fix; actually that's a good stress test for nimsuggest; IMO nimsuggest should be spawned by another process that would restart (with exponential backoff) it when it "misbehaves" such as using 100% cpu for > n seconds

**Comment by ee7** [comment] 2020-12-19 08:19
I remember this one. Previously reported in https://github.com/nim-lang/Nim/issues/13008, with slightly different examples.

**Comment by timotheecour** [comment] 2020-12-19 08:24
duplicate of https://github.com/nim-lang/Nim/issues/13008

**Closed as completed by timotheecour** 2020-12-19 08:24 UTC
Labels: Low Priority, Type Sections, Compiler Crash, Distinct Types
