### ISSUE TITLE
enhancement: make the raises pragma tell the origin of the missed exceptions

### ISSUE THREAD

**Issue by kobi2187** [nim-lang/Nim#10439] opened 2019-01-24 04:53 UTC
I tried putting the raises pragma, right after the main proc, to see whether I missed exceptions throughout the program. 
`proc main() {.raises: [].} =`

I get an error list such as:
```
can raise an unlisted exception: ref RegexError (36,23)
can raise an unlisted exception: ref DocoptLanguageError (36,23)
can raise an unlisted exception: Exception (36,23)
can raise an unlisted exception: ref Exception (36,23)
can raise an unlisted exception: ref DocoptExit (36,23)
can raise an unlisted exception: ref IOError (36,23)
can raise an unlisted exception: ref IndexError (36,23)
can raise an unlisted exception: ref Keyerror (36,23)
can raise an unlisted exception: TimeParseError (36,23)
can raise an unlisted exception: Defect (36,23)
can raise an unlisted exception: ref EOFError (36,23)
can raise an unlisted exception: ref OSError (36,23)
```
The column and line numbers refer to the raises pragma next to the main proc.
It would be really nice if the compiler can tell me the location of where the exception originated from. (or at least which proc is responsible)
Thanks!

**Comment by GULPF** [comment] 2019-01-24 07:05
Duplicate of #8482

**Closed by GULPF** 2019-01-24 07:05 UTC

**Comment by kobi2187** [comment] 2019-01-24 08:39
thanks!
