### ISSUE TITLE
Generic instantiation error with method call syntax

### ISSUE THREAD

**Issue by SSPkrolik** [nim-lang/Nim#2698] opened 2015-05-12 08:51 UTC
Consider the next source:

```
type
    AssetFormat* = enum
        ObjFormat = "obj",

proc someFunc2[T](af: AssetFormat): int =
    let x: T = 0
    echo x
    return 0
```

And how we call the proc:

```
    echo ObjFormat.someFunc2[int32]()  # Works fine
    echo someFunc2[int32](ObjFormat)   # Gives error
```
And the error as follows:

```
obj.nim(36, 19) Info: template/generic instantiation from here
obj.nim(26, 16) Error: cannot instantiate: 'T'
```

**Comment by kirbyfan64** [comment] 2015-05-12 16:03
I think there was another issue about this, and it was labeled intended (but undocumented) behavior.

**Comment by yglukhov** [comment] 2015-06-10 13:32
This one? #1782

**Comment by kirbyfan64** [comment] 2015-06-10 14:11
@yglukhov I think so?

**Comment by Araq** [comment] 2015-07-01 01:36
Duplicate of #1782.

**Closed by Araq** 2015-07-01 01:36 UTC
Labels: Generics
