### ISSUE TITLE
Move optimization does not work with `let seq`

### ISSUE THREAD

**Issue by mratsim** [nim-lang/Nim#6423] opened 2017-09-23 12:55 UTC
I would expect the move optimization from the [manual](https://nim-lang.org/docs/manual.html#ast-based-overloading-move-optimization) to work with `let seq` but it does not.

```Nim
import macros, sequtils

let a = toSeq(1..10)

proc arewemoving[T](s: seq[T])=
  echo "no we aren't"

proc arewemoving[T](s: seq[T]{call})=
  echo "yes we are"

a.arewemoving #no we aren't"
```

**Comment by Yardanico** [comment] 2017-09-23 13:00
@mratsim {call} is not about a move optimization, it's about an expression which is a call
You can use
```nim
proc arewemoving[T](s: seq[T]{call, `let`})=
  echo "yes we are"
```

**Comment by mratsim** [comment] 2017-09-23 13:02
Wow, I guess it should be tagged documentation then

**Comment by edubart** [comment] 2017-09-23 13:06
I think it was intended to work for **rvalues** this way:

```Nim
import macros, sequtils

proc arewemoving[T](s: seq[T])=
  echo "no we aren't"

proc arewemoving[T](s: seq[T]{call})=
  echo "yes we are"

arewemoving(toSeq(1..10))
```

In this example `s` will be a rvalue, however it doesn't work either.
More about lvalues and rvalues can read at https://eli.thegreenplace.net/2011/12/15/understanding-lvalues-and-rvalues-in-c-and-c

**Comment by Yardanico** [comment] 2017-09-23 13:13
@edubart toSeq is a template

**Comment by edubart** [comment] 2017-09-23 13:16
```Nim
import macros, sequtils

proc arewemoving[T](s: seq[T])=
  echo "no we aren't"

proc arewemoving[T](s: seq[T]{call})=
  echo "yes we are"

proc mysec(): auto =
  toSeq(1..10)

arewemoving(mysec()) # yes we are"
```

@Yardanico thanks for noting, now worked

**Comment by Araq** [comment] 2017-09-23 14:58
It is not correct to use ``let`` here, in ``let x = ...`` you can access ``x`` after it was moved. Since the documentation is correct, I'm closing this.

**Closed by Araq** 2017-09-23 14:58 UTC
