### ISSUE TITLE
[language design] `Error: attempt to redefine:` when using a field in multiple cases of an algebraic data type

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/Nim#8877] opened 2018-09-04 23:30 UTC
in my use case I want a field `url` to be in a subset of all cases (here, in 2 out of 3 cases); but this errors `Error: attempt to redefine: url`
Is there a fundamental reason this can't be supported? what's a simple workaround (besides the obvious "rename `url` or add `url` to all cases by putting it outside the case statement)

```nim
type
  Kind* {.pure.} = enum
    kfile,
    kurl,
    kgithubHash,

  Foo* = object
    case kind*: Kind
    of kfile:
      file*: File
    of kurl:
      url*: string
    of kgithubHash:
      hash*: string
      url*: string
```

**Comment by awr1** [comment] 2018-09-05 00:12
Duplicate of #3629

**Closed** 2018-09-05 00:40 UTC
