### ISSUE TITLE
Compiler internal error on invalid code: expr(skModule); unknown symbol

### ISSUE THREAD

**Issue by nc-x** [nim-lang/Nim#20275] opened 2022-08-26 05:54 UTC
### What happened?

Code:
```nim
import std / random

random
```
Output:
```
❯ nim c -r t.nim
Hint: used config file '/Users/alpha/Desktop/Nim/config/nim.cfg' [Conf]
Hint: used config file '/Users/alpha/Desktop/Nim/config/config.nims' [Conf]
....................................................................................................
t.nim(5, 1) Error: internal error: expr(skModule); unknown symbol
No stack traceback available
To create a stacktrace, rerun compilation with './koch temp c <file>', see https://nim-lang.github.io/Nim/intern.html#debugging-the-compiler for details
```

### Nim Version

```
Nim Compiler Version 1.7.1 [MacOSX: amd64]
Compiled at 2022-08-25
Copyright (c) 2006-2022 by Andreas Rumpf

git hash: 16f6dc05fdb2e1ca3086936c15c2ad3de542d991
active boot switches: -d:release
```

### Notes

Found this when I had a function with same name as imported module and was having issues with calling the function because module name was taking priority.

**Comment by ringabout** [comment] 2022-10-11 02:27
Duplicate of https://github.com/nim-lang/Nim/issues/19225

**Closed as completed by ringabout** 2022-10-11 02:27 UTC
