### ISSUE TITLE
Corruption of a sequence when using arc ou orc memory management

### ISSUE THREAD

**Issue by lscrd** [nim-lang/Nim#21085] opened 2022-12-12 15:25 UTC
### Description

The following program gives a wrong result when compiled with --gc:arc or --gc:orc.

```Nim
type Vector = seq[int]

var vect: Vector = newSeq[int](5)
echo vect

# Needed to get the problem. Could also use "var".
let vectCopy = vect

# Then some procedure definition is needed to get the problem.
proc p(): int = 3

echo vect
```

### Nim Version

Nim Compiler Version 1.6.10 [Linux: amd64]
Compiled at 2022-11-21
Copyright (c) 2006-2021 by Andreas Rumpf

git hash: f1519259f85cbdf2d5ff617c6a5534fcd2ff6942
active boot switches: -d:release

### Current Output

```text
@[0, 0, 0, 0, 0]
@[]
```

### Expected Output

```text
@[0, 0, 0, 0, 0]
@[0, 0, 0, 0, 0]
```

### Possible Solution

Use another GC.

### Additional Information

As noted in the program, the assignment is needed and we need  a procedure definition after that.

The issue is also encountered with development version.

**Comment by ringabout** [comment] 2022-12-12 15:26
Work around

```nim
type Vector = seq[int]

proc main =
  var vect: Vector = newSeq[int](5)
  echo vect

  # Needed to get the problem. Could also use "var".
  let vectCopy = vect

  # Then some procedure definition is needed to get the problem.
  proc p(): int = 3

  echo vect

main()
```

**Comment by ringabout** [comment] 2022-12-12 15:27
Duplicate of https://github.com/nim-lang/Nim/issues/19795

**Closed as completed by ringabout** 2022-12-12 15:27 UTC
