### ISSUE TITLE
[RFC] Nim development and release model - 1.0 and beyond

### ISSUE THREAD

**Issue by genotrance** [nim-lang/Nim#7527] opened 2018-04-06 17:01 UTC
Based on the IRC conversations on [Jan 30th, 2018](https://irclogs.nim-lang.org/30-01-2018.html#16:35:53), two proposals were captured for Nim's development and release process going forward.

- [Trunk based](https://trunkbaseddevelopment.com/) development that allows for multi-version release management with a single source branch
- Branch based development which is the traditional approach of development and resorts to multiple source branches for each release

Details and pros/cons of each approach are [documented here](https://gist.github.com/genotrance/4e4158909972617082dc223b2bb0b2f0) in detail.

This RFC aims to consolidate all feedback on both approaches and move towards the most appropriate release process for Nim going forward. The current inclination is to try out trunk based development since it more practical given the resources available today and already kind of how Nim is being developed today.

**Comment by timotheecour** [comment] 2018-04-06 21:50
@genotrance thanks for the RFC; can you change wording to let users vote, eg +1 for Trunk, -1 for Branch based?

**Comment by data-man** [comment] 2018-04-06 22:09
## Poll: trunk based development

**Comment by data-man** [comment] 2018-04-06 22:09
## Poll: branch based development

**Comment by timotheecour** [comment] 2018-04-06 22:11
I'm strongly against trunk based proposal and in favor of branch based development.
Rationale:

* not standard ; could you perhaps list major projects that use the trunk approach in the trunk proposal?

* most important point: maintaining all the `{.version: "1.x.x".}` will cause a lot more maintenance headache and keep in legacy code. Eg, each change will require thinking about whether to keep old behavior around with a pragma version block; this adds much complexity and will cause bugs

> Pro : all versions in one binary available to try out - easier packaging

I don't buy this argument. Since proposal only mentions keeping 4 versions, users that need other(eg older) versions will anyway need to have an easy way to access that. Besides, unlike D where the situation is a lot more complex (split repos bw dmd,druntime,phobos ; and also split compilers (dmd,ldc,gdc)), in Nim it should be **very easy** to build and package a given version. Even in D there's https://github.com/CyberShadow/Digger which is as easy to use as:
```
digger build v2.064.2 # build a specific version
digger build "master +dmd#7757  +tools#292" # build master modified by 2 PR's against dmd and tools
# etc see docs
```

* will make it harder to find regressions and change meaning of `version 1.2.3` since 1.2.3 won't point to a fixed commit but be a moving target whose semantics/bugs could depend on code outside version pragma blocks

* nim binary size increases (most minor point)

**Comment by Araq** [comment] 2018-04-07 06:15
> most important point: maintaining all the {.version: "1.x.x".} will cause a lot more maintenance headache and keep in legacy code. Eg, each change will require thinking about whether to keep old behavior around with a pragma version block; this adds much complexity and will cause bugs

That is very value-able information for the documentation anyway and would need to be added manually otherwise.

**Comment by dom96** [comment] 2018-04-07 11:09
For what it's worth: as far as I know Rust and Swift both use the trunk-based model. Rust has adopted a concept of "epochs", see this discussion for a description: https://internals.rust-lang.org/t/evolving-rust-through-epochs/5475/4.

**Comment by Araq** [comment] 2018-10-30 21:51
I changed my mind, I now prefer to backport the most critical bugfixes into a "last stable release" branch. Backporting can be automated by cherrypicking every commit that contains "[backport]", release building should be automatic.

**Comment by Araq** [comment] 2018-10-30 23:30
We'll do branch based development but can review this design decision later, closing for now.

**Closed by Araq** 2018-10-30 23:30 UTC
Labels: RFC

**Comment by timotheecour** [comment] 2018-10-30 23:44
> We'll do branch based development but can review this design decision later, closing for now.

maybe a good occasion to introduce the branch `stable` (cf 1st part (out of 2) of https://github.com/nim-lang/Nim/issues/8576#issuecomment-411883936)

**Comment by Araq** [comment] 2019-06-05 09:44
Update: Starting with the release of 0.20 we're trying the trunk based development model since we expect it to work better when we have many, many bugfixes and fewer feature additions.
