### ISSUE TITLE
Path in error message has `..\..\..\..\..\`  prefix since 0.19.0

### ISSUE THREAD

**Issue by tim-st** [nim-lang/Nim#9556] opened 2018-10-29 14:11 UTC
I noticed this a few weeks ago and never saw it before. Here is an example:

```nim
type A* = object
  b: var A
  c: string

echo A()
```
(code is from [here](https://github.com/nim-lang/Nim/issues/8071) )

Errors on devel (windows) and I think also at least on 0.19.0 with
```
filename.nim(5, 7) template/generic instantiation of `$` from here
..\..\..\..\..\C:\Program Files\Nim\lib\system.nim(2661, 15) Error: generic instantiation too nested
```
I'm pretty sure some time ago the paths to filename were normal (@narimiran confirmed it's `same/similar on linux, started not so long ago`).
(I run the compilation from vscode if that makes a difference).

Code producing the new path too:
https://github.com/nim-lang/Nim/issues/9488#issue-373331849
https://github.com/nim-lang/Nim/issues/9420#issue-371294002

**Comment by narimiran** [comment] 2018-10-29 14:13
Here is the linux version, using choosenim:

```
filename.nim(5, 7) template/generic instantiation of `$` from here
../../../../../.choosenim/toolchains/nim-#devel/lib/system.nim(2661, 15) Error: generic instantiation too nested
```

**Comment by tim-st** [comment] 2018-10-29 15:33
The original code crashes on nim 0.18.0 windows so I couldn't test it.
[This one](https://github.com/nim-lang/Nim/issues/9488#issue-373331849) works on version 0.18.0 and produces a path without prefix there.
On 0.19.0 stable and later (devel) the path is for this example with prefix (not good anymore).

**Comment by tim-st** [comment] 2018-11-01 22:31
Here is a minimal example showing where the prefix path appears:

```nim
echo 1
```
compile with `nim c --verbosity:3 file.nim` using nim 0.19.0

**Comment by Araq** [comment] 2018-11-02 09:19
Cannot reproduce this. How do you setup your paths?

**Comment by tim-st** [comment] 2018-11-02 10:16
I have windows 7 x64 with and tested it with nim 0.18.0 and 0.19.0 and gcc 8.1.0 (gcc (x86_64-posix-seh-rev0, Built by MinGW-W64 project) 8.1.0) and gcc 8.2.0 (gcc (Rev3, Built by MSYS2 project) 8.2.0) all x64.

nim is installed to: `C:\Program Files\Nim\bin\nim.exe`
mingw gcc to `C:\Program Files\mingw64\bin\gcc.exe`
msys gcc to `C:\msys64\mingw64\bin\gcc.exe`

when testing the 4 combinations both 0.18.0 show normal paths and both 0.19.0 have the prefix with the example from [here](https://github.com/nim-lang/Nim/issues/9556#issuecomment-435209085).

It seems to change the path prefix dependent on the location of `file.nim` starting with 0.19.0

**Comment by Araq** [comment] 2018-11-02 10:57
But where is your ``file.nim`` located?

**Comment by narimiran** [comment] 2018-11-02 11:53
> But where is your `file.nim` located?

It doesn't matter where (well, the number of `../` changes, depending on the location of `file.nim`), the error always print the path to `system.nim` starting from the location of the file.

**Comment by tim-st** [comment] 2018-11-02 11:56
at `C:\file.nim` I get `Program Files\Nim\lib\system.nim`
at `C:\Users\-\file.nim` I get `..\..\Program Files\Nim\lib\system.nim`
and so on. Before 0.19.0 it was different.
With 0.18.0 I get:
at `C:\file.nim` I get `lib\system.nim`
at `C:\Users\-\file.nim` I get `lib\system.nim`

**Comment by narimiran** [comment] 2018-11-03 07:43
This is marked as fixed, but I've tried to run it with the latest devel (`Compiled at 2018-11-03`) and I still get:

```
filename.nim(5, 7) template/generic instantiation of `$` from here
../../../../.choosenim/toolchains/nim-#devel/lib/system.nim(2673, 15) Error: generic instantiation too nested
```

**Comment by nc-x** [comment] 2018-11-03 07:47
@narimiran See https://github.com/nim-lang/Nim/pull/9604#issuecomment-435411386

**Closed** 2019-01-24 13:40 UTC
Labels: Error messages
