### ISSUE TITLE
Times.nim: Example fails on Windows

### ISSUE THREAD

**Issue by Araq** [nim-lang/Nim#8743] opened 2018-08-23 10:20 UTC
On my machine (Win10) the following program produces different results:

```nim

import times

let dt = initDateTime(01, mJan, 1970, 00, 00, 00, local())
let tm = dt.toTime()

echo $tm
echo "1970-01-01T00:00:00" & format(dt, "zzz")
```

Produces

```
1970-01-01T01:00:00+01:00
1970-01-01T00:00:00+01:00
````

**Comment by GULPF** [comment] 2018-08-23 10:35
As weird as it might look, it's not necessarily incorrect. The date `1970-01-01T00:00:00` might not exist in your timezone, which will cause `initDateTime` to normalize it to the closest one that exists. For instance, this would happen if the UTC offset was moved forward at that date. However, it's very rare for UTC offset changes to happen at `00:00`.

What timezone is the machine in?

**Comment by GULPF** [comment] 2018-08-23 10:45
Never mind, I think I know the cause. This issue is actually just a variant of #6668. Because the `times.local` timezone (currently) can't handle timezone data older than `1970-01-01T00:00:00` on Windows, there will always be a UTC offset change at that date. I think we could work around it until #6668 is fixed by using the offset that is active at `1970-01-01T00:00:00` for older dates rather than assuming `+0`.

**Comment by Araq** [comment] 2018-08-23 11:42
> What timezone is the machine in?

Berlin's.

**Closed** 2018-08-23 15:55 UTC
Labels: Showstopper, Stdlib
