### ISSUE TITLE
Tuple type mismatch with proc() - Returns None

### ISSUE THREAD

**Issue by PixeyeHQ** [nim-lang/Nim#13849] opened 2020-04-02 21:55 UTC
For some reason sending a proc() to a tuple returns None with *specific* proc names. By far I get None when naming procs as ***close() , dispose(), finished()***

type mismatch: got <int, tuple of (proc (){.noSideEffect, gcsafe, locks: 0.}, None)>

### Example
```nim
proc start*()=discard
proc tick*(delta:float)=discard
proc close*()=discard

# just to show the tuple
proc set_scn_ev*(id:int, events: tuple[start: proc(){.nimcall.}, close: proc(){.nimcall.}])=
  discard
# proc check
proc set_scn_ev*(id:int, ev: proc(){.nimcall.})=
  discard

set_scn_ev(id_scene_game,(start,close)) # error, close is treated as None
set_scn_ev(id_scene_game,close) # but this Is OK
```

### Current Output
```
type mismatch: got <int, tuple of (proc (){.noSideEffect, gcsafe, locks: 0.}, None)>
```

### Expected Output
It should compile

```
Nim Compiler Version 1.0.6 [Windows: amd64]
Nim Compiler Version 1.2.0 [Windows: amd64]
```

**Comment by metagn** [comment] 2020-04-03 09:51
Expected behaviour. `close` can mean either your proc or [this proc for closing files](https://nim-lang.org/docs/io.html#close%2CFile). What you have to do is qualify it, like `yourmodulename.close`. [finished](https://nim-lang.org/docs/system.html#finished%2CT) and [dispose](https://nim-lang.org/docs/system.html#dispose%2CForeignCell) are also defined in `system`.

**Comment by PixeyeHQ** [comment] 2020-04-03 10:17
Thanks for your answer :)

👍 I agree that those can be defined in System but let's look at this problem from a different angle. 
I'm a developer that wants to get a result and do things that from my point of view are legal. And as nothing prevents me from writing that code - I can write that code
And I get EXTREMELY confused because 
1) I still can define my custom finished proc to the proc() variable, it doesn't give me any error but gives me when I use that in a tuple.

2) The error itself gives me very little understanding of what's happening.
```but expression '(start, finished)' is of type: tuple of (proc (){.noSideEffect, gcsafe, locks: 0.}, None)```

Why it's None? I guess it could be much more informative if the error would be

Hey, you are trying to redefine the proc name ```finished``` from the system module, if you still wish to do what you want to consider adding ```[YOUR_MODULE_NAME].```
  
What do you think about that?

**Comment by ghost** [comment] 2020-04-03 10:51
Well, 1 is because Nim supports procedure overloading, so you can call both `close` as in your procedure, or close from system module by specifying different number of arguments (without the need to specify which module to call it from)

Although I agree that error message is really confusing

**Comment by metagn** [comment] 2020-04-03 14:40
Sorry, I was going to talk about the error message but I forgot, this isn't the first "type None" procvar error message issue, namely #6359 I would say is the same issue. I wouldn't close this for a duplicate though since #6359 doesn't really have a lot of examples but these issues are related and fixing both should be the focus.

**Closed as completed** 2022-12-01 07:01 UTC
Labels: Error Messages
