### ISSUE TITLE
Inconsistent results of macros/templates with typed parameters

### ISSUE THREAD

**Issue by jwollen** [nim-lang/Nim#11674] opened 2019-07-06 17:50 UTC
Macros and templates with `typed` parameters seem to leave some symbols behind when invoked with certain kinds of statements.

In the following example the macro is expected to remove the body block (as it does for an `untyped` body), leaving `someProc` and `someVar` undefined.

```nim
macro strip(body: typed): untyped =
  discard

strip:
  proc someProc() = discard
  var someVar = 42
  echo "someStatement"

someProc()
echo someVar
```

The `echo` is stripped as expected, while `someProc` is defined and callable anyway. `someVar` is defined, but is not generate by the backend, failing C++ compilation with
```
error: ‘someVar_KTklfhnW9bBhLTmHCQhffBg’ was not declared in this scope
```

The code seems correctly gone from the AST though, when inspecing it (e.g. with `expandMacros`). When returning the `body` in `strip`, all statements remain and work as expected.

Similarily, when using pragma syntax, the proc remains present too. 
```nim
proc someProc() {.strip.} = discard
someProc()
```
In this case however, when returning it from the macro, it gets redefined, making it impossible to replace it in such a macro.

**Comment by Araq** [comment] 2019-07-06 18:06
Widely known issue, but thanks for reporting it.

**Comment by krux02** [comment] 2019-07-07 08:57
duplicate of https://github.com/nim-lang/Nim/issues/4547

**Closed by krux02** 2019-07-07 08:57 UTC
