### ISSUE TITLE
Regression with `mixin` and generics from 2.0.8 to `version-2-0`/`version-2-2`, fixed in `devel`

### ISSUE THREAD

**Issue by tersec** [nim-lang/Nim#24163] opened 2024-09-23 12:22 UTC
### Description

```nim
type
  K = distinct int
  M = object

proc p(e: auto, T: type): T =
  mixin p
  p(e, result)

proc p[T](r: M, g: T) =
  when g is object:
    mixin p
    discard p(r, K)
  else:
    {.error: "u".}

proc p(_: M, _: K | K) = discard
```

### Nim Version

Builds:
`v2.0.8`:
```
Nim Compiler Version 2.0.8 [Linux: amd64]
Compiled at 2024-09-23
Copyright (c) 2006-2023 by Andreas Rumpf

git hash: 5935c3bfa9fec6505394867b23510eb5cbab3dbf
active boot switches: -d:release
```

`devel`:
```
Nim Compiler Version 2.1.99 [Linux: amd64]
Compiled at 2024-09-23
Copyright (c) 2006-2024 by Andreas Rumpf

git hash: a55c15c651b805c5eca4475f9845a57adf6cddef
active boot switches: -d:release
```

Does not build:
`version-2-0`:
```
Nim Compiler Version 2.0.9 [Linux: amd64]
Compiled at 2024-09-23
Copyright (c) 2006-2023 by Andreas Rumpf

git hash: 27381cc60213e19aa34664176bd358ca5e45bd5a
active boot switches: -d:release
```

`version-2-2`:
```
Nim Compiler Version 2.1.99 [Linux: amd64]
Compiled at 2024-09-23
Copyright (c) 2006-2024 by Andreas Rumpf

git hash: 755307be61e4ee7b32c8354b2c303d04bdfc3a3e
active boot switches: -d:release
```

### Current Output

```text
/tmp/v.nim(17, 10) template/generic instantiation of `p` from here
/tmp/v.nim(7, 4) template/generic instantiation of `p` from here
/tmp/v.nim(14, 12) Error: u
```

### Additional Information

Fixed in `devel`, so presumably there's something to backport from `devel` to `version 2-0`/`version-2-2`.

**Comment by metagn** [comment] 2024-09-23 13:26
Was caused by #23870 and fixed by #24144 @narimiran

**Comment by narimiran** [comment] 2024-09-23 14:44
> Was caused by #23870 and fixed by #24144 @narimiran

Thanks for the ping. Backported now. @tersec, it should be ok now (the example now works on my machine).

**Comment by tersec** [comment] 2024-09-23 15:29
> > Was caused by #23870 and fixed by #24144 @narimiran
> 
> Thanks for the ping. Backported now. @tersec, it should be ok now (the example now works on my machine).

Well, I realized the repro I posted above somehow omitted the last line, so it always compiles. For reference, one example of how to complete it:

```nim
type
  K = distinct int
  M = object

proc p(e: auto, T: type): T =
  mixin p
  p(e, result)

proc p[T](r: M, g: T) =
  when g is object:
    mixin p
    discard p(r, K)
  else:
    {.error: "u".}

proc p(_: M, _: K | K) = discard
p(default(M), default(K))
```

and, obviously, that first `p` overload isn't used anymore, and
```nim
type
  K = distinct int
  M = object

proc p[T](r: M, g: T) =
  when g is object:
    mixin p
    discard p(r, K)
  else:
    {.error: "u".}

proc p(_: M, _: K | K) = discard
p(default(M), default(K))
```
exhibits the same pattern.

But haven't verified yet with new `version-2-0`.

**Comment by metagn** [comment] 2024-09-23 16:06
I noticed and forgot to mention it, that's what I used to check the issue

**Comment by narimiran** [comment] 2024-09-29 10:12
The fix is backported, I think this can be closed. (If not, please reopen)

**Closed as completed by narimiran** 2024-09-29 10:12 UTC
Labels: Needs Backporting/Fixed in Devel
