### ISSUE TITLE
Let arguments be left as optional when using "do" notation.

### ISSUE THREAD

**Issue by ReneSac** [nim-lang/Nim#884] opened 2014-02-08 15:06 UTC
This is a feature request, because I want to have optional arguments usable when using do notation. For example:

```nim
template timeit*(number: int = 0, repeat: int = 3, code: stmt): float = 
  var sw = StopWatchInit()
  code
  sw.peek


echo timeit do:  # Have number and repeat as optional arguments
  swtest()     
```

As the "do" can only fill the arguments starting from the last one, there is no ambiguity in letting the optional arguments before it be left unfiled.

**Comment by krux02** [comment] 2018-10-20 20:33
You can use multiple overloads.

```nim
template timeit*(number, repeat: int; code: untyped): untyped =
  echo "start"
  code
  echo "done"

template timeit*(code: untyped): untyped =
  timeit(0,3,code)

timeit:  # Have number and repeat as optional arguments
  echo "hello world"
```

**Comment by Araq** [comment] 2018-10-22 08:57
> You can use multiple overloads.

Ha, but currently you cannot. Overloaded templates need to agree on the position of ``untyped`` parameters.

**Comment by krux02** [comment] 2019-06-05 14:37
@Araq generally you are right, but in this case the overload is unique by the number of arguments used. And the posted code example does work.

**Comment by timotheecour** [comment] 2020-11-13 18:06
closing as duplicate of https://github.com/nim-lang/Nim/issues/14346 (even though this issue is older)

**Closed** 2020-11-13 18:08 UTC
Labels: Feature
