### ISSUE TITLE
Keep Getting Error while attempting to compile

### ISSUE THREAD

**Issue by Lite5h4dow** [nim-lang/Nim#7328] opened 2018-03-12 14:25 UTC
Error = `HError: unhandled exception: Unknown IO Error [IOError]`

Cause = Unknown

Only ever happens when I attempt to compile a program. and happens frequently but always at a random time. could be 2 lines in could be 10.

**Comment by Yardanico** [comment] 2018-03-12 15:22
@Lite5h4dow I assume you use VSCode ? This is a VSCode bug

**Comment by Yardanico** [comment] 2018-03-12 15:22
@Lite5h4dow probably a duplicate of this - https://github.com/nim-lang/Nim/issues/7111

**Closed** 2018-03-18 12:26 UTC
