### ISSUE TITLE
{.this: self.} does not work with Static[T]

### ISSUE THREAD

**Issue by mratsim** [nim-lang/Nim#7618] opened 2018-04-15 22:25 UTC
Here is a working non-static version and the static version.

With static I get `undeclared identifier`

```Nim
type Bar = object
    baz: int

{.this: self.}
proc foo(self: Bar) =
  echo(baz)

foo(Bar(baz: 1))

############################################

type Bar2[N: static[int]] = object
    baz2: int

{.this: self.}
proc foo2[N: static[int]](self: Bar2[N]) =
  echo(baz2) # Undeclared identifier baz2

foo2(Bar2[10](baz2: 1))
```

**Comment by zah** [comment] 2018-04-16 14:34
Duplicate of https://github.com/nim-lang/Nim/issues/7177

**Closed by zah** 2018-04-16 14:34 UTC
Labels: Generics, {.this: self.}
