### ISSUE TITLE
Confusing error behavior when calling slice[T].random

### ISSUE THREAD

**Issue by subsetpark** [nim-lang/Nim#5430] opened 2017-02-24 18:55 UTC
Nim Compiler Version 0.16.1 (2017-02-03) [MacOSX: amd64]
Copyright (c) 2006-2017 by Andreas Rumpf

git hash: 4ac6a2603167a3199dfce60f07dba3a5188ea7a8
active boot switches: -d:release -d:useLinenoise

------

Here's a sample snippet:

```nimrod
import random
let slice = 10.cshort..15.cshort
slice.random
```

It produces the following compiler error:

```
scratch2.nim(3, 6) template/generic instantiation from here
lib/pure/random.nim(98, 30) Error: type mismatch: got (int) but expected 'cshort = int16'
```

Which is confusing, because `random` is implemented as a generic over `Slice[T]`, so it appears that it should return a random `cshort`.

**Comment by dom96** [comment] 2017-02-24 19:01
For reference, here is the ``random`` definition:

```nim
proc random*[T](x: Slice[T]): T =
  ## For a slice `a .. b` returns a value in the range `a .. b-1`.
  result = random(x.b - x.a) + x.a
```

So I think that this shows two problems:

* The error message could be much clearer, it should make reference to the return type of the proc. I thought that the problem was caused by a missing ``+(x: int, y: int16): int`` initially, but it turns out that what is assigned to ``result`` doesn't match ``T``. In @subsetpark's case, ``T`` is ``cshort`` (``int16``) and the ``+`` returns an ``int``. This error message doesn't make that obvious.

* The ``random`` proc doesn't handle smaller-sized integer types correctly. 

The workaround may just simply be to convert your ``Slice[cshort]`` to a ``Slice[int]``.

**Comment by Araq** [comment] 2017-02-24 19:14
I don't know why your reading incompetence needs to be turned into a "error messages" issue. The error message is perfectly clear, it doesn't list '+' so the '+' is not the problem, but the assignment is.

**Closed** 2017-02-25 23:44 UTC
Labels: error messages, Stdlib
