### ISSUE TITLE
`when a() and b()` should short-circuit semcheck

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/Nim#13502] opened 2020-02-26 01:33 UTC
`when declared(Foo) and T is Foo:` fails but there's no reason to: `and` should short-circuit semcheck of 2nd arg when 1st arg is false

### Example
```nim
type T = int
static: doAssert not declared(Foo) # ok
# all these fail with: Error: undeclared identifier: 'Foo'
when declared(Foo) and T is Foo: discard
when false and T is Foo: discard
const isFoo1 = declared(Foo) and (T is Foo)
const isFoo2 = false and (T is Foo)
```

### Current Output
```
Error: undeclared identifier: 'Foo'
```

### Expected Output
works.

in particular, this is useful for eg in generic code in include files etc where you need to specialize for some types, but these may not be present

### workaround
```nim
  template ctAnd(a, b): bool =
    when a:
      when b: true
      else: false
    else: false

  type T = int
  type Bar = int
  static: doAssert not ctAnd(declared(Foo), T is Foo)
  static: doAssert ctAnd(declared(Bar), T is Bar)
  static: doAssert not ctAnd(declared(Bar), T isnot Bar)
```

### Additional Information

* 3dad130034e3212159dda5d61988ca2b18959b24 devel 1.1.1

**Comment by krux02** [comment] 2020-02-26 02:33
what you want is short circuit semantic checking not short circuit evaluation. The later one already happens. And btw -1 for the feature request.

**Comment by Araq** [comment] 2020-02-26 10:00
This is a bug, not a feature request. In fact, it's a duplicate of some other bug report.

**Comment by Araq** [comment] 2020-03-02 09:58
I take it back, I misunderstood this problem. This is not a bug, the sem'checking for ``and`` follows Nim's basic rules and it's overloaded even, so no ``untyped´`-like behaviour is desired.

**Closed as completed by Araq** 2020-03-02 09:58 UTC
Labels: Won't Fix
