### ISSUE TITLE
Call operator conflicts with `newSeq`

### ISSUE THREAD

**Issue by jwollen** [nim-lang/Nim#9831] opened 2018-11-30 15:30 UTC
The following fails to compile. Curiously other generic calls, e.g. `newSeqOfCap` work.
```nim
{.experimental: "callOperator".}

type Foo = object
proc `()`(foo: Foo) = discard
let x = newSeq[int]()
```

**Comment by metagn** [comment] 2021-02-09 01:09
Duplicate of #6981

**Closed** 2022-11-28 20:33 UTC
