### ISSUE TITLE
Equality is not working if Ref Object defined in a block scope

### ISSUE THREAD

**Issue by al6x** [nim-lang/Nim#17965] opened 2021-05-07 23:01 UTC
The equality operator `==` works incorrectly if the `ref object` is defined inside of a `block:` scope.

In the example the result of `@[a] == @[b]` would be `false`, but if the block scope removed, it will be `true`.

### Example

[playground](https://play.nim-lang.org/#ix=3m7W)

```nim
if is_main_module: # or block:
  type User = ref object
    id: int

  proc `==`(a, b: User): bool = a[] == b[]

  var a = User(id: 1)
  var b = User(id: 1)
  echo a == b       # ==> true
  echo @[a] == @[b] # ==> false - Error!
```

```
Nim Compiler Version 1.4.6 [MacOSX: amd64]
Compiled at 2021-05-06
Copyright (c) 2006-2020 by Andreas Rumpf

active boot switches: -d:release```

**Comment by timotheecour** [comment] 2021-05-07 23:16
sounds like duplicate of https://github.com/nim-lang/Nim/issues/13747

ok to close this as duplicate?

**Comment by al6x** [comment] 2021-05-07 23:20
Sure, thanks!

**Closed as completed** 2021-05-07 23:20 UTC
