### ISSUE TITLE
Sometimes closing a Channel will cause a segfault on Windows

### ISSUE THREAD

**Issue by johnnovak** [nim-lang/Nim#4747] opened 2016-09-10 02:53 UTC
As the title says... It's completely random and doesn't happen too frequently, but it's still a bug. I guess the workaround is to never close my channels and let the be cleanup up on application exit, but this still should be fixed sometime...

Some examples:

```
channels.nim(260)        close
channels.nim(49)         deinitRawChannel
alloc.nim(686)           deallocOsPages
alloc.nim(172)           llDeallocAll
SIGSEGV: Illegal storage access. (Attempt to read from nil?)
```

```
channels.nim(260)        close
channels.nim(49)         deinitRawChannel
alloc.nim(218)           deallocOsPages
SIGSEGV: Illegal storage access. (Attempt to read from nil?)
```

**Comment by Araq** [comment] 2017-02-02 10:49
The cause for these crashes has finally been found. Can you test again?

**Comment by Araq** [comment] 2018-07-01 09:06
No feedback, closing.

**Closed by Araq** 2018-07-01 09:06 UTC
Labels: S: Waiting on author
