### ISSUE TITLE
break in closure iterator causes `finally` to be executed twice

### ISSUE THREAD

**Issue by dom96** [nim-lang/Nim#20624] opened 2022-10-22 22:20 UTC
```nim
import asyncdispatch

proc tryFinally(){.async.} =
  block route:
    try:
      echo "trying"
      raise
    except:
      echo "exception caught"
      break route
    finally:
      echo "finally block"
```

Output:

```
trying
exception caught
finally block
finally block
```

Originally reported in https://github.com/dom96/jester/issues/301. CC @sdmcallister

**Comment by dom96** [comment] 2022-10-22 22:21
Actually seems to be a closure iterator bug. Same result for:

```nim
iterator tryFinally() {.closure.} =
  block route:
    try:
      echo "trying"
      raise
    except:
      echo "exception caught"
      break route
    finally:
      echo "finally block"

var x = tryFinally
x()
```

**Comment by ringabout** [comment] 2022-10-23 07:24
Duplicate of https://github.com/nim-lang/Nim/issues/18824

**Closed as completed** 2022-10-23 13:56 UTC
