### ISSUE TITLE
std/segfaults doesn't raise (reliably?) NilAccessDefect on ARM64 Linux nor windows

### ISSUE THREAD

**Issue by alaviss** [nim-lang/Nim#17114] opened 2021-02-20 05:09 UTC
### Build log
See full log [here](https://github.com/nim-lang/nightlies/runs/1939486935?check_suite_focus=true#step:9:5906)

```
   Hint: /home/runner/work/nightlies/nightlies/nim-1.5.1/build/nimcache/nim/wrapnils_r/runnableExamples/wrapnils_group0_examples  [Exec]
  0
  /home/runner/work/nightlies/nightlies/nim-1.5.1/lib/system/assertions.nim(125) wrapnils_examples1
  /home/runner/work/nightlies/nightlies/nim-1.5.1/lib/system/assertions.nim(58) raiseAssert
  /home/runner/work/nightlies/nightlies/nim-1.5.1/lib/system/fatal.nim(53) sysFatal
  Error: unhandled exception: expected raising 'NilAccessDefect', instead nothing was raised by: 
  echo (?.f2.x2.x2).x3[] [AssertionDefect]
  Error: execution of an external program failed: '/home/runner/work/nightlies/nightlies/nim-1.5.1/build/nimcache/nim/wrapnils_r/runnableExamples/wrapnils_group0_examples '
  [runnableExamples] failed: generated file: '/home/runner/work/nightlies/nightlies/nim-1.5.1/build/nimcache/nim/wrapnils_r/runnableExamples/wrapnils_group0_examples.nim' group: 'rdoccmd: 
  docCmd: 
  code: # autogenerated by docgen
  # source: /home/runner/work/nightlies/nightlies/nim-1.5.1/lib/std/wrapnils.nim
  # rdoccmd: 
  import r"/home/runner/work/nightlies/nightlies/nim-1.5.1/build/nimcache/nim/wrapnils_r/runnableExamples/wrapnils_examples1.nim"
  
  index: 0
  ' cmd: /home/runner/work/nightlies/nightlies/nim-1.5.1/bin/nim c -r --lib:/home/runner/work/nightlies/nightlies/nim-1.5.1/lib --warning:UnusedImport:off --path:/home/runner/work/nightlies/nightlies/nim-1.5.1/lib/std --nimcache:/home/runner/work/nightlies/nightlies/nim-1.5.1/build/nimcache/nim/wrapnils_r/runnableExamples   /home/runner/work/nightlies/nightlies/nim-1.5.1/build/nimcache/nim/wrapnils_r/runnableExamples/wrapnils_group0_examples.nim
  
  Took 71m16.120s
  Error: Process completed with exit code 1.
```

### Additional Information

First happened with [Nightlies build #205](https://github.com/nim-lang/nightlies/runs/1859390226?check_suite_focus=true#step:9:4242), commit ba64d0c8ab93c7f38b87567059cb2b66747d022c.

Commit: 1efaef52a2f916441d153917486ef8a4218a6111

## links
related:
* [SIGSEGV hangs instead of raising NilAccessDefect with `import segfaults` and gc:arc · Issue #16415 · nim-lang/Nim](https://github.com/nim-lang/Nim/issues/16415)
* [memory corrupted; possibly by try/catch using `import segfaults` · Issue #9752 · nim-lang/Nim](https://github.com/nim-lang/Nim/issues/9752)
* (somewhat related) [setControlCHook - Nim forum](https://forum.nim-lang.org/t/7886)

**Comment by Araq** [comment] 2021-02-24 22:04
It works when you disable these lines:

```
#  import std/segfaults # enable `NilAccessDefect` exceptions
#  doAssertRaises(NilAccessDefect): echo (?.f2.x2.x2).x3[]
```

**Comment by timotheecour** [comment] 2021-02-25 01:20
I've sent out https://github.com/nim-lang/Nim/pull/17178 which should fix nightlies but let's keep this issue open, it looks like a bug that's specific to arm64

Before closing this we should investigate:
* whether it's a bug in arm64 platform (unlikely) and if so can this be mitigated
* whether there's something codegen should do to handle arm64 correctly
* we also need a minimzed test case; preferably someone who has access to a arm64 machine could help with that

(and yes, `segfaults` is useful and should be supported; example use cases include long running processes, REPL's or code taking possilby buggy user code that should survive segfaults, debugging, etc)

**Comment by alaviss** [comment] 2021-02-25 03:39
> whether it's a bug in arm64 platform (unlikely)

It seems to be one ATM, @Araq managed to reproduce it on his M1 Mac

**Comment by timotheecour** [comment] 2021-02-25 04:09
> It seems to be one ATM

but we should determine whether it's a bug with nim's codegen on arm64 or whether the bug can be reproduced with plain C (not generated by nim)

**Comment by Araq** [comment] 2021-02-25 07:37
As far as I can tell, our `segfaultHandler` is simply not signal-safe and it's unclear how it can be written in a signal-safe style.

**Comment by johnnovak** [comment] 2021-05-01 02:53
I can't get `segfaults` to work on Windows 10 either. This is an essential feature for desktop applications shipped to users; in case of any error, you want to capture the stacktrace in a crash log, then the user can send you that file along with the bug report.

```nim
import segfaults

type
  Obj = ref object
    a: int

try:
  var o: Obj
  o.a = 5

except NilAccessDefect as e:
  echo "### NilAccessDefect caught: " & e.msg
  writeStackTrace()

except Exception as e:
  echo "### Exception caught: " & e.msg
  writeStackTrace()
```

Output:

```
Traceback (most recent call last)
D:\Work\Code\gridmonger\errortest.nim(9) errortest
SIGSEGV: Illegal storage access. (Attempt to read from nil?)
Error: execution of an external program failed: 'D:\Work\Code\gridmonger\errortest.exe '
```

**Comment by timotheecour** [comment] 2021-05-01 05:57
what's the output you get for:
```
nim -v
nim c -r tests/stdlib/tstdlib_various.nim
```

I'm asking this because that test runs in CI (including on windows)

**Comment by johnnovak** [comment] 2021-05-01 23:30
> 
> 
> what's the output you get for:
> 
> ```
> nim -v
> nim c -r tests/stdlib/tstdlib_various.nim
> ```
> 
> I'm asking this because that test runs in CI (including on windows)

```
Nim Compiler Version 1.4.6 [Windows: amd64]
Compiled at 2021-04-15
Copyright (c) 2006-2020 by Andreas Rumpf

active boot switches: -d:release
```

Output for `nim c -r tests/stdlib/tstdlib_various.nim`:

```
abc
def
definition
prefix
xyz
def
definition
Hi Andreas! How do you feel, Rumpf?

@[0, 2, 1]
@[1, 0, 2]
@[1, 2, 0]
@[2, 0, 1]
@[2, 1, 0]
@[2, 0, 1]
@[1, 2, 0]
@[1, 0, 2]
@[0, 2, 1]
@[0, 1, 2]
055this should be the casehugh@["(", "+", " 1", " 2", ")"]
caught a crash!
caught a crash!
caught a crash!
caught a crash!
caught a crash!
caught a crash!
[5]
[4, 5]
[3, 4, 5]
[2, 3, 4, 5]
[2, 3, 4, 5, 6]
[1, 2, 3, 4, 5, 6]
true
<h1><a href="http://force7.de/nim">Nim</a></h1>

```

But when I run with `gc:arc`, so `nim c --gc:arc -r tests/stdlib/tstdlib_various.nim`:

```
abc
def
definition
prefix
xyz
def
definition
Hi Andreas! How do you feel, Rumpf?

@[0, 2, 1]
@[1, 0, 2]
@[1, 2, 0]
@[2, 0, 1]
@[2, 1, 0]
@[2, 0, 1]
@[1, 2, 0]
@[1, 0, 2]
@[0, 2, 1]
@[0, 1, 2]
055this should be the casehugh@["(", "+", " 1", " 2", ")"]
Traceback (most recent call last)
tstdlib_various.nim(175) tstdlib_various
tstdlib_various.nim(167) main
SIGSEGV: Illegal storage access. (Attempt to read from nil?)
Error: execution of an external program failed: 'C:\dev\nim-1.4.6-x64\tests\stdlib\tstdlib_various.exe '
```

Bamm, ARC is the problem! I guess I could live without it; I just turned it on because it's supposed to be the best GC for Nim.

**Comment by timotheecour** [comment] 2021-05-01 23:34
in this case, should we close this issue as duplicate of https://github.com/nim-lang/Nim/issues/16415 ? /cc @alaviss were you using --gc:arc as well?

**Comment by alaviss** [comment] 2021-09-17 06:09
> in this case, should we close this issue as duplicate of #16415 ? /cc @alaviss were you using --gc:arc as well?

Nope, this is just a standard `./koch docs` from nightlies CI.

**Comment by Araq** [comment] 2021-09-19 22:40
segfaults is simply broken and needs to be removed from Nim.

**Closed as completed by Araq** 2021-09-19 22:40 UTC
Labels: Won't Fix, OS/Architecture Specific

**Comment by theAkito** [comment] 2021-09-19 22:55
> segfaults is simply broken and needs to be removed from Nim.

Will there be any kind of replacement or alternative in any form?
