### ISSUE TITLE
Using generics in template where instantiate a object with generics got a compile error

### ISSUE THREAD

**Issue by lguzzon** [nim-lang/Nim#10167] opened 2019-01-02 10:27 UTC
Using generics in template where instantiate a object with generics got a compile error

### Example
```nim
type
  Maybe* [T] =  object {. final .}
    case hasValue*: bool
    of true: value*: T
    else: discard


proc Just* [T](aValue: T): Maybe[T] {. inline .} =
  result = Maybe[T](hasValue: true, value: aValue)

template template_Just* [T](aValue: T): Maybe[T] =
  Maybe[T](hasValue: true, value: aValue)

proc Nothing* [T]: Maybe[T] {. inline .} =
  result = Maybe[T](hasValue: false)

echo Just[int](1)
echo template_Just[int](1)
```

### Current Output
```sh
Hint: used config file 'C:\Users\a72c\scoop\apps\nim\current\config\nim.cfg' [Conf]
Hint: system [Processing]
Hint: issueTemplateGenerics [Processing]
issueTemplateGenerics.nim(22, 24) template/generic instantiation from here
issueTemplateGenerics.nim(13, 8) Error: cannot instantiate Maybe
got: <int>
but expected: <T>
```
Code compiled with Nim (nim 0.19.2) 

### Expected Output
```sh
(hasValue: true, value: 1)
(hasValue: true, value: 1)
```
See [here](https://ideone.com/haKCmu) code compiled with Nim (nim 0.16.0)

**Comment by bluenote10** [comment] 2019-01-02 13:17
Duplicate of https://github.com/nim-lang/Nim/issues/5926?

**Comment by lguzzon** [comment] 2019-01-02 14:40
Yes!!!
Thanks

**Comment by krux02** [comment] 2019-01-02 15:00
Closing this because it is a duplicate.

**Closed by krux02** 2019-01-02 15:00 UTC
Labels: Generics, Templates
