### ISSUE TITLE
"value out of range" error when using +/- signs with intXX.high/low in case..of..else expression

### ISSUE THREAD

**Issue by xomachine** [nim-lang/Nim#8815] opened 2018-08-30 14:09 UTC
I think I've found the regression in upcoming 0.18.1 version. Take a look at the example:
```nim
const y = 127
let x = 0
case x
of (int8.high+1)..int16.high:    # replace this
#of 128..int16.high:             # with this to make it working
#of (127+1)..int16.high:         # this works as well
#of (y+1)..int16.high:           # and this too
  echo("between int8.high and int16.high")
else:
  echo("between int8.high and int16.high")
```
On the version 0.18.0 it compiles perfectly:
```bash
$ nim -v
Nim Compiler Version 0.18.0 [Linux: amd64]
Copyright (c) 2006-2018 by Andreas Rumpf

active boot switches: -d:release -d:nativeStackTrace
$ nim c --run test.nim 
Hint: used config file '/etc/nim.cfg' [Conf]
Hint: system [Processing]
Hint: test [Processing]
CC: nesm_test
Hint:  [Link]
Hint: operation successful (11722 lines compiled; 0.267 sec total; 22.727MiB peakmem; Debug Build) [SuccessX]
Hint: /home/xomachine/.Soft/projects/nesm/test  [Exec]
not between int8.high+1 and int16.high
```
But version 0.18.1 from devel shows an compilation error:
```bash
$ nim -v
Nim Compiler Version 0.18.1 [Linux: amd64]
Compiled at 2018-08-30
Copyright (c) 2006-2018 by Andreas Rumpf

git hash: 3e6b58323bb1c33bfa6d1a70905ee10e4f20f638
active boot switches:
$ nim c --run test.nim 
Hint: used config file '/home/xomachine/.Soft/projects/Nim/config/nim.cfg' [Conf]
Hint: system [Processing]
Hint: test [Processing]
stack trace: (most recent call last)
test.nim(3)
test.nim(3, 14) Error: unhandled exception: value out of range
```

**Comment by hlaaftana** [comment] 2018-08-30 14:46
It should error, `int8.high + 1` is a glaring overflow. The following compiles and runs in devel:

```nim
let x = 0
case x
of (int8.high.int + 1)..int16.high.int: # also works if you do int16.high
  echo "between int8.high and int16.high"
else:
  echo "not between int8.high and int16.high"
```

Error should probably be OverflowError and not RangeError though.

**Comment by xomachine** [comment] 2018-08-30 14:56
Well, I expected that int8.high + 1 will result some bigger integer like `int16` or just `BiggestInt`. Especially considering that in my original code the `x`s type is int64 and the expression can be evaluated at the compile time. Although, there is not overloading by return value in Nim.

May be the `intXX.high/low` values should be something like a macro that returns a literal instead of the value of the intXX type?

**Comment by Araq** [comment] 2018-08-30 15:05
That's not how arithmetic works in Nim, there is no promotion to "bigger types", int8 + int literal(X) produces the type int8.

**Comment by GULPF** [comment] 2019-06-07 22:57
Closing since it's working as intended

**Closed by GULPF** 2019-06-07 22:57 UTC
