### ISSUE TITLE
''nil' statement is deprecated' in macro

### ISSUE THREAD

**Issue by vegansk** [nim-lang/Nim#3561] opened 2015-11-19 06:21 UTC
This code must print ``"test"`` to the console.
```nimrod
import macros, future, strutils

type
  Option[T] = ref object
    case valid: bool
    of true:
      data: T
    else:
      discard

proc some[T](v: T): Option[T] = Option[T](valid: true, data: v)
proc none[T](v: T): Option[T] = Option[T](valid: false)
proc none(T: typedesc): Option[T] = Option[T](valid: false)

proc map[T,U](o: Option[T], f: T -> U): Option[U] =
  case o.valid
  of true:
    f(o.data).some
  else:
    U.none

proc notEmpty(o: Option[string]): Option[string] =
  case o.valid
  of true:
    if o.data.strip == "": string.none else: o.data.strip.some
  else:
    o

proc getOrElse[T](o: Option[T], def: T): T =
  case o.valid
  of true:
    o.data
  else:
    def

proc quoteStr(s: string): Option[string] =
  s.some.notEmpty.map(v => "\"" & v & "\"")

macro str(s: static[string]): stmt =
  let sn = newStrLitNode(quoteStr(s).getOrElse("NONE"))
  result = quote do:
    echo `sn`

str"Test"
```

But it comiles with warning:
```
macro_issue.nim(36, 6) Warning: 'nil' statement is deprecated; use an empty 'discard' statement instead [NilStmt]
```
and does nothing when run

**Comment by vegansk** [comment] 2016-03-23 10:26
Still not working...

**Comment by Araq** [comment] 2016-04-04 00:10
It's the ``map`` that doesn't work at compile-time.

**Comment by Araq** [comment] 2016-04-04 00:26
Seems to be a duplicate of #2409.

**Closed** 2016-04-04 00:45 UTC
Labels: High Priority, VM
