### ISSUE TITLE
arc bug using iterator parentDirs returning inside a try

### ISSUE THREAD

**Issue by c-blake** [nim-lang/Nim#22001] opened 2023-06-04 13:20 UTC
### Description

```Nim
import std/os

iterator parentDirs*(path: string, fromRoot=false, inclusive=true): string =
# Nim-devel-f552618d6b1cddee3fdad7b4cf1917481ca346d4 w/arc breaks here
# finding `current` to be "" prematurely.  Nim-1.6.12 works.  iterator
# lifted from `lib/std/private/ospaths2.nim` to be more self-contained.
  if not fromRoot:  # Commenting out the if & else: when.. hides bug
    var current = path
    if inclusive: yield path
    while true:
      if current.isRootDir: break # <- current=="" => current.isRootDir
      current = current.parentDir
      yield current
  else: # Any simplification below that drops `for` hides bug
    when doslikeFileSystem:
      let start = path.splitDrive.drive.len
    else:
      const start = 0
    for i in countup(start, path.len - 2): # ignore the last /
      if path[i] in {DirSep, AltSep} and
          (i == 0 or path[i-1] notin {DirSep, AltSep}):
        yield path.substr(0, i)
    if inclusive: yield path

proc finOp(wd, name: string): (string,File) = # Find & open FIRST `name`
  for dir in parentDirs(wd):                  #.. going up to the root.
    echo dir  # Commenting out try/except below hides bug
    try: result[0] = dir/name; result[1] = open(result[0]); return
    except CatchableError: discard

let (path, f) = finOp("/1/2/3", "4")  # All same if this->inside a proc
```

### Nim Version

I tried both Nim-devel f552618d6b1cddee3fdad7b4cf1917481ca346d4 as well as Nim-devel 767fec164088f3a808740805e9605fb5354435d2 .

### Current Output

```text
/1/2/3
/1/2
```

### Expected Output

```text
/1/2/3
/1/2
/1
/
```

### Possible Solution

I just worked around this by not doing some of the things where the comments say it hides the bug.

### Additional Information

The problem does not seem to manifest on Nim-1.6.12 or with either `--mm:markAndSweep` or `--mm:refc`.

So, someone with more patience than I have at the moment could run `nim c --expandArc:finOp --mm:arc this.nim` or maybe do a `git bisect` first.

EDIT: I first tested this code about 3..4 weeks prior to this issue filing and I did not notice this problem then.

**Comment by ringabout** [comment] 2023-06-05 06:00
It's quite infuriating to bisect this problem because I have to switch to 1.6.12 compiler and do some git stash tricks constantly.

Nevertheless, here is probably the regression that causes this issue => https://github.com/nim-lang/Nim/pull/20471

**Comment by c-blake** [comment] 2023-06-05 08:52
Thank you for having the patience to track that down (to an admittedly large set of changes).

**Comment by Araq** [comment] 2023-06-05 09:50
Nonsense, the new move analyser is perfect. The problem is Kauffman's string tunneling device.

**Comment by Araq** [comment] 2023-06-27 18:28
Reduced to:

```nim

proc finOp2(path, name: string): (string,File) = # Find & open FIRST `name`
  var current = path
  while true:
    if current.isRootDir: break # <- current=="" => current.isRootDir
    current = current.parentDir
    let dir = current
    echo dir  # Commenting out try/except below hides bug
    try: result[0] = dir/name; result[1] = open(result[0]); return
    except CatchableError: discard

let (path, f) = finOp2("/1/2/3", "4")  # All same if this->inside a proc
```

**Comment by Araq** [comment] 2023-06-27 18:42
The control flow graph move analyser misinterprets the `try except`.

**Comment by c-blake** [comment] 2023-06-27 18:49
I am glad you looked into it!  FWIW, I cannot get *current* nim-devel to break with that same code.  So, we may need a more robustly breaking test case.  I suppose one could bisect again the current head with one of those two revisions I mentioned to see what perturbed things, but unless it was intentionally fixed there is probably still a bug lurking.

**Comment by Araq** [comment] 2023-06-27 19:29
It's all trivial to reproduce for me and a fix is in the CI now. No worries.

**Closed as completed** 2023-06-27 20:42 UTC
Labels: Showstopper, Regression, ARC/ORC Memory Management
