### ISSUE TITLE
JS backend doesn't handle float->int type conversion 

### ISSUE THREAD

**Issue by dom96** [nim-lang/Nim#8404] opened 2018-07-22 22:06 UTC
Untested but should give a pretty close idea of what the bug was:

```nim
import math
var x = 5.5
doAssert $(x.int64) == "5.5"
doAssert $(round(x).int64) == "6"
```

**Comment by krux02** [comment] 2018-08-01 12:53
I tested it, the javascript compiler generates code likes this ``cstrToNimstr((((x_127014)|0))+"")``, that is correct, it converts ``x`` → ``int`` → ``js string`` → ``nim string``

**Comment by dom96** [comment] 2018-08-03 14:38
You mean that my code works? Perhaps my reproduction doesn't work :/

**Comment by skilchen** [comment] 2018-08-03 17:47
Keep in mind that the js backend has no support for `int64`. The conversion to `int` works, as long as your `int` fits into an `int32`. I don't know if it is a good thing that the js backend conversion to int64 simply returns the umodified input. If you want to change that you would have to modify line [1843 in  jsgen.nim](https://github.com/nim-lang/Nim/blob/devel/compiler/jsgen.nim#L1843) from:
```
  of tyInt:
```
to
```
  of tyInt, tyInt64:
```

**Comment by dom96** [comment] 2018-08-03 17:50
> I don't know if it is a good thing that the js backend conversion to int64 simply returns the umodified input. 

From what I can tell that behaviour is buggy. A ``$`` on an integer shouldn't give me a float.

**Comment by skilchen** [comment] 2018-08-03 18:33
The advantage of the current solution is that something like `x.int64 div 1` gives correct results on a much larger range of inputs (~ +/- 2^52) than if you force the conversion to `int64` to be something else than a noop (~ +/- 2^31).

You have to be aware that you are on buggy territory if you use `int64` (or any kind of `uint`) on the js backend. I don't think that Nim should enforce this 'awareness' by eg. raising exceptions if you try to use something that is not properly supported on the js backend.

**Comment by krux02** [comment] 2018-08-03 20:56
@dom96 I don't know what you are talking about. I can't reproduce your problem. ``(5.5 | 0) + ""`` in javascript returns ``"5"`` as a string, not ``"5.5"`` as you are claiming.
@skilchen No, you are not correct. the the  ``(x | 0)`` operation actually converts to ``int32``. So ``x.int64 div 1`` is as good as ``x.int32 div 1``.  You should treat ``int64`` as non-existent when compiling to javascript.

**Comment by skilchen** [comment] 2018-08-03 21:27
@krux its better to try out running examples than to theorize:
```
var x = 5.5
echo x.int64
``` 
gives:
```
5.5
```
on the js backend.

and 
```nim
import math
var x = 2.0 ^ 52
echo x.int64 div 1
```
gives:
```
4503599627370496
```
which is clearly not the same as
```nim
import math
var x = 2.0 ^ 52
echo x.int32 div 1
```
giving:
```
0
```
on the js backend.

All using:
```
Nim Compiler Version 0.18.1 [Linux: amd64]
Copyright (c) 2006-2018 by Andreas Rumpf

git hash: 9a390d66fb86eb68851000738be5744bea1261a0
active boot switches: -d:release
```
And if you carefully look at the generated JavaScript code you will see, that you made a mistake claiming
that x.int64 will be translated to (x | 0).

**Comment by krux02** [comment] 2018-08-03 21:56
Well I don't know how to run the js backend, ``nim js -r`` doesn't work. But you are right I checked again, this time there was no ``(x|0)``. Last time I checked, there was one.

**Comment by skilchen** [comment] 2018-08-03 22:10
You need to have [Node.js](https://nodejs.org) installed to use `nim js -r`.

**Comment by dom96** [comment] 2018-08-03 22:11
@krux02 it really would have been better not to state:

> I tested it

Because that sounds like you're claiming that you've compiled to JS and tested the code in your browser.

**Comment by dom96** [comment] 2018-08-03 22:13
In any case, I don't know how much more clearly I can describe the issue. The examples at the top should be clear enough.

**Comment by dom96** [comment] 2018-08-03 22:14
> You have to be aware that you are on buggy territory if you use int64 (or any kind of uint) on the js backend.

When I'm using the JS backend I don't think about these things and I think that's fine. We shouldn't expect users to know about such edge cases. Nim should either give a compile-time error or the semantics of int64 in JS should be the same as for the C backend.

**Comment by krux02** [comment] 2018-08-04 12:56
@dom96 I did test it. I compiled. and testet the generated code in the browser. For some reason the first test I did ther compiler generated different code. It had the ``x | 0`` in there.

**Comment by metagn** [comment] 2020-04-27 11:58
Duplicate of #7169, close that one or this one? That one has a worse error (`== 0`).

**Closed** 2020-11-13 12:44 UTC
Labels: JS
