### ISSUE TITLE
Operator overloads [] and []= don't work with importcpp in JS

### ISSUE THREAD

**Issue by mcclure** [nim-lang/Nim#4728] opened 2016-09-07 01:16 UTC
I am running with nim 80fe763915ac742314069489906c5 self-built from git. I have only tested the following with `nim js`; I am not sure how to set up an appropriate `nim c` test.

I put this in a file and compile it with `nim js -o:testnim.js -d:release testnim.nim`:

	type TestType* {.importc.} = ref object of RootObj
	    length* {.importc.}: float
	proc newTestType*() : TestType {.importcpp:"new Object".}
	proc `[]=`*(t: var TestType, key: float, val: float) {.importcpp.}
	proc `[]`*(t: TestType, key: float) : float {.importcpp.}

	var x1 {.exportc.} = newTestType()
	x1[1.0] = 5.0
	let x2 {.exportc.} = x1[1.0]

The importc'd type is meant to mimic a Javascript class, such as `Float32Array`, which has a [] operator whose indices are numbers and whose thusly stored values are also numbers.

**Observed behavior**: A file is generated ending with the lines:

	var x1 = new Object();
	x1[0].[]=(1.0000000000000000e+000, 5.0000000000000000e+000);
	var x2 = x1[0].[](1.0000000000000000e+000);

Importcpp interpreted the `[]` and `[]=` procs literally, and tried to access fields named `.[]` and `.[]=` on the object. This does not work, and produces an `Unexpected token [` error when run.

(In addition, apparently because I used `var` on the first argument to `proc []=`, which is mandatory for `proc []=`),  the generated code included a incorrect mystery `[0]`. I am going to file this separately.)

**Expected behavior**: It should be possible to use importcpp with `proc []=` and `proc []` and by default this should emit code that uses the normal [] and []= operators of the target language. This should be true in both C++ and JavaScript targets. The final two lines should be `x1[1.0] = 5.0; var x2 = x1[1.0]`.

**Comment by Araq** [comment] 2016-09-07 06:27
Duplicate of #4729

**Closed by Araq** 2016-09-07 06:27 UTC
