### ISSUE TITLE
Request to make OSError more descriptive

### ISSUE THREAD

**Issue by kaushalmodi** [nim-lang/Nim#13192] opened 2020-01-18 13:59 UTC
### Summary

Right now, if an OSError happens for not finding a file or directory, it's almost impossible to figure out what caused that error, because it does not print the file or directory it's trying to access.

### Description

Here's an example error:

```
Hint: used config file '/home/kmodi/usr_local/apps/6/nim/devel/config/nim.cfg' [Conf]
Hint: used config file '/home/kmodi/usr_local/apps/6/nim/devel/config/config.nims' [Conf]
Hint: used config file '/home/kmodi/usr_local/apps/6/nim/devel/config/nimdoc.cfg' [Conf]
Hint: system [Processing]
Hint: widestrs [Processing]
Hint: io [Processing]
Hint: foo [Processing]
oserr.nim(94)            raiseOSError
Error: unhandled exception: No such file or directory [OSError]
```

Ref: https://github.com/nim-lang/Nim/issues/13191

Is it possible for that error to do these:
1. Print the file/dir attempted to be accessed as well?
2. Print a back trace of where this OSError got issued from. Example. If a `copyFile` call in `nimdoc.nim` caused this, the error should show that information.

Thanks.

**Comment by timotheecour** [comment] 2020-01-19 04:15
duplicate of https://github.com/nim-lang/Nim/issues/8391

the fix is to extend what was done here https://github.com/nim-lang/Nim/pull/8393 to other procs; ideally simply show the minimal runtime information that's sufficient to debug what went wrong; eg:
`raiseOSError(osLastError())`
=>
`raiseOSError(osLastError(), dir)`

> Print a back trace of where this OSError got issued from. Example. If a copyFile call in nimdoc.nim caused this, the error should show that information.

that's just a matter of adding --stacktrace:on

**Closed as completed** 2020-01-19 10:46 UTC
Labels: Standard Library, Error Messages

**Comment by sk-Prime** [comment] 2021-01-03 03:57
![Screenshot from 2021-01-02 22-00-31](https://user-images.githubusercontent.com/26684644/103470916-32aae280-4da3-11eb-9f53-e79b208a769f.png)
here is another error message which can be improved. when `copyFile` proc got directory as argument this error message appear.
Improved error message should include "is not a file" sentence.

**Comment by timotheecour** [comment] 2021-01-10 20:09
> here is another error message

=> transferred to https://github.com/nim-lang/Nim/issues/8391#issuecomment-757535814 since this issue is already closed
