### ISSUE TITLE
posix_other.nim(530, 3) Error: cannot 'importc' variable at compile time`

### ISSUE THREAD

**Issue by Wh1teDuke** [nim-lang/Nim#10056] opened 2018-12-20 10:30 UTC
Error:
`../../Nim/lib/posix/posix_other.nim(530, 3) Error: cannot 'importc' variable at compile time`
I don't know where the error in my project is, but it wasn't an issue before.

Culprit: https://github.com/nim-lang/Nim/pull/10016

Workaround: `rm config/config.nims`
***
```nim
>nim -v
Nim Compiler Version 0.19.9 [Linux: i386]
Compiled at 2018-12-20
Copyright (c) 2006-2018 by Andreas Rumpf

git hash: 68ec42cec70496eef072c921f54a91686bb8b43b
active boot switches: -d:release
```

**Comment by alaviss** [comment] 2018-12-20 12:35
Then I don't think anyone can reproduce it with that little information. It must have come from some module importing `posix`, but other than that I've no idea.

**Comment by Wh1teDuke** [comment] 2018-12-20 12:50
@alaviss I'm checking what commit introduced the error.

**Comment by Wh1teDuke** [comment] 2018-12-20 13:16
Issue introduced here https://github.com/nim-lang/Nim/commit/86c3ac6a611d7e4eaa9eb017036e8ef3b20b0cd9

**Comment by alaviss** [comment] 2018-12-20 15:21
do you have any NimScript file in your project?

**Comment by Wh1teDuke** [comment] 2018-12-20 16:53
I have a .nim.cfg file named the same as the main module.

**Comment by timotheecour** [comment] 2021-05-07 02:33
closing this, feel free to re-open if you still have this issue.

This is most likely due to a mis-match between bootstrapping nim (csources) and what nim expects.
This should be fixed now that nim keeps track of which csources version is needed in a future proof way, see https://github.com/nim-lang/Nim/issues/17907#issuecomment-831654235 for details, which also explains how to bootstrap reliably.

(https://github.com/nim-lang/Nim/issues/15843#issuecomment-834010657 was also closed for similar reasons)

**Closed by timotheecour** 2021-05-07 02:33 UTC
Labels: Nimscript, VM
