### ISSUE TITLE
Seq assignment does not perform a deep copy

### ISSUE THREAD

**Issue by Wh1teDuke** [nim-lang/Nim#6004] opened 2017-06-19 17:57 UTC
Test
````nim
proc test =
  type Foo = ref object
    bar:   seq[int]

  let 
    foo   = Foo(bar: @[1])
    bar2  = foo.bar  # Expected deep copy

  setLen foo.bar, 0  
  assert len(bar2) == 1, "Len: " & $len(bar2)

test()
````
yields: `Error: unhandled exception: len(bar2) == 1 Len: 0 [AssertionError]`
***
````nim
>nim -v
Nim Compiler Version 0.17.1 (2017-06-19) [Windows: i386]
Copyright (c) 2006-2017 by Andreas Rumpf

git hash: 0fbca73e7140e891df6a5797ee7d7d38563f28da
active boot switches: -d:release
````

**Comment by andreaferretti** [comment] 2017-06-20 07:24
Yet this correctly echoes `@[1]`:

```nim
proc test() =
  type Foo = ref object
    bar:   seq[int]

  let 
    foo   = Foo(bar: @[1])
    bar2  = foo.bar  # Expected deep copy

  foo.bar[0] = 3
  echo bar2
 
test()
```

:-/

**Comment by narimiran** [comment] 2019-02-20 10:45
> Yet this correctly echoes `@[1]`

Not on my end and Nim 0.19.9 — it echoes `@[3]`, so at least it got consistent :P

But put the whole block outside of a proc and it will echo `@[1]`, and the original example will work too.
And it will also work (make a deep copy) if you declare `bar2` as `var` (not with `let`).

Having said that, this becomes a duplicate of https://github.com/nim-lang/Nim/issues/2314

**Closed by narimiran** 2019-02-20 10:45 UTC
