### ISSUE TITLE
required type: HttpClient but expression 'client' is of type: HttpClient

### ISSUE THREAD

**Issue by Imperator26** [nim-lang/Nim#7778] opened 2018-05-05 14:47 UTC
code:
`let response = client.post(url=endpoint, extraHeaders=header, multipart=payload)`

```
Error: type mismatch: got <HttpClient, url: string, extraHeaders: string, multipart: MultipartData>
but expected one of: 
proc post(url: string; extraHeaders = ""; body = ""; maxRedirects = 5;
         sslContext: SSLContext = defaultSSLContext; timeout = -1;
         userAgent = defUserAgent; proxy: Proxy = nil; multipart: MultipartData = nil): Response
  first type mismatch at position: 1
  required type: string
  but expression 'client' is of type: HttpClient
proc post(client: HttpClient; url: string; body = ""; multipart: MultipartData = nil): Response
  first type mismatch at position: 1
  required type: HttpClient
  but expression 'client' is of type: HttpClient
proc post(client: AsyncHttpClient; url: string; body = "";
         multipart: MultipartData = nil): Future[AsyncResponse]
  first type mismatch at position: 1
  required type: AsyncHttpClient
  but expression 'client' is of type: HttpClient

expression: post(client, url = endpoint, extraHeaders = header, multipart = payload)
```

**Comment by dom96** [comment] 2018-05-05 17:29
Actually this looks wrong to me:

> ```
> proc post(client: HttpClient; url: string; body = ""; multipart: MultipartData = nil): Response
>  first type mismatch at position: 1
>  required type: HttpClient
> but expression 'client' is of type: HttpClient
>```

The first mismatch there is the ``extraHeaders`` not ``client``.

**Comment by Imperator26** [comment] 2018-05-05 17:54
I can't find where `newHttpHeaders()` is defined

**Comment by dom96** [comment] 2018-05-05 18:31
Here is an example of how to use it to specify headers: https://nim-lang.org/docs/httpclient.html#using-http-post

You can find the procedure by searching in the doc index: http://nim-lang.org/docs/theindex.html

**Comment by Imperator26** [comment] 2018-05-05 18:48
It's in `httpcore` https://nim-lang.org/docs/httpcore.html

**Comment by Yardanico** [comment] 2018-05-05 20:02
@Imperator26 but httpclient imports and exports httpcore, so you don't need to import it directly

**Comment by Araq** [comment] 2019-02-09 07:39
Cannot reproduce, even

```

import httpcore, httpclient

let response = client.post(url=endpoint, extraHeaders=header, multipart=payload)
```

does not compile. I'm not guessing any further what might have been meant. Please provide a full minimal example the next time. Closing.

**Closed by Araq** 2019-02-09 07:39 UTC
Labels: Error messages
