### ISSUE TITLE
0.12.0 build.sh fails on Mac OS X Yosemite (10.10.5)

### ISSUE THREAD

**Issue by desophos** [nim-lang/Nim#3487] opened 2015-10-28 18:14 UTC
After following exactly the steps described in http://nim-lang.org/download.html (Installation from Github), I get the following error:

    mbp-op-128:csources desophos$ sh build.sh
    : command not found
    : invalid option: set: -
    set: usage: set [--abefhkmnptuvxBCHP] [-o option] [arg ...]

If I change `set -e` to `set --e` in build.sh, I get:

    : command not found
    build.sh: line 6: set: --: invalid option
    set: usage: set [--abefhkmnptuvxBCHP] [-o option] [arg ...]

These commands were run from a bash shell. This might also be relevant:

    mbp-op-128:csources desophos$ /bin/sh
    sh-3.2$ ./build.sh
    sh: ./build.sh: /bin/sh^M: bad interpreter: No such file or directory

But:

    mbp-op-128:csources desophos$ which sh
    /bin/sh

**Comment by strcmp** [comment] 2015-10-28 18:18
yeah, that strange `^M` character can sometimes happen when saving files on Windows and then editing them from something like osx/linux.

**Comment by kirbyfan64** [comment] 2015-10-28 18:40
What if you run `dos2unix build.sh` first?

**Comment by desophos** [comment] 2015-10-28 18:45
http://stackoverflow.com/a/2613834

I found that running `sed 's/^M$//' new_build.sh` and replacing build.sh with new_build.sh worked. (^M is `control-V`, `control-M`, as mentioned in the stackoverflow answer I linked.) The problem is that build.sh has Windows line endings. I suppose dos2unix would also work, but I don't have it installed.

**Comment by Araq** [comment] 2015-10-31 23:38
Cannot reproduce. Closing, but feel free to reopen, of course.

**Closed by Araq** 2015-10-31 23:38 UTC
Labels: Installation, Tools
