### ISSUE TITLE
typedesc treated differently with proc and template

### ISSUE THREAD

**Issue by slangmgh** [nim-lang/Nim#14411] opened 2020-05-21 00:56 UTC
The following code works fine.

```nim
proc `||`*[T](x, y: T): T =
   if x == default(T): y else: x
echo "hello" || "world"
```

But this code gives compiler error.
```nim
template `||`*[T](x, y: T): T =
   if x == default(T): y else: x
echo "hello" || "world"
```

```
D:\Tool\Nim\tmp\a16.nim(2, 19) Error: type mismatch: got <string>
but expected one of: 
proc default(T: typedesc): T:type
  first type mismatch at position: 1
  required type for T: typedesc
  but expression 'T' is of type: string

expression: default(T)
```

```
$ nim -v
D:\Tool\Nim\tmp>nim -v
Nim Compiler Version 1.3.3 [Windows: i386]
Compiled at 2020-05-13
Copyright (c) 2006-2020 by Andreas Rumpf

active boot switches: -d:release
```

**Comment by kaushalmodi** [comment] 2020-05-23 05:27
I don't know if that syntax is supposed to work with templates, but this works:

```nim
template `||`*(x, y): untyped =
  if x == default(typeof(x)): y else: x
echo "hello" || "world"
```

**Comment by slangmgh** [comment] 2020-05-23 14:16
I now use the following code:
```nim
template `||`*[T](x, y: T): T =
   if x == default(typeof(T)): y else: x
```

The code is works for both proc and template, though I don't know why it works. I have never truly understand the difference of typeof() type() typedesc etc.

**Comment by kaushalmodi** [comment] 2020-05-23 14:45
@slangmgh I haven't used `type` much, but the [`typeof`][1] proc, as the name suggests, returns the **type of** the arg. Just as `int` or `string` is a **type**, the _type_ of **type** is **typedesc**.

You will notice that as `typeof` returns a **type**, it's return type is **typedesc**. I hope that explanation doesn't cause more confusion :)
 
[1]: https://nim-lang.github.io/Nim/system.html#typeof%2Cuntyped

**Comment by timotheecour** [comment] 2020-05-23 15:22
duplicate of https://github.com/nim-lang/Nim/issues/13527 
closing but feel free to reopen if you disagree

**Closed as completed by timotheecour** 2020-05-23 15:22 UTC
