### ISSUE TITLE
Incorrect C code generation when trying to echo a Lock variable

### ISSUE THREAD

**Issue by 3n-k1** [nim-lang/Nim#12855] opened 2019-12-08 18:53 UTC
Bad C code is generated with the following Nim code:

### Example
```nim
import locks

var l: Lock
echo l
```

### Current Output
```
CC: ltest.nim
Error: execution of an external compiler program 'gcc -c  -w  -I/home/tay/.choosenim/toolchains/nim-1.0.4/lib -I/home/tay -o /home/tay/.cache/nim/ltest_d/stdlib_dollars.nim.c.o /home/tay/.cache/nim/ltest_d/stdlib_dollars.nim.c' failed with exit code: 1

/home/tay/.cache/nim/ltest_d/stdlib_dollars.nim.c: In function ‘dollar___3Dq1hcGH7a2iNlnh4hnPbg’:
/home/tay/.cache/nim/ltest_d/stdlib_dollars.nim.c:219:50: error: ‘pthread_mutex_t’ {aka ‘union <anonymous>’} has no member named ‘abi’
  219 |  addQuoted__N56rmvBL9a3xqnKq09cKdb3A((&result), x.abi);
      |                                                  ^
```

### Expected Output
Compiler either compiles properly or errors before C code gen

### Possible Solution

* It looks like there might be an issue with the implementation of `$` for the Lock type

### Additional Information

* Fedora 31: `Linux localhost.localdomain 5.3.11-300.fc31.x86_64 #1 SMP Tue Nov 12 19:08:07 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`

```
$ nim -v
Nim Compiler Version 1.0.4 [Linux: amd64]
Compiled at 2019-11-27
Copyright (c) 2006-2019 by Andreas Rumpf

git hash: c8998c498f5e2a0874846eb31309e1d1630faca6
active boot switches: -d:release
```

**Comment by ghost** [comment] 2020-04-19 12:04
Why close? The issue is still there

**Comment by ghost** [comment] 2020-04-20 19:34
It's been several months and there was no feedback, I figured an issue wasn't necessary.

**Comment by ghost** [comment] 2020-04-20 19:42
@3n-k1 that's not how it works in open-source in general - it just means that nobody worked on the issue yet, but as long as the bug is still there it should be open

**Comment by ghost** [comment] 2020-04-21 01:53
I understand how FOSS works. Now, I would prefer if you didn't mention me again as I would prefer not to receive notifications for this.

**Comment by ghost** [comment] 2020-07-01 04:59
It's been over half a year, and I get a bad taste in my mouth every time I see this. I'm closing this, and I will be blocking anyone who responds or re-opens; I really don't care if that makes me an ass.

Y'all have a minimal example and all the information necessary for this, feel free to open a ***new*** issue with a copy-paste of the initial issue I posted here.

This is me officially leaving the Nim community. So long, and thanks for all the fish.

**Closed** 2020-07-01 05:00 UTC

**Comment by ghost** [comment] 2020-07-01 05:47
> It's been over half a year, and I get a bad taste in my mouth every time I see this. I'm closing this, and I will be blocking anyone who responds or re-opens; I really don't care if that makes me an ass.
> 
> Y'all have a minimal example and all the information necessary for this, feel free to open a ***new*** issue with a copy-paste of the initial issue I posted here.
> 
> This is me officially leaving the Nim community. So long, and thanks for all the fish.

I'm okay with getting blocked by you - but really, "leaving" the community because of INCORRECT Nim code not compiling (even if it compiles it'll crash at best since you didn't initialize the lock, and for printing you can just try to use repr or cast to a pointer and repr) is not okay. Also this is open source, not some software you paid for, so you maybe should've tried fixing it yourself before? :)

**Comment by beef331** [comment] 2020-07-01 05:54
Just brigading so I can get my promised block. I certainly would not like you to use anything I contribute on.

**Comment by ghost** [comment] 2020-07-01 14:35
@Yardanico I'm leaving the community because Araq has treated me like shit numerous times, but thanks for playing.

**Comment by ghost** [comment] 2020-07-01 14:36
The fact you need to bitch and moan about someone not wanting to be treated like a fucking piece of garbage just confirms this community is fucking garbage.

**Comment by ghost** [comment] 2020-07-01 14:45
@beef331 Even if I *did* want to use any of your trash, it would be a bit difficult since you apparently can't bring yourself to write more than two sentences in a readme, assuming you write anything at all.

Nice website by the way, I really enjoy the gif of your superman64 clone playing as the site's background.

You wanna get shitty? Let's fuckin' go, kid. At least I actually contributed to Nim before Araq treated me like shit, unlike you.

Araq, be careful who you treat like garbage, you may lose one of your shitty niche language's biggest evangelists.

**Comment by ghost** [comment] 2020-07-01 14:47
Am I ranting now? Sure the fuck am. I thought you'd all be able to be fucking adults about this, but I guess fucking not.

**Comment by ghost** [comment] 2020-07-01 14:52
@Yardanico I tried to be as polite as possible when closing this, and you attempt to dogpile and bitch? Real fucking mature.
![image](https://user-images.githubusercontent.com/51172302/86258541-ecbd5980-bb88-11ea-8e54-477aaba9f3ef.png)

**Comment by ghost** [comment] 2020-07-01 14:53
just gonna document why I'm leaving. You're all petulant children.
![image](https://user-images.githubusercontent.com/51172302/86258654-0ced1880-bb89-11ea-8517-36188fecf092.png)

**Comment by ghost** [comment] 2020-07-01 14:54
Please do google "inurl:irclogs.nim-lang.org simula". Better yet, search "from:simula#3097" in the discord server. My last interaction is exactly the bullshit I'm talking about. Glad to see it hasn't ended.
![image](https://user-images.githubusercontent.com/51172302/86258722-22fad900-bb89-11ea-8ab6-a109557aad3d.png)
