### ISSUE TITLE
should `f(a:int) => a` compile?

### ISSUE THREAD

**Issue by chaemon** [nim-lang/Nim#16834] opened 2021-01-26 13:02 UTC
I like => operator in sugar. I found the bug that the following code cannot compile.  

```nim
import sugar

f(a:int, b:int) => a + b
echo f(2021, 126)
```

The reason is that f(a:int, b:int) is regarded as nnkObjConstr and not as nnkCall. So I suggest fixing line 92 of sugar.nim to 
```nim
  since (1, 3):
    if p.kind == nnkCall or p.kind == nnkObjConstr:
      # foo(x, y) => x + y
```

It seems that it works. Since I'm not familiar with macro, please check this fix is collect. Thanks.

**Comment by metagn** [comment] 2021-01-26 13:14
This is fixed in devel:

https://github.com/nim-lang/Nim/blob/ecc9704bf406c65dce549b0c5542727d33816e7f/lib/pure/sugar.nim#L88

**Comment by chaemon** [comment] 2021-01-26 13:18
Sorry, I didn't notice it. Thanks for pointing out.

**Comment by timotheecour** [comment] 2021-02-01 01:35
@hlaaftana should that even compile? 

either way, there's something missing here:
* either it should not compile (ie regression introduced probably in https://github.com/nim-lang/Nim/pull/16190) and we need to ensure it doesn't compile, or it should compile and be documented as such via a runnableExamples + test in tsugar.nim

I'm marking for now as accepts invalid, but the other interpretation would be: "needs a runnableExamples" but IMO sounds fishy, we should instead use:
```nim
let f1 = (a:int, b:int) => a + b
const f2 = (a:int, b:int) => a + b
```

**Comment by metagn** [comment] 2021-02-01 05:12
It was added as a feature in #14200. It's meant to be a shorthand for `proc f(a: int, b: int): auto = a + b` for people familiar with Dart or C# where it works similarly I believe. I wrote about it in the changelog for 1.4 but not in the actual sugar docs it seems. If the feature is too weird and out of place, it could be removed since it's not really documented, but if this issue was created that means at least some people know it exists.

**Comment by timotheecour** [comment] 2021-02-01 07:14
I think the feature is acceptable, but definitely should be documented (with runnableExamples) and with tests in tsugar.nim, in particular ones that test overloading etc:
```nim
f1(a: int) => a*2
template fn() =
  f1(a: int) => a*2
doAssert not compiles(fn()) # would cause redefinition error
f1(a, b: int) => a*2 # ok: it's an overload
f1(a) => a*2 # ok: it's an overload with generic param `a: auto`
```

docs should also mention alternatives, eg: `var/let/const f1 = a=>a`

**Comment by timotheecour** [comment] 2021-02-01 20:17
@hlaaftana while we're discussing =>, ->:

isn't the pragma placement for `->` inconsistent with the way a proc is declared?
```
proc (name: string): string {.noSideEffect.}
vs:
string {.noSideEffect.} -> string
```

current:
```nim
proc (name: string): string {.noSideEffect.}
string {.noSideEffect.} -> string
a {.noSideEffect.} => a
```

alternative:
```nim
proc (name: string): string {.noSideEffect.}
string -> string {.noSideEffect.} 
a => a {.noSideEffect.} 
```

**Comment by metagn** [comment] 2021-02-02 08:08
`string -> string {.noSideEffect.}` could be supported but `a => a {.noSideEffect.}` is wrong. It would be like doing `proc foo(a) = a {.noSideEffect.}`.

The thing about `->` is that this is invalid syntax:

```nim
import sugar

var x: string -> string {.noSideEffect.}
type Foo = string -> string {.noSideEffect.}
```

You have to surround `string -> string {.noSideEffect.}` with parentheses. Same actually goes for `string {.noSideEffect.} -> string`.

**Comment by timotheecour** [comment] 2021-03-04 09:26
> string -> string {.noSideEffect.} could be supported but a => a {.noSideEffect.} is wrong. It would be like doing proc foo(a) = a {.noSideEffect.}.

related: [`=>` doesn't work with {.async.} (neither js nor c) · Issue #17254 · nim-lang/Nim](https://github.com/nim-lang/Nim/issues/17254)

**Closed as completed** 2021-03-05 11:08 UTC
Labels: Standard Library, Documentation, Easy
