### ISSUE TITLE
[Bad codegen] Default argument equal to previous argument.

### ISSUE THREAD

**Issue by mratsim** [nim-lang/Nim#7755] opened 2018-05-03 11:09 UTC
The following generates the wrong C code:

```Nim
proc bar(x: int, y: int = x) =
  discard


let b = 1
bar(b)
```

```
<...>/nimcache/arraymancer_self_arg.c:112:56: error: use of undeclared identifier 'x'
        bar_GyI5fxcaGMO6Syld12djPw(b_pQM3Mc49cOSyDNhXxFOV2ZQ, x);
```

**Comment by dom96** [comment] 2018-05-03 11:26
Duplicate of https://github.com/nim-lang/Nim/issues/1046

**Closed by dom96** 2018-05-03 11:26 UTC
Labels: Codegen
