### ISSUE TITLE
Seems like var items = 1 shadows proc items()

### ISSUE THREAD

**Issue by bodoss** [nim-lang/Nim#3715] opened 2016-01-14 09:55 UTC
type Foo = object
    field1 : int

proc `()`(i: Foo) =
    discard

var arr : seq[int] = @[1,2,3]
var items = 1 # try to comment this line and code works
for i in arr:
    echo($i)

above code can't be compiled.

type mismatch: got (int, seq[int])
but expected one of: 
main.()(i: Foo)

Seems like var items = 1 shadows proc items()

**Comment by Araq** [comment] 2016-01-14 09:59
No, this works:

```nim
var arr : seq[int] = @[1,2,3]
var items = 1
for i in arr:
    echo($i)
```

The underlying gotcha will be addressed in 0.13.0.

**Comment by bohdantp** [comment] 2016-01-14 10:18
type Foo = object
    field1 : int

proc `()`(i: Foo) =
    discard

var arr : seq[int] = @[1,2,3]
var items = 1 # try to comment this line and code works
for i in arr:
    echo($i)

**Comment by Araq** [comment] 2016-01-14 10:31
Gah, did you edit your snippet or am I stupid?

**Comment by Araq** [comment] 2016-01-14 10:34
Well the reason is the overloaded `()` operator which I don't think will stay in the language. (Is it even documented?)

**Comment by narimiran** [comment] 2019-02-10 17:33
> Well the reason is the overloaded () operator

Duplicate of https://github.com/nim-lang/Nim/issues/1072

> which I don't think will stay in the language.

Can we remove it then?

**Closed by narimiran** 2019-02-10 17:33 UTC
Labels: Low Priority
