### ISSUE TITLE
Format error while adding :g flag

### ISSUE THREAD

**Issue by vivekimsit** [nim-lang/Nim#9023] opened 2018-09-20 21:11 UTC
I need to import `strformat` in unit tests otherwise I get the following error:

```
unit.nim(3, 7) template/generic instantiation from here
unit.nim(4, 8) template/generic instantiation from here
unit.nim(5, 11) template/generic instantiation from here
lib/pure/unittest.nim(610, 43) template/generic instantiation from here
/Users/vivekpoddar/dev/pretty-bytes/src/prettybytes.nim(17, 13) template/generic instantiation from here
lib/pure/strformat.nim(276, 5) Error: undeclared identifier: 'format'
       Tip: 4 messages have been suppressed, use --verbose to show them.
     Error: Execution failed with exit code 256
```

**Comment by mratsim** [comment] 2019-05-09 09:50
Tested and it works since 0.19.0 (but not in 0.18.0). Pretty sure it was duplicate of #7632.

**Closed by mratsim** 2019-05-09 09:50 UTC
Labels: Stdlib, Symbol Resolution
