### ISSUE TITLE
`DWORD` in std/winlean inconsistent with MS's definition.

### ISSUE THREAD

**Issue by litlighilit** [nim-lang/Nim#22298] opened 2023-07-20 10:50 UTC
According to <https://learn.microsoft.com/en-us/windows/win32/winprog/windows-data-types>,  
`DWORD` is "A 32-bit unsigned integer".
<https://github.com/nim-lang/Nim/blob/c1a82aa5c5ab68dfc2ab6f09779d9ab9bbf3758f/lib/windows/winlean.nim#L36>  
Why not `uint32`
Does this difference matter?

**Comment by demotomohiro** [comment] 2023-07-21 07:58
Dupulicate of : https://github.com/nim-lang/Nim/issues/12327

**Comment by ringabout** [comment] 2023-07-21 08:00
Duplicate of https://github.com/nim-lang/Nim/issues/12327

**Closed as completed by ringabout** 2023-07-21 08:00 UTC
