### ISSUE TITLE
loss of type information in macro parameter

### ISSUE THREAD

**Issue by stefantalpalaru** [nim-lang/Nim#11414] opened 2019-06-05 22:37 UTC
With Nim devel, this tuple param is being converted into a NimNode:

```nim
import typetraits

type InstInfo = tuple[filename: string, line: int, column: int]

macro m(lineInfo: InstInfo): untyped =
  echo type(lineInfo) # NimNode
  ## this fails:
  # echo lineInfo.filename

template t() =
  let i = instantiationInfo()
  echo type(i) # tuple[filename: string, line: int, column: int]
  echo i.filename
  m(i)

t()
```

**Comment by Araq** [comment] 2019-06-06 06:27
I'm not sure why this ever worked, you're supposed to use this:

```nim


import typetraits

type InstInfo = tuple[filename: string, line: int, column: int]

macro m(lineInfo: static[InstInfo]): untyped =
  echo type(lineInfo)

template t() =
  let i = instantiationInfo()
  echo type(i) # tuple[filename: string, line: int, column: int]
  echo i.filename
  m(instantiationInfo())

t()
```

**Comment by stefantalpalaru** [comment] 2019-06-06 09:09
Even so, it's not possible to access lineInfo's fields:

```nim
import typetraits

type InstInfo = tuple[filename: string, line: int, column: int]

macro m(lineInfo: static[InstInfo]): untyped =
  echo type(lineInfo) # NimNode
  ## this fails:
  echo lineInfo.filename

template t() =
  m(instantiationInfo())

t()
```

Not only it fails, but it does so without giving any info about the trigering line:

```text
stefan$ nim c -f -r test1.nim
Hint: used config file '/mnt/sda3/storage/CODE/status/nimbus/vendor/Nim/config/nim.cfg' [Conf]
Hint: used config file '/mnt/sda3/storage/CODE/status/nimbus/nim.cfg' [Conf]
Hint: used config file '/mnt/sda3/storage/CODE/status/nimbus/vendor/Nim/config/config.nims' [Conf]
Hint: system [Processing]
Hint: widestrs [Processing]
Hint: io [Processing]
Hint: test1 [Processing]
Hint: typetraits [Processing]
InstInfo
/mnt/sda3/storage/CODE/status/nimbus/vendor/Nim/lib/system/fatal.nim(48) sysFatal
Error: unhandled exception: strVal is not accessible [FieldError]
```

**Comment by zah** [comment] 2019-06-06 09:19
This must be a regression. I've used this technique many times and it works fine in 0.19.4.

**Comment by krux02** [comment] 2019-06-06 09:35
this is a duplicate of this bug here: https://github.com/nim-lang/Nim/issues/10751
But it is noted, that this issue is important.

**Comment by krux02** [comment] 2019-06-06 09:39
While

**Comment by stefantalpalaru** [comment] 2019-06-06 10:09
> This must be a regression in devel. I've used this technique many times and it works fine in 0.19.4.

Guess where I ran into it, @zah: https://github.com/status-im/nim-chronicles/blob/249f978fa76ba2b25a48b9585c96e238aded2128/chronicles.nim#L308 :-)

**Comment by Araq** [comment] 2019-06-06 10:51
My mistake, it's a duplicate of  #10751 indeed. Combined with a fix of mine for ``instantiationInfo``.

**Closed** 2019-06-06 10:50 UTC
Labels: Regression
