### ISSUE TITLE
Unsigned integers could not be compared to zero

### ISSUE THREAD

**Issue by cheatfate** [nim-lang/Nim#7174] opened 2018-02-02 00:49 UTC
```nim
when isMainModule:
  var c = 1'u
  if c > 0:
    echo "True"
```
with error:
```
Error: type mismatch: got (int literal(0), uint)
but expected one of: 
proc `<`[Enum: enum](x, y: Enum): bool
proc `<`(x, y: string): bool
proc `<`(x, y: char): bool
proc `<`[T](x, y: set[T]): bool
proc `<`(x, y: bool): bool
proc `<`[T](x, y: ref T): bool
proc `<`[T](x, y: ptr T): bool
proc `<`(x, y: pointer): bool
proc `<`(x, y: int64): bool
proc `<`(x, y: float32): bool
proc `<`(x, y: int): bool
proc `<`[T](x: Ordinal[T]): T
proc `<`(x, y: int8): bool
proc `<`(x, y: float): bool
proc `<`[T: tuple](x, y: T): bool
proc `<`(x, y: int16): bool
proc `<`[T: SomeUnsignedInt](x, y: T): bool
proc `<`(x, y: int32): bool
```

**Comment by mratsim** [comment] 2018-02-10 18:44
Isn't that expected? We can't silently convert signed to unsigned so we have to use that instead:

```Nim
when isMainModule:
  var c = 1'u
  if c > 0'u:
    echo "True"
```

**Comment by Araq** [comment] 2018-02-10 19:06
@mratsim The problem is that sometimes it is allowed since ``int literal(N)`` does convert to unsigned. This makes everything seem much more inconsistent than it is. I might have a solution.

**Comment by timotheecour** [comment] 2020-06-25 03:43
closed by https://github.com/nim-lang/Nim/pull/14795

**Closed by timotheecour** 2020-06-25 03:44 UTC
Labels: unsigned
