### ISSUE TITLE
Type coercion not working for type class parameters

### ISSUE THREAD

**Issue by Wh1teDuke** [nim-lang/Nim#19885] opened 2022-06-12 08:46 UTC
**Test**
```nim
proc foo(bar: int8 or uint8) = doAssert sizeOf(bar) == 1
foo(1)
```
**Got**
```nim
Error: unhandled exception: Test.nim(1, 41) `sizeof(bar) == 1` 8 [AssertionDefect]
```
***
```nim
>nim -v
Nim Compiler Version 1.7.1 [Linux: amd64]
Compiled at 2022-06-11
Copyright (c) 2006-2022 by Andreas Rumpf

git hash: ac89eead8a40a1a8ee170a4650a1d47e203da14c
active boot switches: -d:release
```

**Comment by ringabout** [comment] 2022-06-16 07:34
duplicate of https://github.com/nim-lang/Nim/issues/1214

**Closed as completed by ringabout** 2022-06-16 07:34 UTC
