### ISSUE TITLE
rst/markdown parser can't handle extra parentheses after link

### ISSUE THREAD

**Issue by GULPF** [nim-lang/Nim#10475] opened 2019-01-27 20:57 UTC
Code:
```nim
import packages/docutils/[rstgen, rst], strtabs

echo rstToHtml("( [Nim](https://nim-lang.org/) )", {roSupportMarkdown}, newStringTable(modeStyleInsensitive))
echo rstToHtml("([Nim](https://nim-lang.org/))", {roSupportMarkdown}, newStringTable(modeStyleInsensitive))
```
Output:
```html
( <a class="reference external" href="https://nim-lang.org/">Nim</a> )
([Nim](<a class="reference external" href="https://nim-lang.org/">https://nim-lang.org/</a>))

```
Expected output:
```html
( <a class="reference external" href="https://nim-lang.org/">Nim</a> )
(<a class="reference external" href="https://nim-lang.org/">Nim</a>)
```

**Comment by narimiran** [comment] 2019-04-09 17:22
I've investigated a bit and the problem is that the closing `))` gets parsed as one token inside of `RstParser`, and `parseMarkdownLink` is searching for a token which is `)` — it can't find it and hence it thinks there's no link.

A similar thing would have happened if you had a double `[[` in the beginning of a link, e.g. `[[Nim]((https://nim-lang.org/) some other text]`.

**Closed** 2019-04-10 13:56 UTC
Labels: Doc Generation, Stdlib
