### ISSUE TITLE
Template overloading + identifier injection leads to undeclared identifier

### ISSUE THREAD

**Issue by mratsim** [nim-lang/Nim#9414] opened 2018-10-17 17:33 UTC
Currently it's not possible to overload a template with a template of the same name if identifier injection is used.

Test case:

```Nim
template forLoop*(index: untyped, length: int, test: bool = true, body: untyped) =
  for `index`{.inject.} in 0 ..< length:
      body

template forLoop*(index: untyped, length: int, body: untyped) =
  # overloading
  for_loop(index, length, test = true, body)

template forLoop2*(index: untyped, length: int, body: untyped) =
  # different name
  for_loop(index, length, test = true, body)

var x = newSeq[int](10)

forLoop(i, x.len, test = true): # Works
  x[i] = i

forLoop2(j, x.len): # Works
  x[j] += j

forLoop(j, x.len): # Overloading ident injection issue
  x[j] += j # undeclared identifier j
```

**Comment by Araq** [comment] 2018-10-18 10:17
This is the documented behaviour, currently overloaded templates must agree on the positioning of ``untyped`` parameters. However, there are ideas of how to solve that.

**Comment by timotheecour** [comment] 2020-11-13 18:26
duplicate of https://github.com/nim-lang/Nim/issues/14827

**Closed by timotheecour** 2020-11-13 18:26 UTC
Labels: Symbol Resolution, Templates
