### ISSUE TITLE
typedesc[T] can't be used at compile time, unlike generics

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/Nim#8486] opened 2018-07-31 18:31 UTC
`typedesc[T]` can't be used at compile time, unlike generics, as shown below:
```nim
when defined(case_default_old):
  template default*[T](t: typedesc[T]): T =
    # Error: cannot evaluate at compile time: v116407 var v: T
    var v: T
    v
else:
  proc default*[T]():T=
    var a: T
    return a

proc len(T: typedesc[tuple]):auto=
  when defined(case_default_old):
    const t=default(T)
  else:
    const t=default[T]()

  var n=0
  for _ in t.fields:
    inc n
  return n

proc test()=
  var a=(1,2,3)
  const length = a.type.len
  echo length

test()
```

Can that limitation be lifted?

NOTE: this affect the debate here: [RFC] guidelines for when to use typedesc vs generics #7517
NOTE: the motivating example was from `default` should be public instead of redefined everywhere; should use default[T] instead of default(T) #8485 ; if this limitation were lifted, we'd be able to use `default(T)` (or `int.default`) at compile time, instead of having to resort to `default[T]()`

**EDIT** /cc @yglukhov NOTE: see workaround below via intermediate `defaultImpl[T]():T`
```nim
proc defaultImpl[T]():T=
  var a: T
  return a
template default*[T](t: typedesc[T]): T = defaultImpl[T]()
```

**Comment by yglukhov** [comment] 2018-07-31 18:37
Works with devel
```nim
template default*[T](t: typedesc[T]): T =
    var v: T
    v
const a = default(int)
```

**Comment by timotheecour** [comment] 2018-07-31 18:40
@yglukhov I know, I'm using devel; it works in your example, but not the example I mentioned above:

```
rnim -d:case_default_old bugs/t74_typedesc_CT.nim
nim c --nimcache:/tmp/nim//nimcache/ -o:/tmp/nim//app -r -d:case_default_old bugs/t74_typedesc_CT.nim
/Users/timothee/git_clone/nim/timn/bugs/t74_typedesc_CT.nim(26, 24) template/generic instantiation from here
/Users/timothee/git_clone/nim/timn/bugs/t74_typedesc_CT.nim(6, 9) Error: cannot evaluate at compile time: v116407
      var v: T
          ^


rnim bugs/t74_typedesc_CT.nim
nim c --nimcache:/tmp/nim//nimcache/ -o:/tmp/nim//app -r bugs/t74_typedesc_CT.nim
CC: timn_t74_typedesc_CT
Hint: operation successful (12210 lines compiled; 0.614 sec total; 16.25MiB peakmem; Debug Build) [SuccessX]
3
```

**Comment by yglukhov** [comment] 2018-07-31 18:49
My bad, sorry.

**Comment by dom96** [comment] 2018-07-31 22:05
Duplicate of #7596. (Please consider grouping related issues together).

**Closed by dom96** 2018-07-31 22:05 UTC

**Comment by timotheecour** [comment] 2018-07-31 22:38
@dom96 how about adding a github label `duplicate`?  (I can't as I don't have the required priviledge in this repo); so this can be marked as closed and duplicate

**Comment by dom96** [comment] 2018-08-01 10:10
Why would it be useful to find duplicated issues?

**Comment by andreaferretti** [comment] 2018-08-01 10:47
https://github.com/nim-lang/Nim/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed+duplicate

**Comment by timotheecour** [comment] 2018-08-02 01:39
> Why would it be useful to find duplicated issues?

=> moved discussion here https://github.com/nim-lang/Nim/issues/8507
