### ISSUE TITLE
defer: in an {.async.} function should be transformed similar to try/finally

### ISSUE THREAD

**Issue by RedBeard0531** [nim-lang/Nim#6844] opened 2017-11-30 14:25 UTC
```nim
let thing = await getThing()
defer: thing.release()
await doSomthingElse()
```
Doesn't work, but the equivalent, uglified try/finally does:
```nim
let thing = await getThing()
try:
  await doSomthingElse()
finally:
  thing.release()
```

Using types with destructors also doesn't work. I assume it is the same issue.

**Comment by dom96** [comment] 2018-01-17 20:40
Closing as duplicate of #3877.

**Closed by dom96** 2018-01-17 20:40 UTC
Labels: Async
