### ISSUE TITLE
Error: inheritance only works with non-final objects

### ISSUE THREAD

**Issue by SSPkrolik** [nim-lang/Nim#2264] opened 2015-03-05 09:56 UTC
There's _possibly_ a bug in inheritance.

Consider the next code which works:

```
type 
    SomeObj = object of RootObj
        name: string
    Some = ref object of SomeObj

echo(Some(name: "hello").name)
```

If we change the order of `SomeObj` and `Some` declarations it won't compile, though both of them are in the same `type` block.

So, basically the next code does not compile with `Error: inheritance works only with non-final objects`:

```
type 
    Some = ref object of SomeObj
    SomeObj = object of RootObj
        name: string

echo(Some(name: "hello").name)
```

**Comment by Araq** [comment] 2020-02-05 11:29
Duplicate of other "order still matters within type sections" bugs.

**Closed by Araq** 2020-02-05 11:29 UTC
Labels: Low Priority, Semcheck, Type sections
