### ISSUE TITLE
nim doc fails to parse line

### ISSUE THREAD

**Issue by noahehall** [nim-lang/Nim#21436] opened 2023-02-25 03:29 UTC
### Description

- executing `nim doc file.nim` with the following content

```sh
##[
- *.nims
]##
```

- throws the following error 
  - looks like configs are loaded twice too

```sh
08:31 PM (develop *% u=) 
$ nim doc nim_doc_fails.nim 
Hint: used config file '/home/poop/.choosenim/toolchains/nim-1.6.10/config/nim.cfg' [Conf]
Hint: used config file '/home/poop/.choosenim/toolchains/nim-1.6.10/config/config.nims' [Conf]
Hint: used config file '/home/poop/.choosenim/toolchains/nim-1.6.10/config/nim.cfg' [Conf]
Hint: used config file '/home/poop/.choosenim/toolchains/nim-1.6.10/config/config.nims' [Conf]
Hint: used config file '/home/poop/.choosenim/toolchains/nim-1.6.10/config/nimdoc.cfg' [Conf]
.........................................................
/home/poop/git/foss/nim/nim_doc_fails.nim(1, 8) Error: '*' expected
lineinfos.nim(289)       raiseRecoverableError
Error: unhandled exception: '*' expected [ERecoverableError]

```

### Nim Version

$ nim -v
Nim Compiler Version 1.6.10 [Linux: amd64]
Compiled at 2022-11-21
Copyright (c) 2006-2021 by Andreas Rumpf

git hash: f1519259f85cbdf2d5ff617c6a5534fcd2ff6942
active boot switches: -d:release

### Expected Output

- i can render a bullet list with any string content

### Possible Solution

- remove the `*` in `*.nims`

**Comment by ire4ever1190** [comment] 2023-02-25 04:42
Another solution is to escape the `*` so that the markdown parser skips it

```nim
##[
- \*.nims
]##
```

**Comment by ringabout** [comment] 2023-02-25 04:47
Duplicate of https://github.com/nim-lang/Nim/issues/19607

**Closed as completed** 2023-02-25 04:47 UTC

**Comment by noahehall** [comment] 2023-02-25 10:33
@ire4ever1190  thanks for the work around
