### ISSUE TITLE
Invalid visibility check with set-property

### ISSUE THREAD

**Issue by yekimov** [nim-lang/Nim#3033] opened 2015-07-01 11:42 UTC
Here is the code snippet that leads to compilation error:
```nimrod
# module badmod2

type TA[T] = object
  fA: T

proc `a=`[T](a: var ref TA[T], value: T) = a.fA = value

proc test*[T] =
  var obj = new(TA[T])
  obj.a = 10

# module badmod

import badmod2

test[int]()
```
```
> nim c badmod.nim
\nim\config\nim.cfg(53, 3) Hint: added path: 'C:\Users\yekimov\.babel\pkgs\' [Path]
\nim\config\nim.cfg(54, 3) Hint: added path: 'C:\Users\yekimov\.nimble\pkgs\' [Path]
Hint: used config file '\nim\config\nim.cfg' [Conf]
Hint: system [Processing]
Hint: badmod [Processing]
Hint: badmod2 [Processing]
badmod2.nim(4, 6) Hint: 'badmod2.a=(a: var ref TA[a=.T], value: T)' is declared but not used [XDeclaredButNotUsed]
badmod.nim(3, 5) template/generic instantiation from here
badmod2.nim(8, 6) Error: attempting to call undeclared routine: 'a='
```
I think that there have to be no compilation error, since proc `a=` is used from moulde badmod2, where it is defined. With declaration ```proc `a=`*[T](a: var ref TA[T], value: T) = a.fA = value``` there is no compilation error.

**Comment by Araq** [comment] 2015-07-01 11:46
Duplicate of #2599

**Closed by Araq** 2015-07-01 11:46 UTC
