### ISSUE TITLE
Generic function works in module but importing it fails

### ISSUE THREAD

**Issue by oakes** [nim-lang/Nim#16468] opened 2020-12-25 22:12 UTC
The following code works:

```nim
import sets, sequtils

proc dedupe*[T](arr: openArray[T]): seq[T] =
  arr.toHashSet.toSeq

echo dedupe([1, 2, 3])
```

But if I move the proc to its own module, named `foo`, and try to import it like this...

```nim
import foo

echo dedupe([1, 2, 3])
```

I get this error:

```
nim_misc.nim(3, 12) template/generic instantiation of `dedupe` from here
nim_misc/src/foo.nim(4, 6) Error: type mismatch: got <HashSet[system.int]>
but expected one of: 
iterator items(E: typedesc[enum]): E:type
  first type mismatch at position: 1
  required type for E: type enum
  but expression 'toHashSet(arr)' is of type: HashSet[system.int]
iterator items(a: cstring): char
  first type mismatch at position: 1
  required type for a: cstring
  but expression 'toHashSet(arr)' is of type: HashSet[system.int]
iterator items(a: string): char
  first type mismatch at position: 1
  required type for a: string
  but expression 'toHashSet(arr)' is of type: HashSet[system.int]
iterator items[IX, T](a: array[IX, T]): T
  first type mismatch at position: 1
  required type for a: array[IX, T]
  but expression 'toHashSet(arr)' is of type: HashSet[system.int]
iterator items[T: char](a: openArray[T]): T
  first type mismatch at position: 1
  required type for a: openArray[T: char]
  but expression 'toHashSet(arr)' is of type: HashSet[system.int]
iterator items[T: not char](a: openArray[T]): lent2 T
  first type mismatch at position: 1
  required type for a: openArray[T: not char]
  but expression 'toHashSet(arr)' is of type: HashSet[system.int]
iterator items[T](a: seq[T]): lent2 T
  first type mismatch at position: 1
  required type for a: seq[T]
  but expression 'toHashSet(arr)' is of type: HashSet[system.int]
iterator items[T](a: set[T]): T
  first type mismatch at position: 1
  required type for a: set[T]
  but expression 'toHashSet(arr)' is of type: HashSet[system.int]
iterator items[T](s: HSlice[T, T]): T
  first type mismatch at position: 1
  required type for s: HSlice[items.T, items.T]
  but expression 'toHashSet(arr)' is of type: HashSet[system.int]
```

### Expected Output
The `import` should work without error.

### Possible Solution

* If you put `import sets` before the `import foo`, it works.
* In the `foo` module, if you do `export sets.items` it works.
* If you make `dedupe` a non-generic function (declaring it as `proc dedupe*(arr: openArray[int]): seq[int]` for example) it works.

### Additional Information
```
$ nim -v
Nim Compiler Version 1.4.2 [MacOSX: amd64]
Compiled at 2020-12-21
Copyright (c) 2006-2020 by Andreas Rumpf

active boot switches: -d:release
```

**Comment by Clyybber** [comment] 2020-12-25 22:21
Duplicate of https://github.com/nim-lang/Nim/issues/11167

**Closed as completed by Clyybber** 2020-12-25 22:21 UTC
