### ISSUE TITLE
`toSeq` result can't be assigned to a const inside a generic proc 

### ISSUE THREAD

**Issue by dawkot** [nim-lang/Nim#14192] opened 2020-05-02 10:04 UTC
### Example
```nim
import sequtils

proc myProc[T](x: T) =
  const myConst = toSeq(1..3)

myProc 123
```

### Current Output
```
/usercode/in.nim(6, 8) template/generic instantiation of `myProc` from here
/playground/nim/lib/pure/collections/sequtils.nim(712, 11) Error: cannot evaluate at compile time: i`gensym3690237
```

### Workaround
```nim
import sugar

proc myProc[T](x: T) =
  const myConst = collect(newSeq, for i in 1..3: i)

myProc 123
```

### Additional Information

* Nim 1.2.0

**Comment by metagn** [comment] 2020-05-02 20:31
Compiler SIGSEGVs if you do:

```nim
import sequtils

proc myProc[T](x: T) =
  const myConst = static(toSeq(1..3))

myProc 123
```

**Comment by timotheecour** [comment] 2020-06-25 04:08
* @dawkot this has nothing to do with generics, when you state `can't be assigned to a const inside a generic proc` you really have to check whether it would instead work inside a non-generic.
It turns out it also doesn't work:
```nim
when true:
  import sequtils
  proc myProc() =
    const myConst = toSeq(1..3)
  myProc()
```
=> same error


and in fact this is a duplicate of https://github.com/nim-lang/Nim/issues/13795

* @hlaaftana the SIGSEGV mentioned here: https://github.com/nim-lang/Nim/issues/14192#issuecomment-623009474 is a different bug, I've reduced it here: https://github.com/nim-lang/Nim/issues/14802

**Closed as completed** 2020-06-25 04:46 UTC
