### ISSUE TITLE
`Error: undeclared identifier: 'format'` when generic calls strformat.fmt

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/Nim#8609] opened 2018-08-11 01:50 UTC
t05_fmt_undecl_identifier_format2.nim:
```nim
import strformat

proc bar*[T]():string= # ok if non generic
  var a=1
  # result = fmt"{b}" #ok
  result = fmt"{a:#x}" #BUG Error: undeclared identifier: 'format'
```

```main.nim
import t05_fmt_undecl_identifier_format2
echo bar[int]()
```

rnim bugs/stdlib/t05_fmt_undecl_identifier_format.nim
nim c --nimcache:/tmp/nim//nimcache/ -o:/tmp/nim//app -r bugs/stdlib/t05_fmt_undecl_identifier_format.nim
/Users/timothee/git_clone/nim/timn/bugs/stdlib/t05_fmt_undecl_identifier_format.nim(5, 6) template/generic instantiation from here
/Users/timothee/git_clone/nim/timn/bugs/stdlib/t05_fmt_undecl_identifier_format2.nim(6, 15) template/generic instantiation from here
/Users/timothee/git_clone/nim/Nim/lib/pure/strformat.nim(278, 5) Error: undeclared identifier: 'format'
      format($arg, option, res)

workaround: `export strformat.format` in `t05_fmt_undecl_identifier_format2`

**Comment by GULPF** [comment] 2018-08-11 06:01
Duplicate of #7632

**Closed** 2018-08-11 07:08 UTC
