### ISSUE TITLE
cannot add custom pragma to templates

### ISSUE THREAD

**Issue by hamidb80** [nim-lang/Nim#18212] opened 2021-06-07 17:16 UTC
### Example
```nim
import macros

macro myCustomPragma(s: untyped): untyped =
  discard

template myTmplt(): untyped  {.myCustomPragma.}=
  discard
```

### Current Output
> Error: cannot attach a custom pragma to 'myTmplt'

### Expected Output
compiles successfully

### Additional Information
- Nim compiler version: 1.4.8
- OS: windows 10

**Comment by kaushalmodi** [comment] 2021-06-07 18:52
I can confirm this on Nim devel too.

From https://nim-lang.org/docs/manual.html#userminusdefined-pragmas-custom-annotations:

> Custom pragmas can be used in all locations where ordinary pragmas can be specified. It is possible to annotate procs, templates, type and variable definitions, statements, etc.

But running below:

```nim
template myCustomPragma {.pragma.}

template myTmplt() {.myCustomPragma.} =
  discard
```

gives:

> Error: cannot attach a custom pragma to 'myTmplt'

```
> nim -v
Nim Compiler Version 1.5.1 [Linux: amd64]
Compiled at 2021-06-07
Copyright (c) 2006-2021 by Andreas Rumpf

git hash: 5bad022d58e21f0da455fbd7d421cd26a2b5c812
active boot switches: -d:release
```

**Comment by timotheecour** [comment] 2021-06-08 01:01
please check if duplicate of https://github.com/nim-lang/Nim/issues/15920, is so, close it

**Comment by hamidb80** [comment] 2021-06-08 05:18
related to https://github.com/timotheecour/Nim/issues/129

**Comment by Clyybber** [comment] 2021-06-08 09:32
> please check if duplicate of #15920, is so, close it

It isn't. template/macro pragma not working *inside* templates is different than not being able to attach a custom pragma to templates.

**Comment by hamidb80** [comment] 2021-06-08 17:07
@Clyybber, it is the same as 

> related to [timotheecour#129](https://github.com/timotheecour/Nim/issues/129)

**Comment by timotheecour** [comment] 2021-06-08 17:17
> related to timotheecour#129

that's not in nim repo though, it's my own issue tracker, so wouldn't count as duplicate

**Closed as completed** 2022-01-20 19:57 UTC
Labels: Pragmas, Templates
