### ISSUE TITLE
No link to std/exitprocs in docs (+enumerate,jsonutils etc)

### ISSUE THREAD

**Issue by Benjamin-Lee** [nim-lang/Nim#16046] opened 2020-11-19 05:12 UTC
See #15694 for discussion. I tried importing `exitprocs`  only to get an error saying it couldn't open it. Turns out it's in `std` and the docs page makes no mention of how to import it. In addition, it's not listed in the stdlib directory.

**Comment by timotheecour** [comment] 2020-11-19 06:14
> In addition, it's not listed in the stdlib directory

see https://github.com/nim-lang/Nim/issues/15694#issuecomment-715462420

note that search works:

![image](https://user-images.githubusercontent.com/2194784/99628142-6a73eb80-29ea-11eb-9467-a8cd65fcd69e.png)

if you click on the link there's at least now a Source link that shows it's under `Nim/lib/std/exitprocs.nim`


> Turns out it's in std

like all new modules in stdlib.
it'd be redundant to mention this "by hand" in each stdlib module.

instead, this is how we can improve things:


## automatically show proper fully qualified import syntax in docs
in docs, instead of showing the module name (exitprocs for https://nim-lang.github.io/Nim/exitprocs.html) or depending on `--project` (+docroot) option, the relative path (src/fusion/pools for https://nim-lang.github.io/fusion/src/fusion/pools.html), we should also show the `import` syntax eg:

for exitprocs: `import std/exitprocs`
for tables: `import std/tables` # even if relative path is under lib/pure/collections/tables.nim)
for pools: `import fusion/pools`


this should be auto-generated (not mentioned for each module in some doc comment), otherwise it's a total waste of time.

## make sure each stdlib module is referenced in doc/lib.rst (https://nim-lang.github.io/Nim/lib.html)
kochdocs could add some logic to check that all docgen'd stdlib modules are mentioned in lib.rst, that way, it'd always stay in sync.

I'm sure other modules are missing.

**Comment by Benjamin-Lee** [comment] 2020-11-19 06:27
Autogenerating the import syntax in the docs would be great

**Comment by Benjamin-Lee** [comment] 2020-11-19 06:35
Also https://nim-lang.org/docs/jsonutils.html is unlinked.

**Comment by timotheecour** [comment] 2020-11-19 07:45
> https://github.com/nim-lang/Nim/issues/15694#issue-728348487
> If not, I'm happy to PR it.

Note that https://nim-lang.github.io/Nim/theindex.html already references all modules (including exitprocs etc), and in general automated solutions are preferable.
A PR to **automatically** add proper import syntax would be welcome, IMO, but check with others first.

**Comment by ringabout** [comment] 2022-09-24 05:31
Duplicate of https://github.com/nim-lang/Nim/issues/16656

**Closed as completed by ringabout** 2022-09-24 05:31 UTC
Labels: Low Priority, Documentation Generation
