### ISSUE TITLE
For osproc.startprocess to support pipes, need to be able to pass in pipe arrays

### ISSUE THREAD

**Issue by maxgrenderjones** [nim-lang/Nim#6275] opened 2017-08-25 00:53 UTC
## Context

I'm writing a shell in nim, so I want to be able to implement pipes i.e. `cat /etc/passwd | grep root`

I'm starting both `cat` and `grep` using `startProcess`, so I want to create a pipe between `cat`'s output and `grep`'s input. As far as I can tell however, I can't call `dup2` from the parent process to connect the input/output to the pipe. However, if I can pass a pipe into `startProcess`, all works as desired.

My code (connector is `ref` because I don't know what the equivalent of `isNil` is for values):
```nim
var connector: ref array[0..1, cint]
new(connector)
discard $pipe(connector[])
let say = startProcess("/bin/echo", args = ["hello"], pipeStdout = connector)
let hear = startProcess("/bin/cat", args = [], pipeStdIn = connector)

discard waitForExit(say)
close(say)
echo "Output: " & strip(hear.outputStream().readAll)
discard waitForExit(hear)
close(hear)
```
The new `startProcess`:

```nim
proc startProcess(command: string,
                 workingDir: string = "",
                 args: openArray[string] = [],
                 env: StringTableRef = nil,
                 pipeStdin: ref array[0..1, cint] = nil,
                 pipeStdout: ref array[0..1, cint] = nil,
                 pipeStderr: ref array[0..1, cint] = nil,
                 options: set[ProcessOption] = {poStdErrToStdOut}): Process =
    var
      pStdin, pStdout, pStderr: array[0..1, cint]
    new(result)
    result.options = options
    result.exitStatus = -3 # for ``waitForExit``
    if poParentStreams notin options:
      if pipe(pStdin) != 0'i32 or pipe(pStdout) != 0'i32 or
         pipe(pStderr) != 0'i32:
        raiseOSError(osLastError())
      if not isNil(pipeStdin):
        pStdin = pipeStdin[]
      if not isNil(pipeStdout):
        pStdout = pipeStdout[]
      if not isNil(pipeStderr):
        pStderr = pipeStderr[]
#... rest is as before ...
```

It's hacky, but what's the right way to do this? Does `osproc` need a new method, or could I do this some other way? I assume doing it this way isn't cross platform, but I know even less about how to do the equivalent on windows.

**Comment by maxgrenderjones** [comment] 2017-08-25 08:39
Am pretty sure it's a feature request not a question, but would be happy to have it answered either way :)

**Comment by vegansk** [comment] 2017-08-25 09:22
btw, about this:
> connector is ref because I don't know what the equivalent of isNil is for values

Use `Option` type (https://nim-lang.org/docs/options.html)

**Comment by maxgrenderjones** [comment] 2017-08-25 11:23
Good point, thanks 👍

**Comment by maxgrenderjones** [comment] 2017-08-25 11:24
I'm guessing the right way to do it would be to create a `Pipe` type that was automatically backed by a OS-appropriate pipe, and then pass that in?

**Comment by dom96** [comment] 2017-08-25 21:57
To be honest the ``osproc`` code is considered complex by us all. It might be best if you hack on a custom version (which you seem to be doing already). As for how to get what you want working I'm afraid I do not know, you might need to delve into lots of POSIX docs to find out.

**Comment by krux02** [comment] 2018-10-28 21:40
Sorry for digging out this old question, but I don't understand the question. Can you update your API request to use Options instead of ret types? That makes it more clear to me what you actually want. I also don't get the array part of the argument. Why do you want an API with an array of two integers?

**Comment by timotheecour** [comment] 2020-11-07 06:00
duplicate of https://github.com/nim-lang/Nim/issues/6001 and https://github.com/nim-lang/Nim/issues/7999

**Closed by timotheecour** 2020-11-07 06:00 UTC
Labels: Feature
