### ISSUE TITLE
macros/error should marked as noReturn

### ISSUE THREAD

**Issue by codehz** [nim-lang/Nim#16410] opened 2020-12-20 07:49 UTC
https://github.com/nim-lang/Nim/blob/version-1-4/lib/core/macros.nim#L417

Function `error` in `macros` should be marked as noReturn, so we can use it in case of expression...

### Example
```nim
import macros

macro demo(cond: static string) =
  let isok = case cond:
  of "ok": true
  of "notok": false
  else: error("expected as ok or not ok")
```

### Current Output
```
/usercode/in.nim(5, 12) Error: expression 'true' is of type 'bool' and has to be used (or discarded)
```

### Expected Output
no compiler error when compile this macro

### Possible Solution

just mark error in macros as noReturn

**Comment by timotheecour** [comment] 2020-12-23 03:57
@codehz instead please make a PR :)

**Comment by ringabout** [comment] 2021-03-28 09:39
Duplicate of #14329

**Closed as completed** 2021-03-28 09:40 UTC
Labels: Low Priority, Standard Library, Macros
