### ISSUE TITLE
Wrong code generation for tables with "let".

### ISSUE THREAD

**Issue by lscrd** [nim-lang/Nim#16311] opened 2020-12-10 11:59 UTC
When assigning a source table "t1" to a destination table "t2" using "let", if "t1" is modified afterwards and when accessing "t2", we get the data of "t1" (i.e. it seems that a copy has not be done).

### Example
```nim
import tables

proc p() =
  var t1 = {0: 0}.toTable()
  let t2 = t1  # Works if replacing "let" by "var".
  echo "t1 = ", t1
  echo "t2 = ", t2
  t1[1] = 1
  echo "t1 = ", t1
  echo "t2 = ", t2

p()
```

### Current Output
```
t1 = {0: 0}
t2 = {0: 0}
t1 = {0: 0, 1: 1}
t2 = {0: 0, 1: 1}
```

### Expected Output
```
t1 = {0: 0}
t2 = {0: 0}
t1 = {0: 0, 1: 1}
t2 = {0: 0}

```

### Possible Solution

Use "var" instead of "let".

### Additional Information

Same error in devel.

```
$ nim -v
Nim Compiler Version 1.4.2 [Linux: amd64]
Compiled at 2020-11-30
Copyright (c) 2006-2020 by Andreas Rumpf

git hash: 3fb5157ab1b666a5a5c34efde0f357a82d433d04
active boot switches: -d:release
```

**Comment by ee7** [comment] 2020-12-10 14:05
(This issue doesn't occur with `--gc:arc` or `--gc:orc`).

**Comment by timotheecour** [comment] 2020-12-10 19:26
seems like duplicate of https://github.com/nim-lang/Nim/issues/2314

**Closed as completed** 2020-12-10 19:54 UTC
