### ISSUE TITLE
IntLikeForCount in system.nim

### ISSUE THREAD

**Issue by StefanSalewski** [nim-lang/Nim#3821] opened 2016-02-04 13:13 UTC
Sorry, but I have the feeling that this may be wrong:

https://github.com/nim-lang/Nim/blob/master/lib/system.nim

when sizeof(int) <= 2:
  type IntLikeForCount = int|int8|int16|char|bool|uint8|enum
else:
  type IntLikeForCount = int|int8|int16|int32|char|bool|uint8|uint16|enum

No uint32 and int64 listed? May that be old Pascal code from times before 64 bit CPU?

And, more important: Would be fine to have this type exported for writing own iterators.

**Comment by Yardanico** [comment] 2017-08-27 20:10
it's used for example in countup and countdown iterators
all IntLikeForCount types are converted to int, and converting to int64 would make it less optimized
maybe we can close this? @dom96

**Comment by Araq** [comment] 2018-07-01 08:53
> Sorry, but I have the feeling that this may be wrong

Come on, your feelings are not a bug report.

**Closed by Araq** 2018-07-01 08:53 UTC
