### ISSUE TITLE
nim doc - Have an option to hide all the deprecated procs in the generated docs

### ISSUE THREAD

**Issue by ghost** [nim-lang/Nim#7744] opened 2018-05-01 14:45 UTC
Right now, it is difficult to use the docs because CTRL+F finds deprecated procs and with the overloading there are many procs of same name, half of which are deprecated, making even the index at the side useless.
So it would be great if the docs have an option to hide the deprecated procs.
The option should work per-project, and should not reset back to default automatically on each module/single-file documentation.

**Comment by krux02** [comment] 2018-05-01 22:39
I would already be happy when deprecated functions would be shaded with a lower contrast to the background, like if they are fading out slowly.

**Comment by NeeleshChandola** [comment] 2018-06-05 12:09
related https://github.com/nim-lang/Nim/issues/6425

**Comment by krux02** [comment] 2018-06-05 14:11
Like I said it in the other thread, I would prefere low contrast like if it is half way faded out. Much more important though is that deprecated functions don't appear in the center of the documentation anymore. It doesn't help to deprecate functions if you still see them constantly.

**Comment by dom96** [comment] 2018-06-12 19:49
Duplicate of #7744

**Closed by dom96** 2018-06-12 19:49 UTC
Labels: Documentation, Tools
