### ISSUE TITLE
Issue initialising seq of procs gets a type mismatch

### ISSUE THREAD

**Issue by ftsf** [nim-lang/Nim#10817] opened 2019-03-10 11:51 UTC
When trying to assign a sequence of procs in an initialiser the type is mismatched.

### Example

```nim
type
  Object = object
    foo: seq[proc(self: Object): bool]

proc bar(self: Object): bool =
  return true

proc newObject(): Object =
  var ret: Object

  # causes error: test.nim(12, 9) Error: type mismatch: got <seq[proc (self: Object): bool{.noSideEffect, gcsafe, locks: 0.}]> but expected 'seq[proc (self: Object): bool{.closure.}]'
  ret.foo = @[bar]

  # however, this works fine
  #ret.foo = @[]
  #ret.foo.add(bar)

  # this also fails
  #ret.foo = @[]
  #ret.foo.add([bar])

  return ret
```

### Current Output
```
test.nim(12, 11) Error: type mismatch: got <seq[proc (self: Object): bool{.noSideEffect, gcsafe, locks: 0.}]> but expected 'seq[proc (self: Object): bool{.closure.}]'
```

### Expected Output

```
None
```

### Possible Solution
Using add to add individually works, however why this is, is not clear.

### Additional Information

```
$ nim -v
Nim Compiler Version 0.19.4 [Windows: amd64]
Compiled at 2019-03-08
Copyright (c) 2006-2018 by Andreas Rumpf

git hash: b6d96cafc8bcad1f3d32f2910b25cd11a93f7751
active boot switches: -d:release
```

**Comment by GULPF** [comment] 2019-05-05 08:41
See https://nim-lang.org/docs/manual.html#types-procedural-type.

The important parts:
 > closure is the default calling convention for a procedural type that lacks any pragma annotations. 

> nimcall is the default convention used for a Nim proc.

> As a special extension, a procedure of the calling convention nimcall can be passed to a parameter that expects a proc of the calling convention closure.

So `bar` has the calling convention `nimcall`, but the type `proc(self: Object): bool` has the calling convention `closure`. For `add` it works anyway because the compiler can promote `nimcall` to `closure`, but this promotion doesn't work when the proc type is inside a seq like in the assignment. Maybe the compiler can be improved to allow promoting `nimcall` to `closure` in more contexts.

**Comment by metagn** [comment] 2020-04-30 17:04
This is a duplicate of #2614, and intended behaviour, #2614 is tagged error messages for this reason

**Comment by Clyybber** [comment] 2020-07-10 16:58
Closing as duplicate of #2614

**Closed by Clyybber** 2020-07-10 16:58 UTC
