### ISSUE TITLE
fresh compile works but compiling again raises OsError [windows]

### ISSUE THREAD

**Issue by sk-Prime** [nim-lang/Nim#12249] opened 2019-09-24 14:40 UTC
the code snippet i added below compiles first time, i mean fresh compile works fine, but if you try to compile it again it produces osError. the error log is at the bottom of the code snippet. the problem is not with this package, because i tried another package and faced same problem. Previous version of nim worked fine.

edit: compiling with `-f` switch produces no error, but if i remove `-f` same error appears.

### Example

```nim
import nigui

app.init()

var window = newWindow("Hello World")
window.width= 300
window.height= 130

var container = newLayoutContainer(Layout_Vertical)
window.add(container)

var label = newLabel("Hello world")
label.fontSize = 50.0
container.add(label)

window.show()
app.run()
```
```
oserr.nim(94)            raiseOSError
Error: unhandled exception: The filename, directory name, or volume label syntax is incorrect.
 [OSError]
```
though i can compile `echo "hello world"` as many time as i want without any issue.
### Additional Information
* It works previous version of nim which is 0.20.2
```
Nim Compiler Version 1.0.0 [windows amd64]
```

**Comment by narimiran** [comment] 2019-09-24 14:48
This is probably a duplicate of https://github.com/nim-lang/Nim/issues/12242

**Comment by narimiran** [comment] 2019-09-25 20:04
It should be fixed by https://github.com/nim-lang/Nim/pull/12265

**Closed by narimiran** 2019-09-25 20:04 UTC

**Comment by ShieldHero** [comment] 2019-09-25 21:25
This issue should be reopened, the fix is not working.
