### ISSUE TITLE
Slow ``post`` requests using HttpClient on Linux

### ISSUE THREAD

**Issue by vegansk** [nim-lang/Nim#5388] opened 2017-02-14 03:00 UTC
[The discussion is posted on forum](https://forum.nim-lang.org/t/2790). Do I need to replicate details here?

The result of the test (SyncClient - HttpClient):
```
TEST[SyncClient]: Processed 1000 requests in 40 seconds!
TEST[DeprecatedAPI]: Processed 1000 requests in 1 seconds!
TEST[ApacheBenchmark]: Processed 1000 requests in 1 seconds!
```

**Comment by vegansk** [comment] 2017-02-15 11:05
@dom96, here is ``strace -r`` log from another test, that uses just net module. Each ``recv`` call made after ``send`` hangs for some time.
```
[Suite] newzenith
     0.000000 socket(PF_INET, SOCK_STREAM, IPPROTO_TCP) = 3
     0.000097 socket(PF_LOCAL, SOCK_STREAM|SOCK_CLOEXEC|SOCK_NONBLOCK, 0) = 4
     0.000016 connect(4, {sa_family=AF_LOCAL, sun_path="/var/run/nscd/socket"}, 110) = -1 ENOENT (No such file or directory)
     0.000038 socket(PF_LOCAL, SOCK_STREAM|SOCK_CLOEXEC|SOCK_NONBLOCK, 0) = 4
     0.000013 connect(4, {sa_family=AF_LOCAL, sun_path="/var/run/nscd/socket"}, 110) = -1 ENOENT (No such file or directory)
     0.000818 socket(PF_INET, SOCK_DGRAM|SOCK_NONBLOCK, IPPROTO_IP) = 4
     0.000015 connect(4, {sa_family=AF_INET, sin_port=htons(53), sin_addr=inet_addr("192.168.2.100")}, 16) = 0
     0.000034 sendto(4, "\320\33\1\0\0\1\0\0\0\0\0\0\vportal-zsrv\teldisso"..., 43, MSG_NOSIGNAL, NULL, 0) = 43
     0.000529 recvfrom(4, "\320\33\205\0\0\1\0\1\0\1\0\1\vportal-zsrv\teldisso"..., 1024, 0, {sa_family=AF_INET, sin_port=htons(53), sin_addr=inet_addr("192.168.2.100")}, [16]) = 93
     0.000052 connect(3, {sa_family=AF_INET, sin_port=htons(33333), sin_addr=inet_addr("192.168.2.18")}, 16) = 0
     0.000454 sendto(3, "\1\0\237\0\0\0nim\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0"..., 159, MSG_NOSIGNAL, NULL, 0) = 159
     0.000027 recvfrom(3, "\1\0\22\0\0\0\0\0\0\0L\0\0\0d\0\0\0", 4000, 0, NULL, NULL) = 18
     5.490575 sendto(3, "\3\0\16\0\0\0L\0\0\0S\0\0\0", 14, MSG_NOSIGNAL, NULL, 0) = 14
     0.000059 recvfrom(3, "\3\0\16\0\0\0\1\0\0\0\0\0\0\0", 4000, 0, NULL, NULL) = 14
     4.711757 sendto(3, "<__MESSAGE METHOD_NAME=\"GETMYOPE"..., 83, MSG_NOSIGNAL, NULL, 0) = 83
     0.000060 recvfrom(3, "\3\0\16\0\0\0\1\0\0\0r\\\0\0", 4000, 0, NULL, NULL) = 14
     4.781283 sendto(3, "\4\0\16\0\0\0L\0\0\0r\\\0\0", 14, MSG_NOSIGNAL, NULL, 0) = 14
     0.000045 recvfrom(3, "\4\0\26\0\0\0\2\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0", 4000, 0, NULL, NULL) = 22
(header: (type: 4, length: 22), msgState: 2, dataLength: 0, reserved: ...)
22
     4.769134 sendto(3, "\4\0\16\0\0\0L\0\0\0r\\\0\0", 14, MSG_NOSIGNAL, NULL, 0) = 14
     0.000072 recvfrom(3, "\4\0\26\0\0\0\1\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0", 4000, 0, NULL, NULL) = 22
(header: (type: 4, length: 22), msgState: 1, dataLength: 0, reserved: ...)
22
     4.749980 sendto(3, "\4\0\16\0\0\0L\0\0\0r\\\0\0", 14, MSG_NOSIGNAL, NULL, 0) = 14
     0.000164 recvfrom(3, "\4\0\26\0\0\0\1\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0", 4000, 0, NULL, NULL) = 22
(header: (type: 4, length: 22), msgState: 1, dataLength: 0, reserved: ...)
22
     4.750080 sendto(3, "\4\0\16\0\0\0L\0\0\0r\\\0\0", 14, MSG_NOSIGNAL, NULL, 0) = 14
     0.000150 recvfrom(3, "\4\0\26\0\0\0\1\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0", 4000, 0, NULL, NULL) = 22
(header: (type: 4, length: 22), msgState: 1, dataLength: 0, reserved: ...)
22
     4.749996 sendto(3, "\4\0\16\0\0\0L\0\0\0r\\\0\0", 14, MSG_NOSIGNAL, NULL, 0) = 14
     0.000155 recvfrom(3, "\4\0\26\0\0\0\0\0\0\0\236\0\0\0\0\0\0\0\0\0\0\0", 4000, 0, NULL, NULL) = 22
(header: (type: 4, length: 22), msgState: 0, dataLength: 158, reserved: ...)
22
     9.449778 sendto(3, "\5\0\16\0\0\0L\0\0\0r\\\0\0", 14, MSG_NOSIGNAL, NULL, 0) = 14
     0.000053 recvfrom(3, "\5\0\n\0\0\0\236\0\0\0<?xml version=\"1.0\" en"..., 4000, 0, NULL, NULL) = 168
     4.749928 sendto(3, "\2\0\n\0\0\0L\0\0\0", 10, MSG_NOSIGNAL, NULL, 0) = 10
     0.000108 recvfrom(3, "\2\0\n\0\0\0\1\0\0\0", 4000, 0, NULL, NULL) = 10
  [OK] sync API
     4.750480 +++ exited with 0 +++
```

**Comment by vegansk** [comment] 2017-02-16 03:17
@dom96, I found the reason. It's in the flag ``MSG_NOSIGNAL`` at line https://github.com/nim-lang/Nim/blob/devel/lib/pure/net.nim#L1137. Why do we need ``MSG_NOSIGNAL`` here?

**Comment by dom96** [comment] 2017-02-16 17:24
hrm, did you delete your comment?

> I found the reason. It's in the flag MSG_NOSIGNAL at line https://github.com/nim-lang/Nim/blob/devel/lib/pure/net.nim#L1137.
> Why do we need MSG_NOSIGNAL here?


``MSG_NOSIGNAL`` is used to to prevent SIGPIPE being sent to the process.

**Comment by vegansk** [comment] 2017-02-17 02:01
Yes, because it wasn't the reason

**Comment by dom96** [comment] 2017-11-26 23:52
Cannot reproduce on macOS. I'm guessing it's Linux-only.

**Comment by zedeus** [comment] 2020-01-06 00:01
On Linux with devel:
```
TEST[SyncClient]: Processed 1000 requests in 405 milliseconds, 36 microseconds, and 631 nanoseconds seconds!
TEST[ApacheBenchmark]: Processed 1000 requests in 223 milliseconds, 803 microseconds, and 642 nanoseconds seconds!
```

**Comment by dom96** [comment] 2020-01-06 21:14
I'm assuming that means this is fixed. Closing.

**Closed by dom96** 2020-01-06 21:14 UTC
Labels: OS/Arch specific, Stdlib
