### ISSUE TITLE
gcc error "invalid use of void expression" from (mis)use of nil

### ISSUE THREAD

**Issue by jrfondren** [nim-lang/Nim#15623] opened 2020-10-18 15:46 UTC
### Example
```nim
when defined(direct):
  echo cast[ptr int](nil)[]

when defined(indirect):
  var x: ref int = nil
  echo cast[ptr int](x)[]
```

### Current Output -d:indirect
```
Traceback (most recent call last)
/home/jfondren/nim/learn/error1.nim(6) error1
SIGSEGV: Illegal storage access. (Attempt to read from nil?)
```

### Current Output -d:direct
```
/home/jfondren/.cache/nim/error1_d/@merror1.nim.c: In function ‘NimMainModule’:
/home/jfondren/.cache/nim/error1_d/@merror1.nim.c:152:24: error: invalid use of void expression
  152 |  T1_[0] = nimIntToStr((*NIM_NIL));
      |                       ~^~~~~~~~~
Error: execution of an external compiler program 'gcc -c  -w -fmax-errors=3   -I/home/jfondren/.choosenim/toolchains/nim-1.4.0/lib -I/home/jfondren/nim/learn -o /home/jfondren/.cache/nim/error1_d/@merror1.nim.c.o /home/jfondren/.cache/nim/error1_d/@merror1.nim.c' failed with exit code: 1
```

### Additional Information
This isn't a blocker to anything. This is my riffing off someone's `nil[]` joke from IRC.
```
$ nim -v
Nim Compiler Version 1.4.0 [Linux: amd64]
Compiled at 2020-10-16
Copyright (c) 2006-2020 by Andreas Rumpf

git hash: bdcd87afca238a0a7b2c70971827cf9172817b12
active boot switches: -d:release
```

**Comment by ringabout** [comment] 2020-11-17 02:19
This is caused by constants folding:
`cast[ptr int](nil)` is folded to `nil`.

**Comment by timotheecour** [comment] 2020-11-18 01:06
@cooldome when you revert please remember to re-open whatever was closed by the original PR (or add a comment mentioning that it should stay closed)

**Closed as completed** 2020-11-18 07:28 UTC
Labels: Low Priority, Code Generation
