### ISSUE TITLE
i = "A".ord # ==> Error: internal error: invalid kind for last(tyString)

### ISSUE THREAD

**Issue by StefanSalewski** [nim-lang/Nim#3750] opened 2016-01-20 13:08 UTC
var
      #i = 'A'.ord # fine
      i = "A".ord # invalid
      i = ord(3.1) # invalid

    echo i

Not very nice compiler message, beginners may confuse "" for char literal.

    #Nim Compiler Version 0.13.0 (2016-01-20) [Linux: amd64]  
    #Error: internal error: invalid kind for last(tyString)
    #No stack traceback available
    #To create a stacktrace, rerun compilation with ./koch temp c <file>

**Comment by Araq** [comment] 2016-01-20 18:37
Duplicate of #3658

**Closed by Araq** 2016-01-20 18:37 UTC
