### ISSUE TITLE
`type Data = object {.exportc: "DataAux".}` shouldn't compile (exportc is ignored silently)

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/Nim#9883] opened 2018-12-07 04:32 UTC
Nim accepts invalid code, where `exportc` is in wrong position:
```nim
#[
KEY exportc object type
]#

# type Data {.exportc: "DataAux".} = object # correct form, gives `struct DataAux {`
type Data = object {.exportc: "DataAux".} # BUG: compiler accepts this but exportc has no effect, gives `struct tyObject_Data_25MnVmebWay3KnvC5cQREg {`
  cmd: cstring

{.emit: """
DataAux a;
"""
.}

var data: Data
```

**Comment by Araq** [comment] 2018-12-07 08:17
Duplicate of some other bug that I can't find. (Too many open issues.)

**Closed by Araq** 2018-12-07 08:17 UTC
Labels: Codegen, Pragmas, accepts invalid

**Comment by timotheecour** [comment] 2019-06-25 21:37
update:
that code now produces a warning: `Warning: type pragmas follow the type name; this form of writing pragmas is deprecated [Deprecated]`
(nit: but the declaration still compiles and ignores the exportc pragma, so code will compile if we remove the emit statement that refers to `DataAux`); probably good enough given that we at least have a warning

**Comment by lpirl** [comment] 2020-04-09 11:44
> Duplicate of some other bug that I can't find. (Too many open issues.)

#7448?
