### ISSUE TITLE
strange result from executing code in const expression

### ISSUE THREAD

**Issue by deansher** [nim-lang/Nim#10465] opened 2019-01-26 22:09 UTC
I'm not going to speculate yet on what's happening here.

### Example
```nim
import strformat

var fib_n {.compileTime.}: int
var fib_prev {.compileTime.}: int
var fib_prev_prev {.compileTime.}: int

proc next_fib(): int {.compileTime.} =
  let fib = if fib_n < 2:
    fib_n
  else:
    fib_prev_prev + fib_prev
  inc(fib_n)
  fib_prev_prev = fib_prev
  fib_prev = fib
  fib

const f0 = next_fib()
const f1 = next_fib()
const f2 = next_fib()
const f3 = next_fib()
const f4 = next_fib()

static:
  echo fmt"Fibonacci sequence: {f0}, {f1}, {f2}, {f3}, {f4}"

const fib_continues = block:
  var result = fmt"Sequence continues: "
  for i in 0..10:
    if i > 0:
      add(result, ", ")
    add(result, $next_fib())
  result

static:
  echo fib_continues 
```

### Current Output
```
Fibonacci sequence: 0, 1, 1, 2, 3
Sequence continues: 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5
```

### Additional Information
```
$ nim -v
Nim Compiler Version 0.19.2 [MacOSX: amd64]
Compiled at 2018-12-31
Copyright (c) 2006-2018 by Andreas Rumpf

git hash: 7beea1642ddf7845a9a0034c7a93ccbe15894c36
active boot switches: -d:release
```

**Comment by deansher** [comment] 2019-01-26 22:13
Eliminating the `{.compileTime.}` from `next_fib()` makes it work.

**Comment by mratsim** [comment] 2019-01-27 09:30
Seems like a duplicate of https://github.com/nim-lang/Nim/issues/9817 that is fixed in devel by https://github.com/nim-lang/Nim/issues/9817

**Comment by ringabout** [comment] 2020-07-08 06:28
It works in 1.0.6

```
Fibonacci sequence: 0, 1, 1, 2, 3
Sequence continues: 5, 8, 13, 21, 34, 55, 89, 144, 233, 377, 610
```

**Closed** 2020-07-08 23:51 UTC
Labels: Pragmas, VM
