### ISSUE TITLE
Update official docs to stack overloaded procs in the sidebar to clean up the documentation

### ISSUE THREAD

**Issue by exts** [nim-lang/Nim#7628] opened 2018-04-16 19:19 UTC
Lets use the [strutils module](https://nim-lang.org/docs/strutils.html) docs as an example. There's a TON of overloaded procs here and my suggestion would turn 

```
isSpaceAscii
isLowerAscii
isUpperAscii
toLowerAscii
toLowerAscii
toUpperAscii
toUpperAscii
capitalizeAscii
isSpace
isLower
isUpper
isAlpha
isAlpha
isSpace
isLower
isUpper
toLower
toLower
toUpper
toUpper
```

To:

```
capitalizeAscii
isAlpha
isLower
isLowerAscii
isSpace
isSpaceAscii
isUpper
isUpperAscii
toLower
toLowerAscii
toUpper
toUpperAscii
```

I also think procs should be organized by special characters then alphabetical order.  This would clean up the sidebar and make the docs look a bit cleaner and approachable.

**Comment by data-man** [comment] 2018-04-16 20:36
Duplicate of #2775

**Closed by data-man** 2018-04-16 20:36 UTC
