### ISSUE TITLE
Nesting closure iterators produce incorrect code if for loop is used  

### ISSUE THREAD

**Issue by cooldome** [nim-lang/Nim#5690] opened 2017-04-10 22:21 UTC
The following code compiles, but produces incorrect result, expected '99 99', but '99 0' is produced
```
proc filter[T](it: (iterator : T), f: proc(x: T): bool): (iterator : T) =
  return iterator (): T {.closure.} =
    for x in it():
      if f(x): 
        yield x

proc len[T](it : iterator : T) : Natural =
  for i in it():
    result += 1

proc simpleSeqIterator(s :seq[int]) : iterator : int =
  iterator it: int {.closure.} =
    for x in s:
      yield x
  result = it

let a = newSeq[int](99)
echo len(a)
echo len(simpleSeqIterator(a).filter(iter, proc(x : int) : bool = true))
```

Interesting that workaround exists, switch to while loop in the filter[T], like this:
```
proc filter[T](it: (iterator : T), f: proc(x: T): bool): (iterator: T) =
  return iterator(): T =
    while (let x = it(); not finished(it)):
      if f(x):
        yield x

```

**Comment by vegansk** [comment] 2017-04-11 02:35
Possible duplicate of #5522

**Comment by cooldome** [comment] 2017-04-11 22:23
#5340 seems to be also related

**Comment by narimiran** [comment] 2019-02-20 10:05
Works correctly with Nim 0.19.9

**Closed by narimiran** 2019-02-20 10:05 UTC
Labels: Iterators
