### ISSUE TITLE
closures don't work in VM when using js backend

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/Nim#18417] opened 2021-07-02 03:24 UTC
### Example
```nim
when true: # D20210701T201807
  proc main =
    var x = 2
    proc fn3(a: int) =
      let x2 = x # Error: cannot evaluate at compile time: x
    fn3(1)

  static: main()
  main()
```

### Current Output
Error: cannot evaluate at compile time: x

### Expected Output
works

### Additional Information
1.5.1 3ceaf5c1309ac8d4d68e6f39c13b021bcc1b15f4
works with c or cpp backend (RT+VM)
works with js backend (RT)
fails with js backend in VM

**Comment by ringabout** [comment] 2021-07-02 03:52
Duplicate of #12492

**Closed as completed by ringabout** 2021-07-02 03:52 UTC
Labels: Javascript, Medium Priority, VM
