### ISSUE TITLE
-d:release results in "internal compiler error"

### ISSUE THREAD

**Issue by axbender** [nim-lang/Nim#2295] opened 2015-03-09 09:48 UTC
Compiling a program of mine w/o -d:release works fine, with -d:release results in the following compiler error:

```
In file included from g:\src\nim\opts\nimcache\opts.c:8:0:
g:\src\nim\opts\nimcache\opts.c: In function 'optsInit':
g:\src\nim\opts\nimcache\opts.c:855:30: internal compiler error: Segmentation fault
NIM_EXTERNC N_NOINLINE(void, optsInit)(void) {
                              ^
D:\tools\nim\lib/nimbase.h:138:71: note: in definition of macro 'N_NOINLINE'
#  define N_NOINLINE(rettype, name) rettype __attribute__((noinline)) name
                                                                     ^
Please submit a full bug report,
with preprocessed source if appropriate.
See <http://sourceforge.net/projects/mingw-w64> for instructions.
Error:  execution of an external program failed; rerun with --parallelBuild:1 to see the error message
```

System is Windows 7-64, gcc (x86_64-win32-sjlj-rev0, Built by MinGW-W64 project) 4.9.2, nim of today.
Whose responsibility is this?

**Comment by reactormonk** [comment] 2015-03-09 14:55
Please post a smallest reproducible snippet.

**Comment by axbender** [comment] 2015-03-09 16:55
```nim
import strutils

var
   p: seq[string]
   # Before you say, hey this isn't initialized,
   # uncomment the next line!
#  q: seq[string] = @["2", "3"]

iterator next(): string =
   for i in 0 .. 1:
      var
         yld = "abc"
         o   = 0

      while o <= 1:
         if p[i].startsWith("aa"):
            break
         inc o

      if false:
         var numeric: bool
         try:
            numeric = true
         except ValueError:
            numeric = false

         if numeric:  yld = "abc"
         elif o == 1: yld = "abc"

      yield yld

for val in next():
   echo val

**Comment by Araq** [comment] 2015-03-11 19:22
Works for me if I initialize 'p'. (mingw 32 bit.)

**Comment by axbender** [comment] 2015-03-12 17:27
I stripped this down as far as I could - no longer doing anything useful. Be assured, that p is initialized in my not-stripped down program. Also, when you eliminate the declaration of "q" the *compile-time* error disappears.
I'll try to provide a more useful sample.

**Comment by axbender** [comment] 2015-03-13 13:26
@Araq:
Please have a look at this:
```nim
import os
import strutils

var
   G_base: array[0..1, string]

iterator nextOption(): string =
   var
      args = commandLineParams()

   var i = 0
   while i < paramCount():
      var
         par = args[i]
         yld = "_unknown"

      var o = 0
      while o <= 1:
         if par.startsWith("aa"): break
         inc o

      if (o <= 1):
         if o == 1:
            inc i
            continue

         else:
            try: discard "cc".parseFloat() except ValueError: discard
            yld = G_base[o]

      inc i
      yield yld

for opt in nextOption():
   echo "OPT: ", opt
```

**Comment by axbender** [comment] 2015-03-13 15:58
Even smaller:

```nimrod
import strutils

var
   G_base: array[0..1, string]

iterator nextOption(): string =
   var
      args = ["aa", "bb", "cc"]

   var i = 0
   while i < args.len:
      var
         yld = "_unknown"

      var o = 0
      while o <= 1:
         if args[i].startsWith("aa"): break
         inc o

      if (o <= 1):
         if o == 1:
            inc i
            continue

         else:
            try: discard "cc".parseFloat() except ValueError: discard
            yld = G_base[o]

      inc i
      yield yld

for opt in nextOption():
   echo "OPT: ", opt
```

**Comment by Araq** [comment] 2015-03-17 12:07
Your latest program produces: 

```
OPT: nil
OPT: _unknown
OPT: _unknown
```

for me. So what's the error for you? Nim crashing or GCC crashing?

**Comment by axbender** [comment] 2015-03-17 12:22
I can't compile the program with -d:release. The compiler throws
```
In file included from d:\temp\down\nimcache\test.c:8:0:
d:\temp\down\nimcache\test.c: In function 'testInit':
d:\temp\down\nimcache\test.c:395:30: internal compiler error: Segmentation fault
 NIM_EXTERNC N_NOINLINE(void, testInit)(void) {
                              ^
D:\tools\nim\lib/nimbase.h:138:71: note: in definition of macro 'N_NOINLINE'
 #  define N_NOINLINE(rettype, name) rettype __attribute__((noinline)) name
                                                                       ^
Please submit a full bug report,
with preprocessed source if appropriate.
See <http://sourceforge.net/projects/mingw-w64> for instructions.
Error:  execution of an external program failed; rerun with --parallelBuild:1 to see the error message
```
Omitting the -d:release switch, I obtain the same results as you do.

**Comment by axbender** [comment] 2015-03-17 15:19
Using the WinBuilds toolchain (gcc 4.8.3) the code compiles. It does not compile with MinGW-w64 gcc 4.9.2.

**Comment by Araq** [comment] 2016-04-04 14:26
Still works for me.

**Comment by Yardanico** [comment] 2017-08-27 20:31
Maybe close? Others haven't confirmed this issue, and it seems to be C compiler crash

**Comment by Araq** [comment] 2017-08-28 08:40
Closing until more feedback arrives.

**Closed by Araq** 2017-08-28 08:40 UTC
Labels: Codegen, S: Waiting on author
