### ISSUE TITLE
"Most of the winlean declarations are incorrect or non stable."

### ISSUE THREAD

**Issue by alaviss** [nim-lang/Nim#15231] opened 2020-08-27 14:53 UTC
This issue is created to track the [feedback](https://github.com/status-im/nim-stew/pull/53#issuecomment-681850810) regarding `winlean` from @cheatfate 

> Most of the `winlean` declarations are incorrect or non stable.
> 
> 1. `int32` as `DWORD`, but `DWORD` is actually `uint32`.
> 
> 2. Sometimes return values are missed completely.
> 
> 3. Some of the declarations are made for specific case `useWinUnicode`, so API calls you are using can become unavailable when compilation flags got changed.
> 
> 4. Some `ptr arg` arguments sometimes declared as `var arg` and you can't use `nil` as an argument...

**Comment by arnetheduck** [comment] 2020-08-31 08:43
Duplicate of https://github.com/nim-lang/Nim/issues/12327 mostly

**Closed as completed** 2020-08-31 21:22 UTC
