### ISSUE TITLE
Error in rendering empty JSON array

### ISSUE THREAD

**Issue by andreaferretti** [nim-lang/Nim#4399] opened 2016-06-23 15:06 UTC
The following

```nim
import json

let y = %[]

echo y
```

prints `{}`. This is particularly inconvenient when using the `%*` macro, where the empty sequence could be nested arbitrarilly

**Comment by Araq** [comment] 2016-06-23 17:42
What should it produce instead? ``[]``?

**Comment by andreaferretti** [comment] 2016-06-23 18:16
Yes. There are easy workaround (such as using `newSeq[...]()`) but `[]` is definitely what I would expect

**Comment by jangko** [comment] 2016-06-25 05:43
the compiler confused between this two procs

```nimrod
proc `%`*(keyVals: openArray[tuple[key: string, val: JsonNode]]): JsonNode =
  ## Generic constructor for JSON data. Creates a new `JObject JsonNode`
  result = newJObject()
  for key, val in items(keyVals): result.fields[key] = val

proc `%`*[T](elements: openArray[T]): JsonNode =
  ## Generic constructor for JSON data. Creates a new `JArray JsonNode`
  result = newJArray()
  for elem in elements: result.add(%elem)
```

and the compiler choose the the first one, the one wrong one.
looks like a semcheck issue too.

**Comment by jangko** [comment] 2016-06-25 07:27
this is a duplicate of #3950

**Comment by Araq** [comment] 2016-06-25 07:39
> looks like a semcheck issue too.

No, the compiler adheres the spec which says that in this case the non-generic implementation is to be preferred.

**Comment by Araq** [comment] 2016-06-25 07:43
The problem here is that ``{:}`` is a synonym for ``[]`` and while ``%[]`` should produce an empty JSON list, ``%{:}`` should produce an empty object. ``%{:}`` is not used out there I bet (since it's not known), so the right fix is to make the % for openArray special casing the len==0.

**Comment by jangko** [comment] 2016-06-25 08:00
I've tried it, and it fix the issue altough a bit weird

```nimrod
proc `%`*(keyVals: openArray[tuple[key: string, val: JsonNode]]): JsonNode =
  ## Generic constructor for JSON data. Creates a new `JObject JsonNode`
  if keyVals.len == 0: return newJArray()
  result = newJObject()
  for key, val in items(keyVals): result.fields[key] = val
```

**Comment by Araq** [comment] 2016-06-26 09:00
PR please!

**Comment by jangko** [comment] 2016-06-26 13:26
the above solution not work for `%{:}` because now it's produce `[]` too, which is wrong.
need to find another solution.

**Comment by Varriount** [comment] 2016-06-26 15:10
Hm. Would a term-rewriting macro work? Of course, that would only affect 'literal' values, not computed ones...

**Comment by Araq** [comment] 2016-06-27 00:45
> the above solution not work for %{:} because now it's produce [] too, which is wrong.

I said so, but I don't think it's a problem, few people know about %{:}

**Closed** 2016-07-08 19:13 UTC
Labels: High Priority, Stdlib
