### ISSUE TITLE
Koch tests doesn't run tests for `lib/impure/re.nim`

### ISSUE THREAD

**Issue by cyberlis** [nim-lang/Nim#9683] opened 2018-11-11 17:07 UTC
Koch tests doesn't run tests for `lib/impure/re.nim`
I tried to test `lib/impure/re.nim` with command `./koch tests`. After execution of this command, I didn't find any mention of `re.nim`

Inside `re.nim`, in the end of the file there are tests under `when isMainModule:`. But even if you change this test (break it) command  `./koch tests` doesn't run this tests.

I tested this module by hand using this command `nim c -r lib/impure/re.nim`

I don't know how to add this module to all tests in `./koch tests`, that's why I can't fix it myself.

**Comment by timotheecour** [comment] 2018-12-06 06:31
duplicate of https://github.com/nim-lang/Nim/issues/9328
see my finding here: https://github.com/nim-lang/Nim/issues/9328#issuecomment-434518662

indeed: that's what's currently being run:
testStdlib(r, "lib/pure/*.nim", options, cat)
testStdlib(r, "lib/packages/docutils/highlite", options, cat)

**Closed by timotheecour** 2018-12-06 06:31 UTC
Labels: koch
