### ISSUE TITLE
`sugar.collect` doesn't work when there are conflicting symbols

### ISSUE THREAD

**Issue by Menduist** [nim-lang/Nim#22011] opened 2023-06-05 15:37 UTC
### Description

```nim
import sugar

proc collect(i: int) = discard

var x = collect(newSeq()):
  for i in 0..5: i
echo x
```

When removing the `proc collect`, or switching to `newSeq[int]()` this works. However in my real code, using `newSeq[int]` doesn't work, so its not an option (looking into why)

### Nim Version

b880cdff49576c0eb83a043cbae595d3587c95b4

### Current Output

```text
/tmp/test2.nim(5, 23) template/generic instantiation of `newSeq` from here
/home/tavon/.choosenim/toolchains/nim-#devel/lib/system.nim(590, 14) Error: cannot instantiate: 'T'
```

### Expected Output

```text
@[0, 1, 2, 3, 4, 5]
```

**Comment by Araq** [comment] 2023-06-05 19:39
Overloads must agree on the positions of `untyped` parameters. Old language problem but not a bug. Alternatively consider it a duplicate of lots of other reported bugs. Write it as `sugar.collect` explicitly and it should work.

**Closed as completed by Araq** 2023-06-05 19:39 UTC
