### ISSUE TITLE
The `func` keyword for "pure" functions

### ISSUE THREAD

**Issue by ozra** [nim-lang/Nim#2716] opened 2015-05-14 14:08 UTC
As I'm investigating this interesting language, somewhere, on some page, I saw a mention that a `func` keyword as more convenient syntax for declaring a procedure 'purely functional' was considered.
I couldn't find a issure refering to it, so I add it here, since I find it an essential feature.

Nim is ofcourse a systems language (which is what I'm after!), still purely functional coding is proven to be safer, so enabling and pushing for purer functionalistic coding style while still allowing everything would be a good thing.

Also, many backend (out of Nim perspective) compilers (C/C++) has pragmas and annotations for "pure" or "const" ("really pure") functions which can be leveraged and hints and helps the backend compiler generate even faster code. 

So:
- Already on the table for Nim (as far as I understand)
- Expresses coders intent
- Intent verifiable
- Possibly increased performance in final binary.

**Comment by reactormonk** [comment] 2015-05-14 21:50
So what would be the difference to `proc {.noSideEffect.}`?

**Comment by ozra** [comment] 2015-05-15 01:09
None. Just more sugar on the porridge. Cleaner syntax, promoting its use.

**Comment by reactormonk** [comment] 2015-05-15 03:05
Ok, feel free to implement it. Lexer for the keyword, parser for the pragma stuff.

**Comment by dom96** [comment] 2015-05-15 14:36
Araq mentioned that he was considering making the 'func' keyword something that could be library-defined. So by default it would mean noSideEffects but a library could potentially change that meaning.

**Comment by ozra** [comment] 2015-05-20 09:44
@reactormonk cool, I'll just have to get more aquainted with Nim first, gonna code a couple of utils for myself to get warm.
@dom96 - Some thoughts: I think `func` has a pretty obvious meaning, so instead of over generalizing the language, perhaps it's good to cut some things in stone.
Whether a piece of code is procedural or purely functional is of great value both to the code reviewer / programmer and the compiler to know. So the semantic value is high imo.

- When it comes to backend optimizability, gcc has the pragmas `pure` and `const` for "functions"  - I think opting for the gcc-`const`-pragma-def would be a good thing (which essentially boils down to "purely pure". If I remember correctly the `pure` pragma still allows globals, but not mutating arguments. `const` allows no side effects. 
- For readability and intent: I think seeing `func` lends naturally, in relation to having the `proc`-keyword, that it refers to a pure function - having behavior redefined by libraries would just be confusing, would be better to use another keyword with a more open meaning for that perhaps?
- Compilation performance: I've just stumbled upon Nim, one of the things that attract me, and is the driving force for me to constantly try to ditch C++, is compilation time. I have no clue as to performance hits, I'll admit, but when putting more and more of (potentially) commonly used patterns into macros and templates - won't that put more and more of compilation time in the VM, vs native code?

**Comment by dom96** [comment] 2015-05-20 09:47
@ozra I agree. I think that if @Araq truly wants a library-defined keyword he should introduce 'custom' or something.

**Comment by Araq** [comment] 2015-05-20 13:29
@ozra 'func' doesn't have a "pretty obvious" meaning, that's why it still hasn't been added to the language. ;-) The library-defined keyword fills a real hole in the language since you can have a macro resembling a control flow structure like 

```nim
match x:
of "[a-z]*": echo "identifier"
```

but a macro that resembles a routine is not possible due to parser limitations:

```nim
mymacro foo(x, y: var int): string = ... 
```

but not misusing 'func' for that is fine with me, it's not a hole in the language that keeps me awake at night anyway.

**Comment by Araq** [comment] 2015-05-20 13:31
I like Jehan's suggestion, but keeping ``{. .}`` for pragma statements is good enough. These are rare.

**Comment by dom96** [comment] 2015-05-20 14:29
> I like Jehan's suggestion, but keeping ``{. .}`` for pragma statements is good enough. These are rare.

@Araq, was that meant to be a reply to #2721?

**Comment by ozra** [comment] 2015-05-20 14:48
@Araq - yeah in the #2742 it became apparent that there are more things to it than being 'the obvious', haha. I'm reading the compiler internals straight through now to get a broader picture first.

@Araq, @dom96  - eh, yes, I can't figure out who Jehan is? I'll save commentary for #2721..

**Comment by abudden** [comment] 2016-06-01 12:50
Having seen the RFC label on this, I just thought I'd add my opinion to the discussion.  As someone who has done a lot of (mostly C) code reviewing in my time, I really like the idea of having a dedicated, clean syntax (i.e. `func`) for procedures with no side effects.  The use of `func` rather than `proc {.noSideEffect.}` seems to me to encourage people to actually use the feature rather than being lazy and just doing `proc`.  The single meaning of `func` to *always* be `proc {.noSideEffect.}` is clear and consistent for those of us who get to review code.

Having some other keyword for library-defined stuff seems like a good idea, but I think `func` is not the word for that.

**Comment by mraxilus** [comment] 2017-05-29 14:04
As someone who prefers to write in a more functional style wherever possible, `func` makes sense and avoids unnecessary repetition of the whole `{. noSideEffect .}` boilerplate.

**Comment by bluenote10** [comment] 2017-05-29 20:25
@mraxilus To me the fact that `func` is a reserved keyword actually gets more in the way of writing in a functional style then it would help. For higher order functions I would often like to name a function argument `func` (instead of just `f`, if the single letter "f" has another domain specific meaning), but I can't. If it turns out that Nim doesn't need this keyword, I would even leave the name for the users.

**Comment by mraxilus** [comment] 2017-06-04 21:28
Regardless, the point is whether or not `func` should be provided as a short-hand. I believe the crux of the issue is that some of us would like to be able to have procedures default to having `{. noSideEffect .}` and having to specify `{. withSideEffect .}` instead.

Just as you have the choice of `let` and `var`, the choice between side effects or no for functions should be just as easy.

**Comment by dom96** [comment] 2017-12-23 14:26
We should do this for v1.0 I think.

**Comment by Yardanico** [comment] 2017-12-23 14:27
@dom96 Araq is working on it (you can see his commits related to DFA)

**Comment by dom96** [comment] 2017-12-23 14:36
Yes, I guess he's improving data flow analysis. This issue is just about making 'func' work which is separate.

**Comment by GULPF** [comment] 2017-12-23 15:12
I think Araq has mentioned that `func` shouldn't just be sugar for `{. noSideEffect .}`, but that it should indicate an actual pure function (e.g no side effects at all, which sadly isn't what the `noSideEffect` pragma does). I might be remembering things wrong though.

**Comment by Yardanico** [comment] 2017-12-23 16:23
@dom96 Araq will use DFA for `func`

**Comment by andreaferretti** [comment] 2018-01-03 09:23
> no side effects at all, which sadly isn't what the noSideEffect pragma does

@GULPF What do you mean by this?

**Comment by GULPF** [comment] 2018-01-03 09:46
This is what the manual says about `noSideEfffect`:
>The noSideEffect pragma is used to mark a proc/iterator to have no side effects. This means that the proc/iterator only changes locations that are reachable from its parameters and the return value only depends on the arguments. If none of its parameters have the type var T or ref T or ptr T this means no locations are modified. It is a static error to mark a proc/iterator to have no side effect if the compiler cannot verify this.

So it's valid for a proc with the `noSideEffect` pragma to have side effects, as long as it only mutates its arguments. This compiles and runs fine, even though `mutate`obviously has side effects:

```nim
proc mutate(x: var int) {.noSideEffect.}=
  x.inc

var x = 1
mutate(x)
doAssert x == 2
```

**Comment by Araq** [comment] 2018-01-03 12:49
> This compiles and runs fine, even though mutate obviously has side effects:

"Side effect" has no precise definition and by Nim's definition it doesn't have "side" effects (it's part of the parameter declaration). ``mutate`` obviously does mutate, that's it.

**Comment by GULPF** [comment] 2018-01-03 13:14
Fair enough, but I'd argue that most people count mutating arguments as a side effect. [Wikipedia](https://en.wikipedia.org/wiki/Side_effect_(computer_science)):
>In computer science, a function or expression is said to have a side effect if it modifies some state outside its scope or has an observable interaction with its calling functions or the outside world besides returning a value. For example, a particular function might modify a global variable or static variable, __modify one of its arguments__, raise an exception, write data to a display or file, read data, or call other side-effecting functions. In the presence of side effects, a program's behaviour may depend on history; that is, the order of evaluation matters. Understanding and debugging a function with side effects requires knowledge about the context and its possible histories.[1][2]

In the `mutate` example it doesn't look to bad since the mutating behavior is part of the signature, but it gets worse when a proc takes a ref type as an argument. It's fine to use a Nim-specific definition of side effect, but I think it would be highly confusing to call a `noSideEffect` proc "pure", as I doubt FP purists (which the `pure` syntax appeals to) shares that definition.

**Comment by Araq** [comment] 2018-01-03 13:48
We could introduce ``noGlobals`` as an alias for ``noSideEffect``.

**Comment by Araq** [comment] 2018-04-23 09:25
``func`` is now an alias for ``proc {.noSideEffect.}``. Closing.

**Closed by Araq** 2018-04-23 09:25 UTC
Labels: RFC

**Comment by GULPF** [comment] 2018-04-23 09:35
@Araq Have you given up on write tracking, or will it be implemented later? I think lots of FP-purists will be disappointed when they realize `func` doesn't prevent mutations.

**Comment by Araq** [comment] 2018-04-23 10:05
@GULPF Can always be done later, but I consider it less important now that Nim is moving towards more ``var object`` vs ``object`` (as opposed to ``ref object``) where the mutability control is clearly visible in the parameters already.
