### ISSUE TITLE
Packed pragma does not work on windows

### ISSUE THREAD

**Issue by Electric-Blue** [nim-lang/Nim#3511] opened 2015-11-04 08:39 UTC
`Packed` pragma does not work on windows (win-10_x64 nim-0.12.0_x64) as expected.

``` nim
type
  testStruct {.packed.} = object
    field1: int8
    field2: int32

var
  testVar: testStruct

assert(sizeof(testVar) == 5)
```

The cause is bug in mingw compiler (https://gcc.gnu.org/bugzilla/show_bug.cgi?id=52991).
Adding `-t: "-mno-ms-bitfields"` to `nim.cfg` fixed this issue for me.

**Comment by cheatfate** [comment] 2017-03-18 18:59
Same issue #4763.

**Comment by Araq** [comment] 2017-07-17 07:30
Duplicate of #4763 and was fixed.

**Closed by Araq** 2017-07-17 07:30 UTC
Labels: OS/Arch specific, Pragmas
