### ISSUE TITLE
finish.exe seems not to exist, but installation was straightforward!

### ISSUE THREAD

**Issue by edreamleo** [nim-lang/Nim#23152] opened 2024-01-01 16:08 UTC
### Description

A report about my installation experience. **tl;dr:**

- Installation was easy, despite glitches. Well done, Nim devs!
- There may be a way around false malware reports.

**Documentation glitch?**

The [Windows installation page](https://nim-lang.org/install_windows.html) says:

"The zip file includes a simple application called `finish.exe` that can attempt to add both directories to your PATH. This tool also checks for the presence of a C compiler and can install MingW, the GNU C compiler collection for Windows."

I did not find `finish.exe` anywhere. But this was *after* Bitdefender deleted the supposed malware.

**nimble to the rescue**

Happily, I knew about the [nim package](https://nimble.directory/pkg/nim).

`nimble install nim` just worked even without changing my Windows path.

*Perhaps I got lucky*: I had already installed gcc (and added gcc.cmd), so nimble could invoke gcc.

**Did Bitdefender delete finish.exe?**

I have no way of knowing. Bitdefender disinfected the .zip file before I opened it.

**Summary**

- I did not find `finish.exe` anywhere. Perhaps Bitdefender deleted it.
- Installation using `nimble install nim` was straightforward, but **I had already installed gcc**.

So installation was possible *even after Bitdefender deleted the supposed malware*.

But doesn't that mean there *is* a way to avoid the false positive malware reports:

- Delete whatever Bitdefender deleted!
- If Bitdefender *did* delete `finish.exe`, tell people to use `nimble install nim`.

There are guesses. What do you think?

### Nim Version

```console
Nim Compiler Version 2.0.2 [Windows: amd64]
Compiled at 2023-12-15
Copyright (c) 2006-2023 by Andreas Rumpf

active boot switches: -d:release
```

**Comment by penguinite** [comment] 2024-01-02 20:14
BitDefender most likely deleted finish.exe since I was able to find it in a freshly-downloaded archive. I have already reported Nim 2.0.0 and Nim 2.0.2 as false positives to BitDefender, so now its just time to wait for them to respond and for them to delete it off of their lists.

And also here are the virus-total results for the plain nim 2.0.0 and 2.0.2 release zip files.
Nim 2.0.0 https://www.virustotal.com/gui/file/54ef6f0c3ed26d9615b3f0e442fcbf780dbf31b54d2adcf61257b880a2512d60
Nim 2.0.2 https://www.virustotal.com/gui/file/948dbf8e3fdd1b5242e3d662fd25c50e9b2586e097be8a85c22d7db2bde70bad

And here are the virus-total results for nim 2.0.0 and 2.0.2 (where I removed finish.exe)
Nim 2.0.0 https://www.virustotal.com/gui/file/ab5d62bb3d3bf875838903e2ecc1f168052ac9e2a68f17526962f7e2fc9ab7c3?nocache=1
Nim 2.0.2 https://www.virustotal.com/gui/file/ef79581d41875280f191f9e4257aa7fea0bb5a2ece252daef1e09c77d7698a02?nocache=1

Removing finish.exe reduced quite a lot of AV false positives but its obvious that there are still some, which means the anti-viruses are detecting a bit pattern in all Nim binaries (maybe NimMain? I am not sure)  and not a single binary.

Ultimately there are three solutions to this AV problem:
1. Switch out binaries in the releases for scripts whenever possible. (This will not completely reduce AV false positives)
2. Buy a certificate for Nim. (This is costly and it won't reduce AV false positives for people distributing software built with Nim)
3. Complain to the AV companies

Out of all three of these options, number 3 is the best we have, if we complain enough to these AV developers then they might eventually realize that not every Nim binary is malware, and we will have solved this problem for good.

Unfortunately, it also requires patience, a lot of time and persistence. This AV problem is genuinely a pain to deal with. I especially dislike it when AV companies do not provide an email address for false positives, and they instead force me to use a hacky, broken HTML form. (Avast and AVG's false positive submission forms have failed like 5 times on me when I tried to submit Nim)

**Comment by edreamleo** [comment] 2024-01-03 10:41
@systemonia Thanks for you detailed response. Surely this must be a frustrating situation for you.

Perhaps there is a fourth option. Is there a way you can track down the bit pattern that is causing the problem?

Nim #23151 gives the following Bitdefender log:

```console
nim-2.0.2_x64.zip=>nim-2.0.2/bin/nimgrab.exe
Trojan.GenericKD.70907822 Deleted
 Gen:Variant.Tedy.472027 Deleted
```

Presumably the bit patterns for these two malware are public knowledge.

Perhaps you could hack your sources so these patterns no longer appear in the binaries.

**Comment by edreamleo** [comment] 2024-01-03 20:09
@systemonia Or maybe rewrite `finish.nim` in python, and package it as `finish.exe`?

**Comment by edreamleo** [comment] 2024-01-04 10:31
@systemonia @ringabout @Araq 

There are at least two python tools that convert `.py` files to `.exe`:
- [pyinstaller](https://pypi.org/project/pyinstaller/)
- [auto-py-to-exe](https://pypi.org/project/auto-py-to-exe/)

Any comments?

**Comment by Araq** [comment] 2024-01-04 13:59
No, won't do that.

**Comment by penguinite** [comment] 2024-01-04 16:06
finish.exe is not the only binary causing issues, nimgrab.exe, nimgrep.exe and others are also causing issues. I am currently trying to investigate specifically what antiviruses flag as suspicious behavior since replacing every binary isn't practical.

In addition, I am also trying to deploy the third solution of simply reporting Nim false positives to AVs. I've already got Nim 1.6.16 to 2.0.0 off a couple of AVs thankfully.

**Comment by edreamleo** [comment] 2024-01-04 16:07
@systemonia Thanks for the update. Best of luck to you.

**Comment by ringabout** [comment] 2024-10-25 11:37
Duplicate of https://github.com/nim-lang/Nim/issues/23307

**Closed as not planned by ringabout** 2024-10-25 11:37 UTC
Labels: Installation
