### ISSUE TITLE
terminal crashes Unicode output

### ISSUE THREAD

**Issue by axbender** [nim-lang/Nim#2982] opened 2015-06-24 16:34 UTC
``` nim
import os, terminal
var dir = paramStr(1)
for kind, path in walkDir(dir):
   setForegroundColor(fgRed, true)
   setBackgroundColor(bgBlue)
   writeLine(stdout, path)
```

Crashes when executed in a Windows Console with codepage 65001 (Unicode) set if there are file names containing non-ASCII characters. It does not crash however if e.g. codepage 1252 is set, or when echo() is used in favor of write().
The problem with echo() is that it always issues a NL which makes it unusable for formatted output.
So - from my point of view - one could either provide a non-NL echo() proc or make write(stdout, ...) behave like echo().

Addendum: Compiling terminal.nim by itself crashes with

> Traceback (most recent call last)
> terminal.nim(468)        terminal
> terminal.nim(245)        eraseLine
> system.nim(2312)         sysFatal
> Error: unhandled exception: over- or underflow [OverflowError]

**Comment by Araq** [comment] 2015-06-25 09:23
Ok, now I know. We check on windows' version of 'write' if we're in a TTY and if so don't check the return value?

**Comment by johnnovak** [comment] 2016-11-27 01:06
@Araq I tried to fix it that way, and while it prevented the crash, `write` produces incorrect output with Unicode strings, while `echo` works perfectly fine, as described in https://github.com/nim-lang/Nim/issues/2348. Any ideas on how to make `write` work like `echo`? I understand `echo` is a built-in and I just couldn't find where it's defined in the codebase...

**Comment by yuutayamada** [comment] 2017-10-07 16:12
> I understand echo is a built-in and I just couldn't find where it's defined in the codebase...

@johnnovak I think the echo's implementation is genEcho in compiler/ccgexprs.nim. (I'm not bright to nim compiler, but it looks the file is implementation of magic pragmas for me) hope this help.

**Comment by FedericoCeratto** [comment] 2019-01-18 23:47
@injekt666 is seeing an error that looks similar. It happens on Windows, not on Linux, and only when mixing colors and unicode. The output gets garbled after the unicode symbol.

```
import terminal
styledWriteLine(stderr, fgRed, "Error: ┌ ", resetStyle, "hello")
```

**Comment by injekt666** [comment] 2019-01-18 23:49
can confirm, this returns https://i.imgur.com/rZ4zTWW.png

**Comment by Araq** [comment] 2019-08-17 10:15
Duplicate of #11618.

**Closed by Araq** 2019-08-17 10:15 UTC
Labels: Low Priority, OS/Arch specific, Stdlib, Unicode
