### ISSUE TITLE
[arc] `var a: seq[int]; a.reverse` has undefined behavior (kinda benign without -fsanitize=undefined)

### ISSUE THREAD

**Issue by MaskRay** [nim-lang/Nim#19066] opened 2021-10-28 08:26 UTC
### Example
```nim
import algorithm
var a: seq[int]
a.reverse
```

### Current Output

When compiled with arc/orc,
```
% nim c --gc:arc -t:-fsanitize=undefined -l:-fsanitize=undefined a.nim
% ./a
/home/maskray/.cache/nim/a_d/@ma.nim.c:196:21: runtime error: member access within null pointer of type 'struct tySequence__qwqHTkRvwhrRyENtudHQ7g_Content'
```

The culprit line is `reverse_a_3(a_a_2.p->data, a_a_2.len);` where `a_a_2` is `{len = 0, p = 0x0}`. Dereferencing `data` (compiler converts this to add an offset 8 to the `a_a_2.p`) is a UB:

```c
struct tySequence__qwqHTkRvwhrRyENtudHQ7g_Content { NI cap; NI data[SEQ_DECL_SIZE];};
```

### Expected Output
No output.

### Additional Information

```
% nim --version
Nim Compiler Version 1.7.1 [Linux: amd64]
Compiled at 2021-10-20
Copyright (c) 2006-2021 by Andreas Rumpf

git hash: c239db4817586f769327a6d27c244682111f903a
active boot switches: -d:release
```

**Comment by metagn** [comment] 2021-10-28 10:47
Same issue as #9887?

**Comment by MaskRay** [comment] 2021-10-28 16:44
Seems so.

**Comment by Araq** [comment] 2021-10-29 10:37
Duplicate of #9887, closing.

**Closed as completed by Araq** 2021-10-29 10:37 UTC
Labels: ARC/ORC Memory Management
