### ISSUE TITLE
echo type(1..2).name => int ; shouldn't it be HSlice[system.int, system.int] ?

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/Nim#8309] opened 2018-07-13 19:42 UTC
is this a bug?
```nim
import typetraits
echo type(1..2).name
int # shouldn't that be HSlice[system.int, system.int] ?

let a=1..2;
echo type(a).name
HSlice[system.int, system.int]
```

**Comment by kaushalmodi** [comment] 2018-07-13 20:32
Interesting.. and this works:

```nim
import typetraits
echo (1 .. 2).type.name # HSlice[system.int, system.int]
```

**Comment by Araq** [comment] 2018-07-13 23:40
This is not a bug. ``type`` prefers the iterator interpretation and the ``..`` iterator yields ``int`` for your case. @kaushalmodi 's example is indeed weird though. :-)

**Comment by timotheecour** [comment] 2018-07-14 00:41
the following would seem like saner behavior:
```nim
# for all expression a (including iterators, 1..2 etc)
assert type(a) is a.type
let b = a
assert type(a) is type(b)
```
if for some reason that's not possible, at least having a `type2` that satisfies these

**Comment by dom96** [comment] 2018-07-14 12:12
> This is not a bug. type prefers the iterator interpretation and the .. iterator yields int for your case.

Shouldn't it output ``iterator `..`(slice: HSlice[int, int]): int`` then?

**Comment by Araq** [comment] 2018-07-14 14:09
> if for some reason that's not possible, at least having a type2 that satisfies these

``type`` should get an optional parameter that describes the desired context. And "iterator context" should not be the default...

> Shouldn't it output iterator `..`(slice: HSlice[int, int]): int then? (or whatever the iterator definition is?)

But the iterator is "called" and that then produces an ``int``.

**Comment by Araq** [comment] 2018-07-17 14:12
echo (1..2).type.name

vs.

echo type(1..2).name

is actually a feature. But probably we need a better solution here.

**Comment by Araq** [comment] 2019-05-25 22:54
Now that #9498 is fixed we have a better solution for this problem. Closing.

**Closed by Araq** 2019-05-25 22:54 UTC
Labels: typetraits
