### ISSUE TITLE
internal error: expr(nkVarTuple); unknown node kind

### ISSUE THREAD

**Issue by HJarausch** [nim-lang/Nim#16292] opened 2020-12-08 16:59 UTC
```nim
type
  ACTION = enum
    Exit = -1
    First= 1
    Second= 2

  ACTIONS = seq[ACTION]
  PATH = seq[(ACTION,string)]

iterator Show_Loop(P:var PATH) : (ACTION,string) {.closure.} =
  block :
    let pc = P.pop()
    if pc[0] == Exit :
        break
    yield (pc[0],pc[1])
    
var Paths : PATH = @[(First,"Go on"),(Exit,"Last one"),(Second,"still Go on")]

for (A,Msg) in Show_Loop(Paths) :   ### HERE internal error
  echo(A,"   ",Msg)
```
This is with

```
$ nim -v
Nim Compiler Version 1.5.1 [Linux: amd64]
Compiled at 2020-12-08
Copyright (c) 2006-2020 by Andreas Rumpf

git hash: 4c533b2d92162980dc8fac2332b0eb0739dbda25
active boot switches: -d:release
```

**Comment by HJarausch** [comment] 2020-12-08 19:21
The problem is caused by the *closure* attribute.
Here are somewhat reduced example
```nim
type
  ACTION = enum
    Exit = -1
    First= 1
    Second= 2

  ACTIONS = seq[ACTION]
  PATH = seq[(ACTION,string)]

# iterator Show_Loop(P:PATH) : (ACTION,string)  =   # This works just fine
iterator Show_Loop(P:PATH) : (ACTION,string) {.closure.} =
  block :
    var pc : (ACTION,string)
    for i in 0..2 :
      if P[i][0] == Exit :
        break
      yield (P[i][0],P[i][1])
    
var Paths : PATH = @[(First,"Go on"),(Exit,"Last one"),(Second,"still Go on")]

for (A,Msg) in Show_Loop(Paths) :
  echo(A,"   ",Msg)
```

**Comment by ringabout** [comment] 2021-08-28 09:44
Duplicate of https://github.com/nim-lang/Nim/issues/15924

**Closed as completed by ringabout** 2021-08-28 09:44 UTC
Labels: Compiler Crash, Iterators
