### ISSUE TITLE
nimpretty messes alignment, after import statement

### ISSUE THREAD

**Issue by kobi2187** [nim-lang/Nim#9811] opened 2018-11-27 14:26 UTC
example:
```
import future,
       strutils

proc issue() =
       echo "formatting issue"
```

nimpretty remembers the indentation from the import block, and uses it later on.

**Comment by nc-x** [comment] 2019-04-04 13:14
Reopen? AFAICT, this didn't get fixed by https://github.com/nim-lang/Nim/issues/9811, it was only a documentation change.

**Comment by Araq** [comment] 2019-06-07 11:05
By design nimpretty detects the indentation by the first "section of spaces" that it encounters. Use ``--indent:2`` switch to prevent it from doing that.

**Closed by Araq** 2019-06-07 11:05 UTC
Labels: nimpretty
