### ISSUE TITLE
Unsigned literal types not inferred correctly in comparison operations

### ISSUE THREAD

**Issue by johnnovak** [nim-lang/Nim#5042] opened 2016-11-22 01:23 UTC
The type of the literal `5` could be easily inferred by the compiler to be `uint8` in the below example. Instead, it fails with a compiler error:

```
var a: uint8 = 42

if a > 5:
  echo "boom"
```

```
nibbletest.nim(3, 6) template/generic instantiation from here
lib/system.nim(355, 5) Error: type mismatch: got (int literal(5), uint8)
but expected one of:
proc `<`[Enum: enum](x, y: Enum): bool
proc `<`(x, y: string): bool
proc `<`(x, y: char): bool
proc `<`[T](x, y: set[T]): bool
proc `<`(x, y: bool): bool
proc `<`[T](x, y: ref T): bool
proc `<`[T](x, y: ptr T): bool
proc `<`(x, y: pointer): bool
proc `<`(x, y: int8): bool
proc `<`(x, y: float): bool
proc `<`(x, y: int32): bool
proc `<`[T: SomeUnsignedInt](x, y: T): bool
proc `<`(x, y: int64): bool
proc `<`(x, y: int): bool
proc `<`(x, y: int16): bool
proc `<`[T: tuple](x, y: T): bool
proc `<`(x, y: float32): bool
proc `<`[T](x: Ordinal[T]): T
```

Interestingly, equality checking works as expected:

```
var a: uint8 = 42

if a == 5:
  echo "boom"
```

Signed types seem to work OK too:

```
var a: int8 = 42

if a > 5:
  echo "boom"
```

**Comment by narimiran** [comment] 2019-02-19 13:18
Duplicate of #2586.

**Closed by narimiran** 2019-02-19 13:18 UTC
Labels: unsigned
