### ISSUE TITLE
Bugged Case objects inside const array

### ISSUE THREAD

**Issue by Wh1teDuke** [nim-lang/Nim#9021] opened 2018-09-20 11:00 UTC
Test
```nim
type
  FooKind = enum FK1 FK2 FK3

  Foo     = object
    case  kind: FooKind
    of FK1:
      a:  int
    of FK2:
      b:  float
    of FK3:
      c:  bool
      

const FOO_LIST = [
  Foo(kind: FK1, a: 5),
  Foo(kind: FK2, b: 5.0),
  Foo(kind: FK3, c: true),
]

echo FOO_LIST
# [(kind: FK1, a: 5), (kind: FK2, b: 0.0), (kind: FK3, c: false)]
```
I guess an array of case objects is illegal to begin with.
***
```nim
>nim -v
Nim Compiler Version 0.18.1 [Linux: i386]
Compiled at 2018-09-15
Copyright (c) 2006-2018 by Andreas Rumpf

git hash: 4342b79a3c05fcfb1e6fc97152daa0075b0b9603
active boot switches: -d:release
```

**Comment by andreaferretti** [comment] 2018-09-20 11:28
It looks like the problem here is the `const`ness of `FOO_LIST`. If you declare it with `let FOO_LIST = `, then everything works fine

**Comment by LemonBoy** [comment] 2018-09-20 12:46
Duplicate of #8007/#8015, as suggested drop the `const` for a temporary workaround.

**Closed by LemonBoy** 2018-09-20 12:46 UTC
