### ISSUE TITLE
nim check on multiple files combine results

### ISSUE THREAD

**Issue by bung87** [nim-lang/Nim#18446] opened 2021-07-07 12:12 UTC
### Summary

current, nim check do single file check, for multiple files I need check it one by one, I want multiple check on git staged file , nim check do aware the lib entry file so it may only check once, or re-use compiled graphs
### Alternatives

or maybe just multiple threads check parallel

### Additional Information

nim: 1.5.1 Compiled at 2021-07-02

**Comment by timotheecour** [comment] 2021-07-08 18:07
nim check works as designed here and reports errors across module imports
```nim
# t12567.nim:
import t12567b
proc fn2*(): int = 1.3

# t12567b.nim:
proc fn1*(): int = 1.2
```

A tool that would loop through several files and call nim check on them is out of scope, because of separation of concerns (there'd be nothing to benefit from by integrating this in compiler, unlike other tools which require compiler support)

```
nim check $timn_D/tests/nim/all/t12567.nim
/Users/timothee/git_clone/nim/timn/tests/nim/all/t12567.nim(5, 1) template/generic instantiation from here
/Users/timothee/git_clone/nim/timn/tests/nim/all/t12567b.nim(1, 20) Error: type mismatch:
 got 'float64' for '1.2' [float declared in /Users/timothee/git_clone/nim/Nim_devel/lib/system.nim(28, 3)]
 but expected 'int' [int declared in /Users/timothee/git_clone/nim/Nim_devel/lib/system/basic_types.nim(2, 3)]
  proc fn1*(): int = 1.2
                     ^
/Users/timothee/git_clone/nim/Nim_devel/compiler/types.nim(1603, 15) compiler msg initiated here [MsgOrigin]
/Users/timothee/git_clone/nim/timn/tests/nim/all/t12567.nim(6, 20) Error: type mismatch:
 got 'float64' for '1.3' [float declared in /Users/timothee/git_clone/nim/Nim_devel/lib/system.nim(28, 3)]
 but expected 'int' [int declared in /Users/timothee/git_clone/nim/Nim_devel/lib/system/basic_types.nim(2, 3)]
  proc fn2*(): int = 1.3
                     ^
/Users/timothee/git_clone/nim/Nim_devel/compiler/types.nim(1603, 15) compiler msg initiated here [MsgOrigin]
/Users/timothee/git_clone/nim/timn/tests/nim/all/t12567.nim(5, 8) Warning: imported and not used: 't12567b' [UnusedImport]
  import t12567b

```

**Comment by Varriount** [comment] 2021-07-09 00:29
To add: It is generally best to call `nim check` on the "main" file in your project, otherwise the compiler may not be able to resolve imports correctly.

**Closed as completed by Varriount** 2021-07-09 00:29 UTC
Labels: Feature, Won't Fix, Nim Check
