### ISSUE TITLE
String range in case accepted but broken

### ISSUE THREAD

**Issue by metagn** [nim-lang/Nim#20128] opened 2022-08-01 12:34 UTC
Low priority

### Example
```nim
case "abc"
of "aba".."abz": echo "works"
```

### Current Output
```
```

### Expected Output
```
works
```
OR error

### Possible Solution

* error on non-ordinal types in [semBranchRange](https://github.com/nim-lang/Nim/blob/77891cedaeeb9283793c34b231d8d8c4f19002de/compiler/semtypes.nim#L531) 

```
$ nim -v
Nim Compiler Version 1.7.1
```

**Comment by ringabout** [comment] 2022-08-01 17:50
String range also breaks for for loop.

```nim
for i in "aba".."abz":
  echo i
```

```nim
system\iterators_1.nim(98, 10) Error: type mismatch: got <string>   
but expected one of:
proc inc[T: Ordinal](x: var T; y = 1)
  first type mismatch at position: 1
  required type for x: var T: Ordinal
  but expression 'res' is of type: string
```

**Comment by ghost** [comment] 2022-08-01 18:14
Duplicate of https://github.com/nim-lang/Nim/issues/19678

**Closed as completed** 2022-08-01 18:24 UTC
