### ISSUE TITLE
Hashes: Adding Macros to Make an User Defined object Hashable

### ISSUE THREAD

**Issue by loloiccl** [nim-lang/Nim#7731] opened 2018-04-29 17:52 UTC
I want macro used as pragma who makes `proc hash(x: UserDefinedObject): Hash`.

example:
(`hashable` is the name of the macro)

```example1.nim
import hashes

type
  MyObject {.hashable.} = object
    foo: int
    bar: string
```
is converted to
```converted1.nim
import hashes

type
  MyObject = object
    foo: int
    bar: string

proc hash(x: MyObject): Hash =
  ## Computes a Hash from `x`.
  var h: Hash = 0
  h = h !& hash(x.foo)
  h = h !& hash(x.bar)
  result = !$h
```

another example:

```example2.nim
import hashes

type
  MyKind = enum
    A, B
  MyObject {.hashable.} = object
    case kind: MyKind
    of A:
      foo: int
    of B:
      bar: string
```
is converted to
```converted2.nim
import hashes

type
  MyKind = enum
    A, B
  MyObject = object
    case kind: MyKind
    of A:
      foo: int
    of B:
      bar: string

proc hash(x: MyObject): Hash =
  ## Computes a Hash from `x`.
  var h: Hash = 0
  h = h !& hash(x.kind)
  case x.kind
  of A:
    h = h !& hash(x.foo)
  of B:
    h = h !& hash(x.bar)
  result = !$h
```

**Comment by data-man** [comment] 2018-04-29 18:03
And...?

**Comment by loloiccl** [comment] 2018-04-29 18:10
I hope a new feature like the examples' hashable macro will be implemented.
Sorry for my poor English ;(

**Comment by yglukhov** [comment] 2018-04-29 18:12
Somewhat duplicate of #6696

**Comment by mratsim** [comment] 2018-04-29 19:56
Why is it `won't fix` @data-man ? I could see that in sugar.nim

**Comment by data-man** [comment] 2018-04-29 20:04
@mratsim 
Sorry for my poor English!

**Comment by dom96** [comment] 2018-04-29 20:54
I don't think this is possible. Your ``hashable`` macro generates code that is outside the scope of the ``type`` block. You can already do something like this, which I think makes more sense:

```nim
import hashes

hashable:
  type
    MyObject = object
      foo: int
      bar: string
```

**Comment by Bulat-Ziganshin** [comment] 2018-07-15 19:07
@dom96 and on the next day you will need to generate hashable+comparable :)

Until the language itself solved the problem, it may be better to provide meta-macro:

```Nim
derive hashable, comparable, serializable("BE"):
  type
    MyObject = object
      foo: int
      bar: string
```
where each submacro only generates extra procedures and `derive` collects their results + type itself.

**Comment by Araq** [comment] 2018-07-17 09:54
@Bulat-Ziganshin ``sugar.derive`` seems entirely possible with today's Nim. No new feature required.

**Comment by Araq** [comment] 2020-02-07 10:06
Useful feature, but not scheduled for 2020 and the existing workarounds are perfectly acceptable.

**Closed by Araq** 2020-02-07 10:06 UTC
Labels: Feature, Low Priority, Macros, Pragmas
