### ISSUE TITLE
template treated as template(): untyped when using in template without bracket

### ISSUE THREAD

**Issue by slangmgh** [nim-lang/Nim#14330] opened 2020-05-13 01:09 UTC
### Example
```nim
type Buffer = object
   lines: seq[string]

var buffer: Buffer

proc p1(ss: seq[string]) = discard
template code_lines: untyped = buffer.lines
template p2() = p1(code_lines)    # change `template` to `proc` make the compiler success

p2()

```

### Current Output
```
D:\Tool\Nim\tmp\a12.nim(10, 3) Error: type mismatch: got <template (): untyped>
but expected one of:
proc p1(ss: seq[string])
  first type mismatch at position: 1
  required type for ss: seq[string]
  but expression 'code_lines' is of type: template (): untyped

expression: p1(code_lines)
```

### Expected Output
```
compile success.
```

### Possible Solution

change the second template to proc

### Additional Information

```
$ nim -v
Nim Compiler Version 1.3.3 [Windows: i386]
Compiled at 2020-05-13
Copyright (c) 2006-2020 by Andreas Rumpf

active boot switches: -d:release
```

**Comment by kaushalmodi** [comment] 2020-05-13 06:06
I think that the behavior to see is expected. You are trying to expand the code_lines template, right? If so, I think that it should have the parens. 

Your code modified: https://play.nim-lang.org/#ix=2lRb

**Comment by slangmgh** [comment] 2020-05-13 07:45
But the following code is ok. I think people will be confused why the ``proc`` cannot change to ``template``.

```nim
proc p2()  = p1(code_lines)
```

**Comment by slangmgh** [comment] 2020-05-13 15:42
This is the same bug with #14332, add {.dirty.} to the template can fix the problem too.

**Comment by metagn** [comment] 2020-05-13 21:46
Duplicate of #13515

**Comment by timotheecour** [comment] 2020-05-14 02:17
closing as duplicate

**Closed as completed by timotheecour** 2020-05-14 02:17 UTC
