### ISSUE TITLE
segfault with toSeq(countdown(..)) and gc:arc and d:useMalloc

### ISSUE THREAD

**Issue by ghost** [nim-lang/Nim#14984] opened 2020-07-14 21:37 UTC
### Example
`nim c -d:release -d:useMalloc --gc:arc file.nim`
```nim
import algorithm
import sequtils

proc main() =

    var s = toSeq(countdown(65535u16, 0u16))
    for _ in 1..10:
        s.add(s)
    sort(s)
    echo s.isSorted

main()
```

### Current Output
```
SIGSEGV: Illegal storage access. (Attempt to read from nil?)
```

### Expected Output
```
true
```

### Possible Solution

* not using gc:arc and d:useMalloc together
* using **`toSeq(65535u16..0u16)`** instead of `toSeq(countdown(65535u16, 0u16))`

### Additional Information
```
Nim Compiler Version 1.3.5 [Windows: amd64]
Compiled at 2020-07-13
Copyright (c) 2006-2020 by Andreas Rumpf

active boot switches: -d:release
```

related https://github.com/nim-lang/Nim/issues/14983

**Comment by Araq** [comment] 2020-07-15 07:50
Well ``    s.add(s)`` is bad code fwiw. :-)

**Comment by Clyybber** [comment] 2020-07-15 09:25
Duplicate of #14983, just that its crashing here due to the corruption.

**Closed as completed by Clyybber** 2020-07-15 09:25 UTC

**Comment by tim-st** [comment] 2020-09-04 18:51
@Clyybber 
It turns out that this was not a duplicate. With the latest nim version the code above works. The issue marked as duplicate still doesn't work.

**Comment by ghost** [comment] 2020-09-04 18:55
After testing it again, it seems the compiler sometimes compiles binaries that just work for all runs and other binaries that crash for all runs.
