### ISSUE TITLE
[bug or not] object construction for seq[T] failed without space after colon

### ISSUE THREAD

**Issue by oskca** [nim-lang/Nim#5999] opened 2017-06-18 13:15 UTC
`bug.nim` code:
```
type
    AO = ref object of RootObj
        str: cstring
        i: int
        list: seq[int]

var o = AO(str:"asdf", i:10, list:@[1,2,3])
# var o = AO(str:"asdf", i:10, list: @[1,2,3]) ## this line works with the space

echo o.list
```

nim c output:
```
cfg' [Conf]
Hint: system [Processing]
Hint: bug [Processing]
Error: internal error: (filename: semobjconstr.nim, line: 47)
No stack traceback available
To create a stacktrace, rerun compilation with ./koch temp c <file>
```

Nim version: 
```
Nim Compiler Version 0.17.0 (2017-05-23) [Linux: amd64]
Copyright (c) 2006-2017 by Andreas Rumpf
```

I now can avoid this error by simply add a space between the colon `:` and `@`, but is this a compiler bug or something else?

**Comment by TiberiumN** [comment] 2017-06-18 14:41
This is not a bug, because ":@" can be a custom operator.
You must use spaces there

**Comment by oskca** [comment] 2017-06-18 15:21
thank you for your note @TiberiumN 

but I think the compiler should give some more information on the spot, not just 
```Error: internal error: (filename: semobjconstr.nim, line: 47)``` 
which makes  this mistake really hard to find, especially for new users who may not known the language well

**Comment by TiberiumN** [comment] 2017-06-18 15:22
@oskca but I may be wrong :)

**Comment by TiberiumN** [comment] 2017-08-14 16:19
This was fixed by my PR - https://github.com/nim-lang/Nim/pull/6237
@dom96 close?
I know that current error message isn't the best, but this issue is mostly about a compiler crash

**Comment by dom96** [comment] 2017-08-14 17:34
What's the error message now?

**Comment by TiberiumN** [comment] 2017-08-14 17:45
@dom96 b.nim(7, 11) Error: incorrect object construction syntax
probably we need to keep this open until we somehow add proper error messages

**Closed** 2017-12-14 20:39 UTC
Labels: Crash, Easy, Error messages, High Priority
