### ISSUE TITLE
[ARC] segmentation fault with `now().utc`

### ISSUE THREAD

**Issue by ee7** [nim-lang/Nim#14968] opened 2020-07-12 12:20 UTC
`now().utc` produces SIGSEGV with `--gc:arc`. This issue was reported in the forum: https://forum.nim-lang.org/t/6536

### Example
```nim
import times
echo now().utc
```

### Current Output
`$ nim c -f --gc:arc -r /tmp/foo.nim`
```
2020-07-12T12:20:00Z
Traceback (most recent call last)
/usr/lib/nim/pure/times.nim(1090) foo
/usr/lib/nim/system/refs_v2.nim(162) nimRawDispose
/usr/lib/nim/system/alloc.nim(972) dealloc
/usr/lib/nim/system/alloc.nim(871) rawDealloc
/usr/lib/nim/system/avltree.nim(74) del
SIGSEGV: Illegal storage access. (Attempt to read from nil?)
Error: execution of an external program failed: '/tmp/foo '
```

### Expected Output
```
2020-07-12T12:20:00Z
```

### Possible Solution
Seems to be resolved by https://github.com/nim-lang/Nim/pull/14964 - I found that https://github.com/nim-lang/Nim/pull/14964/commits/8bdcbde07014432e42162ef2b21eee7f186f751d produces the expected output.

### Additional Information
Present on latest devel https://github.com/nim-lang/Nim/commit/9ec9a31f46697a615630fce3614e68e57d390a74.
Works on 1.2.4.

**Comment by planetis-m** [comment] 2020-07-12 18:46
~duplicate of~ #14961. At least the workaround is the same, append ``result =`` at the end of [inZone](https://github.com/nim-lang/Nim/blob/devel/lib/pure/times.nim#L1182) proc.

**Comment by ghost** [comment] 2020-07-12 19:58
@planetis-m I think it's still a duplicate because the root cause is the same? :thinking:

**Closed as completed** 2020-07-14 12:15 UTC
