### ISSUE TITLE
Error: undeclared field when iterating over return value

### ISSUE THREAD

**Issue by bryansquared** [nim-lang/Nim#4118] opened 2016-04-26 16:48 UTC
Given this program:

```
type
    Point = tuple
        x,y: int

proc Neighbors(pos:Point):seq[Point] =
    result = @[]
    for offset in @[(0,-1),(0,1),(-1,0),(1,0)]:
        var newPos = pos
        newPos.x = newPos.x + offset[0]
        newPos.y = newPos.y + offset[1]
        result.add(newPos)

for pos in (x:3,y:3).Neighbors():
    echo pos.x # error is here
```

An error "undeclared field 'x' ..." occurs

FWIW changing the code slightly removes the error:

```
type
    Point = tuple
        x,y: int

proc Neighbors(pos:Point):seq[Point]

for pos in (x:3,y:3).Neighbors():
    echo pos.x

proc Neighbors(pos:Point):seq[Point] =
    result = @[]
    for offset in @[(0,-1),(0,1),(-1,0),(1,0)]:
        var newPos = pos
        newPos.x = newPos.x + offset[0]
        newPos.y = newPos.y + offset[1]
        result.add(newPos)
```

**Comment by andreaferretti** [comment] 2017-06-26 12:19
What version of nim do you have? I cannot reproduce this error either on 0.17 or on devel

**Comment by TiberiumN** [comment] 2017-06-26 12:49
@andreaferretti maybe because he posted this issue one year ago ? :)

**Comment by andreaferretti** [comment] 2017-06-26 13:36
Sounds reasonable :-) I am closing the issue - reopen if it still happens for you

**Closed by andreaferretti** 2017-06-26 13:36 UTC
Labels: Not reproduced
