### ISSUE TITLE
htmlparser.nim snippet test breaks nightlies

### ISSUE THREAD

**Issue by genotrance** [nim-lang/Nim#10773] opened 2019-03-03 06:16 UTC
Following change enables testing of a snippet but that now fails in nightlies.

https://github.com/nim-lang/Nim/commit/5d67208e340e9db892539c342f462190871f6f69#diff-755980cbd8dad475b9a36fbe384216bfR33

Nightlies failure: https://travis-ci.org/nim-lang/nightlies/jobs/501003880#L8790

cc: @narimiran

**Comment by narimiran** [comment] 2019-03-03 06:51
Thanks for bringing it to my attention, will change it.

Btw, how come this passes both Travis and Appveyor here and fails in nightlies?

**Comment by narimiran** [comment] 2019-03-03 09:57
I cannot reproduce the fail locally.

**Comment by genotrance** [comment] 2019-03-03 16:00
This is the failing command.

`bin\nim.exe doc --hint[Conf]:off --hint[Path]:off --hint[Processing]:off -d:boot --putenv:nimversion=0.19.9  --doc.googleAnalytics:UA-48159761-1 --git.url:https://github.com/nim-lang/Nim -o:web\upload\0.19.9\htmlparser.html --index:on lib/pure/htmlparser.nim`

Note from Travis that it passes on 64-bit Linux and osx but fails on 32-bit Linux and windows, and 64-bit windows.

**Comment by narimiran** [comment] 2019-03-19 13:10
Fixed by #10862, as far as I can tell.

**Closed by narimiran** 2019-03-19 13:10 UTC
Labels: Showstopper
