### ISSUE TITLE
Maybe a bug in newruntime, lowest priority

### ISSUE THREAD

**Issue by StefanSalewski** [nim-lang/Nim#11356] opened 2019-05-30 08:29 UTC
This compiles and runs fine with

```
# nim c --newruntime n.nim
import tables, hashes
type
  O = ref object of RootRef
    i: int

var GNRR = initCountTable[RootRef]()

proc hash(r: RootRef): Hash =
  hash(cast[int](r))

proc nr_ref(r: RootRef) =
  GNRR.inc(r) 

proc nr_unref(r: RootRef) =
  GNRR.inc(r, -1) 

proc t: O =
  var o: O
  o = O(i: 0)
  #nr_ref(o)
  echo o.i
  #nr_unref(o)
  return o

proc main =
  var x = t()
  echo x.type

main()

```

From my current understanding it should not -- who owns and frees the object?

Will fail to compile nicely with this modification:

```nim
  #var o: O
  var o = O(i: 0)
```

**Comment by StefanSalewski** [comment] 2019-05-31 20:06
Sorry, I am even more confused: Verbatim example from

https://nim-lang.org/araq/ownedrefs.html

```nim
type
  Node = ref object
    data: int

var x = Node(data: 3) # inferred to be an ``owned ref``
let dangling: Node = x # unowned ref
assert dangling.data == 3
x = Node(data: 4) # destroys x! But x has dangling refs --> abort.

echo dangling.data
```

compiles and  runs fine. I that an old bug or new feature?

```
Nim Compiler Version 0.19.9 [Linux: amd64]
Compiled at 2019-05-30
Copyright (c) 2006-2019 by Andreas Rumpf

git hash: 1d00f7f9d73edb79cc581ca9b49fb038573c01d5
active boot switches: -d:release
```

**Comment by Araq** [comment] 2019-06-01 08:40
Duplicate of #11350

**Closed by Araq** 2019-06-01 08:40 UTC
