### ISSUE TITLE
Error when building with `tcc` as a backend: undefined symbol 'fabs'

### ISSUE THREAD

**Issue by rempas** [nim-lang/Nim#19192] opened 2021-11-25 10:47 UTC
I'm trying to use the tiny c compiler (tcc) as a backend but I'm getting the following error:

```
tcc: error: undefined symbol 'fabs'
Error: execution of an external program failed: 'tcc -o /tmp/test    -ldl    /home/rempas/.cache/nim/test_d/stdlib_digitsutils.nim.c.o /home/rempas/.cache/nim/test_d/stdlib_assertions.nim.c.o /home/rempas/.cache/nim/test_d/stdlib_dollars.nim.c.o /home/rempas/.cache/nim/test_d/stdlib_io.nim.c.o /home/rempas/.cache/nim/test_d/stdlib_system.nim.c.o /home/rempas/.cache/nim/test_d/@mtest.nim.c.o'
```

I'm compiling using the following command: `nim -d:tinyc --CC:tcc compile test.nim` where "test.nim" is the name of my file.

### Possible Solution
Either replace the symbol with something portable or check what compiler is used as a backend and generate it if needed (I don't know if compilers other then TCC have the same problem)

### Additional Information
I downloaded the latest version of nim for Linux using the "choosenim" tool. 

Output of "nim -v":

```
Nim Compiler Version 1.6.0 [Linux: amd64]
Compiled at 2021-10-19
Copyright (c) 2006-2021 by Andreas Rumpf

git hash: 727c6378d2464090564dbcd9bc8b9ac648467e38
active boot switches: -d:release
```

Output of "choosenim -v":
`choosenim v0.8.2 (2021-10-05 20:21:40) [linux/amd64]`

**Comment by ajusa** [comment] 2021-11-28 05:20
Probably a duplicate of #19041. Can you try the solution listed in that issue?

**Comment by ringabout** [comment] 2022-01-23 14:45
Please try the solution from https://github.com/nim-lang/Nim/issues/19041

**Closed as completed** 2022-01-23 14:45 UTC
Labels: OS/Architecture Specific, Waiting on Author
