### ISSUE TITLE
[docgen] runnableExamples causes subsection to be rendered as a section

### ISSUE THREAD

**Issue by nitely** [nim-lang/Nim#15176] opened 2020-08-11 07:15 UTC
Maybe this is intended, or the right way is to use `.. code-block:: nim` with `:test:`. If that's the case close this.

### Example
```nim
##[
Section
*********

Subsection 1
###########

]##
runnableExamples:
  doAssert true
##[
Subsection 2
###########

]##
```

### Current Output

"Subsection 2" is rendered as `<h1>Subsection 2</h1>`

### Expected Output

"Subsection 2" is rendered as `<h2>Subsection 2</h2>`

### Additional Information

Using a code block works as expected:

```
.. code-block:: nim
    :test:
    doAssert true
```

```
$ nim -v
Nim Compiler Version 1.3.5 [Linux: amd64]
Compiled at 2020-08-03
Copyright (c) 2006-2020 by Andreas Rumpf
```

**Comment by timotheecour** [comment] 2020-12-02 06:27
reduced:
the root cause isn't `runnableExamples`, it's the fact that headings are wrong when doc comment is split in multiple parts:

case3 bugs, case3b works
```nim
when defined case3:
  ## Basic usage
  ## ===========
  ##
  ## Encoding data
  ## -------------
  ##
  ## Apart from strings you can also encode lists of integers or characters:

  ## Decoding data
  ## -------------
  ##

when defined case3b:
  ## Basic usage
  ## ===========
  ##
  ## Encoding data
  ## -------------
  ##
  ## Apart from strings you can also encode lists of integers or characters:
  ##
  ## Decoding data
  ## -------------
  ##
```

**Comment by timotheecour** [comment] 2021-06-20 09:04
@a-mr it turns out your PR https://github.com/nim-lang/Nim/pull/18256 also fixes this issue; do we need a test case for this before closing? (ideally using `toAst`) 

it's not clear to me whether https://github.com/nim-lang/Nim/pull/18256 actually did add a test for this (at least not ones based on toAst, only html)

**Comment by a-mr** [comment] 2021-06-20 19:36
@timotheecour ,
no tests were added in #18256 , so i need to add tests in a follow-up PR.

**Closed as completed** 2024-01-22 14:32 UTC
Labels: Documentation Generation, works_but_needs_test_case
