### ISSUE TITLE
Internal error when using int32/int64 as array length

### ISSUE THREAD

**Issue by konsumlamm** [nim-lang/Nim#17193] opened 2021-02-26 14:25 UTC
An `AssertionError` is thrown when trying to use `int64` or `uint64` as an array length parameter.

When using `int32` or `int64`, a linking error occurs.

### Example
```nim
var test: array[int64, float]
```

```nim
var test: array[int32, float]
```

### Current Output
```
....fatal.nim(53)            sysFatal
Error: unhandled exception: int128.nim(72, 11) `arg.sdata(2) == 0` out of range [AssertionDefect]
```

```
~/.cache/nim/testing_d/@mtesting.nim.c.o: In Funktion »main«:
@mtesting.nim.c:(.text+0xed): relocation truncated to fit: R_X86_64_PC32 against symbol `cmdLine' defined in COMMON section in ~/.cache/nim/testing_d/@mtesting.nim.c.o
@mtesting.nim.c:(.text+0xf6): relocation truncated to fit: R_X86_64_PC32 against symbol `cmdCount' defined in COMMON section in ~/.cache/nim/testing_d/@mtesting.nim.c.o
@mtesting.nim.c:(.text+0x101): relocation truncated to fit: R_X86_64_PC32 against symbol `gEnv' defined in COMMON section in ~/.cache/nim/testing_d/@mtesting.nim.c.o
collect2: error: ld returned 1 exit status
Error: execution of an external program failed: 'gcc   -o ~/Projects/Nim/testing/src/testing  ~/.cache/nim/testing_d/stdlib_system.nim.c.o ~/.cache/nim/testing_d/@mtesting.nim.c.o    -ldl'
```

### Expected Output
Not sure, either no output or a compiler error message.

### Additional Information
This does not seem to be a regression (I tested it with devel, 1.4.4, 1.2.10 and 1.0.10).
```
$ nim -v
Nim Compiler Version 1.5.1 [Linux: amd64]
Compiled at 2021-02-25
Copyright (c) 2006-2021 by Andreas Rumpf

git hash: b725e0ed4d6a799cda2074b629883eaae92a1706
```

**Comment by ghost** [comment] 2021-02-26 14:34
Duplicate of https://github.com/nim-lang/Nim/issues/17163, closing :)

**Closed as completed by ghost** 2021-02-26 14:34 UTC
