### ISSUE TITLE
wrong context shown for `Error: can raise an unlisted exception`

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/Nim#10325] opened 2019-01-16 02:25 UTC
```
git clone https://github.com/nitely/nim-regex
cd nim-regex
git checkout 31f3e283e5e992fe0f05c87fb4a885665b28525e # because I'm fixing it, so need to be before the fix to repro this bug
nimble develop
```

t0118.nim:
```nim
import pkg/regex
```
```
nim c -r $timn_D/bugs/all/t0118.nim
nim c --hint:conf:off --nimcache:/tmp/nim//nimcache/ -o:/tmp/nim//app -r /Users/timothee/git_clone//nim//timn//bugs/all/t0118.nim
/Users/timothee/git_clone/nim/timn/bugs/all/t0118.nim(5, 1) template/generic instantiation from here
/Users/timothee/git_clone/nim/nim-regex/src/regex.nim(2838, 45) template/generic instantiation from here
/Users/timothee/git_clone/nim/Nim/lib/pure/parseutils.nim(285, 54) Error: can raise an unlisted exception: ValueError
```

this is super confusing since `parseutils.nim(285, 54)` points to `parseInt` which does list `ValueError`
```
proc parseInt*(s: string, number: var int, start = 0): int {.
  rtl, extern: "npuParseInt", noSideEffect, raises: [ValueError].} =
```

## note: 
* nim's revision at latest devel is fbd6743ea1db89eef3dd89ceb7c0cdcb648c8055 (to get proper line numbers)

* the fix is to s/OverflowError/ValueError/ in regex.nim (see https://github.com/nitely/nim-regex/pull/34) but the error should point to `parseRepRange` declaration (which is the one that can raise an unlisted error, before fixing as below) so please don't close this issue after https://github.com/nitely/nim-regex/pull/34 is merged as root cause is still there

```nim
  try:
    discard parseInt(first, firstNum)
    discard parseInt(last, lastNum)
  except OverflowError:
    prettycheck(
      false,
      "Invalid repetition range. Max value is $#" %% $int16.high)
```

* the regression in regex probably happened because of ~~https://github.com/nim-lang/Nim/pull/10246~~ https://github.com/nim-lang/Nim/pull/10284, however the root cause for this bug is that context reporting is wrong.
* Also, that regression is yet 1 more example why we need nimble-wide CI, cf https://github.com/nim-lang/Nim/pull/10247

## potential solution

it could simply be as simple as addressing this comment (untested): https://github.com/nim-lang/Nim/pull/10284/files/aab97182d52f71b98499f143c105b9b282243e3e#r247322180

> Please turn this into a proc that does the raise and mark the proc with .noinline, produces better code.

**Comment by GULPF** [comment] 2019-01-16 07:44
This looks like a duplicate of #8482

**Comment by GULPF** [comment] 2019-01-24 07:06
Closing as duplicate of #8482

**Closed by GULPF** 2019-01-24 07:06 UTC
Labels: Error messages, Exceptions
