### ISSUE TITLE
Extend documentation on object variants

### ISSUE THREAD

**Issue by GooRoo** [nim-lang/Nim#6678] opened 2017-11-02 19:31 UTC
Follow-up of #6674 

A user of the language should know about possible limitations of object variants, including necessity of definition of own `==` operator, before she/he decides that it's a good idea to use it.

Language [manual](https://nim-lang.org/docs/manual.html#types-object-variants) has to be extended accordingly (till #6676 and #6677 are resolved)

**Comment by Araq** [comment] 2017-11-02 21:18
The manual does not need to document the standard library. Also duplicate of #6676

**Closed by Araq** 2017-11-02 21:18 UTC

**Comment by GooRoo** [comment] 2017-11-02 22:40
@Araq, I wasn't able to find any other place with proper documentation regarding the problem described above. Maybe you can give me a link?

If not, then should I create one more duplicate of the issue or you'll re-open this one? :)

Once again: IMO the limitation of the "default" `==` is artificial and incorrect. If I, let's say, create a concept *EqualityComparable* and then use it in my procedures as a constraint, object with `case` will satisfy the constraint, but the code won't work. 

This either has to be documented somewhere or fixed. Or, as I proposed, documented until fixed.
