### ISSUE TITLE
nim c => nim cpp => nim c causes `Undefined symbols` errors

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/Nim#8228] opened 2018-07-07 04:58 UTC
test1.nim
```nim
echo 1
```

nim c test1.nim
#ok
nim cpp test1.nim
#ok
nim c test1.nim
#error:

```
Undefined symbols for architecture x86_64:
  "std::set_terminate(void (*)())", referenced from:
      colonanonymous__wRTldVNfvmb9aFVVqjJYXRw() in stdlib_system.o
      systemInit000() in stdlib_system.o
  "vtable for __cxxabiv1::__class_type_info", referenced from:
      typeinfo for RootObj in stdlib_system.o
...
clang: error: linker command failed with exit code 1 (use -v to see invocation)
Error: execution of an external program failed: 'clang   -o /Users/timothee/temp/nim/d02/test1  /Users/timothee/temp/nim/d02/nimcache/test1.o /Users/timothee/temp/nim/d02/nimcache/stdlib_system.o    -ldl'
```

tree
```
.
├── nimcache
│   ├── stdlib_system.c
│   ├── stdlib_system.cpp
│   ├── stdlib_system.o
│   ├── test1.c
│   ├── test1.cpp
│   ├── test1.json
│   └── test1.o
└── test1.nim

```

**Comment by shaoxie1986** [comment] 2018-07-08 15:05
you need using -f for force rebuilding, cause the source file has not changed, the "test1.o" is compiled by cpp,  and the third time, test1.o will not be generated again by test1.c, so the error came.
Sorry, I am a Chinese. My English is poor. I hope you can understand it.

**Comment by timotheecour** [comment] 2018-07-08 21:00
no worries regarding your english.

however, I thought that was the whole point of the json file in `nimcache/test1.json` ; it should track how each file was generated to see if something needs to be rebuilt. sounds like a bug

**Comment by andreaferretti** [comment] 2018-07-09 07:56
Closing as duplicate of https://github.com/nim-lang/Nim/issues/5219

**Closed by andreaferretti** 2018-07-09 07:56 UTC
