### ISSUE TITLE
addr of backwards index into immutable container not allowed

### ISSUE THREAD

**Issue by SirOlaf** [nim-lang/Nim#21036] opened 2022-12-06 19:04 UTC
### Description

Getting the address of a location backwards indexed into a container like string defined using let does not work

```nim
let a = "a"
discard addr a[0] # fine
discard addr a[a.len() - 1] # fine
discard addr a[^1] # not fine?
```

### Nim Version

Hash `9ba07edb2ec7fcdd628cfa7155c4853160ebd5c3` (devel), also broken on other versions using unsafeAddr

### Current Output

```text
Error: expression has no address
```

### Expected Output

```text
Successful compile
```

**Comment by metagn** [comment] 2022-12-07 12:29
This would be possible if we changed the return type to `lent T` [here](https://github.com/nim-lang/Nim/blob/d6b485493d712a20155a3e77f44c19c34e47ea73/lib/system/indices.nim#L22), but I'm guessing this will break due to the array subscript magic.

Workaround is `addr (unsafeAddr a)[][^1]`

**Comment by ringabout** [comment] 2022-12-08 03:26
Duplicate of https://github.com/nim-lang/Nim/issues/8732

**Closed as completed by ringabout** 2022-12-08 03:26 UTC
