### ISSUE TITLE
Const variant object fields are incorrectly set to zero

### ISSUE THREAD

**Issue by exelotl** [nim-lang/Nim#15218] opened 2020-08-23 00:25 UTC
When a variant object is bound to a `const`, the latter fields are initalised to 0, which *overwrites* the former fields.

### Example

```nim
type
  Kind = enum
    A, B, C
  Rocket = object
    case kind: Kind
    of A: a: int
    of B: b: int
    of C: c: int

const a = Rocket(kind: A, a: 20)
const b = Rocket(kind: B, b: 30)
const c = Rocket(kind: C, c: 40)

echo a
echo b
echo c
```

### Current Output
```
(kind: A, a: 0)
(kind: B, b: 0)
(kind: C, c: 40)
```

### Expected Output
```
(kind: A, a: 20)
(kind: B, b: 30)
(kind: C, c: 40)
```

### Additional Information

This only seems to happen when using `const`  
i.e. the following are fine:

```nim
let a = Rocket(kind: A, a: 20)
echo a                        # (kind: A, a: 20)
echo Rocket(kind: B, b: 30)   # (kind: B, b: 30)
```

---

```
$ nim -v
Nim Compiler Version 1.2.6 [Linux: amd64]
```

**Comment by shirleyquirk** [comment] 2020-08-23 15:55
Duplicate of #13081, link #8007 #8015
See https://forum.nim-lang.org/t/6530 for workarounds

**Comment by ghost** [comment] 2020-08-23 16:10
Closing as a duplicate of #13081 :)

**Closed as completed by ghost** 2020-08-23 16:10 UTC
