### ISSUE TITLE
json module cannot be imported in nimscript

### ISSUE THREAD

**Issue by geekrelief** [nim-lang/Nim#19974] opened 2022-07-05 20:11 UTC
https://nim-lang.github.io/Nim/nims.html says the json should be available to nimscript.

With `--mm:orc` enabled.

### Example
test.nims:
```nim
import std / json
```

Run with: `nim e test.nims`

### Current Output
```
C:\Nim\lib\pure\json.nim(465, 24) template/generic instantiation of `==` from here
C:\Nim\lib\system\comparisons.nim(298, 18) template/generic instantiation of `seqToPtr` from here
C:\Nim\lib\system\comparisons.nim(294, 25) Error: undeclared identifier: 'NimSeqV2'
```

### Expected Output
No error. 

### Possible Solution
https://github.com/nim-lang/Nim/blob/7d0285853f4327a0a4f683e13971dc3429aad1f3/lib/system.nim#L1799-L1801
This prevents seqs_v2 from being included for nimscript.

### Additional Information
```
Nim Compiler Version 1.7.1 [Windows: amd64]
Compiled at 2022-07-04
Copyright (c) 2006-2022 by Andreas Rumpf

git hash: d2d8f1342b3125aac8e0592da25df61e6feb95b2
active boot switches: -d:release
```

**Comment by beef331** [comment] 2022-07-05 21:47
Your min reproduction does not error so I can only assume you're attempting to compile the nimvm with `orc` or `arc`.

**Comment by geekrelief** [comment] 2022-07-06 02:12
Yes, this is with orc.

**Comment by ringabout** [comment] 2023-02-21 13:18
```nim
--mm:orc
import std/json
```
fixed by https://github.com/nim-lang/Nim/pull/21379 since now it parses the whole module.

**Closed as completed** 2023-02-22 19:34 UTC
Labels: ARC/ORC Memory Management
