### ISSUE TITLE
JS closure compile time error cannot evaluate variable

### ISSUE THREAD

**Issue by nitely** [nim-lang/Nim#15151] opened 2020-08-03 08:32 UTC
This only occurs when compiling with the js target.

### Example
```nim
proc main() =
  var s = "foo"
  proc foo() =
    echo s
  foo()
static:
  main()
```

### Current Output
```
Error: cannot evaluate at compile time: s
```

### Expected Output
```
foo
```

### Additional Information
* I tried it in Nim 1.0.8, 1.2.6, and devel; same result.

```
$ nim -v
Nim Compiler Version 1.3.5 [Linux: amd64]
Compiled at 2020-08-03
Copyright (c) 2006-2020 by Andreas Rumpf
```

**Comment by arjunkathuria** [comment] 2020-09-13 07:51
Hi, im looking to get started with contributing to the nim compiler.
This looks like an approachable issue. if someone can guide me what to do here and where to do it. i'd be happy to take this up.

**Edit**: i ran the code above. it compiled _just fine_. it did emit `foo` while compiling, but nothing when i ran the foo binary `./foo`.

```
Nim Compiler Version 1.2.6 [Linux: amd64]
Compiled at 2020-07-29
Copyright (c) 2006-2020 by Andreas Rumpf

active boot switches: -d:release
```

**Comment by nitely** [comment] 2020-09-15 22:45
@arjunkathuria it only fails when using the JS backend. It works fine when using C. You should try asking on IRC if you want to work on this, btw.

**Comment by arjunkathuria** [comment] 2020-09-16 08:06
@nitley i looked into a bit and found that using the compileTime pragma makes it compile in the js mode

```nim
proc main() {.compileTime.} =
  var s = "foo"
  proc foo() =
    echo s
  foo()
static:
  main()
```

but it also removes it from the output code after running it at compile time. is that something that works for your use-case?

**Comment by nitely** [comment] 2020-09-16 08:14
I needed it at both compile time and run time. I ended up writing it the
iterative way.

ah yes, I forget the original code used a recursive function, and passing the string as parameter is another workaround.

**Comment by Araq** [comment] 2020-09-21 08:46
> Hi, im looking to get started with contributing to the nim compiler.
> This looks like an approachable issue. if someone can guide me what to do here and where to do it. i'd be happy to take this up.

Contact us on IRC please. As a starting guide, see why transf.nim and lambdalifting.nim have special logic for ``.backend == backendJs``

**Comment by arjunkathuria** [comment] 2020-09-21 16:26
Hi @Araq ,

i think this should be it.
from `lambdalifting.nim`

```nim
proc liftLambdas*(g: ModuleGraph; fn: PSym, body: PNode; tooEarly: var bool): PNode =
  # XXX backend == backendJs does not suffice! The compiletime stuff needs
  # the transformation even when compiling to JS ...

  # However we can do lifting for the stuff which is *only* compiletime.
  
  let isCompileTime = sfCompileTime in fn.flags or fn.kind == skMacro

  if body.kind == nkEmpty or (
      g.config.backend == backendJs and not isCompileTime) or
      fn.skipGenericOwner.kind != skModule:

    # ignore forward declaration:
    result = body
    tooEarly = true
```

that's why it works when i add the {.CompileTime.} pragma too.
it doesn't check that for c or other backends, thus they tend to work.

is that a correct observation?

**Comment by Araq** [comment] 2020-09-21 19:12
Yes, as you can see, the problem is tough. Most probably the best fix is to change ``vmgen`` to ensure lambda-lifting before it performs the VM codegen part.

**Comment by arjunkathuria** [comment] 2020-09-22 04:18
Hi @Araq .

i looked around and found that all the tranf stuff is probably happening before the gen part already.
https://github.com/nim-lang/Nim/blob/aca9c5fb30fe2de12671e9103e93b81201bb8e71/compiler/vmgen.nim#L2240-L2257

here's where `transformBody` is defined which calls `liftingLambdas`
https://github.com/nim-lang/Nim/blob/aca9c5fb30fe2de12671e9103e93b81201bb8e71/compiler/transf.nim#L1084-L1097

https://github.com/nim-lang/Nim/blob/aca9c5fb30fe2de12671e9103e93b81201bb8e71/compiler/lambdalifting.nim#L850-L881

BUT:-

from what i found is. the C compile is doing MUCH more transformations. about 4x to 5x times more than the js compile. i just need to figure out where are all these transforms happening from and why are they different. 

any pointers (no pun intended) for how to go about it. `echo` and `repr` debugging is taking a lot of time and i have to focus real hard to find differences ?

**Comment by Araq** [comment] 2020-09-22 05:32
Nah, there is much better way to understand the compiler. 

- Add code like ``echo "MYID ", n.id`` for a node you're curious about where it came from.
- Compile with ``koch temp -d:useNodeIds testprog.nim``. 
- Look for "MYID <x>" in the compiler's output. 
- Now edit ``compiler/ast.nim``
  - Change the line ``const nodeIdToDebug* = -1`` , change the -1 to the value that was echo'ed.
- Compile **again** with ``koch temp -d:useNodeIds testprog.nim``. 
- Look for a stack trace from within the compiler that reports where the node was constructed.

It's a poor man's time travelling debugger but it works much better than all other ways that I tried including commercial debuggers which actually can go back in time.

**Comment by ringabout** [comment] 2020-11-15 14:25
duplicated issue:
#12492

**Comment by Clyybber** [comment] 2020-11-15 14:47
Closing as dup of #12492

**Closed as completed by Clyybber** 2020-11-15 14:47 UTC
Labels: Javascript
