### ISSUE TITLE
untyped param: wrong error message (undeclared identifier) on type mismatch of another param

### ISSUE THREAD

**Issue by mratsim** [nim-lang/Nim#12019] opened 2019-08-23 20:09 UTC
A macro with a mix of untyped arguments and generic arguments will display "undeclared identifier" instead of type mismatch if the generic semcheck fails.

Test case

```Nim
import macros

macro forEach*(
        idx: untyped,
        s: Slice,
        funcCall: untyped{call}
      ): untyped =

  echo getTypeInst(s).treerepr


proc foo(i: int) =
  echo i

forEach(i, 0..2, foo(i))     # works
forEach(i, 0'u..2'u, foo(i)) # works
forEach(i, 0'u..2, foo(i))   # Error: undeclared identifier: 'i' // expected type mismatch
forEach(i, 0..2'u, foo(i))   # Error: undeclared identifier: 'i' // expected type mismatch
```

Seems linked to https://github.com/nim-lang/Nim/issues/8677

**Comment by timotheecour** [comment] 2019-08-24 04:02
@mratsim the issue is not with macros nor generics, it's with `untyped`; maybe change the title?
```nim
template fun1(x1: untyped, x2: int) = discard
fun1(nonexistant, 2)
fun1(nonexistant, 2.1)  # Error: undeclared identifier: 'nonexistant'
```
(from https://github.com/timotheecour/Nim/issues/23)

**Comment by timotheecour** [comment] 2020-11-13 17:21
~~closing as duplicate of https://github.com/nim-lang/Nim/issues/14827~~

closing as duplicate of https://github.com/nim-lang/Nim/issues/9620

**Closed by timotheecour** 2020-11-13 17:21 UTC
Labels: Error messages, Semcheck, Symbol Resolution, Templates
