### ISSUE TITLE
adding an overload causes a compilation failure

### ISSUE THREAD

**Issue by krux02** [nim-lang/Nim#11122] opened 2019-04-26 19:21 UTC
### Example
This works:
```nim
import macros

macro foobar(arg1: int; args: untyped): untyped =
  echo "foobar 2: ", args.lispRepr

foobar(1, [2,"123"])
```

This doesn't:

```nim
import macros

proc foobar(arg1: int; arg2: string): void =
  echo "foobar 1"

macro foobar(arg1: int; args: untyped): untyped =
  echo "foobar 2: ", args.lispRepr

foobar(1, [2,"123"]) # Error: type mismatch: got <string> but expected 'int literal(2)'
```

### Additional Information

This is currently causing problems during my refactoring of the ropes in the compiler.

```
$ nim -v
Nim Compiler Version 0.19.9 [Linux: amd64]
Compiled at 2019-04-26
Copyright (c) 2006-2019 by Andreas Rumpf

git hash: e48f420ab0161d6fc46c72a5a4f0142e77ed9796
active boot switches: -d:release
```

**Comment by yglukhov** [comment] 2019-04-26 23:16
Duplicate of #6643?

**Comment by mratsim** [comment] 2019-04-27 08:41
And also probably duplicate of this: https://github.com/nim-lang/Nim/issues/9414

**Comment by Araq** [comment] 2019-04-29 15:18
Just read the manual one day, ok?

**Closed by Araq** 2019-04-29 15:18 UTC
Labels: Macros, Semcheck
