### ISSUE TITLE
cannot use logical operators with nimvm

### ISSUE THREAD

**Issue by jangko** [nim-lang/Nim#12518] opened 2019-10-25 10:46 UTC
illogical nimvm

### Example
```nim
proc test() =
  when not nimvm:
     echo "NOT VM"
  else:
    echo "VM" 

static:
  test()

test()
```

### Current Output
```
NOT VM
NOT VM
```

### Expected Output
```
VM
NOT VM
```

```
$ nim -v
Nim Compiler Version 1.0.2 [Windows: amd64]
Compiled at 2019-10-24
Copyright (c) 2006-2019 by Andreas Rumpf

git hash: 193b3c66bbeffafaebff166d24b9866f1eaaac0e
active boot switches: -d:release
```

**Comment by krux02** [comment] 2019-10-25 14:59
I can't reproduce it. I get the following error: ``Error: illegal context for 'nimvm' magic``

**Comment by krux02** [comment] 2019-10-25 15:49
I am closing this issue as I think it is not an issue right now. I know it is annoying that you can't write ``when not nimvm`` and you have to write ``when nimvm: discard else: [...]``, but it is also documented that `when nimvm` is a special construct that is not really a when statement. 

Maybe it is better to have a special construct for this, for example a `nimvmBranch: [...] else: [...]` that  make people believe that `nimvm` is a constant that you can use in `when` expressions like other constants.

**Closed** 2019-10-25 16:12 UTC
