### ISSUE TITLE
Nim standard library not compatible with OpenSSL 3.0 on Ubuntu 

### ISSUE THREAD

**Issue by metagn** [nim-lang/Nim#19993] opened 2022-07-09 17:59 UTC
Came across this while upgrading a Nim Heroku app to the Heroku-22 stack (now likely the default) which [only ships with OpenSSL 3.0](https://devcenter.heroku.com/articles/heroku-22-stack#openssl-3). Googling it gave [this Reddit post](https://www.reddit.com/r/nim/comments/uwa1qv/installing_nim_using_choosenim_on_pop_os_fails/) and the [google groups post linked in it](https://groups.google.com/g/linux.debian.bugs.dist/c/VbEsniKRGQI?pli=1), however I could not find a report of it on Github.

### Example
From Google Groups post:
```
$ ./bin/nimble
```
Or any Nim program using SSL, not just Nimble.

### Current Output
```
could not import: SSL_get_peer_certificate 
```

### Possible Solution

* [Location of missing symbol import](https://github.com/nim-lang/Nim/blob/e8ee2f9c2ad06cad2f62fe7505acbb43530f28d7/lib/wrappers/openssl.nim#L807)
* List of obsolete symbols used by Nim according to Google Groups post:
```bash
$ for sym in $(sed -n -e'/proc.*dynlib:/ { s/^\s*proc\s\+//; s/\**(.*//; p }' lib/wrappers/openssl.nim); do objdump -T /usr/lib/x86_64-linux-gnu/libssl.so.3 /usr/lib/x86_64-linux-gnu/libcrypto.so.3 |grep -q $sym\$ || echo "missing symbol $sym"; done
missing symbol SSL_library_init
missing symbol SSL_load_error_strings
missing symbol SSLv23_method
missing symbol SSLeay
missing symbol SSL_state
missing symbol SSLv23_client_method
missing symbol SSLv2_method
missing symbol SSLv3_method
missing symbol SSL_CTX_get_ex_new_index
missing symbol bioNew
missing symbol bioFreeAll
missing symbol bioSMem
missing symbol bioCtrlPending
missing symbol ErrClearError
missing symbol ErrFreeStrings
missing symbol ErrRemoveState
missing symbol SSL_get_peer_certificate
```

```
$ nim -v
Nim Compiler Version 1.6.6
```

**Comment by dom96** [comment] 2022-07-09 19:40
duplicate of https://github.com/nim-lang/Nim/issues/19604

**Closed as completed by dom96** 2022-07-09 19:40 UTC
