### ISSUE TITLE
Generic casting doesn't work in VM

### ISSUE THREAD

**Issue by PMunch** [nim-lang/Nim#9423] opened 2018-10-18 10:39 UTC
Following the deficiencies I found with the `deques` module I tried to implement my own stack data structure (which is what I was using a `deque` for). It however also ran into trouble when run under a VM. It appears like the conversion back from a `Stack[T]` type to a `seq[T]` makes the VM copy the object while compiled Nim allows this like you would expect. I tried the same with a distinct string instead of a sequence but that didn't seem to trigger the issue so I'm guessing it has to do with the generics.

``` Nim
type Stack*[T] = distinct seq[T]

proc newStack*[T](): Stack[T] =
  Stack[T](newSeq[T]())

proc push*[T](stack: var Stack[T], elem: T) =
  seq[T](stack).add(elem)

proc pop*[T](stack: var Stack[T]): T =
  result = seq[T](stack)[seq[T](stack).high]
  seq[T](stack).setLen(seq[T](stack).high)

proc len*[T](stack: Stack[T]): int =
  seq[T](stack).len

when isMainModule:
  var stack = newStack[int]()

  stack.push(5)
  echo stack.len # Echos 1
  echo stack.pop() # Echos 5

  import macros

  macro something(): untyped =
    result = newStmtList()
    var stack = newStack[int]()

    stack.push(5)
    echo stack.len # Echos 0
    echo stack.pop() # Error: No elements

  something()
```

**Comment by timotheecour** [comment] 2020-12-08 03:38
```nim
when defined case3a:
  type Foo[T] = object
    x: int
  type Foo1 = Foo[int]
  type Foo2 = distinct Foo1
  template fn() =
    var a = Foo2(Foo1(x: 1))
    a.Foo1.x = 2
    echo a.Foo1
  fn()
  static: fn()
```

```nim
when defined case3:
  type Foo = seq[int]
  type Foo2 = distinct Foo
  template fn() =
    var a = Foo2(@[1])
    a.Foo.add 2
    echo a.Foo
  fn()
  static: fn()
```

case3a works
case3 bugs in VM, showing:
```
@[1]
@[1, 2]
```

=> it fails with seq and string and works with object including generic object
=> closing as duplicate of https://github.com/nim-lang/Nim/issues/12282

**Closed by timotheecour** 2020-12-08 03:38 UTC
Labels: VM
