### ISSUE TITLE
Cannot prove that result is initialized for a placeholder base method returning a lent

### ISSUE THREAD

**Issue by MCRusher** [nim-lang/Nim#22673] opened 2023-09-08 12:19 UTC
### Description

When declaring a lent method, where typically you would want to error and give debug information when you accidentally call the empty base method vs a child override of the method, you get a warning about result not being initialized, which is true, but on purpose since it should never be called in the first place.

The "baseless methods" warnings go away once the base type's method warning is fixed, so they don't seem to be a problem

You can change the `doAssert` to a `quit`, `raise`, etc. and the warning still persists

```nim
type RefEntry = ref object of RootObj

type RefFile = ref object of RefEntry
    filename*: string
    data*: string

type RefDir = ref object of RefEntry
    dirname*: string
    files*: seq[RefFile]

method name*(e: RefEntry): lent string {.base.} =
    doAssert false, "Don't call the base method"

method name*(e: RefFile): lent string = e.filename

method name*(e: RefDir): lent string = e.dirname
```

### Nim Version

Nim Compiler Version 2.1.1 [Linux: amd64]
Compiled at 2023-09-04
Copyright (c) 2006-2023 by Andreas Rumpf

git hash: c5495f40d5d881e6bd155c9e6c9c6e5e49b749a7
active boot switches: -d:release

### Current Output

```text
/home/USER/Projects/ahhh.nim(12, 5) Warning: Cannot prove that 'result' is initialized. This will become a compile time error in the future. [ProveInit]
/home/USER/Projects/ahhh.nim(14, 8) Warning: use {.base.} for base methods; baseless methods are deprecated [UseBase]
/home/USER/Projects/ahhh.nim(16, 8) Warning: use {.base.} for base methods; baseless methods are deprecated [UseBase]
```

### Expected Output

```text
No warnings/potential future errors
```

### Possible Solution

Right now, I could remove the lent and lose the potential optimization, or do `result = cast[ptr string](0)[]` to silence the warning in a very ugly and very unsanitary way that doesn't seem very much like good practice but it does seem to work perfectly and is probably what I'll end up doing.

---

Maybe it's possible to check if the method can actually return before warning/erroring in the future about result?

Or some built in way to declare an invalid base method that already knows your intentions of not implementing the method

### Additional Information

The same issue occurs on nim 2.0.0, and 1.6.0

**Comment by ringabout** [comment] 2023-09-08 12:25
Duplicate of https://github.com/nim-lang/Nim/issues/16735

**Comment by ringabout** [comment] 2023-09-18 06:32
Since https://github.com/nim-lang/Nim/pull/22717 has been merged, the remain issues are the 'baseless' warnings. Using a type alias seems to work.

```nim
type
  LentString = lent string
```

**Closed as completed** 2023-11-06 18:36 UTC
