### ISSUE TITLE
Pending recv/accept futures don't fail after closing a socket

### ISSUE THREAD

**Issue by edubart** [nim-lang/Nim#4405] opened 2016-06-24 02:09 UTC
The following example illustrates:

``` Nim
import asyncnet, asyncdispatch

var server = newAsyncSocket()
server.bindAddr(Port(12345))
server.listen()
var fut = newFuture[void]()

proc serve() {.async.} =
  try:
    discard await server.accept()
    echo "accepted"
    fut.complete()
  except:
    echo "got exception"
    fut.complete()

asyncCheck serve()
server.close()
fut.waitFor()
echo "ended"
```

**What happens:**
The stdout will show nothing and the program will run forever.

**What was expected:**
When the server is closed it should generate an error on all futures related to the socket thus generating an exception on async procs and printing "got exception", then the program must exits.

This seems to happen with recv() and recvFrom() procs too in UDP sockets, I suspect that happens with TCP sockets too, this is inconvenient, currently I cannot properly shutdown a server which have a pending recv/accept as the run loop is stuck forever.

**Comment by cheatfate** [comment] 2016-06-24 09:05
To be sure, could you please make same tests for functions you suspect (recv(), recvFrom())? Because currently we see only **accept()** function example, but **accept()** has different semantic.

**Comment by edubart** [comment] 2016-06-24 13:59
@cheatfate in the following, adapted from your tnewasync test, the same problem happens too, the program runs forever.

```Nim
import asyncdispatch, nativesockets, net, strutils, os

var fut = newFuture[void]()

proc prepareAddress(intaddr: uint32, intport: uint16): ptr Sockaddr_in =
  result = cast[ptr Sockaddr_in](alloc0(sizeof(Sockaddr_in)))
  when defined(windows):
    result.sin_family = toInt(nativesockets.AF_INET).int16
  else:
    result.sin_family = toInt(nativesockets.AF_INET)
  result.sin_port = htons(intport)
  result.sin_addr.s_addr = htonl(intaddr)

proc readMessages(server: AsyncFD) {.async.} =
  var buffer: array[16384, char]
  var slen = sizeof(Sockaddr_in).SockLen
  var saddr = Sockaddr_in()
  try:
    var size = await recvFromInto(server, cast[cstring](addr buffer[0]),
                                  16384, cast[ptr SockAddr](addr(saddr)),
                                  addr(slen))
    echo "received", size
    fut.complete()
  except:
    echo "got exception"
    fut.complete()

var name = prepareAddress(INADDR_ANY, 10333)
var server = newAsyncNativeSocket(nativesockets.AF_INET,
                                  nativesockets.SOCK_DGRAM,
                                  Protocol.IPPROTO_UDP)
discard bindAddr(server.SocketHandle, cast[ptr SockAddr](name), sizeof(Sockaddr_in).Socklen);
asyncCheck readMessages(server)
server.closeSocket()
echo "socket closed"
fut.waitFor()
echo "ended"
```

**Comment by dom96** [comment] 2016-06-24 14:05
I bet the cause of this error is that ``close`` unregisters the fd.

**Comment by dom96** [comment] 2016-06-24 14:05
Possible solution: in ``unregister`` check whether there are any pending Futures/callbacks and ``complete`` them with an exception.

**Comment by cheatfate** [comment] 2016-06-24 15:01
@dom96, Windows is not affected because of [this check](https://github.com/nim-lang/Nim/blob/devel/lib/pure/asyncdispatch.nim#L499-L501).

**Comment by cheatfate** [comment] 2016-06-24 15:06
> When the server is closed it should generate an error on all futures related to the socket thus generating an exception on async procs and printing "got exception", then the program must exits.
In any time there only 1 or 2 futures which related to socket. There no many futures... And 2 can be happen only during callback call, after callback is processed only 1 future will stay alive.

**Comment by cheatfate** [comment] 2016-06-24 15:09
@edubart your tests just made full cleanup of (epoll/kqueue) queue. Because selectors.nim don't count for number of registered sockets in selector, you got this never ended cycle.

**Comment by edubart** [comment] 2016-06-24 15:32
@cheatfate What is not affected on windows? Do you get both "got exception" and "ended" messages or just "ended"? 

If a socket is closed, the ideal behavior is to generate erros on any pending recv/send related to it.

I'm came up with a workaround in closeSocket() for linux:

```Nim
  proc closeSocket*(sock: AsyncFD) =
    let disp = getGlobalDispatcher()
    sock.SocketHandle.close()

    # The sock is now closed, this is a hack that calls all pending
    # read/write again so they will forcely fail with bad file descriptor error
    # before unregistering the FD.
    # TODO: this could be ideally changed to a better way when future canceling
    # is supported. We use a while loop deleting one at time for safety,
    # because this list could change while iterating.
    while disp.selector[sock.SocketHandle].data.PData.readCBs.len() != 0:
      var ret = disp.selector[sock.SocketHandle].data.PData.readCBs[0](sock)
      assert ret == true
      disp.selector[sock.SocketHandle].data.PData.readCBs.del(0)

    while disp.selector[sock.SocketHandle].data.PData.writeCBs.len() != 0:
      var ret = disp.selector[sock.SocketHandle].data.PData.writeCBs[0](sock)
      assert ret == true
      disp.selector[sock.SocketHandle].data.PData.writeCBs.del(0)

    disp.selector.unregister(sock.SocketHandle)
```

This is not the ideal solution but it's working for me until someone do a proper fix to all platforms.

**Comment by cheatfate** [comment] 2016-06-24 15:48
@edubart i think you not understand what i'm trying to say to you.
When you make `server.close()` in your first source and when you make `server.closeSocket()` in your second source, internal selector queue becomes empty, so poll() will poll for **zero** sockets and will block for default 500ms... 
For your synthetic tests asyncdispatch works as expected.

**Comment by cheatfate** [comment] 2016-06-24 15:52
But if you want to get your exception working try to close socket as SocketHandle, and your exception will be rised...

**Comment by edubart** [comment] 2016-06-24 15:56
@cheatfate Indeed, this exception seams like to happen on windows because of that check. But still not correct, what I'am saying is that the future should be just finished and poll() never called, because we have this in waitFor:

```Nim
proc waitFor*[T](fut: Future[T]): T =
  ## **Blocks** the current thread until the specified future completes.
  while not fut.finished:
    poll()

  fut.read
```

See that if fut.finished no poll would be called, so that exception of that check would never happen.

In both test cases poll() should not even happen, even if it does for some reason (maybe because of other sockets), it should not throw exception in the waitFor call or block the thread for ever, both windows and linux behavior seems wrong.

**Comment by cheatfate** [comment] 2016-06-24 16:34
Current version of **asyncdispatch.nim** don't support canceling futures, so for your synthetic tests behavior of **asyncdispatch.nim** is absolutely correct.

Your workaround code just a hack, which first of all will cause double call to complete cb(), and possibly more regression bugs.

**Comment by dom96** [comment] 2017-05-17 14:14
I'm probably missing something but the examples in this issue now fail with ``Error: unhandled exception: No handles or timers registered in dispatcher. [ValueError]``

**Comment by dom96** [comment] 2017-11-27 00:39
@edubart can this be closed?

**Comment by dom96** [comment] 2018-02-17 22:08
No reply for a while so I'm going to close this. Feel free to reopen if this is still an issue.

**Closed** 2018-02-17 22:09 UTC
Labels: Async, High Priority, Stdlib
