### ISSUE TITLE
conditional broadcast missing from locks module

### ISSUE THREAD

**Issue by planetis-m** [nim-lang/Nim#17669] opened 2021-04-07 14:44 UTC
### Summary

`broadcast` is used to wake up blocked threads that are placed in a queue. `signal` on the other hand unblocks a single thread. Some applications require that all threads are [awaken](
http://www.qnx.com/developers/docs/qnxcar2/topic/com.qnx.doc.neutrino.getting_started/topic/s1_procs_Condvar_signal_vs_broadcast.html) . This api is currently missing.

**Comment by ringabout** [comment] 2021-04-07 14:49
Yeah, `SysCond` use `Event` in windows which makes it unnatural to implement `broadcast`.

I ever reimplemented it with `RTL_CONDITION_VARIABLE`.
https://gist.github.com/xflywind/bf90bb478b4f5c7f062717d64cf557bd

**Comment by ringabout** [comment] 2021-04-07 14:52
Duplicate of https://github.com/nim-lang/Nim/issues/7998

**Closed as completed by ringabout** 2021-04-07 14:52 UTC
Labels: Feature

**Comment by planetis-m** [comment] 2021-04-07 16:34
That's awesome, thanks for looking into it. Any plans on upstreaming it?

**Comment by ringabout** [comment] 2021-04-07 23:07
yeah, will make a PR soon.
