### ISSUE TITLE
ICE with proc not annotated with 'compileTime' that takes a parameter of type 'typed'

### ISSUE THREAD

**Issue by exetoc** [nim-lang/Nim#3208] opened 2015-08-13 17:33 UTC
```nim
proc p(s:typed)=discard
```

```
Error: internal error: getTypeDescAux(tyStmt)
Traceback (most recent call last)
nim.nim(97)              nim
nim.nim(61)              handleCmdLine
main.nim(252)            mainCommand
main.nim(63)             commandCompileToC
modules.nim(206)         compileProject
modules.nim(154)         compileModule
passes.nim(203)          processModule
passes.nim(137)          processTopLevelStmt
cgen.nim(1217)           myProcess
ccgstmts.nim(1116)       genStmts
ccgexprs.nim(2070)       expr
ccgstmts.nim(1116)       genStmts
ccgexprs.nim(2134)       expr
cgen.nim(787)            genProc
cgen.nim(741)            genProcNoForward
cgen.nim(723)            genProcPrototype
ccgtypes.nim(748)        genProcHeader
ccgtypes.nim(348)        genProcParams
ccgtypes.nim(689)        getTypeDescAux
msgs.nim(962)            internalError
msgs.nim(866)            rawMessage
msgs.nim(863)            rawMessage
msgs.nim(796)            handleError
```

**Comment by Araq** [comment] 2015-09-18 13:17
Duplicate of some other bug.

**Closed by Araq** 2015-09-18 13:17 UTC
