### ISSUE TITLE
project-level config.nims overrides module-level .nim.cfg

### ISSUE THREAD

**Issue by arnetheduck** [nim-lang/Nim#13446] opened 2020-02-20 14:58 UTC
with a project-level `config.nims` and for a specific module, a `.nim.cfg`, one would expect the `.nim.cfg` to be handled after `config.nims` because it's more specific, but instead nim processes all `.cfg` files first, then all `nims`, breaking the ability to mix the two styles and retain the documented configuration file hierarchy.

for example, if `config.nims` contains `-d:setme` and module.nim.cfg contains `-u:setme`, the symbol should not be defined in `module.nim`

**Comment by genotrance** [comment] 2020-02-20 16:49
Duplicate of https://github.com/nim-lang/Nim/issues/9405

**Closed as completed** 2020-02-21 07:34 UTC
