### ISSUE TITLE
JSON comparator preserver order in objects

### ISSUE THREAD

**Issue by PMunch** [nim-lang/Nim#3967] opened 2016-03-15 14:34 UTC
According to the JSON specification: "An object is an unordered set of name/value pairs. "
This means that the object:

    {
        "key1":"value1",
        "key2":"value2"
    }

is the same as the object:

    {
        "key2":"value2",
        "key1":"value1"
    }

The JSON module comparator `==` however does not detect those objects as equal.

**Comment by def-** [comment] 2016-03-15 15:19
I believe this is fixed in the devel branch already. Can't reproduce.

**Closed by def-** 2016-03-15 15:19 UTC
