### ISSUE TITLE
importc var should be disallowed at proc scope; {.nodecl.} only respected in global scope

### ISSUE THREAD

**Issue by dumjyl** [nim-lang/Nim#12685] opened 2019-11-19 19:39 UTC
### Example
```nim
proc foo =
  var doesNotExist {.importc, nodecl.}: int
  echo doesNotExist
foo()
```

### Current Output
```
0
```

### Expected Output
```
backend error about undeclared identifier
```

**Comment by Araq** [comment] 2019-11-20 06:58
Er, I would expect a compiler error message, you cannot import local variables.

**Comment by timotheecour** [comment] 2020-11-13 16:44
https://github.com/nim-lang/Nim/issues/12876 was caused by this; maybe we could add some logic in cgen to support importc var at local scope so that it'd do the right thing, but in the meantime the simplest is to disallow it

**Comment by ringabout** [comment] 2020-11-14 01:43
JS backend: doesn't ignore these flags
VM: ignore these flags

**Comment by timotheecour** [comment] 2020-12-08 01:58
closing in favor of https://github.com/nim-lang/Nim/issues/16289 ; feel free to re-open (with a comment) if you disagree

**Closed by timotheecour** 2020-12-08 01:58 UTC
Labels: Codegen, Low Priority, accepts invalid
