### ISSUE TITLE
Don't warn against unused global imports

### ISSUE THREAD

**Issue by Wh1teDuke** [nim-lang/Nim#11917] opened 2019-08-09 08:00 UTC
Don't warn against unused global imports (Imports defined in your project.nim.cfg). Not useful.

***
```nim
Nim Compiler Version 0.20.99 [Linux: i386]
Compiled at 2019-08-09
Copyright (c) 2006-2019 by Andreas Rumpf

git hash: 3b8f7214603b7d7df2ecf38974997517222ac6f0
active boot switches: -d:danger
```

**Comment by krux02** [comment] 2019-08-09 08:03
Can you alaborate a bit? A context where the warning is annoying? And why it is not a good idea?

**Comment by Wh1teDuke** [comment] 2019-08-09 08:12
Consider you import strutils globally. For me that doesn't mean "Every single module will need strutils" but "The number of modules that needs it is enough to import it globally and avoid doing it by hand". Otherwise global imports are not useful to me.

But if in your project you have, say, 100 modules and strutils is used only in 30 of them, you will get 70 UnusedImport warnings.
In my case I have around 300 modules and more than 10 global imports.

**Comment by krux02** [comment] 2019-08-09 10:44
Yea I found out that you mean the nim argument to import import something even though the import statement in the file is missing. I personally recommend you to not use this feature. It might be handy to use and you can simply create new projects where you don't need to care about imports, but it makes reproducable builds harder.

**Comment by timotheecour** [comment] 2020-09-17 22:23
duplicate of https://github.com/nim-lang/Nim/issues/13185
(close this even though it's older as the other one has more context)

**Closed by timotheecour** 2020-09-17 22:23 UTC
Labels: Error messages, RFC
