### ISSUE TITLE
nim doc2 ignores --docSeeSrcUrl parameter

### ISSUE THREAD

**Issue by mratsim** [nim-lang/Nim#6071] opened 2017-07-08 15:42 UTC
Whatever I pass to `--docSeeSrcUrl` is ignored by nim doc2

Source path stays "file:///tree/master/....." on MacOS

```
$  nim -v
Nim Compiler Version 0.17.0 (2017-05-17) [MacOSX: amd64]
Copyright (c) 2006-2017 by Andreas Rumpf

git hash: d3f0f87e81e262ee25fd528aae5b6db0bdf78d5e
active boot switches: -d:release
```

**Comment by timotheecour** [comment] 2018-07-06 03:14
should we close as duplicate of https://github.com/nim-lang/Nim/issues/6071 ?

**Comment by timotheecour** [comment] 2018-07-30 19:44
now that https://github.com/nim-lang/Nim/pull/8423 was merged, we can close this after changing all references to `--docSeeSrcUrl` to `--git.url and --git.commit`

**Comment by FedericoCeratto** [comment] 2019-04-19 12:57
Warning: docSeeSrcUrl has been removed. See --git.url

**Closed** 2020-09-17 17:55 UTC
Labels: Doc Generation
