### ISSUE TITLE
Type ordering matters for `set` fields

### ISSUE THREAD

**Issue by SolitudeSF** [nim-lang/Nim#13040] opened 2020-01-05 14:01 UTC
This snippet fails to compile with `Error: ordinal type expected`
```nim
type
  B = object
   s: set[A]
  A = enum
   a1, a2
```

Moving declaration of `A` to the top fixes the issue.

**Comment by Araq** [comment] 2020-01-05 19:21
Duplicate of https://github.com/nim-lang/Nim/issues/6259

**Closed by Araq** 2020-01-05 19:21 UTC
Labels: Type sections
