### ISSUE TITLE
parsecfg: empty section name with arc/orc

### ISSUE THREAD

**Issue by ba0f3** [nim-lang/Nim#15382] opened 2020-09-21 18:12 UTC
All section names are become empty when using with arc/orc

### Example
test1.ini
```ini
[section1]
foo=bar
```
```nim
import parsecfg
let cfg = loadConfig("test.ini")
echo cfg
```

### Current Output
```
[""]
foo=bar
```

### Expected Output
```
[section1]
foo=bar
```

### Possible Solution

Im not fimiliar with arc/orc yet, but  after some debug  I found that section name become empty, after this line https://github.com/nim-lang/Nim/blob/devel/lib/pure/parsecfg.nim#L470

When I put `var curSection = curSection` above it, it works again like before

```
$ nim -vNim Compiler Version 1.3.7 [Linux: amd64]
Compiled at 2020-09-21
Copyright (c) 2006-2020 by Andreas Rumpf

git hash: f2773d60cff7427282409216f633a70e4695146e
active boot switches: -d:release
```

**Comment by Araq** [comment] 2020-10-02 09:48
Seems to be fixed with my latest cursor inference bugfixes, cannot reproduce anymore.

**Closed as completed by Araq** 2020-10-02 09:48 UTC
Labels: ARC/ORC Memory Management
