### ISSUE TITLE
Bad codegen for static[string]

### ISSUE THREAD

**Issue by yglukhov** [nim-lang/Nim#6133] opened 2017-07-21 21:20 UTC
```nim
proc foo*(q: string, a: int) =
    echo "str len: ", q.len

proc foo*(q: static[string]) =
    foo(q, 5)

foo("123")
```
Expected result: str len: 3
Actual result: str len: (some random value, e.g.) 8391162079615332913

**Comment by Araq** [comment] 2017-07-22 13:48
Fails with the C++ backend. The problem is that the static parameter is not available at runtime. The compiler should not allow this.

**Comment by yglukhov** [comment] 2017-07-22 18:31
Err, are you sure? The code looks perfectly fine to me. Moreover, it works if you rename first `foo` to something else.

**Comment by krux02** [comment] 2017-07-25 00:49
Well the C code generator generates the following code for foo:

```C
N_NIMCALL(void, foo_Y1e9c9bG0Y3DKao86chBszYg)(NimStringDesc* q, NI a) {
	NimStringDesc* T1_;
	T1_ = (NimStringDesc*)0;
	T1_ = nimIntToStr((q ? q->Sup.len : 0));
	printf("%s%s\012", ((NimStringDesc*) &TM_X9bGGOoNyKehOTF7f2xys3g_2)? (((NimStringDesc*) &TM_X9bGGOoNyKehOTF7f2xys3g_2))->data:"nil", T1_? (T1_)->data:"nil");
	fflush(stdout);
}
```

```C
N_NIMCALL(void, foo_KjkeqgtUGSSeeXfajY5p0g)(void) {
	foo_Y1e9c9bG0Y3DKao86chBszYg("123", ((NI) 5));
}
```

when I rename the second foo to foox, it generates this code instead:

```C
N_NIMCALL(void, foox_KjkeqgtUGSSeeXfajY5p0g)(void) {
	foo_Y1e9c9bG0Y3DKao86chBszYg(((NimStringDesc*) &TM_X9bGGOoNyKehOTF7f2xys3g_3), ((NI) 5));
}
```

So the static string is for some unknown reason not properly converted to a Nim string literal.

**Comment by zah** [comment] 2017-07-25 16:22
I agree that this should work. I'll take a look.

**Comment by GULPF** [comment] 2018-01-18 17:18
Workaround: avoid calling overloads from static[T] procs. The example works if the procs have different names.

**Comment by GULPF** [comment] 2018-01-19 14:04
Found this bizarre case that is probably related:
```nim
type E = enum A

if false:
    var e = A
    discard $e

proc foo*(a: string) =
    echo len(a) # 16640

proc foo*(a: static[bool]) =
    discard

foo("")
```
The enum stringification is somehow affecting the result, even though it never runs. Only seems to happen with enums, and the enum must be defined in the same module. Note that the `static[T]` proc is never called, and that this doesn't need `static[string]` to trigger like the other example.

**Comment by GULPF** [comment] 2018-01-19 14:12
And with the JS backend it's even worse. This is all that is needed to reproduce the bug:
```nim
proc foo*(a: string) =
    echo len(a) # prints 2, should be 3

proc foo*(a: static[bool]) =
    discard

foo("abc")
```
Note that the definitions of foo can be defined by different modules. For example, this results in a runtime crash with the JS backend:
```nim
import strutils

proc parseInt*(f: static[bool]) = discard

echo "123".parseInt
```

**Comment by LemonBoy** [comment] 2018-06-24 13:54
This is fixed by #8072, at least on the C side of the moon

**Comment by GULPF** [comment] 2018-06-30 12:00
Still buggy with the JS backend

**Comment by skilchen** [comment] 2018-06-30 13:54
@LemonBoy s fix needs to be applied also in `jsgen.nim`
@GULPF s issue would be fixed by changing [line 2067](https://github.com/nim-lang/Nim/blob/devel/compiler/jsgen.nim#L2067) from
```nim
if skipTypes(n.typ, abstractVarRange).kind == tyString:
```
to
```nim
if skipTypes(n.typ, abstractVarRange + {tyStatic}).kind ==  tyString:
```
As i don't really know, what i am talking about here, i don't know if there are other places in `jsgen.nim` where @LemonBoy s fix needs to be applied.

**Closed** 2021-04-01 10:46 UTC
Labels: Error messages, Static[T]
