### ISSUE TITLE
`Error: cannot evaluate at compile time` when using a `var`/`let` within `proc`

### ISSUE THREAD

**Issue by tersec** [nim-lang/Nim#22215] opened 2023-07-03 21:00 UTC
### Description

```nim
const r = block:
  var res: int
  res

const c = static:
  var res: int
  res

const y = block:
  let res = 0
  res

const t = static:
  let res = 0
  res

proc s() =
  const j = block:
    var res: int
    res

  const n = static:
    var res: int
    res

  const w = block:
    let res = 0
    res

  const v = static:
    let res = 0
    res
```

### Nim Version

```
Nim Compiler Version 1.9.5 [Linux: amd64]
Compiled at 2023-07-03
Copyright (c) 2006-2023 by Andreas Rumpf

git hash: c513e37a7052d44b789b6ec8ccfc94885193a7b5
active boot switches: -d:release
```

### Current Output

```text
$ nim c /tmp/m.nim
/tmp/m.nim(19, 9) Error: cannot evaluate at compile time: res
$ vim /tmp/m.nim  # comment out const j = ...
$ nim c /tmp/m.nim
/tmp/m.nim(23, 9) Error: cannot evaluate at compile time: res
$ vim /tmp/m.nim  # comment out const n = ...
$ nim c /tmp/m.nim
/tmp/m.nim(27, 9) Error: cannot evaluate at compile time: res
$ vim /tmp/m.nim  # comment out const w = ...
$ nim c /tmp/m.nim
/tmp/m.nim(31, 9) Error: cannot evaluate at compile time: res
```

### Expected Output

```text
Consistent behavior when one of these Nim VM-executing blocks (`static:` or `const foo = static:`) is in a `proc` or not in a `proc`
```

**Comment by ringabout** [comment] 2023-07-04 02:04
Duplicate of https://github.com/nim-lang/Nim/issues/12172

**Closed as completed by ringabout** 2023-07-04 02:04 UTC
