### ISSUE TITLE
Can't declare a mixin.

### ISSUE THREAD

**Issue by deech** [nim-lang/Nim#11237] opened 2019-05-12 22:51 UTC
Can't `mixin` a function.

### Example
```nim
proc f() = 
  mixin a
  echo a()

proc a():string = "a"

echo f()
```

### Current Output
```
testmixin.nim(2, 3) Error: invalid expression: mixin a1
```

### Expected Output

```
a
```

### Additional Information
```
$ nim -v
Nim Compiler Version 0.19.9 [Linux: amd64]
Compiled at 2019-05-12
Copyright (c) 2006-2019 by Andreas Rumpf

git hash: a3e27ffa2c721b2ef3b0481d7db5c45039072050
active boot switches: -d:release
```

**Comment by deech** [comment] 2019-05-12 22:58
The issue is that for some reason a `mixin` only works inside a `template` or a generic proc, so this works:
```
template f() = 
  mixin a
  echo a()

proc a():string = "a"

f()
```
and so does this:
```
proc f[T]() =
  mixin a
  echo a()

proc a():string = "a"

f[int]()
```

If this is intended behavior it should be documented in the manual.

**Comment by mratsim** [comment] 2019-05-13 07:11
Seems like a simplified duplicate of https://github.com/nim-lang/Nim/issues/7385

**Closed** 2019-05-13 08:49 UTC
Labels: Symbol Resolution
