### ISSUE TITLE
Macros do not return bool as expected

### ISSUE THREAD

**Issue by jgh-** [nim-lang/Nim#8606] opened 2018-08-10 18:11 UTC
The following macro:
```
macro checkSame(x: typed): bool =
  sameType(getType(float32), x.getType)
```
should return `bool` but instead returns `<int literal(1)>` or `<int literal(0)>` depending on the result of `sameType`.

SO that means you cannot do 
```
if checkSame(y):
  ...
```
because you get the error `type mismatch: got <int literal(1)> but expected 'bool'`

You can try this:
```
macro checkSame(x: typed): int =
  sameType(getType(float32), x.getType)
```
But you will get the following error: `got <bool> but expected 'int'`

So finally you give up on the world and now you're doing this:
```
macro checkSame(x: typed): int =
  int(sameType(getType(float32), x.getType))

if checkSame(y) == 1:
  ...
```

**Comment by cooldome** [comment] 2018-08-13 08:14
You need to use ``bindSym"true"`` and ``bindSym"false"``

**Comment by jgh-** [comment] 2018-08-13 08:17
Could you explain where I need to use that? Something like this:
```
macro checkSame(x: typed): bool =
 if sameType(getType(float32), x.getType):
   bindSym"true"
 else:
  bindSym"false"
```
?

**Comment by drslump** [comment] 2018-08-13 14:46
@jgh- to check at runtime using a template should work:

```nim
template checkSame(x: typed): bool =
    float32 is type(x)
```

at compile time this should work:

```nim
macro checkSame(x: typed): bool =
  if sameType(getType(float32), getType(x)):
    result = bindSym"true"
  else:
    result = bindSym"false"
```

Anyhow, it seems that your first example should have worked, the macro should convert the `bool` value returned by `sameType` into a `true` or `false` automatically.

**Comment by jgh-** [comment] 2018-08-13 14:54
OK thanks for the explanation, I didn't realize there were templates in addition to macros.

**Comment by andreaferretti** [comment] 2018-08-13 15:32
(probably what you are trying to do is just `when x is float32: ...`)

**Comment by mratsim** [comment] 2018-08-15 09:02
My rule of thumb is that macro always return `NimNode` so I always use `untyped` as a return type.

In any case, duplicate of https://github.com/nim-lang/Nim/issues/7375 (Macro: bool is converted to static[int] when passed to other macros)

**Comment by Clyybber** [comment] 2020-05-29 22:32
Closing as a duplicate of #7375

**Closed by Clyybber** 2020-05-29 22:32 UTC
Labels: Macros
