### ISSUE TITLE
Inconsistent behavior between newSeq and newSeqOfCap

### ISSUE THREAD

**Issue by lscrd** [nim-lang/Nim#7298] opened 2018-03-04 21:50 UTC
The following program shows a different behavior between NewSeq and newSeqOfCap.

```nim
proc p() =
  var x = newSeq[int]()
  let y = x
  x.add(1)
  echo x, " ", y

proc q() =
  var x = newSeqOfCap[int](16)
  let y = x
  x.add(1)
  echo x, " ", y

p()
q()
```

In the first case, "x" and "y"  are different at the end. When adding 1 to "x" a reallocation has been done. This behavior seems to be as expected (copy semantic) but for the wrong reason.

In the second case, "x" and "y" are identical at the end (and indeed share the same data). `let y = x` is simply translated as a pointer assignment so the data is shared until a reallocation is done.

Thus, the content of "y" is identical to the content of "x" until a reallocation is done or until "x" is assigned a new value. If the content of "x" changes without a reallocation, the content of "y" changes.  Normally, it should contain a copy of "x" when it is initialized and should not change afterwards.

**Comment by narimiran** [comment] 2019-02-20 16:31
Closing because this is similar to #6004, which, in turn, is a duplicate of #2314.

**Closed by narimiran** 2019-02-20 16:31 UTC
