### ISSUE TITLE
Wrong code being generated for procs declared as closures.

### ISSUE THREAD

**Issue by rbehrends** [nim-lang/Nim#2921] opened 2015-06-14 09:47 UTC
Assigning globally declared closures from a separate module breaks, because `ccgexprs.genAssignment` assumes that the source is a closure struct rather than a function pointer.

```nim
# alpha.nim
import beta
var x: proc() = f
```

```nim
# beta.nim
proc f*() {.closure.} = discard
```

**Comment by Araq** [comment] 2015-06-14 21:16
Top level .closure procs will not be supported anymore in the future.

**Comment by rbehrends** [comment] 2015-06-14 22:43
In this case, it would be nice to have a macro that turns procedures into anonymous closures. Like:

```nim
import macros

macro closure*(p: proc): untyped =
  let pname = p
  let ptype = p.getType
  for i in 1..len(ptype)-1:
    if ptype[i].kind != nnkSym:
      error("closure: all argument types of procedure be named")
  var fn = newTree(nnkLambda,
    newEmptyNode(),
    newEmptyNode(),
    newEmptyNode(),
    newNimNode(nnkFormalParams),
    newEmptyNode(),
    newEmptyNode(),
    newStmtList(newCall(pname)))
  var args = fn[3]
  var call = fn[6][0]
  let rtype = ptype[1].typeKind
  if rtype == ntyEmpty:
    args.add newEmptyNode()
  else:
    args.add ptype[1]
  for i in 2..len(ptype)-1:
    let sym = genSym(nskParam, "t" & $(i-1))
    args.add newTree(nnkIdentDefs,
      sym, ptype[i], newEmptyNode())
    call.add sym
  return fn
```

**Comment by Araq** [comment] 2015-06-14 23:14
I agree, but 'x => f(x)' from future is not too bad either.

**Comment by dom96** [comment] 2016-01-16 14:01
Duplicate of #1793?

**Comment by Araq** [comment] 2016-05-15 18:55
Now produces Error: '.closure' calling convention for top level routines is invalid
which is correct.

**Closed by Araq** 2016-05-15 18:55 UTC
Labels: Lambda lifting, Low Priority
