### ISSUE TITLE
Windows Defender detects nimble.exe as Win32/Zpevdo.B trojan

### ISSUE THREAD

**Issue by KainAlive** [nim-lang/Nim#18933] opened 2021-09-30 16:19 UTC
I don't know if this counts as a valid error, but Windows Defender detects nimble.exe (Nim 1.4.8) as Win32/Zpevdo.B trojan (see screenshot).
I guess this counts as a bug.

![nimble_trojan](https://user-images.githubusercontent.com/33988011/135492706-a027206d-2ed5-4011-b66b-ca3b8b9aa659.PNG)

Translation:
Warning level: Severe
Status: Active
Date: 30.09.2021 18:09 (06:09 PM)
Category: Trojan
Details: This programme is dangerous. It executes commands from an attacker.
Affected items:
file: C:\nim-1.4.8\bin\nimble.exe

**Comment by ringabout** [comment] 2021-10-01 03:59
Duplicate of https://github.com/nim-lang/Nim/issues/17820

**Closed as completed by ringabout** 2021-10-01 03:59 UTC
