### ISSUE TITLE
openArray[] used against `or` cannot be used in generic

### ISSUE THREAD

**Issue by awr1** [nim-lang/Nim#10966] opened 2019-04-05 04:24 UTC
```nim
proc foo[T: openArray[int] or int](x: T): int =
  when not(T is int):
    result = x[0]
  else:
    result = x

echo(foo(@[1]))
```

```
Error: type mismatch: got <seq[int]>
but expected one of: 
proc foo[T: openArray[int] or int](x: T): int

expression: foo(@[1])
```

**Comment by mratsim** [comment] 2019-04-05 10:30
Closing as duplicate of https://github.com/nim-lang/Nim/issues/7432

**Closed by mratsim** 2019-04-05 10:30 UTC
