### ISSUE TITLE
Calling generic proc from a different module requires importing features used in proc at call site

### ISSUE THREAD

**Issue by coffeepots** [nim-lang/Nim#2832] opened 2015-05-28 15:33 UTC
Calling a generic procedure from a different module yields a type mismatch if the calling module doesn't import features used in that procedure.

```nimrod
### module: test
import tables
 
proc useTable*[T](a: string, data: T) =
  var t = initTable[string, T]()
  t[a] = data  # <- error here (see below), but only when calling from module test2
  # Error: type mismatch: got (Table[system.string, system.int], string, int)
  # but expected one of:
  # system.[]=(a: var array[Idx, T], x: Slice[system.int], b: openarray[T])
  # system.[]=(a: var array[Idx, T], x: Slice[[]=.Idx], b: openarray[T])
  # system.[]=(s: var seq[T], x: Slice[system.int], b: openarray[T])
  # system.[]=(s: var string, x: Slice[system.int], b: string)
 
when isMainModule:
  useTable[int]("test", 4) # this works fine because module test imports Tables
 

### module: test2
import test
# import tables # <- this will allow it to work
 
useTable[int]("test", 4) # this will now raise the error mentioned above inside 'useTable'

```

**Comment by Araq** [comment] 2015-07-01 01:49
Yes. Duplicate of some other high priority bug.

**Closed by Araq** 2015-07-01 01:49 UTC
