### ISSUE TITLE
filterIt().sortedByIt() result with following Error: internal error: environment misses: result`gensym340031

### ISSUE THREAD

**Issue by jringuette** [nim-lang/Nim#12928] opened 2019-12-19 00:03 UTC
Doing a filterIt(...).sortedByIt(...) crash with the following: `Error: internal error: environment misses: result`gensym340031`

### Example
```nim
import sequtils, algorithm, unittest

type
    Student* = tuple[name: string, grade: int]
    School* = object
        students*: seq[Student]

func grade*(school: School, grade: int): seq[string] =
    return school.students.filterIt(it.grade == grade).sortedByIt(
            it.name).mapIt(it.name)

test "grade returns the students in that grade in alphabetical order":
  let school = School(students: @[("Franklin", 5), ("Bradley", 5), ("Jeff", 1)])
  check school.grade(5) == @["Bradley", "Franklin"]
```
https://play.nim-lang.org/#ix=24Pp

### Current Output
```
/playground/nim/lib/pure/collections/sequtils.nim(495, 7) Error: internal error: environment misses: result`gensym340031
```

### Expected Output
```
[OK] grade returns the students in that grade in alphabetical order
```

### Possible Solution

Use a temp variable to split the filter from the sort like this

```nim
func grade*(school: School, grade: int): seq[string] =
    let tmp = school.students.filterIt(it.grade == grade)
    return tmp.sortedByIt(it.name).mapIt(it.name)
```
https://play.nim-lang.org/#ix=24Pq

### Additional Information

```
$ nim -v
Nim Compiler Version 1.0.4 [Linux: amd64]
Compiled at 2019-11-27
Copyright (c) 2006-2019 by Andreas Rumpf

git hash: c8998c498f5e2a0874846eb31309e1d1630faca6
active boot switches: -d:release
```

**Comment by ghost** [comment] 2020-10-25 10:05
Closing as a  duplicate of https://github.com/nim-lang/Nim/issues/10456

**Closed by ghost** 2020-10-25 10:05 UTC
Labels: Crash

**Comment by jpleboeuf** [comment] 2020-10-26 01:17
I encountered the same exact internal error working on this Exercism problem a few days ago, which I reported on the Nim-lang forum there: "[Why is the chaining order of It templates a problem in this example?](https://forum.nim-lang.org/t/6983#43773)".

@shirleyquirk suggested in a reply that in [`sortedByIt`](https://github.com/nim-lang/Nim/blob/226595515c25785eaf078834dfb6f0ac337a5278/lib/pure/algorithm.nim#L504) changing the type of `x` and `y` from `typeof(seq1[0])` to `auto` seems to fix the error.

**Comment by shirleyquirk** [comment] 2020-10-26 17:45
better solution is ``typeof(items(seq1),typeOfIter)``
