### ISSUE TITLE
Sophos thinks 1.4.6 has a virus

### ISSUE THREAD

**Issue by sigzero** [nim-lang/Nim#17877] opened 2021-04-27 19:44 UTC
See the upload screenshot. I just download 1.4.6 today off the Nim website links. False positive?

![screenshot](https://user-images.githubusercontent.com/540937/116302617-6903d780-a76f-11eb-922a-e52c60dede06.png)

**Comment by ringabout** [comment] 2021-04-28 06:09
see https://forum.nim-lang.org/t/7830

Duplicate of https://github.com/nim-lang/Nim/issues/17820

**Closed as completed** 2021-04-28 06:10 UTC
