### ISSUE TITLE
Codegen error with nkStmtListExpr inside nested templates

### ISSUE THREAD

**Issue by dom96** [nim-lang/Nim#12045] opened 2019-08-26 00:16 UTC
Ran into this while attempting to work around #12042.

### Example

```nim
type
  DataView = openarray[byte]
  ArrayBuffer  =string

template newDataViewParamSafe(buffer: var ArrayBuffer, byteOffset, byteLength: int): DataView =
  toOpenArrayByte(
    buffer,
    byteOffset,
    byteOffset + byteLength - 1
  )

template newDataView*(buffer: var ArrayBuffer, byteOffset, byteLength: int): DataView =
  newDataViewParamSafe(buffer, (let bo = byteOffset; bo), (let bl = byteLength; bl))

proc test(dv: DataView) =
  echo dv

proc main() =
  var foo = "hello world"

  test(newDataView(foo, 0, 3))

main()
```

### Current Output
```
Error: execution of an external compiler program 'clang -c  -w  -I/Users/dom/projects/nim/lib -I/private/tmp/aporia -o /Users/dom/.cache/nim/a4_d/a4.nim.c.o /Users/dom/.cache/nim/a4_d/a4.nim.c' failed with exit code: 1

/Users/dom/.cache/nim/a4_d/a4.nim.c:162:5: error: redefinition of 'bo'
        NI bo;
           ^
/Users/dom/.cache/nim/a4_d/a4.nim.c:161:5: note: previous definition is here
        NI bo;
           ^
1 error generated.
```

### Expected Output

```
hell
```

### Additional Information

```
$ nim -v
Nim Compiler Version 0.20.99 [MacOSX: amd64]
Compiled at 2019-08-06
Copyright (c) 2006-2019 by Andreas Rumpf

git hash: 8407a574992ebd6bccec647a902cf54a4de8db18
active boot switches: -d:release
```

**Comment by ringabout** [comment] 2024-08-28 07:55
Duplicate of https://github.com/nim-lang/Nim/issues/15637

**Closed by ringabout** 2024-08-28 07:55 UTC
Labels: Code Generation, Templates
