### ISSUE TITLE
"intVal is not accessible" in VM

### ISSUE THREAD

**Issue by def-** [nim-lang/Nim#6083] opened 2017-07-11 21:35 UTC
As reported in https://github.com/def-/nim-bigints/issues/13 bigint calculations fail in the VM.

```nim
import bigints

proc factorial(accum: BigInt, i : int) : BigInt =
  if i == 1: accum
  else: factorial(accum * initBigInt(i), i - 1)

const fact1000 = factorial(initBigInt(1),1000)

echo fact1000
```
Running with `./koch temp c x.nim`:
```
Traceback (most recent call last)
nim.nim(121)             nim
nim.nim(77)              handleCmdLine
main.nim(163)            mainCommand
main.nim(74)             commandCompileToC
modules.nim(240)         compileProject
modules.nim(180)         compileModule
passes.nim(215)          processModule
passes.nim(135)          processTopLevelStmt
sem.nim(550)             myProcess
sem.nim(522)             semStmtAndGenerateGenerics
semstmts.nim(1839)       semStmt
semexprs.nim(820)        semExprNoType
semexprs.nim(2344)       semExpr
semstmts.nim(628)        semConst
sem.nim(318)             semConstExpr
vm.nim(1585)             evalConstExpr
vm.nim(1581)             evalConstExprAux
vm.nim(508)              rawExecute
vm.nim(205)              putIntoNode
system.nim(2712)         sysFatal
Error: unhandled exception: intVal is not accessible [FieldError]
FAILURE
```

**Comment by jangko** [comment] 2017-07-18 03:08
this is the minimum code to reproduce the bug, both `result.setLen(2)` and `inc tmp`  needed to produce the bug. if one of them commented, the bug is gone

```Nim
proc abc(): seq[int] =
  result = @[0]
  result.setLen(2)
  var tmp: int
    
  for i in 0 .. <2:
    inc tmp
    result[i] = tmp

const fact1000 = abc()
```

**Comment by Parashurama** [comment] 2017-08-19 10:26
This is fixed in latest devel with PR #6224

**Comment by matkuki** [comment] 2019-07-06 19:46
Hi @Araq,

I'm upgrading my application [(chipmunk7_demos)](https://github.com/matkuki/chipmunk7_demos) to work with the latest **Nim** version, but when compiling, I get just this error message and no other information:
```
fatal.nim(48)            sysFatal
Error: unhandled exception: intVal is not accessible [FieldError]
```
Specs:
- Windows 10
- Nim Compiler Version 0.20.99 [Windows: amd64]
Compiled at 2019-07-06
Copyright (c) 2006-2019 by Andreas Rumpf
git hash: 25cd8a5490e94d79eaafaaa19f198d0771d9b40c
active boot switches: -d:release

I have no idea what is happening. Any help would be much appreciated!
If you need me to try anything, just let me know.

**Comment by krux02** [comment] 2019-07-26 17:36
@matkuki I just compiled the example from this issue here on the development branch and everything works as it should work no problems found. So can you please open a new issue with some code where I can reproduce the problem? Because in this issue has indeed been fixed and seems to be unrelated to your problem.

**Closed by krux02** 2019-07-26 17:36 UTC
Labels: Crash, Regression, VM
