### ISSUE TITLE
Nim doc sometimes generates proc description when no description present

### ISSUE THREAD

**Issue by DanielVF** [nim-lang/Nim#9596] opened 2018-11-01 14:45 UTC
My first time working with nim. I fired up `nim doc` on a file, and on some of my procs I'm seeing descriptions when I have not entered any descriptions.

Doc:

![image](https://user-images.githubusercontent.com/837/47858603-d4e56f00-ddc2-11e8-8eb0-5dec086b713c.png)

Code:

![image](https://user-images.githubusercontent.com/837/47858684-0100f000-ddc3-11e8-87ef-4ca4d8c15f34.png)

It appears that it is finding the first documented proc inside my proc, and using that description? It does not do this to all procs, just these two.

    Nim Compiler Version 0.19.0 [MacOSX: amd64]
    Compiled at 2018-09-26
    Copyright (c) 2006-2018 by Andreas Rumpf
    
    git hash: f6c5c636bb1a1f4e1301ae0ba5a8afecef439132
    active boot switches: -d:release

**Comment by kaushalmodi** [comment] 2018-11-01 16:07
This is a duplicate of https://github.com/nim-lang/Nim/issues/9432. 

The good news is that this bug is already fixed on Nim `devel` branch. Try building Nim from devel.

**Comment by Araq** [comment] 2018-11-01 16:13
Sorry for the inconvenience, 0.19.2 will be out soon.

**Closed by Araq** 2018-11-01 16:13 UTC

**Comment by DanielVF** [comment] 2018-11-01 21:34
Thanks guys!
