### ISSUE TITLE
Functor concept from the manual is not working.

### ISSUE THREAD

**Issue by bobeff** [nim-lang/Nim#16835] opened 2021-01-26 13:47 UTC
The functor concept described in the experimental features [manual](https://nim-lang.org/docs/manual_experimental.html#concepts) is not working.

### Example
```nim
import sugar, typetraits

type
  Functor[A] = concept f
    type MatchedGenericType = genericHead(typeof(f))
      # `f` will be a value of a type such as `Option[T]`
      # `MatchedGenericType` will become the `Option` type
    
    f.val is A
      # The Functor should provide a way to obtain
      # a value stored inside it
    
    type T = auto
    map(f, A -> T) is MatchedGenericType[T]
      # And it should provide a way to map one instance of
      # the Functor to a instance of a different type, given
      # a suitable `map` operation for the enclosed values

import options
echo Option[int] is Functor # prints true
```

### Current Output
```
false
```

### Expected Output
```
true
```

### Compiler Version
```
$ nim -v
Nim Compiler Version 1.5.1 [Linux: amd64]
Compiled at 2021-01-26
Copyright (c) 2006-2021 by Andreas Rumpf

git hash: ecc9704bf406c65dce549b0c5542727d33816e7f
active boot switches: -d:danger
```

**Comment by Clyybber** [comment] 2021-01-26 14:00
Duplicate of #5650

**Closed as completed by Clyybber** 2021-01-26 14:00 UTC
