### ISSUE TITLE
type conversion of distinct creates erroneous copy in VM

### ISSUE THREAD

**Issue by Clyybber** [nim-lang/Nim#12282] opened 2019-09-27 13:17 UTC
Compiling the snippet below outputs an empty line, while it should output `c`

### Example
(EDIT) problem with distinct remains even after https://github.com/nim-lang/Nim/pull/15423 which deprecates `TaintedString`
```nim
proc test(s: var TaintedString) =
  s.string.add('c') #Works with s.add('c')

static:
  var s: string
  test(s)
  echo s
```

### Current Output
```

```

### Expected Output
```
c
```

### EDIT: Example 2

see also example with seq in https://github.com/nim-lang/Nim/issues/9423#issuecomment-740353828

### Additional Information

```
$ nim -v
Nim Compiler Version 1.0.0
```

**Comment by krux02** [comment] 2019-10-22 18:43
I ran into a variation of the same bug.

```nim
type
  MyArr = distinct array[3,int]

proc foobar(dst: var array[3,int]) =
  dst[0] = 1
  dst[1] = 2
  dst[2] = 3

proc test() =
  var z: MyArr
  foobar(array[3,int](z))
  echo array[3,int](z)

test()
static:
  test()
```

output:
```
Hint: scratch [Processing]
[0, 0, 0]
Hint:  [Link]
Hint: operation successful (21904 lines compiled; 0.131 sec total; 25.664MiB peakmem; Dangerous Release Build) [SuccessX]
Hint: /tmp/scratch  [Exec]
[1, 2, 3]
```

This is important since my rewrite of the json.to macro requires this to work.

**Comment by timotheecour** [comment] 2020-04-24 23:37
@Clyybber can you change the title to something like: `T <=> distinct[T] conversion creates a copy in VM` 

* it's specific to distinct IIUC
* it's not limited to var param, eg see this:

```nim
when true:  #D20200424T162848:here
  type Foo = distinct string
  proc test() =
    var s: Foo
    s.string.add('c')
    doAssert s.string == "c" #fails
  static: test()
```

## borrow works:
```nim
when true:
  type Foo = distinct string
  proc add(a: var Foo, b: char) {.borrow.}
  proc test() =
    var s: Foo
    s.add('c')
    doAssert s.string == "c" #ok
  static: test()
```

## conversion TO distinct also fails
```nim
when true:
  type Foo = distinct string
  proc add(a: var Foo, b: char) {.borrow.}
  proc test() =
    var s: string
    s.Foo.add('c')
    doAssert s.string == "c" # fails
  static: test()
```

**Comment by timotheecour** [comment] 2020-12-08 03:40
see also example with seq from https://github.com/nim-lang/Nim/issues/9423#issuecomment-740353828, closing https://github.com/nim-lang/Nim/issues/9423 as duplicate of this

**Closed** 2021-03-31 08:15 UTC
Labels: Distinct Types, VM
