### ISSUE TITLE
`osproc.waitForExit` blocks when it should return immediately

### ISSUE THREAD

**Issue by ChengCat** [nim-lang/Nim#18781] opened 2021-09-02 08:26 UTC
### Example
```nim
import osproc, streams

var process = startProcess(
   command = "/bin/sh",
   args = ["-c", "non_existent_path"]
)

var line: string
while process.outputStream.readline(line):
   echo line

echo "wait for exit"
let exit_code = process.waitForExit(3000)
```

### Additional Information
Tested under Linux.

```
git hash: 3469f3a39320cf35d02d11b78c7db0be79e992f8
active boot switches: -d:release
```

**Comment by ringabout** [comment] 2021-09-02 08:31
Duplicate of https://github.com/nim-lang/Nim/issues/5091

**Closed as completed** 2021-09-03 08:06 UTC
