### ISSUE TITLE
Poor error with unclosed parens

### ISSUE THREAD

**Issue by dom96** [nim-lang/Nim#8400] opened 2018-07-22 15:46 UTC
```nim
import asyncdispatch

proc bar(): Future[string] = discard

proc foo(line: string) {.async.} =
  var res: seq[string] = nil
  case line[0]
  of '+', '-': res = @[]
  of '$':
    let x = await bar()
    res = @[""])
  else:
    assert false

waitFor foo("asd")
```

Error:

```
a5.nim(7, 3) Error: not all cases are covered
```

This error really puzzled me. We need a better error message here.

**Comment by GULPF** [comment] 2018-07-23 05:02
Duplicate of #3515

**Comment by andreaferretti** [comment] 2018-07-23 07:50
Closing as duplicate

**Closed by andreaferretti** 2018-07-23 07:50 UTC
Labels: Error messages
