### ISSUE TITLE
Array of types (typedesc) crashes the compiler

### ISSUE THREAD

**Issue by kraptor** [nim-lang/Nim#14305] opened 2020-05-11 15:30 UTC
Creating an array of types, crashes the compiler.

### Example
```nim
let types = [int, uint] 
```

### Current Output
```
Error: internal error: getTypeDescAux(tyNone)
No stack traceback available
To create a stacktrace, rerun compilation with ./koch temp c <file>
```

But this works:
```nim
const types = [int, uint] 
```

### Expected Output
A nice error if forbidden on a non-static context.

### Possible Solution

Not sure.

### Additional Information

Latest version on Nim playground:
https://play.nim-lang.org/#ix=2lEF

On my computer:
```
$ nim -v
Nim Compiler Version 1.2.0 [Windows: amd64]
Compiled at 2020-04-03
Copyright (c) 2006-2020 by Andreas Rumpf

git hash: 7e83adff84be5d0c401a213eccb61e321a3fb1ff
active boot switches: -d:release
```

**Comment by ghost** [comment] 2020-05-11 15:33
Duplicate of https://github.com/nim-lang/Nim/issues/12398

**Comment by kraptor** [comment] 2020-05-11 15:37
thanks @Yardanico, I wasn't able to find the other one 👍

**Comment by ghost** [comment] 2020-05-11 15:41
@kraptor close then? :)

**Closed as completed** 2020-05-11 15:45 UTC
