### ISSUE TITLE
Object constructor violates copy semantics, allows modifying immutable [js only]

### ISSUE THREAD

**Issue by mcclure** [nim-lang/Nim#4703] opened 2016-09-03 16:08 UTC
I am using Nim self-built from git, version 84a09d2f5b0866491e55fef0fef541e8cc548852 . I make a file testnim.nim:

```
# Test 1
block:
    let ary1 = [1, 2, 3]
    var ary2 = ary1

    ary2[1] = 9

    echo ary1[1], " ", ary2[1]

# Test 2
block:
    type TestObj = ref object of RootObj
        ary2: array[3, int]

    let ary1 = [1, 2, 3]
    var obj = TestObj(ary2:ary1)

    obj.ary2[1] = 9

    echo ary1[1], " ", obj.ary2[1]
```

I compile using both C and JS, using `nim js -o:testnim.js -d:nodejs testnim.nim` and `nim c -o:testnim testnim.nim`. I run with `./testnim` and `node testnim.js`.

Expected behavior: In both tests, `ary1` should be immutable and assigning its value to `ary2` should make a copy. The program should print

```
2 9
2 9
```

Observed behavior: The C version works as expected. The js version prints

```
2 9
9 9
```

`ary1` is being modified.

Other notes:
- I tested with several other ways of assigning data between `var`s and `let`s (argument parameters, default arguments etc) and did not see anything incorrect happen unless an object constructor was involved.
- Changing `let ary1` to `const ary1` in test 2 causes the js version to work correctly.

**Comment by mcclure** [comment] 2016-09-03 16:19
Note: I upgraded to 80fe763915ac742314069489906c5530b10e689c and repeated the test. I got the same results.

**Comment by philip-wernersbach** [comment] 2017-03-03 16:36
Possible duplicate of #4139

**Closed** 2017-06-29 16:32 UTC
Labels: JS
