### ISSUE TITLE
Unable to forward declare a proc when its return type is auto

### ISSUE THREAD

**Issue by Obround** [nim-lang/Nim#12033] opened 2019-08-25 04:03 UTC
When I was trying to forward declare a proc with its return type set to auto, the code did not compile; My code:
```nim
proc test_proc[T, U](arg1: T, arg2: U): auto

echo test_proc(3, 5)

proc test_proc[T, U](arg1: T, arg2: U): auto = 
    echo "Proc has been called"
    return arg1 / arg2
```
it raises this ambiguous error:
```
C:\Users\travis\build\nim-lang\nightlies\nim\e7471cebae2a404f3e4239f199f5a0c422484aac\lib\system\fatal.nim(39) sysFatal
Error: unhandled exception: C:\Users\travis\build\nim-lang\nightlies\nim\e7471cebae2a404f3e4239f199f5a0c422484aac\compiler\ccgtypes.nim(196, 17) `false` mapType [AssertionError]
```
but if I declare the return type, the code runs fine:
```nim
proc test_proc[T, U](arg1: T, arg2: U): float

echo test_proc(3, 5)

proc test_proc[T, U](arg1: T, arg2: U): float = 
    echo "Proc has been called"
    return arg1 / arg2
```
Is there some way to set a proc's return type to auto while still forward declaring it?

**Comment by StefanSalewski** [comment] 2019-08-25 05:44
I think that is not a bug. A proc forward declaration has the purpose to tell the compiler the types of the parameters and the return type, so the compiler can generate code to call that proc, while the address (the code) of the actual proc is still unknown, it is inserted later.

What may work: when you know that result type is always the type of the division of variables of type T and U, then you can create a macro that gets these two types, creates two dummy variables of these types and returns the type of the division. I have still to learn more about macros to try that.

Or you may try Nim's experimental code reordering.

**Comment by krux02** [comment] 2019-08-25 12:23
It is almost as @StefanSalewski said. The forward declaration is for the semantic checking. The semantic checker needs to know the function signature in order to do type inference, throw errors when assigned to variables of incompatible type and inject implicit conversions when needed. With the `auto` return type you tell the compiler "I am not telling you the return type, it is upon you to find it out.". This defeats the point of a forward declaration.

But there is an issue here. Forward declarations with `auto` return type should raise an error already when declared.

**Closed** 2019-08-26 18:14 UTC
Labels: Error messages
