### ISSUE TITLE
Space between procname and parameter list -> tuple error

### ISSUE THREAD

**Issue by StefanSalewski** [nim-lang/Nim#12024] opened 2019-08-24 07:53 UTC
```nim
proc t(i, j: int) =
  echo i, j

t (1, 2)
```

```
/tmp/hhh/t.nim(4, 3) Error: type mismatch: got <tuple of (int, int)>
but expected one of: 
proc t(i, j: int)
  first type mismatch at position: 1
  required type for i: int
  but expression '(1, 2)' is of type: tuple of (int, int)

expression: t (1, 2)

```

We had it in IRC logs recently. And well, people should learn Nim, but I think that error messages can be hard for beginners. It is not that uncommon to put a space after proc name for some people, and beginners may not even know what a tuple is, as it is not a basic data type. So maybe add something like "Do you mean ..."

**Comment by bluenote10** [comment] 2019-08-24 09:55
Duplicate of  #12006

**Closed** 2019-08-27 18:05 UTC
