### ISSUE TITLE
Inc/dec/succ/pred try to work for enums with holes too instead of failing compilation

### ISSUE THREAD

**Issue by kaushalmodi** [nim-lang/Nim#8262] opened 2018-07-10 15:53 UTC
From [Nim Manual - Enumeration Types][1]:

> An explicit ordered enum can have holes:

> However, it is then not an ordinal anymore, so it is not possible to use these enums as an index type for arrays. The procedures inc, dec, succ and pred are not available for them either.

But on testing on devel (5c5388c0a66c35319e2f360744ab0b9183ca5160), the `inc` , `dec`, `succ`, `pred` seem to work with enums with holes too, and then printing **(invalid data!)** when those operations end up on a hole.

```nim
type
  Signals = enum
    sigQuit = 3, sigAbort = 6, sigKill = 9

var nonOrdinal = sigQuit
echo "inc on holey enums"
echo " ", nonOrdinal
inc nonOrdinal
echo " ", nonOrdinal
inc nonOrdinal
echo " ", nonOrdinal
inc nonOrdinal
echo " ", nonOrdinal
inc nonOrdinal
echo " ", nonOrdinal
echo "dec on holey enums"
dec nonOrdinal
echo " ", nonOrdinal
dec nonOrdinal
echo " ", nonOrdinal
echo "succ on holey enums"
echo " ", nonOrdinal.succ
echo " ", nonOrdinal.succ(2)
echo "pred on holey enums"
echo " ", nonOrdinal.pred
```

```
inc on holey enums
 sigQuit
 4 (invalid data!)
 5 (invalid data!)
 sigAbort
 7 (invalid data!)
dec on holey enums
 sigAbort
 5 (invalid data!)
succ on holey enums
 sigAbort
 7 (invalid data!)
pred on holey enums
 4 (invalid data!)
```

[1]: https://nim-lang.org/docs/manual.html#types-enumeration-types

**Comment by andreaferretti** [comment] 2018-07-10 16:31
Duplicate of https://github.com/nim-lang/Nim/issues/1239

**Closed by andreaferretti** 2018-07-10 16:31 UTC
