### ISSUE TITLE
[Documentation] boolVal doc is about unequal operator

### ISSUE THREAD

**Issue by mratsim** [nim-lang/Nim#9626] opened 2018-11-05 09:48 UTC
https://nim-lang.org/docs/macros.html#boolVal%2CNimNode
![2018-11-05_10-45-39](https://user-images.githubusercontent.com/22738317/47990514-f8245d00-e0e7-11e8-996e-4bd4d45ac2a3.png)

I don't understand how that can happen as in 0.19 this is the [definition](https://github.com/nim-lang/Nim/blob/v0.19.0/lib/core/macros.nim#L1274-L1276).

```Nim
proc boolVal*(n: NimNode): bool {.compileTime, noSideEffect.} =
  if n.kind == nnkIntLit: n.intVal != 0
  else: n == bindSym"true" # hacky solution for now
```

The hacky solution should trigger a warning btw.

**Comment by skilchen** [comment] 2018-11-05 11:17
this is a duplicate of #9432 which has been fixed via https://github.com/nim-lang/Nim/commit/48f73aaa1cc4228e5ba58f471c5f66116c9e59ad

**Comment by krux02** [comment] 2018-11-05 12:09
yes it's a duplicate

**Closed by krux02** 2018-11-05 12:09 UTC
Labels: Documentation
