### ISSUE TITLE
testament: timeout failure does not affect the overall result

### ISSUE THREAD

**Issue by xzfc** [nim-lang/Nim#12247] opened 2019-09-24 12:35 UTC
### Current Output

```
$ cd testament
$ ./testament --nim:../bin/nim r tests/shouldfail/ttimeout; echo rc=$?
FAIL: tests/shouldfail/ttimeout C
Test "tests/shouldfail/ttimeout" in category "tests"
Failure: reTimeout
Expected:


Gotten:


Used ../bin/nim to run the tests. Use --nim to override.
rc=0
```

### Expected Output

```
FAILURE! total: 1 passed: 0 skipped: 0 failed: 1
rc=1
```

**Comment by Araq** [comment] 2019-09-25 10:44
That's just a quirk of how we setup the testament tests that test testament itself.

**Comment by xzfc** [comment] 2019-09-25 12:06
I am talking about [`testament/tests/shouldfail/ttimeout.nim`](https://github.com/nim-lang/Nim/blob/6b4b329f45ce23fc7590c2c9fb3cc50715b266a1/testament/tests/shouldfail/ttimeout.nim) (which should fail) and not about [`tests/testament/tshouldfail.nim`](https://github.com/nim-lang/Nim/blob/6b4b329f45ce23fc7590c2c9fb3cc50715b266a1/tests/testament/tshouldfail.nim) (which test testament itself).

It prints "FAIL" message to stdout, but the exit code is 0, so CI would think it's passed.

**Comment by Araq** [comment] 2019-09-25 17:08
Ah ok!

**Comment by ringabout** [comment] 2021-03-29 03:24
Duplicate of #17407

**Closed by ringabout** 2021-03-29 03:24 UTC
Labels: Test suite
