### ISSUE TITLE
Regression from 1.6/2.0.4/devel to 2.0.5: `Error: toException(self.eResultPrivate) can raise an unlisted exception: ref LPError`

### ISSUE THREAD

**Issue by tersec** [nim-lang/Nim#23519] opened 2024-04-18 19:02 UTC
### Description

```nim
type
  ResultError[E] = object of ValueError
    error: E

  Result[T, E] = object
    case oResultPrivate: bool
    of false:
      eResultPrivate: E
    of true:
      vResultPrivate: T

  LPError = object of CatchableError

func raiseResultError[T, E](self: Result[T, E]) {.noreturn, noinline.} =
  # noinline because raising should take as little space as possible at call
  # site
  mixin toException

  when E is ref Exception:
    if self.eResultPrivate.isNil: # for example Result.default()!
      raise (ref ResultError[void])(msg: "Trying to access value with err (nil)")
    raise self.eResultPrivate
  elif E is void:
    raise (ref ResultError[void])(msg: "Trying to access value with err")
  elif compiles(toException(self.eResultPrivate)):
    raise toException(self.eResultPrivate)
  elif compiles($self.eResultPrivate):
    raise (ref ResultError[E])(error: self.eResultPrivate, msg: $self.eResultPrivate)
  else:
    raise (ref ResultError[E])(
      msg: "Trying to access value with err", error: self.eResultPrivate
    )

template err[T; E: not void](R: type Result[T, E], x: untyped): R =
  R(oResultPrivate: false, eResultPrivate: x)

func tryValue[T, E](self: Result[T, E]): T {.inline.} =
  mixin raiseResultError
  case self.oResultPrivate
  of false:
    self.raiseResultError()
  of true:
    when T isnot void:
      self.vResultPrivate

{.push raises: [].}
{.push public.}

template tryGet[T: not void, E](self: Result[T, E]): T =
  self.tryValue()

func toException(e: string): ref LPError =
  (ref LPError)(msg: e)

proc `&`*() {.raises: [LPError].} =
  let foo: Result[int, string] = Result[int, string].err("")
  discard foo.tryGet()
```

1.6 builds, `devel` builds.

### Nim Version

Builds:
```
Nim Compiler Version 1.6.21 [Linux: amd64]
Compiled at 2024-04-18
Copyright (c) 2006-2023 by Andreas Rumpf

git hash: 8ebb4dc30af3a5d3dd14bc651698d02b715befed
active boot switches: -d:release
```

```
Nim Compiler Version 2.1.1 [Linux: amd64]
Compiled at 2024-04-18
Copyright (c) 2006-2024 by Andreas Rumpf

git hash: d6823f477672e61017e9c1ce3b5221a2b80fc1b7
active boot switches: -d:release
```

... also builds:
```
Nim Compiler Version 2.0.4 [Linux: amd64]
Compiled at 2024-04-18
Copyright (c) 2006-2023 by Andreas Rumpf

git hash: b47747d31844c6bd9af4322efe55e24fefea544c
active boot switches: -d:release
```

Does not build:
```
Nim Compiler Version 2.0.5 [Linux: amd64]
Compiled at 2024-04-18
Copyright (c) 2006-2023 by Andreas Rumpf

git hash: fd64402e478432e5566d6bb2d5ced30bd82e7dd1
active boot switches: -d:release
```

### Current Output

```text
s.nim(57, 14) template/generic instantiation of `tryGet` from here
s.nim(50, 7) template/generic instantiation of `tryValue` from here
s.nim(41, 9) template/generic instantiation of `raiseResultError` from here
s.nim(14, 1) template/generic instantiation from here
s.nim(26, 5) Error: toException(self.eResultPrivate) can raise an unlisted exception: ref LPError
```

**Comment by juancarlospaco** [comment] 2024-04-18 19:30
!nim c

```nim
type
  ResultError[E] = object of ValueError
    error: E

  Result[T, E] = object
    case oResultPrivate: bool
    of false:
      eResultPrivate: E
    of true:
      vResultPrivate: T

  LPError = object of CatchableError

func raiseResultError[T, E](self: Result[T, E]) {.noreturn, noinline.} =
  mixin toException

  when E is ref Exception:
    if self.eResultPrivate.isNil: # for example Result.default()!
      raise (ref ResultError[void])(msg: "Trying to access value with err (nil)")
    raise self.eResultPrivate
  elif E is void:
    raise (ref ResultError[void])(msg: "Trying to access value with err")
  elif compiles(toException(self.eResultPrivate)):
    raise toException(self.eResultPrivate)
  elif compiles($self.eResultPrivate):
    raise (ref ResultError[E])(error: self.eResultPrivate, msg: $self.eResultPrivate)
  else:
    raise (ref ResultError[E])(
      msg: "Trying to access value with err", error: self.eResultPrivate
    )

template err[T; E: not void](R: type Result[T, E], x: untyped): R =
  R(oResultPrivate: false, eResultPrivate: x)

func tryValue[T, E](self: Result[T, E]): T {.inline.} =
  mixin raiseResultError
  case self.oResultPrivate
  of false:
    self.raiseResultError()
  of true:
    when T isnot void:
      self.vResultPrivate

{.push raises: [].}
{.push public.}

template tryGet[T: not void, E](self: Result[T, E]): T =
  self.tryValue()

func toException(e: string): ref LPError =
  (ref LPError)(msg: e)

proc `&`*() {.raises: [LPError].} =
  let foo: Result[int, string] = Result[int, string].err("")
  discard foo.tryGet()
```

**Comment by juancarlospaco** [comment] 2024-04-18 19:36
@tersec Whats pragma public ?, repro code is wrong. 🤔

**Comment by tersec** [comment] 2024-04-18 20:06
Honestly, no idea.

Apparently whatever it is, it worked before and after 2.0.5.

**Comment by tersec** [comment] 2024-04-18 20:19
Alternative framing: either this is valid code, and 2.0.5 has a bug, or it's not, and 1.6/2.0.4/2.1.1 have an invalid code acceptance bug. But at least one of these statements is true.

**Comment by tersec** [comment] 2024-04-18 21:24
This compiles with 1.6, 2.0.4, 2.0.5, and 2.1.1 as above:
```nim
{.push addr.}
{.push do.}
{.push static.}
{.push type.}
{.push _.}
{.push thread.}
{.push final.}
{.push profiler.}
{.push memtracker.}
{.push objchecks.}
{.push intdefine.}
{.push strdefine.}
{.push booldefine.}
{.push cursor.}
{.push noalias.}
{.push uncheckedAssign.}
{.push immediate.}
{.push destructor.}
{.push override.}
{.push requiresInit.}
{.push align.}
{.push nodecl.}
{.push pure.}
{.push nosinks.}
{.push lib.}
{.push dynlib.}
{.push compilerproc.}
{.push core.}
{.push procvar.}
{.push base.}
{.push used.}
{.push fatal.}
{.push error.}
{.push warning.}
{.push hint.}
{.push warningAsError.}
{.push hintAsError.}
{.push line.}
{.push push.}
{.push pop.}
{.push define.}
{.push undef.}
{.push lineDir.}
{.push link.}
{.push compile.}
{.push linksys.}
{.push deprecated.}
{.push varargs.}
{.push callconv.}
{.push debugger.}
{.push on.}
{.push off.}
{.push checks.}
{.push rangeChecks.}
{.push boundChecks.}
{.push overflowChecks.}
{.push nilChecks.}
{.push floatChecks.}
{.push nanChecks.}
{.push infChecks.}
{.push styleChecks.}
{.push staticBoundChecks.}
{.push nonReloadable.}
{.push executeOnReload.}

# this section is apparently intended to be genuinely pragmas
{.push assertions.}
{.push patterns.}
{.push trmacros.}
{.push sinkInference.}
{.push warnings.}
{.push hints.}
{.push optimization.}
{.push writes.}
{.push reads.}
{.push size.}
{.push effects.}
{.push invariant.}
{.push assume.}
{.push assert.}
{.push deadCodeElim.}
{.push safecode.}
{.push package.}
{.push noforward.}
{.push norewrite.}
{.push nodestroy.}
{.push pragma.}
{.push compileTime.}
{.push fieldChecks.}
{.push subschar.}
{.push computedGoto.}
{.push experimental.}
{.push doctype.}
{.push write.}
{.push gensym.}
{.push inject.}
{.push dirty.}
{.push inheritable.}
{.push threadvar.}
{.push asmNoStackFrame.}
{.push implicitStatic.}
{.push global.}
{.push unchecked.}
{.push guard.}
{.push partial.}
{.push explain.}
{.push liftlocals.}
{.push enforceNoRaises.}

# "codegen keywords, but first the ones that are also pragmas"
{.push goto.}
{.push register.}
{.push union.}
{.push packed.}
{.push volatile.}
{.push bycopy.}
{.push byref.}

# "codegen keywords but not pragmas"
{.push auto.}
{.push bool.}
{.push catch.}
{.push char.}
{.push class.}
{.push compl.}
{.push const_cast.}
{.push default.}
{.push delete.}
{.push double.}
{.push dynamic_cast.}
{.push explicit.}
{.push false.}
{.push float.}
{.push friend.}
{.push int.}
{.push long.}
{.push mutable.}
{.push namespace.}
{.push new.}
{.push operator.}
{.push private.}
{.push protected.}
{.push public.}
{.push reinterpret_cast.}
{.push restrict.}
{.push short.}
{.push signed.}
{.push sizeof.}
{.push static_cast.}
{.push struct.}
{.push switch.}
{.push this.}
{.push throw.}
{.push true.}
{.push typedef.}
{.push typeid.}
{.push typeof.}
{.push typename.}
{.push unsigned.}
{.push void.}

{.push alignas.}
{.push alignof.}
{.push constexpr.}
{.push decltype.}
{.push nullptr.}
{.push noexcept.}
{.push thread_local.}
{.push static_assert.}
{.push char16_t.}
{.push char32_t.}
{.push wchar_t.}
{.push stdin.}
{.push stdout.}
{.push stderr.}
{.push inout.}
{.push oneway.}
{.push bitsize.}
{.push all.}

# Something for all these beautiful pragmas to attach to
proc f() = discard
let x = 0
```

**Comment by tersec** [comment] 2024-04-18 21:25
`{.push emit.}` ICEs, as do a few others. It's also possible to use `{.push ...}` to trigger `nim c` to instead use the C++ backend, but it doesn't do it properly so it doesn't link.

**Comment by juancarlospaco** [comment] 2024-04-19 01:53
That can be a nice test actually... 🤔

**Comment by tersec** [comment] 2024-04-19 02:28
Sure, though some of them are supposed to work and are actual pragmas. I'm not sure any of the "codegen keywords but not pragmas" make sense in this grammatical context though. Not sure what `{.push char16_t.}`, `{.push addr.}`, `{.push do.}`, et cetera should mean either.

Some of them, e.g., `on` and `off`, are kind of strange artifacts of the grammar, apparently, where they seem to be meant to be paired with a `warning` or similar token to provide them meaning, but are parsed regardless.

**Comment by ringabout** [comment] 2024-04-19 05:50
Yeah, the regression on ther version-2-0 failed the nightlies

**Comment by ringabout** [comment] 2024-04-19 05:50
@juancarlospaco Hi, could you add Nim compiler built on the branch `version-2-0` for bisects?

**Comment by narimiran** [comment] 2024-04-19 05:53
I bisected `version-2-0`, and this seems to be the problematic commit: https://github.com/nim-lang/Nim/pull/22941

I'm backporting commits from this list: https://github.com/nim-lang/backport/issues/3, and I have lots of commits yet to backport, so this might be fixed by some later commit. But in the mean time, I can revert the commit linked above.

**Comment by ringabout** [comment] 2024-04-19 06:10
Yeah, it should be reverted on the version-2-0 branch

**Comment by narimiran** [comment] 2024-04-19 06:27
> Yeah, it should be reverted on the version-2-0 branch

Reverted.

@tersec The original example now works on my machine with `version-2-0`, closing.

**Closed as completed by narimiran** 2024-04-19 06:27 UTC

**Comment by ringabout** [comment] 2024-04-22 11:47
Hi, @narimiran nightlies are still broken on version-2-0 branch => https://github.com/nim-lang/nightlies/actions/runs/8776715740/job/24080631890 probably it's a different cause?

**Comment by narimiran** [comment] 2024-04-22 12:49
> Hi, @narimiran nightlies are still broken on version-2-0 branch

Today a new batch of backports will come. Let's see if something changes after that.
