### ISSUE TITLE
`{.experimental: "notnil".}` check ignores early return from function

### ISSUE THREAD

**Issue by tersec** [nim-lang/Nim#21394] opened 2023-02-18 22:01 UTC
### Description

```nim
{.experimental: "notnil".}

proc f(x: ref int not nil) = discard

proc g() =
  var x: ref int
  if x.isNil:
    return
  else:
    f(x)    # not nil check does not trigger here,
  f(x)      # but here, equally unreachable when x is nil
```

https://nim-lang.org/docs/manual_experimental.html#not-nil-annotation states
> The compiler ensures that every code path initializes variables which contain non-nilable pointers.

And, indeed, the Nim compiler correctly reasons about the conditions of the `if` statement, because it has no problem with that first `f(x)`, but does not take appear to take into account the `return`, because the second `f(x)` call triggers the error. This holds as well if one includes only an `f(x)` in the `else` branch:
```nim
{.experimental: "notnil".}

proc f(x: ref int not nil) = discard

proc g() =
  var x: ref int
  if x.isNil:
    return
  else:
    f(x)
```
which compiles, and

```nim
{.experimental: "notnil".}

proc f(x: ref int not nil) = discard

proc g() =
  var x: ref int
  if x.isNil:
    return
  f(x)
```
which claims that `f(x)` might be called, with a `nil` value.

One can find even more minimal examples:
```nim
{.experimental: "notnil".}

proc f(x: ref int not nil) = discard

proc g() =
  if true: return
  f(default(ref int))
```
which does trigger a compiler error, and if one wants an especially interesting juxtaposition of warnings/errors around this:
```
$ cat notnil.nim
{.experimental: "notnil".}

proc f(x: ref int not nil) = discard

proc g() =
  return
  f(default(ref int))
$ nim c notnil.nim
/tmp/notnil.nim(7, 4) Warning: unreachable code after 'return' statement or '{.noReturn.}' proc [UnreachableCode]
/tmp/notnil.nim(7, 12) Error: cannot prove 'default(ref int)' is not nil
```
Those can't both be true/applicable simultaneously. Nim appears to be simply ignoring `return` statements in determining `not nil` possibilities.

### Nim Version

```
Nim Compiler Version 1.6.11 [Linux: amd64]
Compiled at 2023-02-18
Copyright (c) 2006-2021 by Andreas Rumpf

git hash: 7f90bcf5b4cbe5b7da534dd79bafbb4cafb313fa
active boot switches: -d:release
```

```
Nim Compiler Version 1.9.1 [Linux: amd64]
Compiled at 2023-02-18
Copyright (c) 2006-2023 by Andreas Rumpf

git hash: 6b93db7070c984121e18b502d938d5e455d4ba70
active boot switches: -d:release
```

### Current Output

```text
Error: cannot prove 'default(ref int)' is not nil
```

### Expected Output

```text
Fewer false positives on not nil checking on early proc/func return
```

**Comment by tersec** [comment] 2023-02-19 15:50
https://nim-lang.org/docs/manual_experimental.html#strict-not-nil-checking-branches-rules
>  Branches are the reason we do nil checking like this: with flow checking. 
Sources of branching are `if`, `while`, `for`, `and`, `or`, `case`, `try` and combinations with `return`, `break`, `continue` and `raise`

which mentions both `return` and `break`.

https://nim-lang.org/docs/manual_experimental.html#strict-not-nil-checking-unstructured-control-flow-rules even discusses this scenario specifically:
> Unstructured control flow keywords as `return`, `break`, `continue`, `raise` mean that we jump from a branch out.
This means that if there is code after the finishing of the branch, it would be run if one hasn't hit the direct parent branch of those: so it is similar to an `else`. In those cases we should use the reverse nilabilities for the local to the condition expressions.

But adapting the example in the latter link as minimally as possible (adding the `{.experimental: "notnil".}` and implementing some `proc b(... not nil) = discard`):
```nim
{.experimental: "notnil".}

proc b(a: ref int not nil) = discard
var c: seq[ref int]
for a in c:
  if a.isNil:
    break
  b(a)
```
and
```nim
{.experimental: "notnil".}

proc b(a: ref int not nil) = discard
var c: seq[ref int]
for a in c:
  if a.isNil:
    continue
  b(a)
```
same issue, even though the manual explicitly states that `return`, `break`, and `continue`, it "would" and "should" be treated as a kind of "else" for nilability tracking.

**Comment by juancarlospaco** [comment] 2023-02-19 21:04
`notnil` should be deprecated in favor of `strictNotNil`.

**Comment by tersec** [comment] 2023-02-20 05:55
> `notnil` should be deprecated in favor of `strictNotNil`.

Perhaps, but it wouldn't resolve this issue.

```nim
{.experimental: "strictNotNil".}

proc f(x: ref int not nil) = discard

proc g() =
  var x: ref int
  if x.isNil:
    return
  else:
    f(x)    # not nil check does not trigger here,
  f(x)      # but here, equally unreachable when x is nil
```
still results in
```
/tmp/snn.nim(11, 5) Error: cannot prove 'x' is not nil
```
on
```
f(x)      # but here, equally unreachable when x is nil
```

```nim
{.experimental: "strictNotNil".}

proc f(x: ref int not nil) = discard

proc g() =
  var x: ref int
  if x.isNil:
    return
  f(x)      # but here, equally unreachable when x is nil
```
still results in
```
/tmp/snn.nim(9, 5) Error: cannot prove 'x' is not nil
```

```nim
{.experimental: "strictNotNil".}

proc f(x: ref int not nil) = discard

proc g() =
  if true: return
  f(default(ref int))
```
still results in
```
/tmp/snn.nim(7, 12) Error: cannot prove 'default(ref int)' is not nil
```

```nim
{.experimental: "strictNotNil".}

proc f(x: ref int not nil) = discard

proc g() =
  return
  f(default(ref int))
```
still produces
```
/tmp/snn.nim(7, 4) Warning: unreachable code after 'return' statement or '{.noReturn.}' proc [UnreachableCode]
/tmp/snn.nim(7, 12) Error: cannot prove 'default(ref int)' is not nil
```

```nim
{.experimental: "strictNotNil".}

proc b(a: ref int not nil) = discard
var c: seq[ref int]
for a in c:
  if a.isNil:
    break
  b(a)
```
changes:
```
/tmp/snn.nim(4, 5) template/generic instantiation of `setLen` from here
Nim/lib/system/seqs_v2.nim(121, 13) template/generic instantiation of `shrink` from here
Nim/lib/system/seqs_v2.nim(86, 5) Warning: can't deref cast[ptr NimSeqV2[T]](addr x), it might be nil [StrictNotNil]
/tmp/snn.nim(4, 5) template/generic instantiation of `setLen` from here
Nim/lib/system/seqs_v2.nim(126, 25) Warning: can't deref xu, it might be nil [StrictNotNil]
/tmp/snn.nim(4, 5) template/generic instantiation of `setLen` from here
Nim/lib/system/seqs_v2.nim(126, 27) Warning: can't deref xu.p, it might be nil [StrictNotNil]
/tmp/snn.nim(4, 5) template/generic instantiation of `setLen` from here
Nim/lib/system/seqs_v2.nim(127, 57) Warning: can't deref xu, it might be nil
  assigns a value which might be nil on line 0:0 [StrictNotNil]
/tmp/snn.nim(4, 5) template/generic instantiation of `setLen` from here
Nim/lib/system/seqs_v2.nim(127, 9) Warning: can't deref xu, it might be nil
  assigns a value which might be nil on line 0:0 [StrictNotNil]
/tmp/snn.nim(4, 5) template/generic instantiation of `setLen` from here
Nim/lib/system/seqs_v2.nim(128, 7) Warning: can't deref xu, it might be nil
  assigns a value which might be nil on line 0:0 [StrictNotNil]
/tmp/snn.nim(4, 5) template/generic instantiation of `setLen` from here
Nim/lib/system/seqs_v2.nim(130, 9) Warning: can't deref xu, it might be nil
  assigns a value which might be nil on line 0:0 [StrictNotNil]
/tmp/snn.nim(4, 5) template/generic instantiation of `setLen` from here
Nim/lib/system/seqs_v2.nim(130, 11) Warning: can't deref xu.p, it might be nil [StrictNotNil]
/tmp/snn.nim(8, 5) Error: cannot prove 'a' is not nil
```
That `/tmp/snn.nim(8, 5) Error: cannot prove 'a' is not nil` is still there, but all those `seqs_v2` warnings are new. Maybe they're even real and should be fixed in the stdlib; did not check.


```nim
{.experimental: "strictNotNil".}

proc b(a: ref int not nil) = discard
var c: seq[ref int]
for a in c:
  if a.isNil:
    continue
  b(a)
```
similarly adds several `seqs_v2.nim` warnings, then creates the same ultimate error as before:
```
/tmp/snn.nim(4, 5) template/generic instantiation of `setLen` from here
Nim/lib/system/seqs_v2.nim(121, 13) template/generic instantiation of `shrink` from here
Nim/lib/system/seqs_v2.nim(86, 5) Warning: can't deref cast[ptr NimSeqV2[T]](addr x), it might be nil [StrictNotNil]
/tmp/snn.nim(4, 5) template/generic instantiation of `setLen` from here
Nim/lib/system/seqs_v2.nim(126, 25) Warning: can't deref xu, it might be nil [StrictNotNil]
/tmp/snn.nim(4, 5) template/generic instantiation of `setLen` from here
Nim/lib/system/seqs_v2.nim(126, 27) Warning: can't deref xu.p, it might be nil [StrictNotNil]
/tmp/snn.nim(4, 5) template/generic instantiation of `setLen` from here
Nim/lib/system/seqs_v2.nim(127, 57) Warning: can't deref xu, it might be nil
  assigns a value which might be nil on line 0:0 [StrictNotNil]
/tmp/snn.nim(4, 5) template/generic instantiation of `setLen` from here
Nim/lib/system/seqs_v2.nim(127, 9) Warning: can't deref xu, it might be nil
  assigns a value which might be nil on line 0:0 [StrictNotNil]
/tmp/snn.nim(4, 5) template/generic instantiation of `setLen` from here
Nim/lib/system/seqs_v2.nim(128, 7) Warning: can't deref xu, it might be nil
  assigns a value which might be nil on line 0:0 [StrictNotNil]
/tmp/snn.nim(4, 5) template/generic instantiation of `setLen` from here
Nim/lib/system/seqs_v2.nim(130, 9) Warning: can't deref xu, it might be nil
  assigns a value which might be nil on line 0:0 [StrictNotNil]
/tmp/snn.nim(4, 5) template/generic instantiation of `setLen` from here
Nim/lib/system/seqs_v2.nim(130, 11) Warning: can't deref xu.p, it might be nil [StrictNotNil]
/tmp/snn.nim(8, 5) Error: cannot prove 'a' is not nil
```

**Comment by tersec** [comment] 2023-02-20 06:07
@juancarlospaco if you would like to discuss `strictNotNil`, created https://github.com/nim-lang/Nim/issues/21401 on that topic. But it doesn't seem to bear on this issue.

**Comment by ringabout** [comment] 2023-02-20 06:26
Duplicate of https://github.com/nim-lang/Nim/issues/1235

**Closed as completed** 2023-02-20 06:26 UTC
