### ISSUE TITLE
Using arrayWith crashes the compiler

### ISSUE THREAD

**Issue by Nmerryman** [nim-lang/Nim#23169] opened 2024-01-05 08:30 UTC
### Description

Simply using `arrayWith` crashes the compiler without leaving a stack trace.
```nim
var a = arrayWith(1, 3)
```
Is enough to trigger it.

### Nim Version

Nim Compiler Version 2.0.0 [Linux: amd64]
Compiled at 2023-08-01
Copyright (c) 2006-2023 by Andreas Rumpf

git hash: a488067a4130f029000be4550a0fb1b39e0e9e7c
active boot switches: -d:release

### Current Output

```text
home/n/.choosenim/toolchains/nim-2.0.0/lib/system.nim(2818, 25) Error: internal error: genMagicExpr: mDup
No stack traceback available
To create a stacktrace, rerun compilation with './koch temp compile <file>', see https://nim-lang.github.io/Nim/intern.html#debugging-the-compiler for details
```

### Expected Output

```text
Either compilation or a readable error.
```

**Comment by ringabout** [comment] 2024-01-05 08:50
Duplicate of https://github.com/nim-lang/Nim/issues/22923. I will fix it soon

**Closed as completed by ringabout** 2024-01-05 08:50 UTC
