### ISSUE TITLE
SetHandleInformation wrong 'int' to 'HANDLE' casts with VC++ using cpp mode.

### ISSUE THREAD

**Issue by treeform** [nim-lang/Nim#14980] opened 2020-07-14 15:35 UTC
### Repro case
```
nim cpp --cc:vcc .\src\main.nim
```
```nim
import net

let socket = newSocket(
  Domain.AF_INET,
  SockType.SOCK_DGRAM,
  Protocol.IPPROTO_UDP,
  buffered = false
)
```

### Current Output
```
C:\Users\me\.choosenim\toolchains\nim-#devel\lib\system\io.nim(342): error C2664: 'BOOL SetHandleInformation(HANDLE,DWORD,DWORD)': cannot convert argument 1 from 'int' to 'HANDLE'
C:\Users\me\.choosenim\toolchains\nim-#devel\lib\system\io.nim(342): note: Conversion from integral type to pointer type requires reinterpret_cast, C-style cast or function-style cast
C:\Program Files (x86)\Windows Kits\8.1\include\um\handleapi.h(88): note: see declaration of 'SetHandleInformation'
```

### Expected Output
It compiles.

### Possible Solution

If you just do `c` it works fine:
```
nim c --cc:vcc .\src\main.nim
```
```
Hint: 64214 lines; 9.882s; 75.609MiB peakmem; Debug build; ... [SuccessX]
```

Maybe a special case for cpp vs c when using --c:vcc is needed? Casting rules between C and C++ are more strict?

These PRs touched this area recently:
* https://github.com/nim-lang/Nim/pull/14550 @alaviss 
* https://github.com/nim-lang/Nim/pull/14548 @timotheecour
* https://github.com/nim-lang/Nim/pull/14551 @alaviss 

### Additional Information

```
nim -v
Nim Compiler Version 1.3.5 [Windows: amd64]
Compiled at 2020-07-14
Copyright (c) 2006-2020 by Andreas Rumpf

active boot switches: -d:release
```

**Comment by alaviss** [comment] 2020-07-14 15:42
It'd be easier if we can use `winlean` in `io` tbh. This bug is caused by the fact that we don't use the exact types as `HANDLE`. I do know a way around this though.

Can you try changing `io.nim` so that `setHandleInformation` take a `pointer` as the first parameter? Then change every usage of it to `cast` the argument to `pointer`. If that works then I'll try to make a PR for it.

**Comment by treeform** [comment] 2020-07-14 15:51
I switched to nim 1.2.2 (most recent stable version) and it works fine there with `cpp`.

I can try making your changes but I don't feel confident working in that code base.

**Comment by treeform** [comment] 2020-07-14 15:55
I did this in `io.nim`:

```nim
  proc setHandleInformation(handle: pointer, mask, flags: culong): cint {.
    importc: "SetHandleInformation", header: "<handleapi.h>".}

  proc setHandleInformation(handle: FileHandle, mask, flags: culong): cint =
    setHandleInformation(cast[pointer](handle), mask, flags)
```

And it compiles and works fine. Could you make a PR that does that better?

**Comment by timotheecour** [comment] 2020-07-14 22:12
> It'd be easier if we can use winlean in io tbh

no, winlean is large and would make it imported in all nim programs via system=>io=>winlean.
However, I'd be ok with a minimal `winlean_basics` such that system=>io=>winlean_basics and winlean=>winlean_basics to avoid code duplication

whatever's done for this issue, please make sure you read `incorrect types should be fixed` section in https://github.com/nim-lang/Nim/pull/14548#issue-426544097

**Closed as completed** 2020-07-20 04:17 UTC
