### ISSUE TITLE
test suite fails locally

### ISSUE THREAD

**Issue by krux02** [nim-lang/Nim#12053] opened 2019-08-26 12:31 UTC
When I execute ``koch runCI``, the process fails. This in the failing test. This happens all the time when I execute the test suite locally. What I don't understand is, why this failure happens only locally, but not the CI servers.

```
FAIL: compiler/nim.nim C --incremental:writeonly 
Test "compiler/nim.nim" in category "ic"
Failure: reNimcCrash
$ /home/arne/proj/nim/Nim/bin/nim c --hints:on -d:testing --nimblePath:tests/deps --incremental:writeonly --nimCache:nimcache/compiler/nim.nim_0d61f8370cad1d412f80b84d143e1257 --stdout '--hint[Path]:off' '--hint[Processing]:off' compiler/nim.nim
Hint: used config file '/home/arne/proj/nim/Nim/config/nim.cfg' [Conf]
Hint: used config file '/home/arne/.config/nim/nim.cfg' [Conf]
Hint: used config file '/home/arne/proj/nim/Nim/compiler/nim.cfg' [Conf]
Hint: used config file '/home/arne/proj/nim/Nim/config/config.nims' [Conf]
/home/arne/proj/nim/Nim/lib/pure/times.nim(2455, 26) Warning: countLeapYears is deprecated [Deprecated]
/home/arne/proj/nim/Nim/lib/pure/times.nim(2462, 15) Warning: countLeapYears is deprecated [Deprecated]
/home/arne/proj/nim/Nim/lib/pure/times.nim(2470, 24) Warning: countLeapYears is deprecated [Deprecated]
/home/arne/proj/nim/Nim/lib/pure/os.nim(2052, 6) Warning: declared lock level is 0, but real lock level is <unknown> [LockLevel]
/home/arne/proj/nim/Nim/lib/pure/os.nim(2169, 6) Warning: declared lock level is 0, but real lock level is <unknown> [LockLevel]
/home/arne/proj/nim/Nim/lib/pure/os.nim(2302, 6) Warning: declared lock level is 0, but real lock level is <unknown> [LockLevel]
/home/arne/proj/nim/Nim/lib/posix/termios.nim(11, 8) Warning: imported and not used: 'posix' [UnusedImport]
/home/arne/proj/nim/Nim/lib/pure/concurrency/cpuinfo.nim(15, 10) Warning: imported and not used: 'strutils' [UnusedImport]
/home/arne/proj/nim/Nim/lib/pure/concurrency/cpuinfo.nim(18, 10) Warning: imported and not used: 'linux' [UnusedImport]
/home/arne/proj/nim/Nim/lib/pure/concurrency/cpuinfo.nim(15, 27) Warning: imported and not used: 'os' [UnusedImport]
/home/arne/proj/nim/Nim/lib/pure/osproc.nim(31, 10) Warning: imported and not used: 'linux' [UnusedImport]
/home/arne/proj/nim/Nim/lib/pure/osproc.nim(1183, 12) Warning: imported and not used: 'times' [UnusedImport]
/home/arne/proj/nim/Nim/compiler/types.nim(107, 23) Warning: use getOrdvalue; getOrdValue64 is deprecated [Deprecated]
/home/arne/proj/nim/Nim/compiler/semfold.nim(181, 22) Warning: intVal should be Int128; newIntNodeT is deprecated [Deprecated]
/home/arne/proj/nim/Nim/compiler/semfold.nim(199, 38) Warning: intVal should be Int128; newIntNodeT is deprecated [Deprecated]
/home/arne/proj/nim/Nim/compiler/semfold.nim(209, 52) Warning: use getInt; getInt64 is deprecated [Deprecated]
/home/arne/proj/nim/Nim/compiler/semfold.nim(209, 40) Warning: intVal should be Int128; newIntNodeT is deprecated [Deprecated]
/home/arne/proj/nim/Nim/compiler/semfold.nim(210, 32) Warning: use getInt; getInt64 is deprecated [Deprecated]
/home/arne/proj/nim/Nim/compiler/semfold.nim(210, 20) Warning: intVal should be Int128; newIntNodeT is deprecated [Deprecated]
/home/arne/proj/nim/Nim/compiler/semfold.nim(217, 59) Warning: use getInt; getInt64 is deprecated [Deprecated]
/home/arne/proj/nim/Nim/compiler/semfold.nim(217, 25) Warning: intVal should be Int128; newIntNodeT is deprecated [Deprecated]
/home/arne/proj/nim/Nim/compiler/semfold.nim(218, 61) Warning: use getInt; getInt64 is deprecated [Deprecated]
/home/arne/proj/nim/Nim/compiler/semfold.nim(218, 26) Warning: intVal should be Int128; newIntNodeT is deprecated [Deprecated]
/home/arne/proj/nim/Nim/compiler/semfold.nim(219, 61) Warning: use getInt; getInt64 is deprecated [Deprecated]
/home/arne/proj/nim/Nim/compiler/semfold.nim(219, 26) Warning: intVal should be Int128; newIntNodeT is deprecated [Deprecated]
/home/arne/proj/nim/Nim/compiler/semfold.nim(220, 61) Warning: use getInt; getInt64 is deprecated [Deprecated]
/home/arne/proj/nim/Nim/compiler/semfold.nim(220, 26) Warning: intVal should be Int128; newIntNodeT is deprecated [Deprecated]
/home/arne/proj/nim/Nim/compiler/semfold.nim(223, 62) Warning: use getInt; getInt64 is deprecated [Deprecated]
/home/arne/proj/nim/Nim/compiler/semfold.nim(225, 62) Warning: use getInt; getInt64 is deprecated [Deprecated]
/home/arne/proj/nim/Nim/compiler/semfold.nim(226, 70) Warning: use getInt; getInt64 is deprecated [Deprecated]
/home/arne/proj/nim/Nim/compiler/semfold.nim(227, 72) Warning: use getInt; getInt64 is deprecated [Deprecated]
/home/arne/proj/nim/Nim/compiler/semfold.nim(228, 72) Warning: use getInt; getInt64 is deprecated [Deprecated]
/home/arne/proj/nim/Nim/compiler/semfold.nim(229, 72) Warning: use getInt; getInt64 is deprecated [Deprecated]
/home/arne/proj/nim/Nim/compiler/semfold.nim(232, 65) Warning: use getInt; getInt64 is deprecated [Deprecated]
/home/arne/proj/nim/Nim/compiler/semfold.nim(232, 18) Warning: intVal should be Int128; newIntNodeT is deprecated [Deprecated]
/home/arne/proj/nim/Nim/compiler/semfold.nim(234, 63) Warning: use getInt; getInt64 is deprecated [Deprecated]
/home/arne/proj/nim/Nim/compiler/semfold.nim(255, 14) Warning: intVal should be Int128; newIntNodeT is deprecated [Deprecated]
/home/arne/proj/nim/Nim/compiler/semfold.nim(258, 47) Warning: use getInt; getInt64 is deprecated [Deprecated]
/home/arne/proj/nim/Nim/compiler/semfold.nim(258, 66) Warning: use getInt; getInt64 is deprecated [Deprecated]
/home/arne/proj/nim/Nim/compiler/semfold.nim(258, 25) Warning: intVal should be Int128; newIntNodeT is deprecated [Deprecated]
/home/arne/proj/nim/Nim/compiler/semfold.nim(259, 49) Warning: use getInt; getInt64 is deprecated [Deprecated]
/home/arne/proj/nim/Nim/compiler/semfold.nim(259, 69) Warning: use getInt; getInt64 is deprecated [Deprecated]
/home/arne/proj/nim/Nim/compiler/semfold.nim(259, 26) Warning: intVal should be Int128; newIntNodeT is deprecated [Deprecated]
/home/arne/proj/nim/Nim/compiler/semfold.nim(260, 49) Warning: use getInt; getInt64 is deprecated [Deprecated]
/home/arne/proj/nim/Nim/compiler/semfold.nim(260, 69) Warning: use getInt; getInt64 is deprecated [Deprecated]
/home/arne/proj/nim/Nim/compiler/semfold.nim(260, 26) Warning: intVal should be Int128; newIntNodeT is deprecated [Deprecated]
/home/arne/proj/nim/Nim/compiler/semfold.nim(262, 33) Warning: use getInt; getInt64 is deprecated [Deprecated]
/home/arne/proj/nim/Nim/compiler/semfold.nim(262, 46) Warning: use getInt; getInt64 is deprecated [Deprecated]
/home/arne/proj/nim/Nim/compiler/semfold.nim(262, 16) Warning: intVal should be Int128; newIntNodeT is deprecated [Deprecated]
/home/arne/proj/nim/Nim/compiler/semfold.nim(285, 23) Warning: intVal should be Int128; newIntNodeT is deprecated [Deprecated]
/home/arne/proj/nim/Nim/compiler/semfold.nim(287, 14) Warning: intVal should be Int128; newIntNodeT is deprecated [Deprecated]
/home/arne/proj/nim/Nim/compiler/semfold.nim(289, 14) Warning: intVal should be Int128; newIntNodeT is deprecated [Deprecated]
/home/arne/proj/nim/Nim/compiler/semfold.nim(291, 14) Warning: intVal should be Int128; newIntNodeT is deprecated [Deprecated]
/home/arne/proj/nim/Nim/compiler/semfold.nim(292, 23) Warning: intVal should be Int128; newIntNodeT is deprecated [Deprecated]
/home/arne/proj/nim/Nim/compiler/semfold.nim(293, 23) Warning: intVal should be Int128; newIntNodeT is deprecated [Deprecated]
/home/arne/proj/nim/Nim/compiler/semfold.nim(294, 23) Warning: intVal should be Int128; newIntNodeT is deprecated [Deprecated]
/home/arne/proj/nim/Nim/compiler/semfold.nim(295, 23) Warning: intVal should be Int128; newIntNodeT is deprecated [Deprecated]
/home/arne/proj/nim/Nim/compiler/semfold.nim(296, 23) Warning: intVal should be Int128; newIntNodeT is deprecated [Deprecated]
/home/arne/proj/nim/Nim/compiler/semfold.nim(297, 23) Warning: intVal should be Int128; newIntNodeT is deprecated [Deprecated]
/home/arne/proj/nim/Nim/compiler/semfold.nim(299, 35) Warning: use getOrdvalue; getOrdValue64 is deprecated [Deprecated]
/home/arne/proj/nim/Nim/compiler/semfold.nim(299, 53) Warning: use getOrdvalue; getOrdValue64 is deprecated [Deprecated]
/home/arne/proj/nim/Nim/compiler/semfold.nim(299, 14) Warning: intVal should be Int128; newIntNodeT is deprecated [Deprecated]
/home/arne/proj/nim/Nim/compiler/semfold.nim(301, 36) Warning: use getOrdvalue; getOrdValue64 is deprecated [Deprecated]
/home/arne/proj/nim/Nim/compiler/semfold.nim(301, 54) Warning: use getOrdvalue; getOrdValue64 is deprecated [Deprecated]
/home/arne/proj/nim/Nim/compiler/semfold.nim(301, 14) Warning: intVal should be Int128; newIntNodeT is deprecated [Deprecated]
/home/arne/proj/nim/Nim/compiler/semfold.nim(325, 23) Warning: intVal should be Int128; newIntNodeT is deprecated [Deprecated]
/home/arne/proj/nim/Nim/compiler/semfold.nim(326, 23) Warning: intVal should be Int128; newIntNodeT is deprecated [Deprecated]
/home/arne/proj/nim/Nim/compiler/semfold.nim(328, 14) Warning: intVal should be Int128; newIntNodeT is deprecated [Deprecated]
/home/arne/proj/nim/Nim/compiler/semfold.nim(342, 23) Warning: intVal should be Int128; newIntNodeT is deprecated [Deprecated]
/home/arne/proj/nim/Nim/compiler/semfold.nim(369, 14) Warning: intVal should be Int128; newIntNodeT is deprecated [Deprecated]
/home/arne/proj/nim/Nim/compiler/semfold.nim(371, 14) Warning: intVal should be Int128; newIntNodeT is deprecated [Deprecated]
/home/arne/proj/nim/Nim/compiler/semfold.nim(374, 14) Warning: intVal should be Int128; newIntNodeT is deprecated [Deprecated]
/home/arne/proj/nim/Nim/compiler/semfold.nim(455, 16) Warning: intVal should be Int128; newIntNodeT is deprecated [Deprecated]
/home/arne/proj/nim/Nim/compiler/semfold.nim(558, 16) Warning: intVal should be Int128; newIntNodeT is deprecated [Deprecated]
/home/arne/proj/nim/Nim/compiler/semfold.nim(561, 34) Warning: intVal should be Int128; newIntNodeT is deprecated [Deprecated]
/home/arne/proj/nim/Nim/compiler/semfold.nim(564, 31) Warning: intVal should be Int128; newIntNodeT is deprecated [Deprecated]
/home/arne/proj/nim/Nim/compiler/semfold.nim(573, 22) Warning: intVal should be Int128; newIntNodeT is deprecated [Deprecated]
/home/arne/proj/nim/Nim/compiler/semfold.nim(584, 22) Warning: intVal should be Int128; newIntNodeT is deprecated [Deprecated]
/home/arne/proj/nim/Nim/compiler/semfold.nim(640, 22) Warning: intVal should be Int128; newIntNodeT is deprecated [Deprecated]
/home/arne/proj/nim/Nim/compiler/semfold.nim(645, 20) Warning: intVal should be Int128; newIntNodeT is deprecated [Deprecated]
/home/arne/proj/nim/Nim/compiler/semtypinst.nim(12, 54) Warning: imported and not used: 'renderer' [UnusedImport]
/home/arne/proj/nim/Nim/compiler/sigmatch.nim(19, 10) Warning: imported and not used: 'docgen' [UnusedImport]
/home/arne/proj/nim/Nim/compiler/liftdestructors.nim(16, 46) Warning: imported and not used: 'renderer' [UnusedImport]
/home/arne/proj/nim/Nim/compiler/sempass2.nim(16, 10) Warning: imported and not used: 'writetracking' [UnusedImport]
/home/arne/proj/nim/Nim/compiler/rodimpl.nim(13, 3) Warning: imported and not used: 'renderer' [UnusedImport]
/home/arne/proj/nim/Nim/compiler/lambdalifting.nim(14, 11) Warning: imported and not used: 'renderer' [UnusedImport]
/home/arne/proj/nim/Nim/compiler/closureiters.nim(135, 3) Warning: imported and not used: 'renderer' [UnusedImport]
/home/arne/proj/nim/Nim/compiler/transf.nim(23, 11) Warning: imported and not used: 'renderer' [UnusedImport]
/home/arne/proj/nim/Nim/compiler/semmagic.nim(77, 12) Warning: intVal should be Int128; newIntNodeT is deprecated [Deprecated]
/home/arne/proj/nim/Nim/compiler/semmagic.nim(166, 14) Warning: intVal should be Int128; newIntNodeT is deprecated [Deprecated]
/home/arne/proj/nim/Nim/compiler/sem.nim(27, 17) Warning: imported and not used: 'semparallel' [UnusedImport]
/home/arne/proj/nim/Nim/compiler/jsgen.nim(34, 44) Warning: imported and not used: 'renderer' [UnusedImport]
CC: stdlib_ansi_c.nim
CC: stdlib_memory.nim
CC: stdlib_assertions.nim
CC: stdlib_iterators.nim
CC: stdlib_dollars.nim
CC: stdlib_widestrs.nim
CC: stdlib_io.nim
CC: stdlib_system.nim
CC: stdlib_parseutils.nim
CC: stdlib_macros.nim
CC: stdlib_bitops.nim
CC: stdlib_math.nim
CC: stdlib_algorithm.nim
CC: stdlib_unicode.nim
CC: stdlib_strutils.nim
CC: stdlib_osseps.nim
CC: stdlib_pathnorm.nim
CC: stdlib_posix.nim
CC: stdlib_typetraits.nim
CC: stdlib_options.nim
CC: stdlib_times.nim
CC: stdlib_os.nim
CC: stdlib_hashes.nim
CC: stdlib_strtabs.nim
CC: stdlib_sets.nim
CC: pathutils.nim
CC: ropes.nim
CC: stdlib_tables.nim
CC: lineinfos.nim
CC: platform.nim
CC: prefixmatches.nim
CC: stdlib_strformat.nim
CC: stdlib_colors.nim
CC: stdlib_termios.nim
CC: stdlib_terminal.nim
CC: options.nim
CC: msgs.nim
CC: nversion.nim
CC: condsyms.nim
CC: stdlib_streams.nim
CC: stdlib_linux.nim
CC: stdlib_cpuinfo.nim
CC: stdlib_osproc.nim
CC: stdlib_endians.nim
CC: stdlib_sha1.nim
CC: stdlib_sequtils.nim
CC: stdlib_lexbase.nim
CC: stdlib_parsejson.nim
CC: stdlib_json.nim
CC: extccomp.nim
CC: wordrecg.nim
CC: nimblecmd.nim
CC: stdlib_parseopt.nim
CC: idents.nim
CC: idgen.nim
CC: int128.nim
CC: ast.nim
CC: stdlib_intsets.nim
CC: btrees.nim
CC: stdlib_sqlite3.nim
CC: stdlib_db_common.nim
CC: stdlib_db_sqlite.nim
CC: incremental.nim
CC: commands.nim
CC: llstream.nim
CC: nimlexbase.nim
CC: lexer.nim
CC: parser.nim
CC: renderer.nim
CC: filters.nim
CC: filter_tmpl.nim
CC: syntaxes.nim
CC: rodutils.nim
CC: astalgo.nim
CC: trees.nim
CC: types.nim
CC: stdlib_md5.nim
CC: modulegraphs.nim
CC: magicsys.nim
CC: bitsets.nim
CC: nimsets.nim
CC: semfold.nim
CC: modulepaths.nim
CC: vmdef.nim
CC: semdata.nim
CC: linter.nim
CC: nimfix/prettybase.nim
CC: lookups.nim
CC: semtypinst.nim
CC: parampatterns.nim
CC: lowerings.nim
CC: ../lib/packages/docutils/rstast.nim
CC: ../lib/packages/docutils/rst.nim
CC: ../lib/packages/docutils/highlite.nim
CC: ../lib/packages/docutils/rstgen.nim
CC: stdlib_xmltree.nim
CC: stdlib_cookies.nim
CC: stdlib_uri.nim
CC: stdlib_cgi.nim
CC: typesrenderer.nim
CC: docgen.nim
CC: sigmatch.nim
CC: importer.nim
CC: procfind.nim
CC: pragmas.nim
CC: reorder.nim
CC: saturate.nim
CC: guards.nim
CC: writetracking.nim
CC: sighashes.nim
CC: liftdestructors.nim
CC: sempass2.nim
CC: cgmeth.nim
CC: rod.nim
CC: passes.nim
CC: aliases.nim
CC: patterns.nim
CC: dfa.nim
CC: injectdestructors.nim
CC: liftlocals.nim
CC: lambdalifting.nim
CC: closureiters.nim
CC: transf.nim
CC: vmgen.nim
Error: execution of an external compiler program 'gcc -c -w  -I/home/arne/proj/nim/Nim/lib -I/home/arne/proj/nim/Nim/compiler -o /home/arne/proj/nim/Nim/nimcache/compiler/nim.nim_0d61f8370cad1d412f80b84d143e1257/closureiters.nim.c.o /home/arne/proj/nim/Nim/nimcache/compiler/nim.nim_0d61f8370cad1d412f80b84d143e1257/closureiters.nim.c' failed with exit code: 1

gcc: Fehler: /home/arne/proj/nim/Nim/nimcache/compiler/nim.nim_0d61f8370cad1d412f80b84d143e1257/closureiters.nim.c: Datei oder Verzeichnis nicht gefunden
gcc: schwerwiegender Fehler: keine Eingabedateien
Kompilierung beendet.

```

**Comment by timotheecour** [comment] 2021-05-23 18:05
* missing compiler version at which this occurred
* can't reproduce, works for me locally and in CI
closing, feel free to re-open if problem reappears

**Closed by timotheecour** 2021-05-23 18:05 UTC
Labels: Test suite
