### ISSUE TITLE
closure proc isn't captured as result at the end of the expression

### ISSUE THREAD

**Issue by hamidb80** [nim-lang/Nim#19439] opened 2022-01-23 16:58 UTC
### Example
```nim
let a = proc(): int = 1 # works

let b = block: # doesn't works
    proc(): int = 2

let c = # doesn't works
    if true:
      proc(): int = 3
    else:
      proc(): int = 4
```

### Current Output
```
Error: identifier expected, but got '('
```

### Expected Output
compiles successfully

### Workaround
someone in discord channel suggested to put `proc` defs inside parentheses.
```nim
let b = block: # works
    (proc(): int = 2)

let c = # works
    if true:
      (proc(): int = 3)
    else:
      (proc(): int = 4)
```

**info**:
```
Nim Compiler Version 1.6.2 [Windows: amd64]
Compiled at 2021-12-17
```

**Comment by ghost** [comment] 2022-01-23 17:34
Duplicate of https://github.com/nim-lang/Nim/issues/18714

**Closed as completed by ghost** 2022-01-23 17:34 UTC
