### ISSUE TITLE
`ordinal type expected` error where it shouln't be [0.17.2]

### ISSUE THREAD

**Issue by dawkot** [nim-lang/Nim#6865] opened 2017-12-03 14:03 UTC
```nim
block:
    type
        Enum = enum A

        Obj = object
            xs: set[Enum] #works fine

block:
    type
        Obj = object
            xs: set[Enum] #ordinal type expected

        Enum = enum A
```

**Comment by GULPF** [comment] 2017-12-03 14:26
Duplicate of #6259

**Comment by andreaferretti** [comment] 2017-12-04 09:30
Closing as duplicate

**Closed by andreaferretti** 2017-12-04 09:30 UTC
Labels: Type sections
