### ISSUE TITLE
Codegen problem with var parameters

### ISSUE THREAD

**Issue by hohlerde** [nim-lang/Nim#3650] opened 2015-12-16 18:16 UTC
Compiling the following code with "nim c testme" under windows results in a compile error:

```nimrod
type
  BaseRequest* = ref object of RootObj
  BaseResponse* = ref object of RootObj

  Request* = ref object of BaseRequest
  Response* = ref object of BaseResponse

  Handler* = ref object of RootObj

  BaseJob* = ref object of RootObj
    handler: Handler

  Job* = ref object of BaseJob


proc send*(self: Handler, request: var BaseRequest, response: var BaseResponse) =
  discard


proc helper*(self: BaseJob, request: var Request, response: var Response) =
  self.handler.send(request, response)


proc doSomething(self: Job) =
  var
    request = Request()
    response = Response()

  self.helper(request, response)
``` 

Error:
```
Hint: system [Processing]
Hint: testme [Processing]
testme.nim(24, 6) Hint: 'testme.doSomething(self: Job)' is declared but not used [XDeclaredButNotUsed]
CC: testme
CC: stdlib_system
c:\users\x\src\nimcache\testme.c: In function 'helper_105048':
c:\users\x\src\nimcache\testme.c:229:17: error: request for member 'Sup' in something not a structure or union
  LOC1 = &request->Sup;
                 ^
c:\users\x\src\nimcache\testme.c:231:18: error: request for member 'Sup' in something not a structure or union
  LOC2 = &response->Sup;
                  ^
Hint:  [Link]
gcc.exe: error: c:\users\x\src\nimcache\testme.o: No such file or directory
Error: execution of an external program failed: 'gcc.exe   -o c:\users\x\src\testme.exe  c:\users\x\src\nimcache\stdlib_system.o c:\users\x\src\nimcache\testme.o  '
```

Compiling with "nim c -d:release testme" doesn't give any errors, so it seems this is only related to debug builds.

Nim version:
```
Nim Compiler Version 0.12.1 (2015-12-07) [Windows: amd64]
Copyright (c) 2006-2015 by Andreas Rumpf

git hash: ca47256efacf8cad6030c86ce02965cce66e6b37
active boot switches: -d:release
```

**Comment by hohlerde** [comment] 2016-01-06 21:21
It seems this has already been reported before in #3544

**Comment by dom96** [comment] 2016-01-16 15:45
Closing as duplicate of #3544.

**Closed by dom96** 2016-01-16 15:45 UTC
