### ISSUE TITLE
Inconsistent Error Handling in parseHexInt and parseInt

### ISSUE THREAD

**Issue by khchen** [nim-lang/Nim#22222] opened 2023-07-05 02:39 UTC
### Description

It seems that when incorrect input is provided to the parseHexInt function, it fails to raise a ValueError exception. In contrast, the parseInt function within the same module correctly generates a ValueError for similar scenarios.

```nim
import strutils
echo parseHexInt("123456789123456789123456789")
echo parseInt("123456789123456789123456789")
```

### Nim Version

Nim Compiler Version 1.9.5 [Windows: amd64]
Compiled at 2023-07-05
Copyright (c) 2006-2023 by Andreas Rumpf

git hash: 86ff37fab8656f7acd08fc9c3fa237f9e022dbf4
active boot switches: -d:release

### Current Output

```text
The parseHexInt function fails to raise a ValueError exception.
```

### Expected Output

```text
The parseHexInt function should raise a ValueError exception for invalid input, similar to how the parseInt function behaves.
```

### Additional Information

This issue may also exist in the parseOctInt and parseBinInt functions.

**Comment by ringabout** [comment] 2023-07-06 11:03
Duplicate of https://github.com/nim-lang/Nim/issues/17208

**Closed as completed by ringabout** 2023-07-06 11:03 UTC
