### ISSUE TITLE
Docs: proc grouping

### ISSUE THREAD

**Issue by ghost** [nim-lang/Nim#12399] opened 2019-10-10 04:01 UTC
Say you are new to Nim, and you want to make yourself a table. So you write up
this code:

~~~nim
import tables
var m1 = {"sun": 10, "mon": 11}.toTable
~~~

Then you want to know how to do a lookup. So you visit the docs and are
presented with at least 8 options:

1. https://nim-lang.github.io/Nim/tables#[],CountTable[A],A
2. https://nim-lang.github.io/Nim/tables#[],CountTableRef[A],A
3. https://nim-lang.github.io/Nim/tables#[],OrderedTable[A,B],A
4. https://nim-lang.github.io/Nim/tables#[],OrderedTable[A,B],A_2
5. https://nim-lang.github.io/Nim/tables#[],OrderedTableRef[A,B],A
6. https://nim-lang.github.io/Nim/tables#[],Table[A,B],A
7. https://nim-lang.github.io/Nim/tables#[],Table[A,B],A_2
8. https://nim-lang.github.io/Nim/tables#[],TableRef[A,B],A

This just seems overwhelming to me. Its made worse by the fact that *the procs
are not sorted or grouped by proc name*. In addtion the procs signatures are not
listed in the sidebar, so this is what you see:

- `[]`
- `[]`
- `[]`
- `[]`
- `[]`
- `[]`
- `[]`
- `[]`

I think one or more actions should be taken to remedy this:

- sort the procs by proc name
- group the procs by proc name
- remove "duplicates" and list procs with same name under a single header
- list signatures in the sidebar

I am not saying to implement all or even any of these, just some suggestions. I
get that Nim has generics, but in a similar way so does PHP and JavaScript. PHP
deals with this by using the "mixed" type:

https://php.net/function.array

JavaScript uses "element" verbiage:

https://developer.mozilla.org/Web/JavaScript/Reference/Global_Objects/Array#Syntax

I also get this those are interpreted languages, but I am hoping for some
improvement to the current docs, as they seem pretty daunting as a new user.

**Comment by Araq** [comment] 2019-10-10 06:16
Not that I disgree with you but scrolling to the top of module's documentation usually helps too.

**Comment by awr1** [comment] 2019-10-10 09:23
repeat of #9102?

**Comment by narimiran** [comment] 2020-03-10 15:29
> repeat of #9102?

Yes, it is a duplicate of that one. Let's continue there. Closing.

**Closed by narimiran** 2020-03-10 15:29 UTC
Labels: Doc Generation
