### ISSUE TITLE
'Asyncdispatch' library not working on Windows

### ISSUE THREAD

**Issue by dawkot** [nim-lang/Nim#6505] opened 2017-10-14 01:06 UTC
> C:/Users/dawkot/.choosenim/toolchains/mingw32/i686-w64-mingw32/include/ws2tcpip.h:124:8: error: redefinition of 'struct ip_mreq'
>  struct ip_mreq {
>         ^
> In file included from C:/Users/dawkot/.choosenim/toolchains/mingw32/i686-w64-mingw32/include/winsock.h:38:0,
>                  from C:/Users/dawkot/.choosenim/toolchains/mingw32/i686-w64-mingw32/include/windows.h:92,
>                  from C:\Users\dawkot\Documents\NetRPG\nimcache\stdlib_asyncdispatch.c:11:
> C:/Users/dawkot/.choosenim/toolchains/mingw32/i686-w64-mingw32/include/psdk_inc/_ip_mreq1.h:12:8: note: originally defined here
>  struct ip_mreq {

Further along the compiler reports a lot of undefined references in `asyncdispatch' source file from nimache. It happens on both stable and devel.

**Comment by dawkot** [comment] 2017-10-14 02:46
My bad, it doesn't happen on devel.

**Comment by dom96** [comment] 2017-10-14 11:14
So it happens on 0.17.2, but not devel?

**Comment by dawkot** [comment] 2017-10-14 18:30
Yes

**Comment by dom96** [comment] 2017-10-14 22:27
That's weird. Can you give more details? What code are you compiling, what command are you running and the full output please.

**Comment by dawkot** [comment] 2017-10-15 18:55
Actually, it is a combination of asyncdispatch and threadpool, asyncdispatch on it's own imports fine. 
Code: `import asyncdispatch, threadpool`
Command: `nim c test.nim`  or `nim c --threads:on test.nim`
Output:
```
Hint: used config file 'C:\Users\dawkot\.choosenim\toolchains\nim-0.17.2\config\nim.cfg' [Conf]
Hint: system [Processing]
Hint: test [Processing]
Hint: asyncdispatch [Processing]
Hint: os [Processing]
Hint: strutils [Processing]
Hint: parseutils [Processing]
Hint: math [Processing]
Hint: algorithm [Processing]
Hint: times [Processing]
Hint: winlean [Processing]
Hint: dynlib [Processing]
Hint: ospaths [Processing]
Hint: tables [Processing]
Hint: hashes [Processing]
Hint: heapqueue [Processing]
Hint: options [Processing]
Hint: typetraits [Processing]
Hint: asyncstreams [Processing]
Hint: asyncfutures [Processing]
Hint: deques [Processing]
Hint: nativesockets [Processing]
Hint: net [Processing]
Hint: sets [Processing]
Hint: macros [Processing]
Hint: threadpool [Processing]
Hint: cpuinfo [Processing]
Hint: cpuload [Processing]
CC: stdlib_asyncdispatch
In file included from C:\Users\dawkot\Documents\Nim\nimcache\stdlib_asyncdispatch.c:14:0:
C:/Users/dawkot/.choosenim/toolchains/mingw32/i686-w64-mingw32/include/ws2tcpip.h:124:8: error: redefinition of 'struct ip_mreq'
 struct ip_mreq {
        ^
In file included from C:/Users/dawkot/.choosenim/toolchains/mingw32/i686-w64-mingw32/include/winsock.h:38:0,
                 from C:/Users/dawkot/.choosenim/toolchains/mingw32/i686-w64-mingw32/include/windows.h:92,
                 from C:\Users\dawkot\Documents\Nim\nimcache\stdlib_asyncdispatch.c:11:
C:/Users/dawkot/.choosenim/toolchains/mingw32/i686-w64-mingw32/include/psdk_inc/_ip_mreq1.h:12:8: note: originally defined here
 struct ip_mreq {
        ^
Hint:  [Link]
C:\Users\dawkot\Documents\Nim\nimcache\stdlib_asyncdispatch.o:stdlib_asyncdispatch.c:(.text+0xe): undefined reference to `framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw'
C:\Users\dawkot\Documents\Nim\nimcache\stdlib_asyncdispatch.o:stdlib_asyncdispatch.c:(.text+0x18): undefined reference to `framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw'
C:\Users\dawkot\Documents\Nim\nimcache\stdlib_asyncdispatch.o:stdlib_asyncdispatch.c:(.text+0x3f): undefined reference to `framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw'
C:\Users\dawkot\Documents\Nim\nimcache\stdlib_asyncdispatch.o:stdlib_asyncdispatch.c:(.text+0x4c): undefined reference to `framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw'
C:\Users\dawkot\Documents\Nim\nimcache\stdlib_asyncdispatch.o:stdlib_asyncdispatch.c:(.text+0x6a): undefined reference to `framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw'
C:\Users\dawkot\Documents\Nim\nimcache\stdlib_asyncdispatch.o:stdlib_asyncdispatch.c:(.text+0x71): more undefined references to `framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw' follow
C:\Users\dawkot\Documents\Nim\nimcache\stdlib_asyncdispatch.o:stdlib_asyncdispatch.c:(.text+0x2f3): undefined reference to `gch_IcYaEuuWivYAS86vFMTS3Q'
C:\Users\dawkot\Documents\Nim\nimcache\stdlib_asyncdispatch.o:stdlib_asyncdispatch.c:(.text+0xe26): undefined reference to `Dl_130866_'
C:\Users\dawkot\Documents\Nim\nimcache\stdlib_asyncdispatch.o:stdlib_asyncdispatch.c:(.text+0x10c1): undefined reference to `Dl_130866_'
C:\Users\dawkot\Documents\Nim\nimcache\stdlib_asyncdispatch.o:stdlib_asyncdispatch.c:(.text+0x1681): undefined reference to `Dl_130872_'
C:\Users\dawkot\Documents\Nim\nimcache\stdlib_asyncdispatch.o:stdlib_asyncdispatch.c:(.text+0x1a40): undefined reference to `Dl_130932_'
C:\Users\dawkot\Documents\Nim\nimcache\stdlib_asyncdispatch.o:stdlib_asyncdispatch.c:(.text+0x28d8): undefined reference to `Dl_130947_'
C:\Users\dawkot\Documents\Nim\nimcache\stdlib_asyncdispatch.o:stdlib_asyncdispatch.c:(.text+0x31ad): undefined reference to `Dl_130947_'
C:\Users\dawkot\Documents\Nim\nimcache\stdlib_asyncdispatch.o:stdlib_asyncdispatch.c:(.text+0x38df): undefined reference to `Dl_130971_'
C:\Users\dawkot\Documents\Nim\nimcache\stdlib_asyncdispatch.o:stdlib_asyncdispatch.c:(.text+0x3ff6): undefined reference to `Dl_130981_'
C:\Users\dawkot\Documents\Nim\nimcache\stdlib_asyncdispatch.o:stdlib_asyncdispatch.c:(.text+0x45cf): undefined reference to `Dl_130957_'
C:\Users\dawkot\Documents\Nim\nimcache\stdlib_asyncdispatch.o:stdlib_asyncdispatch.c:(.text+0x49ed): undefined reference to `excHandler_rqLlY5bs9atDw2OXYqJEn5g'
C:\Users\dawkot\Documents\Nim\nimcache\stdlib_asyncdispatch.o:stdlib_asyncdispatch.c:(.text+0x49fa): undefined reference to `excHandler_rqLlY5bs9atDw2OXYqJEn5g'
C:\Users\dawkot\Documents\Nim\nimcache\stdlib_asyncdispatch.o:stdlib_asyncdispatch.c:(.text+0x4a04): undefined reference to `excHandler_rqLlY5bs9atDw2OXYqJEn5g'
C:\Users\dawkot\Documents\Nim\nimcache\stdlib_asyncdispatch.o:stdlib_asyncdispatch.c:(.text+0x4a0b): undefined reference to `excHandler_rqLlY5bs9atDw2OXYqJEn5g'
C:\Users\dawkot\Documents\Nim\nimcache\stdlib_asyncdispatch.o:stdlib_asyncdispatch.c:(.text+0x4a18): undefined reference to `framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw'
C:\Users\dawkot\Documents\Nim\nimcache\stdlib_asyncdispatch.o:stdlib_asyncdispatch.c:(.text+0x4a60): undefined reference to `currException_9bVPeDJlYTi9bQApZpfH8wjg'
C:\Users\dawkot\Documents\Nim\nimcache\stdlib_asyncdispatch.o:stdlib_asyncdispatch.c:(.text+0x4a78): undefined reference to `currException_9bVPeDJlYTi9bQApZpfH8wjg'
C:\Users\dawkot\Documents\Nim\nimcache\stdlib_asyncdispatch.o:stdlib_asyncdispatch.c:(.text+0x4a86): undefined reference to `currException_9bVPeDJlYTi9bQApZpfH8wjg'
C:\Users\dawkot\Documents\Nim\nimcache\stdlib_asyncdispatch.o:stdlib_asyncdispatch.c:(.text+0x4ccb): undefined reference to `Dl_130246_'
C:\Users\dawkot\Documents\Nim\nimcache\stdlib_asyncdispatch.o:stdlib_asyncdispatch.c:(.text+0x4e23): undefined reference to `Dl_130202_'
C:\Users\dawkot\Documents\Nim\nimcache\stdlib_asyncdispatch.o:stdlib_asyncdispatch.c:(.text+0x5862): undefined reference to `Dl_130246_'
C:\Users\dawkot\Documents\Nim\nimcache\stdlib_asyncdispatch.o:stdlib_asyncdispatch.c:(.text+0x5c56): undefined reference to `Dl_130202_'
C:\Users\dawkot\Documents\Nim\nimcache\stdlib_asyncdispatch.o:stdlib_asyncdispatch.c:(.text+0x6097): undefined reference to `Dl_131321_'
C:\Users\dawkot\Documents\Nim\nimcache\stdlib_asyncdispatch.o:stdlib_asyncdispatch.c:(.text+0x6175): undefined reference to `Dl_131336_'
C:\Users\dawkot\Documents\Nim\nimcache\stdlib_asyncdispatch.o:stdlib_asyncdispatch.c:(.text+0x6213): undefined reference to `Dl_131422_'
C:\Users\dawkot\Documents\Nim\nimcache\stdlib_asyncdispatch.o:stdlib_asyncdispatch.c:(.text+0x6305): undefined reference to `Dl_131422_'
C:\Users\dawkot\Documents\Nim\nimcache\stdlib_asyncdispatch.o:stdlib_asyncdispatch.c:(.text+0x6391): undefined reference to `Dl_131327_'
C:\Users\dawkot\Documents\Nim\nimcache\stdlib_asyncdispatch.o:stdlib_asyncdispatch.c:(.text+0x6416): undefined reference to `Dl_131422_'
C:\Users\dawkot\Documents\Nim\nimcache\stdlib_asyncdispatch.o:stdlib_asyncdispatch.c:(.text+0x6503): undefined reference to `Dl_131422_'
C:\Users\dawkot\Documents\Nim\nimcache\stdlib_asyncdispatch.o:stdlib_asyncdispatch.c:(.text+0x6634): undefined reference to `Dl_131420_'
C:\Users\dawkot\Documents\Nim\nimcache\stdlib_asyncdispatch.o:stdlib_asyncdispatch.c:(.text+0x66c1): undefined reference to `allocShared0_4cubgSerkjpuLcj5MXjiLw_4'
C:\Users\dawkot\Documents\Nim\nimcache\stdlib_asyncdispatch.o:stdlib_asyncdispatch.c:(.text+0x6876): undefined reference to `Dl_131415_'
C:\Users\dawkot\Documents\Nim\nimcache\stdlib_asyncdispatch.o:stdlib_asyncdispatch.c:(.text+0x6903): undefined reference to `Dl_131422_'
C:\Users\dawkot\Documents\Nim\nimcache\stdlib_asyncdispatch.o:stdlib_asyncdispatch.c:(.text+0x696e): undefined reference to `Dl_131327_'
C:\Users\dawkot\Documents\Nim\nimcache\stdlib_asyncdispatch.o:stdlib_asyncdispatch.c:(.text+0x6a1d): undefined reference to `Dl_131422_'
C:\Users\dawkot\Documents\Nim\nimcache\stdlib_asyncdispatch.o:stdlib_asyncdispatch.c:(.text+0x6b28): undefined reference to `Dl_131336_'
C:\Users\dawkot\Documents\Nim\nimcache\stdlib_asyncdispatch.o:stdlib_asyncdispatch.c:(.text+0x6bc6): undefined reference to `Dl_131422_'
C:\Users\dawkot\Documents\Nim\nimcache\stdlib_asyncdispatch.o:stdlib_asyncdispatch.c:(.text+0x6cb8): undefined reference to `Dl_131422_'
C:\Users\dawkot\Documents\Nim\nimcache\stdlib_asyncdispatch.o:stdlib_asyncdispatch.c:(.text+0x6d44): undefined reference to `Dl_131327_'
C:\Users\dawkot\Documents\Nim\nimcache\stdlib_asyncdispatch.o:stdlib_asyncdispatch.c:(.text+0x6dc9): undefined reference to `Dl_131422_'
C:\Users\dawkot\Documents\Nim\nimcache\stdlib_asyncdispatch.o:stdlib_asyncdispatch.c:(.text+0x6eb6): undefined reference to `Dl_131422_'
C:\Users\dawkot\Documents\Nim\nimcache\stdlib_asyncdispatch.o:stdlib_asyncdispatch.c:(.text+0x6fe7): undefined reference to `Dl_131420_'
C:\Users\dawkot\Documents\Nim\nimcache\stdlib_asyncdispatch.o:stdlib_asyncdispatch.c:(.text+0x7074): undefined reference to `allocShared0_4cubgSerkjpuLcj5MXjiLw_4'
C:\Users\dawkot\Documents\Nim\nimcache\stdlib_asyncdispatch.o:stdlib_asyncdispatch.c:(.text+0x7229): undefined reference to `Dl_131415_'
C:\Users\dawkot\Documents\Nim\nimcache\stdlib_asyncdispatch.o:stdlib_asyncdispatch.c:(.text+0x72b6): undefined reference to `Dl_131422_'
C:\Users\dawkot\Documents\Nim\nimcache\stdlib_asyncdispatch.o:stdlib_asyncdispatch.c:(.text+0x7321): undefined reference to `Dl_131327_'
C:\Users\dawkot\Documents\Nim\nimcache\stdlib_asyncdispatch.o:stdlib_asyncdispatch.c:(.text+0x73d0): undefined reference to `Dl_131422_'
C:\Users\dawkot\Documents\Nim\nimcache\stdlib_asyncdispatch.o:stdlib_asyncdispatch.c:(.text+0x7e01): undefined reference to `Dl_130358_'
C:\Users\dawkot\Documents\Nim\nimcache\stdlib_asyncdispatch.o:stdlib_asyncdispatch.c:(.text+0x801c): undefined reference to `Dl_130358_'
C:\Users\dawkot\Documents\Nim\nimcache\stdlib_asyncdispatch.o:stdlib_asyncdispatch.c:(.text+0x8398): undefined reference to `Dl_130358_'
C:\Users\dawkot\Documents\Nim\nimcache\stdlib_asyncdispatch.o:stdlib_asyncdispatch.c:(.text+0x8b23): undefined reference to `Dl_130358_'
C:\Users\dawkot\Documents\Nim\nimcache\stdlib_asyncdispatch.o:stdlib_asyncdispatch.c:(.text+0x8d4c): undefined reference to `Dl_130358_'
C:/Users/dawkot/.choosenim/toolchains/mingw32/bin/../lib/gcc/i686-w64-mingw32/4.9.1/../../../../i686-w64-mingw32/bin/ld.exe: C:\Users\dawkot\Documents\Nim\nimcache\stdlib_asyncdispatch.o: bad reloc address 0x404 in section `.rdata'
C:/Users/dawkot/.choosenim/toolchains/mingw32/bin/../lib/gcc/i686-w64-mingw32/4.9.1/../../../../i686-w64-mingw32/bin/ld.exe: final link failed: Invalid operation
Error: execution of an external program failed: 'gcc.exe   -o C:\Users\dawkot\Documents\Nim\test.exe  C:\Users\dawkot\Documents\Nim\nimcache\stdlib_system.o C:\Users\dawkot\Documents\Nim\nimcache\test.o C:\Users\dawkot\Documents\Nim\nimcache\stdlib_sharedlist.o C:\Users\dawkot\Documents\Nim\nimcache\stdlib_locks.o C:\Users\dawkot\Documents\Nim\nimcache\stdlib_asyncdispatch.o C:\Users\dawkot\Documents\Nim\nimcache\stdlib_threadpool.o C:\Users\dawkot\Documents\Nim\nimcache\stdlib_os.o C:\Users\dawkot\Documents\Nim\nimcache\stdlib_strutils.o C:\Users\dawkot\Documents\Nim\nimcache\stdlib_parseutils.o C:\Users\dawkot\Documents\Nim\nimcache\stdlib_math.o C:\Users\dawkot\Documents\Nim\nimcache\stdlib_algorithm.o C:\Users\dawkot\Documents\Nim\nimcache\stdlib_times.o C:\Users\dawkot\Documents\Nim\nimcache\stdlib_winlean.o C:\Users\dawkot\Documents\Nim\nimcache\stdlib_dynlib.o C:\Users\dawkot\Documents\Nim\nimcache\stdlib_ospaths.o C:\Users\dawkot\Documents\Nim\nimcache\stdlib_tables.o C:\Users\dawkot\Documents\Nim\nimcache\stdlib_hashes.o C:\Users\dawkot\Documents\Nim\nimcache\stdlib_heapqueue.o C:\Users\dawkot\Documents\Nim\nimcache\stdlib_options.o C:\Users\dawkot\Documents\Nim\nimcache\stdlib_typetraits.o C:\Users\dawkot\Documents\Nim\nimcache\stdlib_asyncstreams.o C:\Users\dawkot\Documents\Nim\nimcache\stdlib_asyncfutures.o C:\Users\dawkot\Documents\Nim\nimcache\stdlib_deques.o C:\Users\dawkot\Documents\Nim\nimcache\stdlib_nativesockets.o C:\Users\dawkot\Documents\Nim\nimcache\stdlib_net.o C:\Users\dawkot\Documents\Nim\nimcache\stdlib_sets.o C:\Users\dawkot\Documents\Nim\nimcache\stdlib_macros.o C:\Users\dawkot\Documents\Nim\nimcache\stdlib_cpuinfo.o C:\Users\dawkot\Documents\Nim\nimcache\stdlib_cpuload.o    '
```

**Comment by cheatfate** [comment] 2017-10-16 08:19
This looks like duplicate of #5939.

**Comment by dom96** [comment] 2017-10-16 08:31
If it's a choosenim bug, then what is choosenim doing wrong?

**Comment by cheatfate** [comment] 2017-10-16 08:41
Without `choosenim` this code compiles fine, i dont know what `choosenim` doing wrong, because i dont use it.
So this is not Nim's bug, and can be closed.

**Comment by Araq** [comment] 2017-10-16 09:40
It could also be a misconfiguration in general. Mismatching Mingw versions?

**Closed** 2019-05-28 23:14 UTC
Labels: Not reproduced, OS/Arch specific
