### ISSUE TITLE
ICE quote do - var not init

### ISSUE THREAD

**Issue by mratsim** [nim-lang/Nim#10624] opened 2019-02-10 17:52 UTC
I forgot quotation in the following quote do snippet and it crashed the compiler (latest devel)

```Nim
import macros

type
  Expr = object of RootObj

  Input[T] = object of Expr
    value: NimNode

  AddExpr[T1, T2] = object of Expr
    lhs: T1
    rhs: T2

proc input[T](value: NimNode): Input[T] =
  Input[T](value: value)

proc `+`[T1, T2](lhs: T1, rhs: T2): AddExpr[T1, T2] =
  result.lhs = lhs
  result.rhs = rhs

proc eval[T](input: Input[T]): NimNode =
  input.value

proc eval(addExpr: AddExpr): NimNode =
  newCall(ident"+", addExpr.lhs.eval, addExpr.rhs.eval)

macro foo(a, b: int): untyped =
  
  let ia = input[int](a)
  let ib = input[int](b)
  
  let c = ia + ib + ia
  echo c.repr
  let val_C = eval(c)

  echo val_C.repr

  result = quote do: val_C # Correct would be `val_C`

let c = foo(1, 3)
```

```
(lhs: (lhs: (value: 1), rhs: (value: 3)), rhs: (value: 1))
`+`(`+`(1, 3), 1)
obj_algebra_ast.nim(37, 12) Error: internal error: expr: var not init val_C_163266
No stack traceback available
To create a stacktrace, rerun compilation with ./koch temp c <file>
```

**Comment by LemonBoy** [comment] 2019-02-10 18:03
Duplicate of #8573, closing.

**Closed by LemonBoy** 2019-02-10 18:03 UTC
Labels: Crash, Macros, quote do
