### ISSUE TITLE
[Regression (?)] -Inf.int throws OverflowError

### ISSUE THREAD

**Issue by mratsim** [nim-lang/Nim#8920] opened 2018-09-08 14:37 UTC
I've noticed the following regression between 0.18.0

```Nim
let x = -Inf.int
echo x

# -9223372036854775808 on 0.18.0
# OverflowError on devel
```

This might be intentional to make conversion more robust though.

This was used to do generic `max` on a sequence of number types in my code, I can use low(int) and low(float32) for my purposes (introduced in #6570).

**Comment by GULPF** [comment] 2018-09-08 15:41
It's an intentional change in #8724. `Inf.int` evaluates to `low(int)`, which means that `-Inf.int` overflows. `Inf.int` shouldn't be allowed IMO, the issue is that Nim never performs range checks for `float` -> `int` conversions (#7179).

**Comment by mratsim** [comment] 2018-09-08 16:40
So the behaviour is:

```Nim
# 0.18.0
echo Inf.int # -9223372036854775808
echo -Inf.int # -9223372036854775808
```

```Nim
# Devel
echo Inf.int # -9223372036854775808
echo -Inf.int # Underflow
```

Looking into pure C, it seems like Inf, -Inf, NaN are all mapped to low(int) when converting float to int which is a rather strange decision. I would expect Inf to be mapped to high(int).

In any case, I think that when bounds checking is on, Nim should throw when converting a float to int if the [float class](https://www.gnu.org/software/libc/manual/html_node/Floating-Point-Classes.html) is NaN or Infinite.

**Comment by GULPF** [comment] 2019-02-10 11:02
Closing this since the original question has been answered and the lack of range checking for float to int conversions are tracked by #7179.

**Closed by GULPF** 2019-02-10 11:02 UTC
