### ISSUE TITLE
Wrong C code generation

### ISSUE THREAD

**Issue by vegansk** [nim-lang/Nim#3353] opened 2015-09-21 06:14 UTC
This example produces code that doesn't compile:
```nimrod
import future, math

{.experimental.}
{.warning[TypelessParam]: off.}

type
  ListNodeKind = enum 
    lnkNil, lnkCons
  List[T] = ref object
    ## List ADT
    case kind: ListNodeKind
    of lnkNil:
      discard
    of lnkCons:
      value: T
      next: List[T] not nil

proc Cons[T](head: T, tail: List[T]): List[T] =
  ## Constructs non empty list
  List[T](kind: lnkCons, value: head, next: tail)

proc Nil[T](): List[T] =
  ## Constructs empty list
  List[T](kind: lnkNil)

type
  OptionKind = enum
    okNone, okSome
  OptionObj[T] = object
    case kind: OptionKind
    of okNone:
      discard
    else:
      value: T
  Option[T] = ref OptionObj[T] not nil

proc Some[T](value: T): Option[T] = Option[T](kind: okSome, value: value)
proc None[T](): Option[T] = Option[T](kind: okNone)

proc isEmpty(o: Option): bool = o.kind == okNone
proc isEmpty(xs: List): bool = xs.kind == lnkNil

proc asList[T](xs: varargs[T]): List[T] =
  proc initListImpl(i: int, xs: openarray[T]): List[T] =
    if i > high(xs):
      Nil[T]()
    else:
      Cons(xs[i], initListImpl(i+1, xs))
  initListImpl(0, xs)

proc foldRight*[T,U](xs: List[T], z: U, f: (T, U) -> U): U =
  case xs.isEmpty
  of true: z
  else: f(xs.value, xs.next.foldRight(z, f))

proc sequence[T](xs: List[Option[T]]): Option[List[T]] =
  proc f(x: Option[T], v: Option[List[T]]): Option[List[T]] =
    if v.isEmpty:
      v
    elif x.isEmpty:
      Some(Nil[T]())
    else: Some(Cons(x.value, v.value))
  xs.foldRight(Some(Nil[T]()), f)

when isMainModule:
  echo: @[Some(1), Some(2), Some(3)].asList.sequence()
```

Error message:
```
/home/vega/work/nim/nimtests/issues/new/nimcache/nimtests_gencodeerr.c: In function ‘foldright_120802’:
/home/vega/work/nim/nimtests/issues/new/nimcache/nimtests_gencodeerr.c:532:26: error: expected identifier before ‘)’ token
   if (!(((2 &(1<<(((*xs).)&7)))!=0))) raiseFieldError(((NimStringDesc*) &TMP290));
                          ^
/home/vega/work/nim/nimtests/issues/new/nimcache/nimtests_gencodeerr.c:533:26: error: expected identifier before ‘)’ token
   if (!(((2 &(1<<(((*xs).)&7)))!=0))) raiseFieldError(((NimStringDesc*) &TMP296));
```

**Comment by Araq** [comment] 2015-09-21 10:06
Duplicate of bug #2637

**Closed by Araq** 2015-09-21 10:06 UTC
