### ISSUE TITLE
unittest require quits program with an exit code of 0

### ISSUE THREAD

**Issue by kdeme** [nim-lang/Nim#14475] opened 2020-05-27 20:39 UTC
uinittest `require` does not always quit the test program with an exit code that indicates an error.
This makes it obviously unusable in automated testing.

### Example
```nim
import unittest

suite "Test":
  test "test require":
    require false
```

### Current Output
```
$ nim c -r req.nim; echo $?
[Suite] Test
    /home/deme/repos/nim-tests/req.nim(5, 12): Check failed: false
0

```

### Expected Output
```
$ nim c -r req.nim; echo $?
[Suite] Test
    /home/deme/repos/nim-tests/req.nim(5, 12): Check failed: false
Error: execution of an external program failed: '... '
1

```

### Additional Information

* Even with an earlier `check` that fails it will still give error code of 0.
* Noticed it does work when require is not in a test block:
```nim
import unittest

suite "Test":
  require false
```
* Was checking the code quickly and noticed that it uses the `abortOnError` internally. Did the same test with `abortOnError=true` and `check` and it has the same problem.

```
$ nim -v
Nim Compiler Version 1.2.0 [Linux: amd64]
Compiled at 2020-04-03
Copyright (c) 2006-2020 by Andreas Rumpf
# and
Nim Compiler Version 1.3.5 [Linux: amd64]
Compiled at 2020-05-27
Copyright (c) 2006-2020 by Andreas Rumpf
```

**Comment by kaushalmodi** [comment] 2020-05-27 20:43
~This is a duplicate of https://github.com/nim-lang/Nim/issues/7913.~ Wow, I've been waiting for a fix for that issue for a while.

**Comment by timotheecour** [comment] 2020-05-28 01:01
I don't see how that's a duplicate, this issue is about exit code being wrong (which is bad), https://github.com/nim-lang/Nim/issues/7913 was about not writing test failures to stderr (which is bad but less bad)

**Comment by kaushalmodi** [comment] 2020-05-28 01:44
>  #7913 was about not writing test failures to stderr (which is bad but less bad)

Hmm, correct

**Closed as completed** 2020-07-14 11:14 UTC
Labels: Standard Library, Medium Priority
