### ISSUE TITLE
The "try except" not work when the "OSError: Too many open files" error occurs!

### ISSUE THREAD

**Issue by mrhdias** [nim-lang/Nim#15925] opened 2020-11-11 18:17 UTC
In certain circumstances the "try except" not work when the "OSError: Too many open files" error occurs!
This issue causes the program to die. when there are many connections.

### Example
```nim
import asynchttpserver, asyncdispatch, asyncnet, posix

var fdLim: RLimit
discard getrlimit(RLIMIT_NOFILE, fdLim)
fdLim.rlim_cur = 5 # fdLim.rlim_max
echo "max-max fd = ", fdLim.rlim_max, " soft = ", fdLim.rlim_cur
discard setrlimit(RLIMIT_NOFILE, fdLim)

proc fileServer(req: Request, staticDir="") {.async.} =
  await req.client.send(
    "HTTP/1.1 200\c\Lcontent-type: text/html\c\Lcontent-length: 3\c\L\c\Lhi\n")

var server = newAsyncHttpServer()
proc cb(req: Request) {.async.} =
  try:
    await req.fileServer("static")
  except:
    echo "Happen a Error!"
    await req.respond(Http200, "Happen a Error!")

waitFor server.serve(Port(8080), cb)
```
To test:
```
terminal1$ ./bug4
terminal2$ curl http://localhost:8080/
terminal1 output:
  max-max fd = 4096 soft = 5
<waiting; then after curl immediate program exit with:>
  bug4.nim(21) bug4
  /usr/lib/nim/lib/pure/asyncdispatch.nim(1934) waitFor
  /usr/lib/nim/lib/pure/asyncdispatch.nim(1626) poll
  /usr/lib/nim/lib/pure/asyncdispatch.nim(1367) runOnce
  /usr/lib/nim/lib/pure/asyncdispatch.nim(208) processPendingCallbacks
  /usr/lib/nim/lib/pure/asyncmacro.nim(22) serveNimAsyncContinue
  /usr/lib/nim/lib/pure/asyncmacro.nim(139) serveIter
  /usr/lib/nim/lib/pure/asyncfutures.nim(372) read
  [[reraised from:
  bug4.nim(21) bug4
  /usr/lib/nim/lib/pure/asyncdispatch.nim(1936) waitFor
  /usr/lib/nim/lib/pure/asyncfutures.nim(372) read
  ]]
  Error: unhandled exception: Too many open files
  Async traceback:
    bug4.nim(21)            bug4
    /usr/lib/nim/lib/pure/asyncdispatch.nim(1934) waitFor
    /usr/lib/nim/lib/pure/asyncdispatch.nim(1626) poll
    /usr/lib/nim/lib/pure/asyncdispatch.nim(1367) runOnce
    /usr/lib/nim/lib/pure/asyncdispatch.nim(208)  processPendingCallbacks
    /usr/lib/nim/lib/pure/asyncmacro.nim(22)      serveNimAsyncContinue
    /usr/lib/nim/lib/pure/asyncmacro.nim(139)     serveIter
    /usr/lib/nim/lib/pure/asyncfutures.nim(372)   read
  Exception message: Too many open files
  Exception type: [OSError]
```

### Additional Information
https://forum.nim-lang.org/t/7064
```
$ nim -v
Nim Compiler Version 1.4.0
```

**Comment by c-blake** [comment] 2020-11-11 19:09
Minor nitpick - "many connections" in your text should actually be "any connection". :-)

**Comment by jackhftang** [comment] 2020-11-12 11:19
FYI, the try/catch works if it is at a correct place. 

```nim
while true:
  try:
    waitFor server.serve(Port(7000), cb)  
  except:
    echo "restarting"
    sleep 1000
```

The problem is that async lib does not know how to self-recover.

**Comment by mrhdias** [comment] 2020-11-12 11:21
The exception is raised in asyncfutures.nim file, but I can't catch it later.

Can someone give me a temporary solution to solve this issue?
```nim
...
proc read*[T](future: Future[T] | FutureVar[T]): T =
  ## Retrieves the value of ``future``. Future must be finished otherwise
  ## this function will fail with a ``ValueError`` exception.
  ##
  ## If the result of the future is an error then that error will be raised.
  {.push hint[ConvFromXtoItselfNotNeeded]: off.}
  let fut = Future[T](future)
  {.pop.}
  if fut.finished:
    if fut.error != nil:
      injectStacktrace(fut)
      echo "Error >>>>>>>: ", $fut.error.msg
      raise fut.error
    when T isnot void:
      result = fut.value
  else:
    # TODO: Make a custom exception type for this?
    raise newException(ValueError, "Future still in progress.")
...
```

**Comment by c-blake** [comment] 2020-11-12 11:52
The @jackhftang approach is better in terms of not crashing in the sense of program termination, but may not be quite enough of a temporary solution since it just freezes.  When I tried it just now with this:
```Nim
import asynchttpserver, asyncdispatch, asyncnet, os, posix

var fdLim: RLimit
discard getrlimit(RLIMIT_NOFILE, fdLim)
fdLim.rlim_cur = 6 # fdLim.rlim_max
echo "max-max fd = ", fdLim.rlim_max, " soft = ", fdLim.rlim_cur
discard setrlimit(RLIMIT_NOFILE, fdLim)

proc fileServer(req: Request, staticDir="") {.async.} =
  await req.client.send(
    "HTTP/1.1 200\c\Lcontent-type: text/html\c\Lcontent-length: 3\c\L\c\Lhi\n")
proc cb(req: Request) {.async.} =
  await req.fileServer("static")
proc main() =
  var server = newAsyncHttpServer()
  while true:
    try:
      waitFor server.serve(Port(8080), cb)
    except:
      echo "Restarting"
      sleep 100
main()
```
With only 1 parallel connection it works fine, but with 2 or more the restart loop never ended and no successful requests went through.  So, *as soon as the condition is hit, from the perspective of clients, the service is frozen/unavailable thereafter*.  The same thing happened if I moved `var server = newAsyncHttpServer()` into the while loop, even in `--gc:arc` mode.

So, AFAICT there remains no way for @mrhdias  to write a reliable server with these APIs.  I haven't really tried to read through the async/http server stuff.  Maybe there is already some clean-up API call to properly shutdown all the sockets that must be issued?  Maybe there needs to be a destructor/that call hooked into it, etc, etc.  I suppose worst case he could maybe loop over all fds > 2, closing them all and re-`execvp` himself.  Gack!

**Comment by mrhdias** [comment] 2020-11-12 12:59
> The @jackhftang approach is better in terms of not crashing in the sense of program termination, but may not be quite enough of a temporary solution since it just freezes. When I tried it just now with this:
> 
> ```nim
> import asynchttpserver, asyncdispatch, asyncnet, os, posix
> 
> var fdLim: RLimit
> discard getrlimit(RLIMIT_NOFILE, fdLim)
> fdLim.rlim_cur = 6 # fdLim.rlim_max
> echo "max-max fd = ", fdLim.rlim_max, " soft = ", fdLim.rlim_cur
> discard setrlimit(RLIMIT_NOFILE, fdLim)
> 
> proc fileServer(req: Request, staticDir="") {.async.} =
>   await req.client.send(
>     "HTTP/1.1 200\c\Lcontent-type: text/html\c\Lcontent-length: 3\c\L\c\Lhi\n")
> proc cb(req: Request) {.async.} =
>   await req.fileServer("static")
> proc main() =
>   var server = newAsyncHttpServer()
>   while true:
>     try:
>       waitFor server.serve(Port(8080), cb)
>     except:
>       echo "Restarting"
>       sleep 100
> main()
> ```
> 
> With only 1 parallel connection it works fine, but with 2 or more the restart loop never ended and no successful requests went through. So, _as soon as the condition is hit, from the perspective of clients, the service is frozen/unavailable thereafter_. The same thing happened if I moved `var server = newAsyncHttpServer()` into the while loop, even in `--gc:arc` mode.
> 
> So, AFAICT there remains no way for @mrhdias to write a reliable server with these APIs. I haven't really tried to read through the async/http server stuff. Maybe there is already some clean-up API call to properly shutdown all the sockets that must be issued? Maybe there needs to be a destructor/that call hooked into it, etc, etc. I suppose worst case he could maybe loop over all fds > 2, closing them all and re-`execvp` himself. Gack!

I have a web server and it works fine. The problem started with an excessive number of static files requests.If there are no requests for files, the server will not crash. More info here: https://forum.nim-lang.org/t/7064

**Comment by dom96** [comment] 2020-11-12 22:30
The behaviour the code exhibits is not surprising, so I don't think this is the right repro for the issue you've described in the forum. Your `fileServer` proc doesn't create any FDs so why would you expect it to throw an exception?

**Comment by c-blake** [comment] 2020-11-13 00:01
Right, right.  As per @jackhftang, the Forum example of @mrhdias was kind of misleading situation.  It *seemed* like the exception from a file open was not being caught, but in fact that (almost surely) was being caught.  The uncaught out-of-fds exception was raised elsewhere and with the try/except in the right place things work ok.  My last example is kind of a lame attempt at recovery from the saturated fds condition, but it cannot really work and that condition is still a problem, at least with the default event loop.

The real "fix" here is probably: After any `accept` generates an `MFILE` `errno`, the event loop must "work down" clients until some new fd is freed up before even trying to `accept` another connection.

It might be even better to wait until "several" open file slots have been freed up in case the work induced by a new `accept` needs a file or three (as per the original forum example).  When pegged near the open files limit, open files are a scarce resource that needs careful management.

There is probably a way to write one's own event loop, but an open file limit is a very common case.  So, some easy/auto facility would be nice for library users.  @mrhdias mentioned, for example, that the Nim Forum is itself susceptible to this problem.

**Closed as completed** 2020-11-13 19:57 UTC
Labels: Showstopper
