### ISSUE TITLE
Top level variables inside loops are not reset in VM

### ISSUE THREAD

**Issue by pgkos** [nim-lang/Nim#13312] opened 2020-02-01 14:38 UTC
Top level variables, declared without an initial value inside loops, are not reset in VM.

### Example
```nim
proc bar =
  for _ in 0 ..< 3:
    var s: string
    s.add("foo")
    echo s

static:
  for _ in 0 ..< 3:
    var s: string
    s.add("foo")
    echo s

  bar()
```

### Current Output
```
foo
foofoo
foofoofoo
foo
foo
foo
```

### Expected Output
```
foo
foo
foo
foo
foo
foo
```

### Additional Information
Replacing `var s: string` with `var s = ""` makes it work correctly.
```
$ nim -v
Nim Compiler Version 1.1.1 [Linux: amd64]
Compiled at 2020-01-31
Copyright (c) 2006-2019 by Andreas Rumpf

active boot switches: -d:release
```

**Comment by disruptek** [comment] 2020-02-01 16:46
Duplicate of #10938.

**Closed as completed** 2022-12-14 12:08 UTC
Labels: VM
