### ISSUE TITLE
`T` in `typedesc[T]` treated as value in templates

### ISSUE THREAD

**Issue by SolitudeSF** [nim-lang/Nim#17240] opened 2021-03-02 21:09 UTC
### Example
```nim
func to(c: int, t: typedesc[float]): t = discard

template converted[I, T](i: seq[I], t: typedesc[T]): seq[T] =
  var result = newSeq[T]()
  result[0] = i[0].to(T)
  result

echo newSeq[int]().converted(float)
```

### Current Output

```
/home/solitude/test.nim(23, 19) Error: type mismatch: got <int, float>
but expected one of:
func to(c: int; t: typedesc[float]): t:type
  first type mismatch at position: 2
  required type for t: typedesc[float]
  but expression 'T' is of type: float

expression: to(newSeq(Natural(0))[0], T)
```

### Expected Output
compiles

### Possible Solution
using typedesc parameter itself like `i[0].to(t)` works.

```
$ nim -v
Nim Compiler Version 1.5.1 [Linux: amd64]
Compiled at 2021-03-01
Copyright (c) 2006-2021 by Andreas Rumpf

git hash: d27c0e2982d19ae2203b40a3227c62ea32d11b72
```

**Comment by timotheecour** [comment] 2021-03-02 21:50
possible duplicate of https://github.com/nim-lang/Nim/issues/13527 (which is more general and explains root cause)

**Closed as completed** 2023-08-25 19:08 UTC
Labels: typedesc[T], Templates
