### ISSUE TITLE
Automatic self insertions not working with generics

### ISSUE THREAD

**Issue by dawkot** [nim-lang/Nim#7177] opened 2018-02-02 16:12 UTC
```nim
type A = object
    x: int

type B = object
    x: int

{.this: self.}

proc prc(self: A or B): int = x #undeclared identifier: 'x'
```

**Comment by zah** [comment] 2018-04-16 14:36
Duplicate of https://github.com/nim-lang/Nim/issues/5053

**Closed** 2018-04-16 14:36 UTC
Labels: Generics, {.this: self.}
