### ISSUE TITLE
Incorrect codegen for VCC compiler

### ISSUE THREAD

**Issue by cheatfate** [nim-lang/Nim#15117] opened 2020-07-29 21:17 UTC
Nim compiler's codegen produces incorrect code for VCC.

### Example
```nim
let a: array[0, byte] = []

proc someProc(a: openarray[byte]): int =
  len(a)

when isMainModule:
  echo someProc(a)
```

### Current Output
```
nim c --cc:vcc emptyarray.nim

Hint: used config file 'C:\Projects\nim-beacon-chain\vendor\nimbus-build-system\vendor\Nim\config\nim.cfg' [Conf]
Hint: used config file 'C:\Projects\nim-beacon-chain\vendor\nimbus-build-system\vendor\Nim\config\config.nims' [Conf]
Hint: system [Processing]
Hint: widestrs [Processing]
Hint: io [Processing]
Hint: emptyarray [Processing]
CC: emptyarray.nim
@memptyarray.nim.c
nimcache\emptyarray_d\@memptyarray.nim.c(62): error C2059: syntax error: '}'
```

### Expected Output
```
0
```

### Additional Information
MinGW compiler works fine with produced c code.

```
Nim Compiler Version 1.2.2 [Windows: amd64]
Compiled at 2020-06-18
Copyright (c) 2006-2020 by Andreas Rumpf

git hash: be34b5abe23e027b71a3a9da67037aac7afea6bc
active boot switches: -d:release
```

**Comment by Chris3606** [comment] 2021-02-17 19:49
I believe this may be a duplicate of https://github.com/nim-lang/Nim/issues/14667; as per my comment there, I'm not certain that this is the only way to produce such code, but it's definitely not valid syntax for MSVC.

**Comment by ringabout** [comment] 2021-03-28 06:29
It works with `nim cpp -r --cc:vcc ttest.nim`.

**Comment by Chris3606** [comment] 2021-03-28 13:53
Apologies if this was a comment intended for the language developers only, however --lib:lib doesn't even compile on my system; so far as I can tell via the [compiler docs](https://nim-lang.org/docs/nimc.html), that flag indicates you're using a custom version of the system library; what custom version are you using?  Is this intended to be a workaround?  Is this just stating it works on the `devel` version?

**Comment by ringabout** [comment] 2021-03-28 14:00
yeah, I mean it works with cpp(vcc) backend.

**Comment by ghost** [comment] 2021-09-27 08:25
Also seems to affect https://github.com/nitely/nim-regex with `--gc:arc` (when compiled with VCC) when you have a const regex, not sure if it's the same issue. 
Works with ARC + CPP backend though.

Code to repro:
```nim
import pkg/regex

const reg = re"(?i-u)[\w-]{24}\.[\w-]{6}\.[\w-]{27}"

proc main = 
   for x in "hello".findAll(reg):
      echo "hi"
main()
```

**Closed as completed** 2022-12-29 23:50 UTC
Labels: Code Generation, OS/Architecture Specific
