### ISSUE TITLE
[minor] with --parallelBuild:1 , no file gets compiled apparently

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/Nim#7502] opened 2018-04-05 00:09 UTC
very odd:
```
nim c --listCmd --parallelBuild:1 -f -o:app -r foo.nim
```
shows no `clang -c ...` line in output (seems buggy)

with any other value of `--parallelBuild:`, it shows files getting compiled (as it should)

**EDIT**
NOTE: the file compiles/runs just fine, and if i add a new--nimcache value it does put all the files there, but just doesn't print anything (CC ... or clang -c ....), hence it's just a minor bug

**Comment by cheatfate** [comment] 2018-04-05 05:53
@timotheecour which operation system you are using?

**Comment by dom96** [comment] 2018-04-05 22:26
Are you sure this isn't just caching? Nim doesn't show the clang line if it doesn't have to recompile the code (because the files didn't change).

**Comment by timotheecour** [comment] 2018-04-06 04:10
yes I'm sure, the `-f` flag is being used. Besides, I also tried with --nimcache:nimcache_new

**Comment by Araq** [comment] 2018-04-06 22:31
Can't reproduce on my OSX.

**Comment by cheatfate** [comment] 2018-04-07 04:41
@timotheecour do you use latest devel version? or you use previous releases of Nim?

**Comment by timotheecour** [comment] 2018-04-07 04:53
I use `brew install nim`
nim --version
Nim Compiler Version 0.18.0 [MacOSX: amd64]
Copyright (c) 2006-2018 by Andreas Rumpf

active boot switches: -d:release -d:useLinenoise

**Comment by cheatfate** [comment] 2018-04-07 14:38
@timotheecour please try latest devel version.

**Comment by timotheecour** [comment] 2018-04-07 20:07
after `brew reinstall --HEAD nim`
```
nim --version
Nim Compiler Version 0.18.1 [MacOSX: amd64]
Copyright (c) 2006-2018 by Andreas Rumpf

git hash: 992300b30057e2b3b489b90fb0e7011607e3e8cf
active boot switches: -d:release -d:useLinenoise
```

same issue.

NOTE: the file compiles/runs just fine, and if i add  a new`--nimcache` value it does put all the files there, but just doesn't print anything (`CC ...` or `clang -c ....`), hence it's just a minor bug

**Comment by narimiran** [comment] 2019-02-26 11:18
> NOTE: the file **compiles/runs just fine**, and if i add a new `--nimcache` value it does put all the files there, but just doesn't print anything (`CC ...` or `clang -c ....`), hence it's just a minor bug

Closing.

**Closed by narimiran** 2019-02-26 11:18 UTC
Labels: OS/Arch specific

**Comment by nc-x** [comment] 2019-02-26 13:00
@narimiran
I can agree with closing this issue because nobody can reproduce it, but the current reason does not justify closing it. Because a minor bug is a bug nonetheless.
