### ISSUE TITLE
for var in <empty_array> throws getTypeDescAux(tyEmpty)

### ISSUE THREAD

**Issue by donpdonp** [nim-lang/Nim#12830] opened 2019-12-06 21:17 UTC
a simple for loop causes an internal error.

### Example
https://play.nim-lang.org/#ix=23IO  

```nim
  for b in []:
    echo "A"
```

### Current Output
```
Error: internal error: getTypeDescAux(tyEmpty)
No stack traceback available
```

### Expected Output
```
```

**Comment by Yardanico** [comment] 2019-12-07 14:10
<details><summary>Output of ./koch temp c on latest devel</summary><p>
```
Error: internal error: getTypeDescAux(tyEmpty)
Traceback (most recent call last)
/home/dian/.nim/compiler/nim.nim(106) nim
/home/dian/.nim/compiler/nim.nim(83) handleCmdLine
/home/dian/.nim/compiler/cmdlinehelper.nim(98) loadConfigsAndRunMainCommand
/home/dian/.nim/compiler/main.nim(188) mainCommand
/home/dian/.nim/compiler/main.nim(92) commandCompileToC
/home/dian/.nim/compiler/modules.nim(144) compileProject
/home/dian/.nim/compiler/modules.nim(85) compileModule
/home/dian/.nim/compiler/passes.nim(210) processModule
/home/dian/.nim/compiler/passes.nim(86) processTopLevelStmt
/home/dian/.nim/compiler/cgen.nim(1880) myProcess
/home/dian/.nim/compiler/ccgstmts.nim(1275) genStmts
/home/dian/.nim/compiler/ccgexprs.nim(2616) expr
/home/dian/.nim/compiler/ccgstmts.nim(624) genBlock
/home/dian/.nim/compiler/ccgexprs.nim(2618) expr
/home/dian/.nim/compiler/ccgexprs.nim(2392) genStmtList
/home/dian/.nim/compiler/ccgstmts.nim(1275) genStmts
/home/dian/.nim/compiler/ccgexprs.nim(2640) expr
/home/dian/.nim/compiler/ccgstmts.nim(402) genVarStmt
/home/dian/.nim/compiler/ccgstmts.nim(384) genSingleVar
/home/dian/.nim/compiler/ccgstmts.nim(301) genSingleVar
/home/dian/.nim/compiler/cgen.nim(536) assignGlobalVar
/home/dian/.nim/compiler/ccgtypes.nim(901) getTypeDesc
/home/dian/.nim/compiler/ccgtypes.nim(894) getTypeDescAux
/home/dian/.nim/compiler/msgs.nim(565) internalError
/home/dian/.nim/compiler/msgs.nim(443) rawMessage
/home/dian/.nim/compiler/msgs.nim(440) rawMessage
/home/dian/.nim/compiler/msgs.nim(356) handleError
/home/dian/.nim/compiler/msgs.nim(346) quit
FAILURE
```
</p></details>

**Comment by ghost** [comment] 2020-05-18 21:19
@narimiran can you close this issue? It's a duplicate of https://github.com/nim-lang/Nim/issues/11684

**Closed** 2020-05-18 21:23 UTC
