### ISSUE TITLE
Static block in a `proc` evaluated even if it is not called ...

### ISSUE THREAD

**Issue by deech** [nim-lang/Nim#11873] opened 2019-08-02 13:04 UTC
Currently if you compile:
```nim
proc f():string = 
  static:
     echo "compile time message!"
  "hello world"
```
it outputs "compile time message!" at compile time. I would expect the static block to only be evaluated at each call-site and not when compiler is interpreting the `proc`.

**Comment by andreaferretti** [comment] 2019-08-05 09:14
Well, not really. Static blocks get executed while the Nim compiler, well, compiles your code. So when it compiles the body of `f` , the static block is executed. I don't see anything unexpected here.

Doing otherwise would require a strange mix of compile time and runtime logic, where the compiler registers the existence of a static block when compiling `f`, and then it executes it when it compiles calls to `f`, which is potentially many, many times for commonly used functions

**Comment by deech** [comment] 2019-08-05 12:11
This is already the case when the static block depends on something in scope, it would be more consistent if it ran the same way all the time. 

```
proc f(s:static[string]):string = 
  static:
    echo s
  s
```

The problem is that VM code can have side effects and it is currently quite difficult to reason about when they get evaluated.

**Comment by mratsim** [comment] 2019-08-05 12:42
AFAIK the VM will print the message at each proc instantiation.

A normal proc is always evaluated for semchecking, compilation and then dead-code elimination while a template or a generic/static proc will be instantiated once per call/generic type/static value or never if they are not called (potentially hiding bugs if they are never called with the bug-triggering type/value).

I.e. it's another symptom of the different treatments and limitations of normal proc vs templates/static/generics

**Comment by andreaferretti** [comment] 2019-08-05 12:58
Yes, usage of static parameters turns your `f` into a generic function - this is just registered as AST, but actual compilation will only happen when generic parameters are turned into concrete ones

**Comment by krux02** [comment] 2019-08-06 18:47
I am sorry, this is not a bug, this is the intended and also expected behavior. Stack blocks are evaluated at compile time. Procedures are not compile again and again each time you write a call to them.

**Closed by krux02** 2019-08-06 18:47 UTC
Labels: VM
