### ISSUE TITLE
Passing anonymous function containing anonymous function to algorithm.sorted produces invalid C

### ISSUE THREAD

**Issue by Kaynato** [nim-lang/Nim#12869] opened 2019-12-10 07:30 UTC
Passing in a potentially ambiguous `cmp[T]` as an anonymous function to a proc that takes a proc, via another anonymous proc, instead of succeeding or failing, produces malformed C code.

Either this should be disallowed or it should be equivalent to the two forms in "Possible Solutions" below.

### Example
```nim
import sugar
from algorithm import sorted, SortOrder

let a = 5

proc sorted*[T](a: openArray[T], key: proc(v: T): int, order = SortOrder.Ascending): seq[T] =
  sorted(a, (x, y) => key(x) < key(y), order)

echo sorted(@[9, 1, 8, 2, 6, 4, 5, 0], (x) => (a - x).abs)
```

Snippet and equivalent forms: https://play.nim-lang.org/#ix=241U

### Current Output
```
/usercode/nimcache/@min.nim.c: In function 'sorted__Xw9ag7uqap9bdJ9cXn9ankU0nw':
/usercode/nimcache/@min.nim.c:395:53: error: incompatible type for argument 3 of 'sorted__5O3VuOf8ACYKXSiV4GiiXA'
  result = sorted__5O3VuOf8ACYKXSiV4GiiXA(a, aLen_0, T1_, order);
                                                     ^~~
In file included from /usercode/nimcache/@min.nim.c:9:0:
/usercode/nimcache/@min.nim.c:233:62: note: expected 'tyProc__fDD7zVPPl59bNBu4ChTEQeQ {aka struct <anonymous>}' but argument is of type 'tyProc__RL6pyyy4SUEQoZYtvZb8QQ {aka struct <anonymous>}'
 N_LIB_PRIVATE N_NIMCALL(tySequence__qwqHTkRvwhrRyENtudHQ7g*, sorted__5O3VuOf8ACYKXSiV4GiiXA)(NI* a, NI aLen_0, tyProc__fDD7zVPPl59bNBu4ChTEQeQ cmp, tyEnum_SortOrder__8iBc6wlNqBa9cju9cUAhUAxA order);
                                                              ^
/playground/nim/lib/nimbase.h:245:44: note: in definition of macro 'N_NIMCALL'
 #  define N_NIMCALL(rettype, name) rettype name /* no modifier */
                                            ^~~~
Error: execution of an external program failed: 'gcc -c  -w  -I/playground/nim/lib -I/usercode -o /usercode/nimcache/@min.nim.c.o /usercode/nimcache/@min.nim.c'
```

### Expected Output
```
@[0, 9, 1, 8, 2, 6, 4, 5]
```

### Possible Solution

The following should be intended equivalent forms:

* Properly defining the cmp function instead of using a potentially ambiguous anonymous function with sugar:
```nim
proc sorted*[T, V](a: openArray[T], key: proc(v: T): V, order = SortOrder.Ascending): seq[T] =
  proc cmp2(a, b: T): int =
    cmp(key(b), key(a))
  sorted(a, cmp2, order)

echo sorted(@[9, 1, 8, 2, 6, 4, 5, 0], (x) => (a - x).abs)
```

* Baseline equivalent form:
```nim
echo sorted(@[9, 1, 8, 2, 6, 4, 5, 0], (x, y) => (a - x).abs < (a - y).abs)
```

### Additional Information

* Observed while trying to write a shortcut for python-like "key-based" `sorted`.

```
$ nim -v
Nim Compiler Version 1.0.4 [Windows: amd64]
Compiled at 2019-11-27
Copyright (c) 2006-2019 by Andreas Rumpf

git hash: c8998c498f5e2a0874846eb31309e1d1630faca6
active boot switches: -d:release
```

Also occurs on:
```
Nim Compiler Version 1.1.1 [Windows: amd64]
Compiled at 2019-12-04
Copyright (c) 2006-2019 by Andreas Rumpf

active boot switches: -d:release
```

**Comment by foldl** [comment] 2019-12-11 11:57
Some observations:

1. The type of `cmp` for `sorted` is `proc(x, y: T): int {.closure.}`, while the expected type of the
lambda is `proc (x, y: T): bool`.

2. If change the lambda to below, we can get the expected result:

```nim
proc sorted*[T](a: openArray[T], key: proc(v: T): int, order = SortOrder.Ascending): seq[T] =
  sorted(a, (x, y) => - key(x) + key(y), order)
```

3. If we give a hint that the type of `x` & `y` in the lambda is `T`, then we can the expected compiling
error report stating type mismatch.

Conclusion, it seems there is something wrong when resolving `auto` type of lambda.

**Comment by bung87** [comment] 2022-12-11 17:05
should close https://play.nim-lang.org/#ix=4ikF

**Comment by ringabout** [comment] 2022-12-11 17:17
The original example doesn't seem to work.

**Comment by bung87** [comment] 2022-12-11 17:18
`key(x) < key(y)` is wrong, it should be `key(y) - key(x)` so the problem is cgen error need to be CT error.

**Closed** 2022-12-12 05:26 UTC
Labels: Code Generation
