### ISSUE TITLE
`varargs[typed]` Doesn't accept `nnkClosedSymChoice` node but `typed` does

### ISSUE THREAD

**Issue by ynfle** [nim-lang/Nim#19446] opened 2022-01-24 17:27 UTC
`varargs[typed]` as macro parameter type doesn't accept a `NimNode` of kind `nnkClosedSymChoice` but just a parameter type of `typed` does.

### Example
```nim
import macros

macro typedVarargs(x: varargs[typed]) =
  echo x[0].kind
  
macro typedSingle(x: typed) =
  echo x.kind
  
typedSingle(len)
typedVarargs(len)
```

### Current Output
```
nnkSym
/usercode/in.nim(10, 13) Error: type mismatch: got <proc (x: HSlice[len.U, len.V]): int{.inline, noSideEffect.} | proc (x: seq[T]): int{.noSideEffect.} | proc (x: string): int{.noSideEffect, gcsafe, locks: 0.} | proc (x: TOpenArray: openArray or varargs): int{.noSideEffect.} | proc (x: set[T]): int{.noSideEffect.} | proc (x: typedesc[array] or array): int{.noSideEffect.} | proc (x: cstring): int{.noSideEffect, gcsafe, locks: 0.} | proc (w: WideCString): int{.noSideEffect, gcsafe, locks: 0.} | proc (n: NimNode): int{.noSideEffect.}>
but expected one of:
macro typedVarargs(x: varargs[typed])
  first type mismatch at position: 1
  required type for x: varargs[typed]
  but expression 'len' is of type: None

expression: typedVarargs(len)
```

### Expected Output
```
nnkSym
nnkClosedSymChoice
```

### Additional Information
Seems to exist at least back from 1.0.0
Testing on nightly

```console
$ nim -v
Nim Compiler Version 1.6.2 [MacOSX: amd64]
Compiled at 2021-12-20
Copyright (c) 2006-2021 by Andreas Rumpf

active boot switches: -d:release
```

**Comment by Vindaar** [comment] 2022-01-24 17:44
Related and/or duplicate of https://github.com/nim-lang/Nim/issues/13913 ?

**Comment by ynfle** [comment] 2022-01-24 17:58
> Related and/or duplicate of #13913 ?

It is, but the issue there isn't the multiple procs, it's that one of them is overloaded.

Any idea where to look to fix this?

**Comment by beef331** [comment] 2022-01-24 19:40
Where you need to look is `sigmatch.typerel` https://github.com/nim-lang/Nim/blob/7bdfeb78190ca9ff6a0cf702c6ec202f379bff2f/compiler/sigmatch.nim#L960

**Comment by ynfle** [comment] 2022-01-25 13:07
So it seems that this is the issue 
https://github.com/nim-lang/Nim/blob/7bdfeb78190ca9ff6a0cf702c6ec202f379bff2f/compiler/sigmatch.nim#L2208-L2211

When it isn't overloaded symbol, then it delegates to `paramTypesMatchAux` which if it doesn't get a match (`r = isNone`), `userConvMatch(c, m, f, a, arg) == nil`, `f.kind == tyVarargs` & `f.n == nil`, it tries to find a match with `base(f)` which has `kind == tyTyped` which matches `nkClosedSymChoice`.

If, however, the symbol is overloaded, it tries every one of the symbols, but doesn't try `base(f)` if it's varargs.

Not sure if this is the intended behaviour or what the proper way to fix it if it isn't the intended behaviour.

I could technically just add and else statement here https://github.com/nim-lang/Nim/blob/7bdfeb78190ca9ff6a0cf702c6ec202f379bff2f/compiler/sigmatch.nim#L2236-L2250

with something like
```nim
elif f.kind == tyVarargs and f.n == nil and userConvMatch(c, m, f, a, arg) == nil:
```
then something like this https://github.com/nim-lang/Nim/blob/7bdfeb78190ca9ff6a0cf702c6ec202f379bff2f/compiler/sigmatch.nim#L2097

I don't know the possibles cases of the compiler well enough to make an informed change

Any guidance (or help) would be much appreciated

**Comment by ynfle** [comment] 2022-01-26 03:39
I guess my questions are:
- primarily, why doesn't `paramTypesMatch` look at the subtype when it's varargs (and maybe the other necessary conditions) https://github.com/nim-lang/Nim/blob/7bdfeb78190ca9ff6a0cf702c6ec202f379bff2f/compiler/sigmatch.nim#L2177-L2182 but `paramTypesMatchAux` does?
- when is `f.n` `nil`? https://github.com/nim-lang/Nim/blob/7bdfeb78190ca9ff6a0cf702c6ec202f379bff2f/compiler/sigmatch.nim#L2178
- What are `userConvMatch` & `localConvMatch` and do I need to care about them in this case?
- When will the `tfVarargs in a.flags` be true? https://github.com/nim-lang/Nim/blob/7bdfeb78190ca9ff6a0cf702c6ec202f379bff2f/compiler/sigmatch.nim#L1214

**Comment by beef331** [comment] 2022-01-26 03:42
> When will the tfVarargs in a.flags be true?

When using the `{.varargs.}` pragma for C interop.

The rest I do not know.

**Comment by ynfle** [comment] 2022-01-26 03:45
> > When will the tfVarargs in a.flags be true?
> 
> When using the `{.varargs.}` pragma for C interop.
> 
> The rest I do not know.

Makes sense

Although there there is this https://github.com/nim-lang/Nim/blob/7bdfeb78190ca9ff6a0cf702c6ec202f379bff2f/compiler/sigmatch.nim#L2513

**Comment by ynfle** [comment] 2022-01-27 02:57
More questions:
- What do `x`, `y`, & `z` represent? https://github.com/nim-lang/Nim/blob/7bdfeb78190ca9ff6a0cf702c6ec202f379bff2f/compiler/sigmatch.nim#L2219-L2221
  - it seems like:
    - `z` is the total matches for the current overloaded candidate
    - `x` is if the best match
- Why is `result` set to `nil` here? https://github.com/nim-lang/Nim/blob/7bdfeb78190ca9ff6a0cf702c6ec202f379bff2f/compiler/sigmatch.nim#L2261
  - It probably depends on what `y` means
  - There for sure is a match, so why is nothing returned?

**Comment by beef331** [comment] 2022-01-27 03:13
Perhaps you should ask these questions inside the internals realtime chat

**Comment by ynfle** [comment] 2022-01-31 03:37
This isn't an issue with `varargs[typed]` but rather `varargs[T]` where the param is an overloaded symbol.
```nim
import sequtils

echo @[1, 3, 4, 5].map(len)
```

**Comment by ynfle** [comment] 2022-01-31 03:51
Not sure how to proceed with this one. Would resolving as a `nnkClosedSymChoice` be helpful?

**Comment by ynfle** [comment] 2022-01-31 04:02
Never mind, it seems like `SymChoice`s aren't intended to be passed in to procs in this way (I think)

**Comment by metagn** [comment] 2024-09-26 01:12
Works now maybe because of opt-in symchoices?

**Closed as completed** 2024-12-09 07:11 UTC
Labels: works_but_needs_test_case
