### ISSUE TITLE
async await: defer breaks, but try/finally works

### ISSUE THREAD

**Issue by niv** [nim-lang/Nim#4116] opened 2016-04-26 12:46 UTC
``` nim
import asyncdispatch

proc inner() {.async.} =
  discard

proc main() {.async.} =
  defer:
    echo "defer"

  await inner()

  try:
    await inner()
  finally:
    echo "finally"

waitFor main()
```

This prints "defer" three times (two times if I leave out the middle await), then coughs up a read-from-nil.

On 0.13.0. #3877 might be related?

**Comment by dom96** [comment] 2016-04-26 15:11
There are many issues which are related. We may need to end up simply refusing compilation if ``defer`` is present, and maybe even refuse if there is an ``await`` inside a ``try``.

**Comment by dom96** [comment] 2016-04-26 15:11
It would be much easier if Nim would support `yield` inside a ``try``

**Comment by dom96** [comment] 2018-01-17 20:39
Closing as duplicate of #3877.

**Closed by dom96** 2018-01-17 20:39 UTC
Labels: Async
