### ISSUE TITLE
Change signature of `reversed`

### ISSUE THREAD

**Issue by konsumlamm** [nim-lang/Nim#16569] opened 2021-01-03 11:13 UTC
The [`reversed`](https://nim-lang.github.io/Nim/algorithm.html#reversed%2CopenArray%5BT%5D%2CNatural%2Cint) proc (from the `algorithm` module) has the following signature:
```nim
proc reversed[T](a: openArray[T]; first: Natural; last: int): seq[T]
```
Notably, the type of `last` is `int` and not `Natural`, like in the [`reverse`](https://nim-lang.github.io/Nim/algorithm.html#reverse%2CopenArray%5BT%5D%2CNatural%2CNatural) proc.

Would it be ok to change the signature for consistency? Note that changing change the type to `Natural` requires changing the implementation of the other [`reversed`](https://nim-lang.github.io/Nim/algorithm.html#reversed%2CopenArray%5BT%5D) proc to:
```nim

proc reversed*[T](a: openArray[T]): seq[T] =
  reversed(a, 0, max(0, a.high))
```

**Comment by timotheecour** [comment] 2021-01-03 21:13
maybe this should be the other way around, and `reverse` proc should be changed to use `int`:

```nim
import algorithm
proc main(a: var string)=
  echo reversed(a, a.low, a.high) # before your suggestion: works; after: RangeDefect
  # a.reverse(a.low, a.high) # RangeDefect => preexisting bug!
var a = "foo"
main(a)

var b = ""
main(b)
```

Also, I don't like signatures using `first, last`, IMO we should use `Slice[int]`, which is harder to misuse, self documenting, etc

**Comment by awr1** [comment] 2021-01-04 00:00
> IMO we should use `Slice[int]`, which is harder to misuse, self documenting, etc

Agreed. Makes it clear that the range is inclusive. In favor of deprecating the original and adding in a new proc that uses `Slice[int]`

**Comment by konsumlamm** [comment] 2021-01-04 00:06
> IMO we should use Slice[int], which is harder to misuse, self documenting, etc

If we do that, we should also change [`fill`](https://nim-lang.github.io/Nim/algorithm.html#fill%2CopenArray%5BT%5D%2CNatural%2CNatural%2CT) and [`reverse`](https://nim-lang.github.io/Nim/algorithm.html#reverse%2CopenArray%5BT%5D%2CNatural%2CNatural) to use slices.

**Comment by timotheecour** [comment] 2021-01-04 00:35
and plenty of other procs in stdlib... I'm in favor of deprecating all similar procs in stdlib (with first + last) to use Slice; if there's some pushback then at least making it a soft-deprecation (ie write deprecated: use ... in doc comment instead of pragma `{.deprecated.}`).

This could be tracked by a new issue to track all such instances (can serve as an RFC)

**Comment by Araq** [comment] 2021-01-04 09:49
There is such a pushback from me. When we break code, we should break it for significant benefits, not for micro-optimizations. All the successful systems we use -- C, C++, Unix, Windows, Java, .NET, X11 are used over the "perfect" designs (Oberon, Plan-9, Modula 2, Modula 3, Haiku) because they care more about compatibility than about perfection. You cannot build quality software on top of a constantly moving target.

Python 3 uses ``isupper`` rather than ``is_upper`` because of compatibility reasons. Compatibility is simply much more valuable than "let's make all code written by multiple authors over a decade (!) consistent, who cares what it breaks".

**Comment by timotheecour** [comment] 2021-01-04 10:07
> When we break code

* `{.deprecated.}` doesn't break any code, it can be marked as deprecated forever
* and furthermore i also suggested soft-deprecation as an alternative, which would not even give a warning, just a doc comment mentioning "deprecated: use xxx instead" so users know what's the recommended way.

The only problem with `{.deprecated.}` right now IMO is that it's an all-or-nothing warning. With https://github.com/timotheecour/Nim/issues/403, we'd be able to error/warn/ignore a specific deprecation message instead of all deprecations, which doesn't scale well.

So until something like https://github.com/timotheecour/Nim/issues/403 is implemented, IMO in this case we should at least give a soft-deprecation.

> All the successful systems we use -- C, C++, Unix, Windows, Java, .NET, X11 are used over the "perfect" designs (Oberon, Plan-9, Modula 2, Modula 3, Haiku) because they care more about compatibility than about perfection.

I'm not arguing against backward compatiblity here. All the languages that I've used (including C, C++, D, python etc...) as well as OS and software make heavy use of deprecations, which doesn't mean they break code; but they clearly indicate some API is not favored and should be replaced by some new API / usage pattern.

eg see those recent deprecations http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2020/p2139r2.html
> Reviewing Deprecated Facilities of C++20 for C++23

**Comment by Araq** [comment] 2021-01-04 10:46
If you soft-deprecate things then people have to read code written 1 month ago where the non-slice versions still were a thing so effectively you have two ways to write the same code. Also, this is not the deprecation method that we currently use, currently we do remove deprecated procs occasionally.

Also, the "soft"-deprecated code keeps working so there is a strong **objective, technical benefit** to use the "outdated" proc, your package can then support older Nim versions.

**Comment by awr1** [comment] 2021-01-04 19:42
My impression is that there is not much of an existing incentive *at the moment* for library/application/etc. authors to support older versions of Nim, especially considering some of the rapid language changes it has experienced, e.g. ARC, view types, sequences and strings no longer requiring nil, experimental features getting deprecated etc. Compatibility matters more when you have a large enough community that will drag its feet about breaking changes. Don't get me wrong, I am sure people have given mild complaints before when Nim changes a certain way and thus they have had to fix their old code accordingly; but really I have not seen people adamant that certain old code must not break (beyond that of regressions), especially when the changes are not too significant.

Nim is still relatively small in terms of userbase which of course has a lot of disadvantages but it also has a few advantages - it's a lot easier to get people to follow along with more 'idiomatic practices' when changes become necessary - you run into fewer people willing to resist these kinds of changes. But I also understand that Nim's relatively rapid pace of change might be unappealing to those looking for a language with a greater degree of stability. I have heard variously that breaking API changes in Rust's standard library, for instance, have sometimes been met with resentment to the extent that people have regarded that as a point against the language as a whole.

You probably have a much more comprehensive perspective on this than I do based on feedback you get from the Nim userbase. In any case this is a discussion that extends well beyond merely changing some function calls to look prettier.

Soft deprecation at the very least also adds compiler warnings that persuade people to fix their code. You could even introduce a new pragma, `{.softDeprecated.}` that aliases to `{.deprecated.}`, if at least for the purpose of making the intent a bit more clear.

**Comment by Araq** [comment] 2021-01-07 10:28
Nim is 14 years old, for 14 years we were doing these micro-optimizations. We released version 1 much too late, but the hope/promise was it would stop these disruptive micro-optimizations. I see no reason to change the plan, since version 1 we're doing much better, all things considered. I will continue to fight against micro-optimizations. "Been there, done that, got the scar."

**Comment by konsumlamm** [comment] 2021-01-14 13:21
If not changing the procs to use slices, what about at least making the types consistent, i.e. using all `Natural` or `int` (as originally suggested)?

**Comment by timotheecour** [comment] 2021-01-16 00:59
deprecate or not deprecate, we can at least add overloads that take a `Slice` (not HSlice, that's just bloat)

**Comment by konsumlamm** [comment] 2021-05-19 15:10
To get this issue closed once and for all: My original question was just about changing the type from `int` to `Natural` (which turned into a discussion about using `Slice[int]`, which was not the intention of this issue). Original question (copied from above):

> The [`reversed`](https://nim-lang.github.io/Nim/algorithm.html#reversed%2CopenArray%5BT%5D%2CNatural%2Cint) proc (from the `algorithm` module) has the following signature:
> ```nim
> proc reversed[T](a: openArray[T]; first: Natural; last: int): seq[T]
> ```
> Notably, the type of `last` is `int` and not `Natural`, like in the [`reverse`](https://nim-lang.github.io/Nim/algorithm.html#reverse%2CopenArray%5BT%5D%2CNatural%2CNatural) proc.
>
> Would it be ok to change the signature for consistency? Note that changing change the type to `Natural` requires changing the implementation of the other [`reversed`](https://nim-lang.github.io/Nim/algorithm.html#reversed%2CopenArray%5BT%5D) proc to:
> ```nim
> proc reversed*[T](a: openArray[T]): seq[T] =
>   reversed(a, 0, max(0, a.high))
> ```

That is all i wanna know for this issue.

> deprecate or not deprecate, we can at least add overloads that take a `Slice` (not HSlice, that's just bloat)

@timotheecour I suggest you open a new issue for this (if you're still interested and haven't already).

**Comment by timotheecour** [comment] 2021-05-19 17:17
> My original question was just about changing the type from int to Natural

that's a bad idea, it would crash for empty openArrays, eg `reversed(seq[int].default)`.

Instead, I'm closing this by deprecating `reversed(a, fisrt, last)` altogether, see https://github.com/nim-lang/Nim/pull/18047

**Closed as completed** 2021-05-30 20:37 UTC
