### ISSUE TITLE
Gcc cross compiler doesn't know '-mno-ms-bitfields'

### ISSUE THREAD

**Issue by jputcu** [nim-lang/Nim#13870] opened 2020-04-04 16:40 UTC
I'm trying to cross compile some very simple code using `nim` but the compiler argument `-mno-ms-bitfields` is passed which is not recognised.
The other compiler options are passed using `nim.cfg`.

### Current Output
```
avr-gcc.exe: error: unrecognized command line option '-mno-ms-bitfields'
        ... avr-gcc.exe: error: unrecognized command line option '-mno-ms-bitfields'
        ... Error: execution of an external compiler program 'avr-gcc.exe -c  -w -mno-ms-bitfields -Os -DF_CPU=16000000UL -mmcu=atmega328p -mrelax -ffunction-sections -fdata-sections -Wno-fatal-errors  -IC:\Users\joris\.choosenim\toolchains\nim-1.2.0\lib -IC:\Users\joris\Workspace\3rdparty\nim_for_embedded\src -o C:\Users\joris\nimcache\nim_for_embedded_r\led.c.o C:\Users\joris\Workspace\3rdparty\nim_for_embedded\src\led.c' failed with exit code: 1
        ... avr-gcc.exe: error: unrecognized command line option '-mno-ms-bitfields'
```

### Additional Information

* Windows 10
* Cross compiler toolchain: https://blog.zakkemble.net/avr-gcc-builds/

```
$ nim -v
Nim Compiler Version 1.2.0 [Windows: amd64]
Compiled at 2020-04-03
Copyright (c) 2006-2020 by Andreas Rumpf

git hash: 7e83adff84be5d0c401a213eccb61e321a3fb1ff
active boot switches: -d:release
```

**Comment by jputcu** [comment] 2020-04-05 08:13
It appears the compilation flag is gotten from nim's own `nim-1.2.0/config/nim.cfg`:
```
gcc.options.always = "-w -mno-ms-bitfields"
```
The option also appears to be related to MSVC behaviour:
https://stackoverflow.com/questions/11283164/a-bug-in-gcc-implementation-of-bit-fields.

So probably not an issue when compiling for AVR

**Comment by alaviss** [comment] 2020-04-05 14:23
How are you setting up Nim for the cross compiling environment? It should be simple to override the default flags as those options don't stack. Just do

    <arch>.<os>.gcc.options.always = "<your flags here or you can leave it empty>"

**Comment by jputcu** [comment] 2020-04-05 16:23
I'm using a `nim.cfg` in de project directory:

```
avr.standalone.gcc.exe = "avr-gcc"
avr.standalone.gcc.linkerexe = "avr-gcc"
passC = "-Os"
passC = "-DF_CPU=16000000UL"
passC = "-mmcu=atmega328p"
passC = "-mrelax -ffunction-sections -fdata-sections"
passC = "-Wno-fatal-errors"
passL = "-mmcu=atmega328p"
passL = "-Wl,--gc-sections -mrelax"
passL = "-Wl,-Map,release/nim_for_embedded.map"
cpu = "avr"
gc = "none"
define = "release"
deadCodeElim = "on"
os = "standalone"
nimcache = ".nimcache"
```

Now adding your suggestion fixed my issue, thanks:

```
avr.standalone.gcc.options.always = "-w"
```

**Comment by alaviss** [comment] 2020-04-05 16:32
Looks like this might be a problem in configuration parsing. When you're targeting other OS it makes little sense to evaluate `@if windows` section.

But then there might be people who rely on this :/ So I'm not even sure if this can be classified as a bug.

@Araq what do you think we should do?

**Comment by genotrance** [comment] 2020-07-04 20:47
Can this be closed?

**Comment by jputcu** [comment] 2020-07-05 06:44
There is no conclusion/fix yet, but there is a workaround so you could close it.

**Comment by Araq** [comment] 2020-07-06 09:49
Duplicate of other issues with configuration related problems.

**Closed as completed by Araq** 2020-07-06 09:49 UTC
Labels: Cross-Compilation
