### ISSUE TITLE
Compiler crash

### ISSUE THREAD

**Issue by lscrd** [nim-lang/Nim#5438] opened 2017-02-25 20:18 UTC
When defining a tuple with recursion (which seems to be forbidden), version 0.16.1 of the compiler crashes. With version 0.15, no error was found and the program compiled fine.
[recursivetuple.txt](https://github.com/nim-lang/Nim/files/801468/recursivetuple.txt)

**Comment by krux02** [comment] 2017-02-28 16:47
Would like to mention, that just replacing `tuple` with `object` makes this code compile

```nim
type
  NodeRef = ref Node
  Node = object
    somedata: int
    next: NodeRef

proc newNode(): NodeRef =
  new(result)
  result.somedata = 1
  result.next = nil
```

**Comment by Araq** [comment] 2017-03-02 19:34
Duplicate of some other "compiler crash" bug.

**Closed by Araq** 2017-03-02 19:34 UTC

**Comment by krux02** [comment] 2017-03-02 20:26
@Araq would be nice, if you could mention it, so that lscrd could follow the other issue.

**Comment by lscrd** [comment] 2017-03-02 22:39
Thanks krux02, but I think I have found it. It seems to be the #1145. The issue is slightly different as recursion in tuple involves a generic type, but the cause may indeed be the same.
