### ISSUE TITLE
Type inference bug with lambdas?

### ISSUE THREAD

**Issue by slomp** [nim-lang/Nim#19736] opened 2022-04-21 00:14 UTC
### Problem

Lambda is returning unexpected result.

### Example
```nim
import sugar

func parrot(f: (float64) -> float64, x: float64) =
    debugEcho f(x)

parrot((x) => 5, -10)
```

### Current Output
```
-10
```

### Expected Output
```
5
```

### Possible Solution

Qualifying the constant as a `float` in the lambda yields the expected output:
```
parrot((x) => 5.0, -10)
```
(note the `5.0` instead of just `5`).

### Additional Information

`nim --version`
```
Nim Compiler Version 1.6.4 [MacOSX: arm64]
Compiled at 2022-02-09
Copyright (c) 2006-2021 by Andreas Rumpf

active boot switches: -d:release -d:nimUseLinenoise
```

**Comment by ghost** [comment] 2022-04-21 04:26
Simplified so it doesn't require sugar (also x can be omitted), I guess it's behaving weirdly because `auto` is also the return type.
```nim
proc parrot(f: proc (x: float): float) =
  echo f(6)

parrot(proc (x: auto): auto = 5)
```

**Comment by ghost** [comment] 2022-04-21 04:34
Not sure if this is even the same bug as I've simplified further, but it seems like this miscompiles in a way that `test` returns an int (because `5` is an int literal), but `parrot` expects it to return a float and treats it in such way:
```nim
proc parrot(f: proc (x: float): float {.nimcall.}): float =
  result = f(6)

proc test(x: auto): auto = 5

echo parrot(test) # 2.470328229206233e-323
```

EDIT: Nvm, this only happens when compiling with `-d:danger` as the C compiler seems to misoptimize it because of wrong C code.

**Comment by ghost** [comment] 2022-04-21 04:41
But yeah, I think this _is_ the cause of the bug.
```nim
proc parrot(f: proc (x: float64): float64) =
  echo f(6)

parrot(proc (x: auto): auto = 5)
```

All compiled with `nim c -f -d:danger --opt:size --gc:arc` (because -O2, -O3 seem to trigger the C misoptimiziation)

Here is the compiled definition of the anonymous proc (notice how it returns an int):
```c
N_LIB_PRIVATE N_NIMCALL(NI, colonanonymous___tas_24)(NF x) {
	NI result;
	result = (NI)0;
	result = ((NI) 5);
	return result;
}
```

And here is the actual parrot function:
```c
N_LIB_PRIVATE N_NIMCALL(void, parrot__tas_1)(tyProc__zZ29aJqVt6bUiE9aXkliPF9bA f) {
	NimStringV2 colontmpD_;
	tyArray__nHXaesL0DJZHyVS07ARPRA T2_;
	NF T3_;
NIM_BOOL* nimErr_;
{nimErr_ = nimErrorFlag();
	colontmpD_.len = 0; colontmpD_.p = NIM_NIL;
	T3_ = (NF)0;
	T3_ = f.ClE_0? f.ClP_0(6.0, f.ClE_0):((TM__py7FFEnKZK6HVkQVTB50ew_2)(f.ClP_0))(6.0);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	colontmpD_ = dollar___system_3756(T3_);
	if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
	T2_[0] = colontmpD_;
	echoBinSafe(T2_, 1);
	{
		LA1_:;
	}
	{
		eqdestroy___system_2592((&colontmpD_));
	}
	if (NIM_UNLIKELY(*nimErr_)) goto BeforeRet_;
	}BeforeRet_: ;
}
```
You can see that it just calls that function pointer with the value of 6.

The fact that 6.0 is also returned without optimizations is just a weird bug, because it is undefined behaviour. Example C program that behaves the same:
```c
#include <stdio.h>

int testVal(double x) {
  int result;
  result = 5;
  return result;
}

int main() {
  double (*myPtr)(double x);
  myPtr = &testVal;
  double res = (*myPtr)(6.0);
  
  printf("%f\n", res);

  return 0;
}
```

**Comment by ghost** [comment] 2022-04-21 04:44
I might be wrong, but in my opinion the compiler should simply reject this code because Nim has no return-type inference and it can't infer that the anonymous proc has to return a float and so it has to treat `5` as a float literal instead of treating `5` as an int literal and making the anon proc return int like it does now.

**Comment by ghost** [comment] 2022-04-21 04:52
Maybe also related to https://github.com/nim-lang/Nim/issues/16244

**Comment by ghost** [comment] 2022-04-21 04:57
Oh, found an older issue about this.

Closing as a duplicate of https://github.com/nim-lang/Nim/issues/16906.

**Closed as completed by ghost** 2022-04-21 04:57 UTC
Labels: Invalid Code Acceptance

**Comment by slomp** [comment] 2022-04-21 15:37
Many thanks for looking further into this.
I scouted the open issues before posting, but failed to make the connection between this issue and https://github.com/nim-lang/Nim/issues/16906.

> in my opinion the compiler should simply reject this code because Nim has no return-type inference.

Yup, that's a perfectly sensible approach to addressing the issue.
