### ISSUE TITLE
internal error: not part of closure object type

### ISSUE THREAD

**Issue by HJarausch** [nim-lang/Nim#19984] opened 2022-07-07 14:19 UTC
I am trying the new recursive closure iterators.
A simple example works just fine.
But a larger one fails with
**internal error: not part of closure object type**

Unfortunately trying to come up with a smaller example source file (just the iterator is reference in the error message)
doesn't show the error.

So, I have to attach the full file with more than 2700 lines.

The error message is

_Sudoku.nim(592, 18) Error: internal error: not part of closure object type_

Nim Compiler Version 1.7.1 [Linux: amd64]
Compiled at 2022-07-07
git hash: 430a1793075866179b34790a461936023fca1c0a

**Comment by HJarausch** [comment] 2022-11-12 16:42
[Sudoku_D.nim.gz](https://github.com/nim-lang/Nim/files/9995433/Sudoku_D.nim.gz)
I have reduced the failing example.
Now, commenting only two lines of code make the compiler error vanish.
Nim Compiler Version 1.7.3 [Linux: amd64]
Compiled at 2022-11-12
git hash: 852cf596ede370994f3f1bb49493ec96aa0653f3
active boot switches: -d:release

**Comment by bung87** [comment] 2022-11-19 12:56
the problem is `Loop_next` call itsself.

**Comment by HJarausch** [comment] 2022-11-19 14:14
Why is this a problem? Due to a recent patch, _closure_ iterators are recursive. 
I have tried simpler examples which all work just fine.
Thanks,
Helmut

**Comment by bung87** [comment] 2022-11-19 15:05
maybe it's just a unhandled case , when I commented the error reporting it compiles and runs but get `IndexError`, didn't looking deeply into your code. could this exmaple be minimal, I haven't writen a resursive iterator myself.

**Comment by HJarausch** [comment] 2023-07-04 16:50
I have reduced the size of the code to less than 50 lines.
The error still occurs with 
Nim Compiler Version 1.9.5 [Linux: amd64]
Compiled at 2023-07-04
Copyright (c) 2006-2023 by Andreas Rumpf

git hash: 31ba1046fc91f110117b9e1cbd28d1afb4432060
[BUG3.nim.txt](https://github.com/nim-lang/Nim/files/11951246/BUG3.nim.txt)

**Comment by Araq** [comment] 2023-07-04 19:09
From bug3.nim.txt:

```nim

#!/usr/bin/env nimr
import std/[sets, tables, sequtils]

type
  i8 = int8
  seq8 = seq[int8]
  Cell    = seq8
  NODE    = tuple[d_in:int8,Strong:bool,link:Cell]
  PATH    = seq[NODE]

var
  R_Cells : int = -1
  max_level : int

var
  Seen:HashSet[NODE]
  path:PATH

iterator Loop_next(strong_link:bool, d_in:int8, node:Cell, head:int8, 
              Seen:var HashSet[NODE], path: var PATH, level:int ) : PATH {.closure.} = 

  if level > max_level :
    return
  let GNode= len(node) > 1   # without this line, the code compiles
  
  var
    rt, ct, st : seq8
    column_type : bool

#[ with this code commented out the compiler error does not occurs ]#
    
  st= filter(st, proc(x:int8) : bool = x notin node)
  if column_type :
    rt= @[]
    ct= filter(ct, proc(x:int8) : bool = x notin node)
  else :  # row type
    rt= filter(rt, proc(x:int8) : bool = x notin node)
    ct= @[]

#[]#
iterator Nice_Loop( ) : PATH {.closure.} =
  for cell in 0i8..80i8 :
    let head= cell

    for pt in  Loop_next(true,0.i8,@[cell], head,Seen,path,0) :
      yield pt

for P in  Nice_Loop() :
  continue

```

**Comment by dxxb** [comment] 2024-10-19 05:46
As far as I can tell this has been fixed by https://github.com/nim-lang/Nim/pull/24316. Thank you @yglukhov.

**Closed as completed** 2024-10-23 08:05 UTC
Labels: Compiler Crash, Iterators, works_but_needs_test_case

**Comment by HJarausch** [comment] 2024-10-23 09:52
Many thanks!
Please change the docs that Nim does have recursive iterators now.
