### ISSUE TITLE
internal error when using typedesc `is` comparison in a macro

### ISSUE THREAD

**Issue by bluenote10** [nim-lang/Nim#10136] opened 2018-12-30 14:35 UTC
The following errors with `internal error: (filename: "semexprs.nim", line: 406, column: 19)`:

```nimrod
import macros

macro toGodotName(T: typedesc) =
  if T is string:
    echo "string"
  else:
    echo "not string"
```
The same works fine when using `proc` instead of `macro`.

This is most likely a regression, because the example is taken from the nim godot bindings, which used to work with 0.18. Is this still supposed to work with 0.19+?

**Comment by nc-x** [comment] 2018-12-30 15:19
Regression due to https://github.com/nim-lang/Nim/pull/8723 cc @LemonBoy

**Comment by nc-x** [comment] 2018-12-30 17:59
Also note that the stacktrace is wrong -
https://github.com/pragmagic/godot-nim/pull/42#issuecomment-450560842
Relevant lines -
```
semexprs.nim(2013)       semMagic
msgs.nim(545)            semIs
msgs.nim(538)            internalError
```

**Comment by LemonBoy** [comment] 2019-01-12 20:19
Oh well, the assertion can be safely (?) replaced by something like:
```nim
if lhsType.base.kind == tyNone:
  return
```

(maybe just checking `lhsType.containsGenericType` if the lhs is a typedesc may be enough since you can't do much at this stage)

This way the `is` operator is resolved by the VM using a shitty `isOpImpl` approximation (the PR that introduced this regression killed a third variant of the same algorithm, scientists are still not 100% sure we know how many more are left in the wild).

Cheers

**Closed** 2019-01-13 13:57 UTC
Labels: Crash, Macros, Regression, typedesc[T]
