### ISSUE TITLE
Assigning a "ref ref" to a "ref" results in invalid C code

### ISSUE THREAD

**Issue by johnnovak** [nim-lang/Nim#4091] opened 2016-04-16 03:08 UTC
Observe the following innocent looking code...

```
type
  Base = ref object of RootObj
  Child = ref object of Base

var
  child: ref Child
  base: ref Base

base = child
```

...blow up spectacularly at compilation:

```
d:\work\code\test\nimcache\error.c: In function 'errorInit000':
d:\work\code\test\nimcache\error.c:382:46: error: request for member 'Sup' in something not a structure or union
  asgnRef((void**) (&base_95014), &child_95012->Sup);
```

The exact same error is raised both with Nim 0.13.0 and the current dev version.

Using a reference to a reference is probably incorrect, as I don't think Nim supports such a thing (like `**` in C), but the Nim compiler should flag this as invalid code if that's the case.

**Comment by Varriount** [comment] 2016-04-16 12:37
Hm. While not used often, double-references should be supported. For example, references to sequences (which themselves are references).

**Comment by johnnovak** [comment] 2016-04-16 13:30
You're right, and `ref ref` is actually used in `tests/overload/tspec.nim`. So this is clearly a bug.

**Comment by Araq** [comment] 2016-04-18 08:57
Duplicate of #3544.  FYI it is invalid code, there is no subtype relation for multiple indirections (it would be unsound).

**Closed by Araq** 2016-04-18 08:57 UTC
