### ISSUE TITLE
For loops over a hardcoded empty array crash the compiler.

### ISSUE THREAD

**Issue by kayabaNerve** [nim-lang/Nim#11684] opened 2019-07-08 00:45 UTC
A for loop over a hardcoded empty array, which is meaningless, causes the compiler to have an internal error.

### Example
```nim
for _ in []:
  discard
```

### Current Output
```
Error: internal error: getTypeDescAux(tyEmpty)
No stack traceback available
To create a stacktrace, rerun compilation with ./koch temp c <file>
```

### Expected Output
```
```

This occurs on the latest devel and stable.

**Comment by ringabout** [comment] 2022-01-27 07:38
Duplicate of https://github.com/nim-lang/Nim/issues/19224

**Closed by ringabout** 2022-01-27 07:38 UTC
Labels: Crash
