### ISSUE TITLE
GC crash in VM with tuple unpacking loop and table

### ISSUE THREAD

**Issue by RSDuck** [nim-lang/Nim#14553] opened 2020-06-03 20:21 UTC
The following code results in a compiler crash.

### Example
```nim
import tables, strutils

const PpcPatterns = @[("aaaa", "bbbb"), ("aaaaa", "bbbbb"), ("aaaaaa", "bbbbbb")]

static:
    var
        needSecondIdentifier = initTable[uint32, seq[(string, string)]]()

    for (name, pattern) in PpcPatterns:
        let
            firstPart = 0'u32
            lastPart = "test"

        needSecondIdentifier.mgetOrPut(firstPart, @[]).add((name, pattern))
```

### Current Output
with nim temp
```
Traceback (most recent call last)
C:\Nim\compiler\nim.nim(117) nim
C:\Nim\compiler\nim.nim(82) handleCmdLine
C:\Nim\compiler\cmdlinehelper.nim(84) loadConfigsAndRunMainCommand
C:\Nim\compiler\main.nim(252) mainCommand
C:\Nim\compiler\main.nim(217) compileToBackend
C:\Nim\compiler\main.nim(93) commandCompileToC
C:\Nim\compiler\modules.nim(143) compileProject
C:\Nim\compiler\modules.nim(84) compileModule
C:\Nim\compiler\passes.nim(210) processModule
C:\Nim\compiler\passes.nim(86) processTopLevelStmt
C:\Nim\compiler\sem.nim(604) myProcess
C:\Nim\compiler\sem.nim(572) semStmtAndGenerateGenerics
C:\Nim\compiler\semstmts.nim(2306) semStmt
C:\Nim\compiler\semexprs.nim(1014) semExprNoType
C:\Nim\compiler\semexprs.nim(2783) semExpr
C:\Nim\compiler\semstmts.nim(2246) semStmtList
C:\Nim\compiler\semexprs.nim(2835) semExpr
C:\Nim\compiler\semstmts.nim(2202) semStaticStmt
C:\Nim\compiler\vm.nim(2194) evalStaticStmt
C:\Nim\compiler\vm.nim(2183) evalConstExprAux
C:\Nim\compiler\vm.nim(773) rawExecute
C:\Nim\lib\system\gc.nim(239) asgnRef
C:\Nim\lib\system\gc.nim(184) incRef
SIGSEGV: Illegal storage access. (Attempt to read from nil?)
```

### Expected Output
It shouldn't crash.

### Additional Information

using commit https://github.com/nim-lang/Nim/commit/55f0df164befdf2304841c74daeaacc5391e08fd

**Comment by RSDuck** [comment] 2020-06-05 20:56
sorry the example code is not reproducible. It works if a few more iterations are added:
```nim
import tables, strutils

const PpcPatterns = @[("aaaa", "bbbb"), ("aaaaa", "bbbbb"), ("aaaaaa", "bbbbbb"), ("aaaaaaa", "bbbbbbb"), ("aaaaaaaa", "bbbbb")]

static:
    var
        needSecondIdentifier = initTable[uint32, seq[(string, string)]]()

    for (name, pattern) in PpcPatterns:
        let
            firstPart = 0'u32
            lastPart = "test"

        needSecondIdentifier.mgetOrPut(firstPart, @[]).add((name, pattern))
```

as a workaround the tuple unpacking in the loop can be removed:
```nim
import tables, strutils

const PpcPatterns = @[("aaaa", "bbbb"), ("aaaaa", "bbbbb"), ("aaaaaa", "bbbbbb"), ("aaaaaaa", "bbbbbbb"), ("aaaaaaaa", "bbbbb")]

static:
    var
        needSecondIdentifier = initTable[uint32, seq[(string, string)]]()

    for entry in PpcPatterns:
        let
            (name, pattern) = entry

            firstPart = 0'u32
            lastPart = "test"

        needSecondIdentifier.mgetOrPut(firstPart, @[]).add((name, pattern))
```

**Comment by ghost** [comment] 2020-06-06 01:57
Seems like it might be a duplicate of (or very similar to) #14410

**Comment by RSDuck** [comment] 2020-06-06 12:16
gc:arc seems to fix this as well, so you're probably right

**Comment by narimiran** [comment] 2021-01-21 17:15
> gc:arc seems to fix this as well,

...but the SIGSEGV is back here if you compile with `--gc:orc`!?

**Closed as completed** 2022-06-22 06:44 UTC
Labels: VM, Garbage Collection
