### ISSUE TITLE
gc:arc cannot fully support threadpool with FlowVar

### ISSUE THREAD

**Issue by khchen** [nim-lang/Nim#13781] opened 2020-03-27 13:51 UTC
# Example
```nim
import threadpool, os

proc thread(): string =
  os.sleep(1000)
  return "ok"

var fv = spawn thread()
sync()
echo ^fv
```

### Current Output
```
Error: cannot bind another '=destroy' to: FlowVarObj; previous declaration was constructed here implicitly: d:\nim\lib\pure\concurrency\threadpool.nim(211, 48)
```

### Expected Output
```
ok
```

$ nim -v
Nim Compiler Version 1.1.1 [Windows: amd64]
Compiled at 2020-03-27```

**Comment by cooldome** [comment] 2020-03-27 21:46
I do have a fix for this one

**Comment by diegomrsantos** [comment] 2022-11-09 23:55
Seems there is a regression. Running the same code as reported outputs the following: 

**Current Output**

```
ok
Traceback (most recent call last)
.choosenim/toolchains/nim-#devel/lib/pure/concurrency/threadpool.nim(216) test
.choosenim/toolchains/nim-#devel/lib/system/orc.nim(486) nimDecRefIsLastCyclicDyn
.choosenim/toolchains/nim-#devel/lib/system/orc.nim(469) rememberCycle
.choosenim/toolchains/nim-#devel/lib/system/orc.nim(147) unregisterCycle
SIGSEGV: Illegal storage access. (Attempt to read from nil?)
```

Nim Compiler Version 1.7.3 [MacOSX: amd64]
Compiled at 2022-11-09
Copyright (c) 2006-2022 by Andreas Rumpf

git hash: cdb136f58545009d2e38e5f1c4822bcc6dc7df83
active boot switches: -d:release

**Comment by Araq** [comment] 2022-11-10 00:02
Report it properly. A test program that fails, a new issue, more information, things like that.

**Comment by diegomrsantos** [comment] 2022-11-10 00:04
I can create a new issue if that's better, but I used the same code as initially reported and posted the current output.

**Comment by Araq** [comment] 2022-11-10 06:10
Ah ok.

**Comment by ringabout** [comment] 2022-11-10 06:11
> I can create a new issue if that's better, but I used the same code as initially reported and posted the current output.

Duplicate of https://github.com/nim-lang/Nim/issues/14901

**Closed as completed** 2022-11-10 08:54 UTC
Labels: ARC/ORC Memory Management
