### ISSUE TITLE
Wrong error message with quote do + template injection + VM bool/enum

### ISSUE THREAD

**Issue by mratsim** [nim-lang/Nim#9625] opened 2018-11-05 09:29 UTC
This is a followup to #7375 and #9520:

Summary of both issues: `bool` and `enum` in the VM are changed to int when passed via quote do or to other macros.

It also triggers a **very misleading error** if they are passed to a template that uses identifier injection.
Instead of saying that one of the parameter is of incorrect type, for example `got static int instead of static bool` we get `undeclared identifier`.

Due to the many other early symbol resolution issues with macro this wrong message led me to try lots of unrelated changes that didn't solve the actual issue.

Test case:
```Nim
import macros

template foo(index: untyped, condition: static bool): untyped =
  for `index`{.inject.} in 0 ..< 1:
    if condition:
      echo "Success"

macro fails(): untyped =
  let macro_idx = newIdentNode"my_index"
  let success = true

  result = quote do:
    foo(`macro_idx`, `success`)

macro works(): untyped =
  let macro_idx = newIdentNode"my_index"
  let success = true

  let success_node = newLit success

  result = quote do:
    foo(`macro_idx`, `success_node`)

# fails() # Error: undeclared identifier: 'my_index'
works()

##########################################
# Trying without static

template foo2(index: untyped, condition: bool): untyped =
  for `index`{.inject.} in 0 ..< 1:
    if condition:
      echo "Success"

macro fails2(): untyped =
  let macro_idx = newIdentNode"my_index"
  let success = true

  result = quote do:
    foo2(`macro_idx`, `success`)

# fails2() # Error: undeclared identifier: 'my_index'

##########################################

macro works3(): untyped =
  let macro_idx = newIdentNode"my_index"
  let success = true

  result = quote do:
    foo2(`macro_idx`, bool(`success`))

works3()
```

**Comment by krux02** [comment] 2018-11-05 12:12
binding to symbols with backticks that are not of type ``NimNode`` is not supported, and it can't reliably be supported. It is a bug though the error message is not correct.

Use ``let success = newLit(true)``.

**Comment by krux02** [comment] 2018-11-05 12:13
this is a duplicate of https://github.com/nim-lang/Nim/issues/9607

**Closed by krux02** 2018-11-05 12:13 UTC
Labels: Error messages, Macros, Symbol Resolution, Templates
