### ISSUE TITLE
Example in `net` module crashes + Wrong error message

### ISSUE THREAD

**Issue by BarelyMalicious** [nim-lang/Nim#8054] opened 2018-06-17 11:38 UTC
```nim
import net

var socket = newSocket()
socket.bindAddr(Port(1234))
socket.listen()

var client = new Socket
var address = ""
while true:
  socket.acceptAddr(client, address)
  echo("Client connected from: ", address)
```

from here - https://nim-lang.org/docs/net.html#examples-creating-a-server

1)  `nim check` shows warning 
```
lib\system.nim(211, 7) Warning: Cannot prove that 'r' is initialized. This will become a compile time error in the future. [ProveInit]
```
This warning comes from `var client = new Socket`

2) Compiling and running the code, and connecting to the server gives -
```
Client connected from: 127.0.0.1
t.nim(27)                t
net.nim(800)             acceptAddr
system.nim(3806)         failedAssertImpl
system.nim(3799)         raiseAssert
system.nim(2853)         sysFatal
Error: unhandled exception: int(client.fd) <= 0 Client socket needs to be initialised with `new`, not `newSocket`. [AssertionError]
Error: execution of an external program failed: 'C:\Users\alpha\Desktop\nim\t.exe '
```
Looking here, we can see that it atleast prints the address of the client before crashing. 

Now I now nothing about sockets so have no idea regarding the reasons for this crash (similar code in python does not crash) but note that atleast the error ` Client socket needs to be initialised with new, not newSocket. [AssertionError]` is wrong as client is initialized with `new`

---
```
λ nim --version
Nim Compiler Version 0.18.1 [Windows: amd64]
Compiled at 2018-06-17
Copyright (c) 2006-2018 by Andreas Rumpf

git hash: 798a8bd45c6631864716566e0681590879015aeb
active boot switches: -d:release
```

**Comment by BarelyMalicious** [comment] 2018-06-17 12:31
Also, (when using netcat,) in python `.recv` returns data even if buffersize not reached but ENTER is pressed.
Whereas in nim, `recv` only returns when buffersize is reached. Is this behaviour expected?

**Comment by dom96** [comment] 2018-06-17 12:44
duplicate of #7848

**Closed by dom96** 2018-06-17 12:44 UTC

**Comment by dom96** [comment] 2018-06-17 13:01
> Is this behaviour expected?

Yes

**Comment by BarelyMalicious** [comment] 2018-06-17 13:29
Yeah sorry, just found `recvLine` in docs.
