### ISSUE TITLE
incorrect iteration in concert with tuple unpacking

### ISSUE THREAD

**Issue by disruptek** [nim-lang/Nim#18347] opened 2021-06-24 21:04 UTC
Courtesy of @c-blake:

### Example
```nim
var x = @[ (6.0, 6, '6'),
           (5.0, 5, '5'),
           (4.0, 4, '4'),
           (3.0, 3, '3'),
           (2.0, 2, '2'),
           (1.0, 1, '1') ]
for (f, i, c) in x: echo f, " ", i, " ", c
echo ""
iterator popAscending*[T](q: var seq[T]): T =
  while q.len > 0: yield q.pop
when defined(ok):
  for t in popAscending(x):
    let (f, i, c) = t
    echo f, " ", i, " ", c
else: # not ok!
  for f, i, c in popAscending(x):
    echo f, " ", i, " ", c
```

### Current Output
```
6.0 6 6
5.0 5 5
4.0 4 4
3.0 3 3
2.0 2 2
1.0 1 1

1.0 2 3
4.0 5 6
```
### Expected Output
```
6.0 6 6
5.0 5 5
4.0 4 4
3.0 3 3
2.0 2 2
1.0 1 1

1.0 1 1
2.0 2 2
3.0 3 3
4.0 4 4
5.0 5 5
6.0 6 6
```

```
Nim Compiler Version 1.5.1 [Linux: amd64]
Compiled at 2021-06-24
Copyright (c) 2006-2021 by Andreas Rumpf

git hash: 0f91b67f5c15328330f74a8769aed9961940aab2
active boot switches: -d:release
```

**Comment by Araq** [comment] 2021-06-25 06:06
Ha, good one.

**Comment by ringabout** [comment] 2021-08-28 09:07
Another workaround:
```nim
var x = @[ (6.0, 6, '6'),
           (5.0, 5, '5'),
           (4.0, 4, '4'),
           (3.0, 3, '3'),
           (2.0, 2, '2'),
           (1.0, 1, '1') ]
for (f, i, c) in x: echo f, " ", i, " ", c
echo ""
iterator popAscending*[T](q: var seq[T]): T =
  while q.len > 0:
    let x = q.pop
    yield x

for f, i, c in popAscending(x):
  echo f, " ", i, " ", c
```

print:

```nim
6.0 6 6
5.0 5 5
4.0 4 4
3.0 3 3
2.0 2 2
1.0 1 1

1.0 1 1
2.0 2 2
3.0 3 3
4.0 4 4
5.0 5 5
6.0 6 6
```

**Comment by ringabout** [comment] 2021-08-28 09:35
Duplicate of #9778

**Closed as completed** 2021-08-28 09:36 UTC
Labels: Medium Priority, Iterators
