### ISSUE TITLE
re.match does not seem to support seqs

### ISSUE THREAD

**Issue by disruptek** [nim-lang/Nim#11759] opened 2019-07-16 20:26 UTC
This runnable example from the documentation works fine:

```nim
var matches: array[2, string]
if match("abcdefg", re"c(d)ef(g)", matches, 2):
  for s in matches:
    echo s       # => d g
```
Although the signature suggests that it accepts an `openArray` for the matches variable, `match()` does not populate that var if a seq is supplied instead of an array.  The proc does correctly identify whether a match exists between the source string an the regular expression pattern.

### Example
```nim
var matches: seq[string]
if match("abcdefg", re"c(d)ef(g)", matches, 2):
  for s in matches:
    echo s       # =>
```

### Current Output
```
```

### Expected Output
```
d
g
```

### Possible Solution
Call a spade a spade and demand an array for output.

### Additional Information
```
Nim Compiler Version 0.20.99 [Linux: amd64]
Compiled at 2019-07-15
Copyright (c) 2006-2019 by Andreas Rumpf

git hash: 8550a8127c6c80754d8a6f4300e4c77ee126e6ec
active boot switches: -d:release
```

**Comment by kaushalmodi** [comment] 2019-07-16 21:25
That's an interesting bug.. I thought this would reproduce the issue, but it doesn't!: https://play.nim-lang.org/#ix=1OHl works well.

See if you can tweak that example to reproduce the bug.

**Comment by kaushalmodi** [comment] 2019-07-16 22:06
Ok, the seq needs to be initialized to the required length, which can be done at run time too. 

So this works: https://play.nim-lang.org/#ix=1OHt

**Comment by kaushalmodi** [comment] 2019-07-16 22:09
May be an error should be thrown if Nim passes an unallocated `matches` to pcre.

**Comment by narimiran** [comment] 2019-07-17 05:48
Duplicate of https://github.com/nim-lang/Nim/issues/9472 ?

**Comment by kaushalmodi** [comment] 2019-07-17 09:59
@narimiran Yes, this one is a duplicate.

**Closed** 2019-07-17 10:32 UTC
Labels: regex
