### ISSUE TITLE
--symbolFiles:on Error: internal error: symStack: module nil:  No stack traceback available

### ISSUE THREAD

**Issue by runvnc** [nim-lang/Nim#1031] opened 2014-03-23 07:43 UTC
``` shell
runvnc@runvnclap ~/code/oic $ cat something.nim
echo "Hello World"runvnc@runvnclap ~/code/oic $ nimrod c --symbolFiles:on something.nim 
config/nimrod.cfg(37, 2) Hint: added path: '/home/runvnc/.babel/pkgs/cairo-1.0' [Path]
config/nimrod.cfg(37, 2) Hint: added path: '/home/runvnc/.babel/pkgs/jester-0.1.0' [Path]
config/nimrod.cfg(37, 2) Hint: added path: '/home/runvnc/.babel/pkgs/gtk2-1.0' [Path]
config/nimrod.cfg(37, 2) Hint: added path: '/home/runvnc/.babel/pkgs/bcrypt-0.2.0' [Path]
config/nimrod.cfg(37, 2) Hint: added path: '/home/runvnc/.babel/pkgs/redissessions-0.1.0' [Path]
config/nimrod.cfg(37, 2) Hint: added path: '/home/runvnc/.babel/pkgs/aporia-0.2.0' [Path]
config/nimrod.cfg(37, 2) Hint: added path: '/home/runvnc/.babel/pkgs/babel-0.2.0' [Path]
config/nimrod.cfg(37, 2) Hint: added path: '/home/runvnc/.babel/pkgs/ipsumgenera-0.1.0' [Path]
config/nimrod.cfg(37, 2) Hint: added path: '/home/runvnc/.babel/pkgs/' [Path]
Hint: used config file '/home/runvnc/code3/Nimrod/config/nimrod.cfg' [Conf]
Hint: symbol file for lib/system.nim does not exist [Processing]
Hint: system [Processing]
Error: internal error: symStack: module nil: 
No stack traceback available
runvnc@runvnclap ~/code/oic $ nimrod --version
Nimrod Compiler Version 0.9.3 (2014-03-13) [Linux: amd64]
Copyright (c) 2006-2014 by Andreas Rumpf
```

**Comment by genotrance** [comment] 2018-04-18 03:00
Just tried this with #head, it no longer crashes.

**Comment by andreaferretti** [comment] 2018-04-18 08:02
Still crashes for me, giving

```
lib/system.nim(25, 3) Error: internal error: rodwrite.process
No stack traceback available
To create a stacktrace, rerun compilation with ./koch temp c <file>
```

**Comment by genotrance** [comment] 2018-04-18 13:42
Sorry, yes still crashes. Following is full stack trace.

```
Hint: used config file 'C:\Users\gt\Desktop\dl\programming\nimdevel\config\nim.cfg' [Conf]
Hint: system [Processing]
lib\system.nim(25, 3) Error: internal error: rodwrite.process
Traceback (most recent call last)
nim.nim(121)             nim
nim.nim(77)              handleCmdLine
main.nim(173)            mainCommand
main.nim(77)             commandCompileToC
modules.nim(241)         compileProject
modules.nim(222)         compileSystemModule
modules.nim(182)         compileModule
passes.nim(250)          processModule
passes.nim(139)          processTopLevelStmt
rodwrite.nim(615)        process
msgs.nim(1066)           internalError
msgs.nim(1037)           liMessage
msgs.nim(886)            handleError
msgs.nim(876)            quit
```

**Comment by andreaferretti** [comment] 2018-06-20 10:49
Does not crash anymore for me, on either MacOS or Linux

**Comment by genotrance** [comment] 2018-06-23 16:13
It doesn't crash anymore, but doesn't generate any symbol files in nimcache - not sure what the behavior should be.

Also noticed that --symbolfiles isn't in basic or advanced options. Where is it documented?

**Comment by andreaferretti** [comment] 2018-06-28 08:10
I am not sure whether this should stay open. Apparently the problem is not there anymore.

The documentation of symbolFiles is [here](https://nim-lang.org/docs/nimc.html#compilation-cache). But the logic for incremental compilation has changed a lot lately, so I am not sure if `--symbolFiles:on` as an option still makes sense. @Araq ?

**Comment by Araq** [comment] 2018-06-29 15:04
> But the logic for incremental compilation has changed a lot lately, so I am not sure if --symbolFiles:on as an option still makes sense. @Araq ?

It's an alias for ``--incremental:on``. And incremental compilation still needs to be battle-tested. On the other hand, at least the code is written already... But I'm closing this one.

**Closed by Araq** 2018-06-29 15:04 UTC
Labels: Crash, Low Priority
