### ISSUE TITLE
Error: cannot 'importc' variable at compile time 

### ISSUE THREAD

**Issue by Krognol** [nim-lang/Nim#4953] opened 2016-10-25 21:41 UTC
Error happens after compiling this code

``` nim
import compiler.nimeval

"echo $1".execute
```

and then running the generated executable.

Running the latest Nim version, 64bit windows 10

**Comment by krux02** [comment] 2016-10-26 17:13
I just opened a new issue #4957 with the same error message, so I thought the issues might be related, but I cannot reproduce your error in your code, I have a different error in your code:

    /home/arne/.nimble/pkgs/compiler-0.14.3/compiler/docgen.nim(16, 40) Error: cannot open 'rstast'

**Comment by Krognol** [comment] 2016-10-26 17:31
I had that error too at the start, but found a fix pretty quickly.
You have to add `path="$lib/packages/docutils"` in `nim/config/nim.cfg`.

**Comment by krux02** [comment] 2018-11-07 20:52
When I try to compile it now, the error message is ``scratch.nim(4, 16) Error: cannot open file: compiler/nimeval``. I guess the time is over to use interal API from the compiler. I wonder if I should close this issue because of it.

**Closed** 2018-11-07 20:53 UTC

**Comment by timotheecour** [comment] 2018-11-07 22:09
@krux02 

compiler/nimeval should still supported and is covered in test suite ; see ./tests/compilerapi/tcompilerapi.nim for new API instead of the less flexible execute

I had also added `evalString` to ./tests/compilerapi/tcompilerapi.nim in https://github.com/nim-lang/Nim/pull/9181  which is a bit similar to the old `execute`
