### ISSUE TITLE
[low priority] testament: nimout too lax, repeated entries in spec are allowed to match just once

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/Nim#11730] opened 2019-07-14 23:17 UTC
repeated consecutive entries in nimout spec are allowed to be found just once in actual nim output

### Example
`./koch tests r tests/main.nim`
with:
```nim
discard """
nimout: '''
foo1
foo1
foo2
foo2
'''
"""

static:
  echo "foo0"
  echo "foo1"
  echo "fooMiddle"
  echo "foo2"
  echo "foo3"
```

### Current Output
passes

### Expected Output
fails, because `nimout` expects `foo1` to appear twice but `foo` is output just once in actual nim output

the doc for `nimoutCheck` says:
```
  # Only check that nimout contains all expected lines in that order.
  # There may be more output in nimout. It is ignored here.
```
which is ambiguously worded, but IMO each line in the specified `nimout` should be found in the actual output.

For example, in `tmacros_issues`, if you replace:
```
  const s = ("TT", 3)
  m(s)
  m(s)
```
with 
```
  const s = ("TT", 3)
  m(s)
```
the test still passes

### Additional Information
* Was it working in the previous Nim releases?
no

```
$ nim -v
Nim Compiler Version 0.20.99 [MacOSX: amd64]
Compiled at 2019-07-10
Copyright (c) 2006-2019 by Andreas Rumpf

git hash: cb3c3c306c6507a09c15da26828a39fbbd4dbc66
active boot switches: -d:release
```

**Comment by ringabout** [comment] 2021-03-29 03:20
Duplicate of #16693

**Closed** 2021-03-29 03:20 UTC
Labels: Test suite
