### ISSUE TITLE
Unhandled value in try-finally incorrectly marks the wrong branch

### ISSUE THREAD

**Issue by cmd410** [nim-lang/Nim#19672] opened 2022-04-03 08:22 UTC
Nim compiler confuses branches of try-finally construction when value in try block is unhandled and incorrectly marks the wrong branch.

### Example
```nim
try:
    10
finally:
    echo "Finally block"
```

### Current Output
```
poc.nim(4, 10) Error: expression 'echo ["Finally block"]' is of type 'int literal(10)' and has to be used (or discarded); start of expression here: poc.nim(1, 1)
```

### Expected Output
```
poc.nim(2, 4) Error: expression '10' is of type 'int literal(10)' and has to be used (or discarded); start of expression here: poc.nim(1, 1)
```

### Possible Solution

No idea.

### Additional Information

Even though in PoC it is trivial to figure out that error message refers to 10 by `type 'int literal(10)'`
in more complicated scenarios it can lead to extremely misleading error messages.

```
$ nim -v
Nim Compiler Version 1.6.2 [Windows: amd64]
Compiled at 2021-12-17
Copyright (c) 2006-2021 by Andreas Rumpf

active boot switches: -d:release
```
I noticed that except clauses when used, produce the correct output:
```nim
try:
    raise newException(Exception, "ARRR")
except:
    12
finally:
    echo "Finally block"
```
will show message:
```
poc.nim(4, 5) Error: expression '12' is of type 'int literal(12)' and has to be used (or discarded)
```
as expected

**Comment by ghost** [comment] 2022-04-03 08:54
Seems like a duplicate of https://github.com/nim-lang/Nim/issues/13871, although it's not specific to templates as in that issue.

**Closed as completed** 2024-06-05 18:53 UTC
Labels: Error Messages
