### ISSUE TITLE
Collision between private types in modules with the same filename but different paths

### ISSUE THREAD

**Issue by dsemi** [nim-lang/Nim#21212] opened 2023-01-01 00:01 UTC
### Description

I have two separate modules with the same file name but contained in different folder. If both of those modules declare a type with the same name (doesn't have to be exported), the definitions manage to clobber each other.

main.nim:
```
import test1/testt as t1
import test2/testt as t2

t1.fun()
t2.fun()
```

test1/testt.nim:
```
type
  Tile = object
    num: int

proc fun*() =
  echo Tile(num: 1)
```

test2/testt.nim:
```
type
  Tile = object
    t: int

proc fun*() =
  echo Tile(t: 1)
```

Running `nim c main.nim` fails with `‘tyObject_Tile__XWpZ9bEYGPCI9bA3zXJFHd2g’ has no member named ‘t’`. When inspecting the generated C code, `tyObject_Tile__XWpZ9bEYGPCI9bA3zXJFHd2g` is the Tile type from test1/testt.nim

Renaming one of the testt.nim files to something else results in a successful compilation. 

### Nim Version

Nim Compiler Version 1.6.10 [Linux: amd64]
Compiled at 2022-11-21
Copyright (c) 2006-2021 by Andreas Rumpf

git hash: f1519259f85cbdf2d5ff617c6a5534fcd2ff6942
active boot switches: -d:release

### Current Output

```text
Hint: used config file '~/.choosenim/toolchains/nim-1.6.10/config/nim.cfg' [Conf]
Hint: used config file '~/.choosenim/toolchains/nim-1.6.10/config/config.nims' [Conf]
...........................................................
CC: .choosenim/toolchains/nim-1.6.10/lib/system/dollars.nim
~/.cache/nim/main_d/@m.choosenim@stoolchains@snim-1.6.10@slib@ssystem@sdollars.nim.c: In function ‘dollar___test50Ztestt_28’:
/home/dan/.cache/nim/main_d/@m.choosenim@stoolchains@snim-1.6.10@slib@ssystem@sdollars.nim.c:188:48: error: ‘tyObject_Tile__XWpZ9bEYGPCI9bA3zXJFHd2g’ has no member named ‘t’
  188 |         addQuoted__test49Ztestt_49((&result), x.t);
      |                                                ^
Error: execution of an external compiler program 'gcc -c  -w -fmax-errors=3   -I~/.choosenim/toolchains/nim-1.6.10/lib -I/home/dan -o ~/.cache/nim/main_d/@m.choosenim@stoolchains@snim-1.6.10@slib@ssystem@sdollars.nim.c.o ~/.cache/nim/main_d/@m.choosenim@stoolchains@snim-1.6.10@slib@ssystem@sdollars.nim.c' failed with exit code: 1
```

### Possible Solution

Perhaps something to do with how the `tyObject_Tile__XWpZ9bEYGPCI9bA3zXJFHd2g` name is generated? If it's doing some sort of hash of the filename of the module, that's not unique enough within a build.

**Comment by metagn** [comment] 2023-01-01 14:32
This is pretty bad, I'm guessing it's because their C file output has the same filename so one writes over the other

**Comment by ringabout** [comment] 2023-01-01 15:11
Duplicate of https://github.com/nim-lang/Nim/issues/20139

**Closed as completed** 2023-01-01 15:11 UTC
