### ISSUE TITLE
Compiler crushes when trying to restrict the variable type by a generic

### ISSUE THREAD

**Issue by levovix0** [nim-lang/Nim#19164] opened 2021-11-18 20:07 UTC
### Example
```nim
var x: seq = @[1, 2, 3]
```

### Current Output
```
Error: internal error: genTypeInfoV1(tyNone)
Traceback (most recent call last)
Nim/compiler/nim.nim(138) nim
Nim/compiler/nim.nim(94) handleCmdLine
Nim/compiler/main.nim(275) mainCommand
Nim/compiler/main.nim(245) compileToBackend
Nim/compiler/main.nim(101) commandCompileToC
Nim/compiler/modules.nim(178) compileProject
Nim/compiler/modules.nim(98) compileModule
Nim/compiler/passes.nim(180) processModule
Nim/compiler/passes.nim(73) processTopLevelStmt
Nim/compiler/cgen.nim(1940) myProcess
Nim/compiler/cgen.nim(1934) genTopLevelStmt
Nim/compiler/cgen.nim(1002) genProcBody
Nim/compiler/ccgstmts.nim(1584) genStmts
Nim/compiler/ccgexprs.nim(2882) expr
Nim/compiler/ccgstmts.nim(410) genVarStmt
Nim/compiler/ccgstmts.nim(392) genSingleVar
Nim/compiler/ccgstmts.nim(324) genSingleVar
Nim/compiler/ccgstmts.nim(24) getTraverseProc
Nim/compiler/ccgtrav.nim(176) genTraverseProcForGlobal
Nim/compiler/ccgtypes.nim(1474) genTypeInfoV1
Nim/compiler/ccgtypes.nim(1050) genTypeInfoAux
Nim/compiler/ccgtypes.nim(1445) genTypeInfoV1
Nim/compiler/ccgtypes.nim(1498) genTypeInfoV1
Nim/compiler/msgs.nim(606) internalErrorImpl
Nim/compiler/msgs.nim(561) liMessage
Nim/compiler/msgs.nim(413) handleError
Nim/compiler/msgs.nim(402) quit
```

### Expected Output
*compiles*

### Additional Information
```
$ nim -v
Nim Compiler Version 1.6.0
```

**Comment by beef331** [comment] 2021-11-18 21:59
Based off https://github.com/nim-lang/Nim/pull/18827#issuecomment-916749832 I'm uncertain if it should compile or if it should error "using typeclass as variable type"

**Comment by levovix0** [comment] 2021-11-19 04:19
I think this should compile because we have converters. And in some case, when you writed, for example, converter from MySeq[T] to seq[T], you may want to use it in variable creation, but not specify seq's generic parameter and not use converter explicitly.

**Comment by metagn** [comment] 2021-11-19 12:22
* `seq[auto]` and `auto` work, but not if the variable isn't immediately initalized.
* `seq(@[1, 2, 3])` works, although it converts to seq instead of restricting to seq. This too for some reason:

  ```nim
  type Foo[T] = object
    s: seq[T]

  converter toFoo[T](s: seq[T]): Foo[T] = Foo[T](s: s)

  var x = Foo @[1, 2, 3]
  ```
* Procs allow `seq` and non-concrete types as a return type, although it delays semantic checking for the proc until instantiation.

Since `seq[auto]` and the like work, unintended or not, fixing it the crash to be consistent with `seq[auto]` instead of disallowing it would be good if it doesn't add complexity.

**Comment by demotomohiro** [comment] 2021-11-25 01:03
As @beef331 and @hlaaftana said, it seems Nim allows type class other than procedure parameter and `is` operator.

Using a type class in return type might makes code slightly more explicit rather than using `auto`.
But I don't see much reason to using type class other than procedure parameter and `is` operator.
"Type class can be used only in procedure/iterator/template/macro parameter and `is` operator" is a simple rule and easy to understand.
But is it a breaking change?

You can write `var a: int or string = 1` but cannot write `var a: int or string` because compiler cannot determine the type of the variable.
Also you cannot use type class when defining object type.
You can use type classes only when there is a expression that makes type class to real type excepts when using `is` operator.

If you call converter explicitly, you don't need to use type class to declare variable.
For example:
```nim
type Foo[T] = object
  s: seq[T]

converter toFoo[T](s: seq[T]): Foo[T] = Foo[T](s: s)

var x = toFoo @[1, 2, 3]
echo x
```

Declaring a variable with generic type type class that implicitly calls converter can creates complicated problem.
```nim
type
  MySeq[T] = object
    x: seq[T]

converter toMyFloatSeq(x: seq[int]): MySeq[float] =
  result.x.setLen(x.len)
  for i in 0 ..< x.len:
    result.x[i] = float(x[i])

converter toMyUintSeq(x: seq[int]): MySeq[uint] =
  result.x.setLen(x.len)
  for i in 0 ..< x.len:
    result.x[i] = uint(x[i])

var a: MySeq[float] = @[1, 2, 3]
echo a
var b: MySeq[uint] = @[1, 2, 3]
echo b

var c: MySeq = @[1, 2, 3]
# Is typeof(c) MySeq[float] or MySeq[uint]?
```

Even this simple code involving implicit type convertion and type class cause strange result.
```nim
var a: uint or float = 1
echo typeof(a)
```

Output:
```nim
int
```

**Comment by ringabout** [comment] 2024-04-23 12:28
Duplicate of #13992

Besides on the devel branch, it gives "Error: invalid type: 'None' in this context: 'seq' for let"

**Closed as completed by ringabout** 2024-04-23 12:28 UTC
