### ISSUE TITLE
Let behaves differently in proc for default gc

### ISSUE THREAD

**Issue by duerrp** [nim-lang/Nim#2314] opened 2015-03-11 16:33 UTC
Hi, 

First, thanks for your outstanding work. I have been playing with nim for a couple of months and it's a joy to work with. Today though, I found myself dumbfounded by a strange behaviour illustrated in the following code:

```nim
var a = @[0, 0, 0]
let b = a

proc modifyVar(a : var seq[int]) =
  var c = a
  echo "a: ", a
  echo "c: ", c
  a[0] = 2
  echo "a: ", a
  echo "c: ", c

proc modifyLet(a : var seq[int]) =
  let c = a
  echo "a: ", a
  echo "c: ", c
  a[0] = 42
  echo "a: ", a
  echo "c: ", c

echo "a: ", a
echo "b: ", b
a[0] = 1
echo "a: ", a
echo "b: ", b

modifyVar(a)
modifyLet(a)
```

With nim-0.10.2 the assignment in the second function changes both `a` and `c` whereas the first assignment does not. Is this the way it should be?

**Comment by def-** [comment] 2015-03-11 16:40
This looks unwanted to me. `let` should only be allowed to make no copy when the right hand side is immutable.

**Comment by Araq** [comment] 2015-03-11 19:15
Well it might be unwanted, but we have no borrow checking.

**Comment by duerrp** [comment] 2015-03-12 00:52
I see, thanks. 

I would personally prefer if `let` makes a copy by default (imho as a nim novice, the performance hit of a copying `let` would be much easier to anticipate than this behavior). Especially since it is not consistent - hunting down the bug in my program, I first wrote a little test like the one above in global scope, looked at the c-code and wrongly concluded that `let` does work as I expected. 

Either way, I can also live with the inconsistency, but in this case it should probably be explained clearly in the tutorial & in the manual.

**Comment by def-** [comment] 2015-11-19 03:24
Another example I just ran into that caused https://github.com/def-/nim-bigints/issues/3

```nimrod
# b creates copy of a
var a = @[1,2,3]
let b = a
a.setLen(0)
echo a # @[]
echo b # @[1,2,3]

# b points to a, no copy
block:
  var a = @[1,2,3]
  let b = a
  a.setLen(0)
  echo a # @[]
  echo b # @[]
```

**Comment by Araq** [comment] 2015-11-23 09:42
Well we can prevent it at compile-time. There are more people fighting the copies than they are fighting with these edge cases, afaict.

**Comment by Araq** [comment] 2018-10-15 09:10
With the move semantics/optimizer we now have a performant way of solving this issue.

**Comment by Araq** [comment] 2019-08-16 16:28
Not "high priority", needs to be documented. Bug is gone with ``--newruntime`` anyway.

**Comment by timotheecour** [comment] 2020-12-10 19:18
This keeps coming up: see these just submitted issues https://github.com/nim-lang/Nim/issues/16312 and https://github.com/nim-lang/Nim/issues/16311 for example.

Labeling this as "documentation" implies current behavior won't be fixed, which is problematic because semantics differ between `--gc:arc` and default gc.

We must uniformize semantics between `--gc:arc` and default gc as much as possible; arc has its own bugs and we can't simply ask users to migrate all their code to arc and ignore default gc.

I've suggested here how to do so here: https://github.com/nim-lang/Nim/issues/13771#issuecomment-607222273

```nim
let a1 {.byaddr.} = expr # reference semantics
let a2 {.bycopy.} = expr # copy semantics
let a3 = expr
  # always copy for pointer types (ref/ptr/pointer/cstring), ordinal, SomeNumber
  # warning (or even error) for other types (seq, string, object, set),
  # since behavior differs bw --gc:arc vs other
```

and after some time, we could introduce `--legacy:letDoesNotCopy` transition flag that can be localized:  https://github.com/nim-lang/Nim/issues/13771#issuecomment-605910897 and change default behavior when this flag isn't passed to make gc:arc consistent with default gc)


----
btw here's a reduced repro:
```nim
when true:
  var a = @[1,2,3] # with array instead, there'd be no difference bw default gc and gc:arc
  template fn =
    let b = a
    a[0] += 10
    echo (b: b, isCopy: b[0].unsafeAddr != a[0].unsafeAddr)
  fn()
  proc main = fn()
  main()
```
default gc:
(b: @[1, 2, 3], isCopy: true)
(b: @[21, 2, 3], isCopy: false)

gc:arc:
(b: @[1, 2, 3], isCopy: true)
(b: @[11, 2, 3], isCopy: true)

(note: as I noted in https://github.com/nim-lang/Nim/issues/13771#issuecomment-742770755, the same happens if `a` is in same scope as `b`, ie it doesnt' matter whether `a` is global vs local; it only matters that `b` is local vs global)

**Comment by Araq** [comment] 2020-12-11 09:11
Fine with me. I think it's better to focus on fixing orc bugs but really -- fine with me.

**Comment by mratsim** [comment] 2020-12-11 09:24
We don't know how much time it will take to fix orc bugs and the default GC has been tested for years and needs to be supported for as long as 1.0 is supported.

**Comment by Araq** [comment] 2020-12-11 09:27
Sure but we cannot backport the breaking "bugfix" change to 1.0 either.

**Comment by ringabout** [comment] 2022-09-23 11:12
Duplicate of https://github.com/nim-lang/Nim/issues/16312

The default GC has changed to ORC.

**Closed by ringabout** 2022-09-23 11:12 UTC
Labels: Documentation Content, Garbage Collection, works_with_arc_orc
