### ISSUE TITLE
Debug GC crashes when creating about 200000 objects (or even less)

### ISSUE THREAD

**Issue by dluciv** [nim-lang/Nim#3426] opened 2015-10-07 09:47 UTC
Hi.

First, thank you for your great language!

I use Nim 0.11.2 x64 to compile this code:

```
type
  Node = ref object of RootObj
    next:  Node

var head: Node = nil

# Uncommenting this prevents the crash
# GC_disable()

for i in 0..200000: # Not so much...
  head = Node(next: head)
```

# Default GC issue

Generated binary crashes under both Windows (7, 10, MinGW installed with Nim) and Linux (kernel 4.2.2, gcc 5.2.0, glibc 2.22). When compiling with `-d:release` or disabling garbage collector (see commented code), everything runs ok.

# Additionally

* Using `--gc:v2` crashes compiler itself.
* Using `-d:gcMarkAndSweep` causes `Error: system module needs 'asgnRefNoCycle'` error.

**Comment by Varriount** [comment] 2015-10-07 20:25
This is a known bug/design flaw. The current default GCC uses a recursive algorithm for certain checks (cyclic structure checking, I think). Under `-d:release` this is optimized away (I think, it might just be the impact of other optimizations).

**Comment by Araq** [comment] 2015-10-14 14:56
Duplicate of https://github.com/nim-lang/Nim/issues/1895

**Comment by Araq** [comment] 2015-10-14 14:57
-d:gcMarkAndSweep is not how to enable the M&S GC. use --gc:markAndSweep for that.

**Closed by Araq** 2015-10-14 14:56 UTC
Labels: GC

**Comment by dluciv** [comment] 2015-10-14 15:16
Yes, about mark and sweep it was my blunder, thank you!
