### ISSUE TITLE
regression: building nim from devel (resp 1.4) uses 846 (rep 680) peakmem

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/Nim#18765] opened 2021-08-28 21:42 UTC
while working on https://github.com/nim-lang/Nim/pull/18760 i noticed a regression in memory peakmem usage:

building nim from devel uses 846 peakmem
building nim from 1.4 uses 680 peakmem

this should be investigated (starting with git bisect) and fixed.
I would expect the gains from https://github.com/nim-lang/Nim/pull/18760 to be orthogonal from the gains that would occur by fixing this, so that we could further the consumption down by a factor 1.25, down to 544 Mib (speculation)

### Additional Information
* 1.5.1 5eba3725707df0f62dcf9c380eaa518635b0f0c0
* EDIT: now that https://github.com/nim-lang/Nim/pull/18760 was merged, we're back to 1.4-level usage, however the regression is still there because https://github.com/nim-lang/Nim/pull/18760 solved a pre-existing problem so there's still an additional 1.25 x factor that should be gained back

**Comment by ringabout** [comment] 2022-04-07 06:22
It seems to be caused by https://github.com/nim-lang/Nim/commit/73a8b950cb6abf36a0d29c210bb7db302ae68325

```
version                                                    refc            orc
1.4.8                                                   545.371MiB      802.953MiB
73a8b95 (regression)                                   679.039MiB     801.545MiB
devel                                                  668.125MiB      1.199GiB
```

**Comment by bung87** [comment] 2022-11-09 07:48
solved ? now orc about 614MB from recent merged PR.

**Comment by ringabout** [comment] 2022-11-09 08:50
It was solved in a different way, not sure whether the root cause was solved.

**Closed as completed** 2023-03-28 17:25 UTC
Labels: Regression, Performance
