### ISSUE TITLE
qouted variable in pramga call not properly parsed.

### ISSUE THREAD

**Issue by slangmgh** [nim-lang/Nim#10326] opened 2019-01-16 03:36 UTC
In the ``quote`` macro, variable can be quoted to reference the outer scope variable, but when using the quoted variable as parameter of pragma call, they are not be parsed properly as usually.

### Example
```nim
template id*(val: int) {.pragma.}
macro m1(): untyped =
   let x = 10
   let r = quote do:
      type T1 {.id(`x`).} = object

   echo r[0][0].treeRepr

m1()
```

### Current Output
```
PragmaExpr
  Sym "T1"
  Pragma
    Call
      Ident "id"
      Ident "3"
```

### Expected Output

```
PragmaExpr
  Sym "T1"
  Pragma
    Call
      Ident "id"
      IntLit 10
```

**Comment by krux02** [comment] 2019-01-22 15:18
duplicate of https://github.com/nim-lang/Nim/issues/9745

**Closed by krux02** 2019-01-22 15:18 UTC
Labels: Macros, quote do

**Comment by krux02** [comment] 2019-07-23 11:35
current output: 

```
PragmaExpr
  Sym "T1"
  Pragma
    Call
      Sym "id"
      IntLit 10
```
