### ISSUE TITLE
regression (1.4.0=>1.4.2, devel): `unittest.check type1 is type2` gives CT error

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/Nim#16474] opened 2020-12-26 17:16 UTC
### Example
```nim
when true:
  import unittest
  check (type(1.0)) is float
```

### Current Output
 Error: invalid type: 'type float64' for var

### Expected Output
works

### Additional Information
1.4.0: works
1.4.2: fails
devel 1.5.1 a29bbeee41e43f00ba7a3b1951445ff5d21ccc52: fails

* without parens, it fails for devel, 1.4.0, 1.2.0
```nim
  import unittest
  check type(0.1) is float
```
(for 1.2.0, the error is: unittest.nim(647, 43) Error: 'typedesc' metatype is not valid here; typed )

* with an intermediate typedef it works, but then the check error message on check fail is not as informative because it doesn't show the expression being asserted:
```nim
when true:
  import unittest
  type T = type(0.1)
  check T is float
  check T is int
```

```
t11582.nim(26, 10): Check failed: T is int
T was float64
int was int
```

**Comment by ringabout** [comment] 2020-12-27 00:37
> with parens, it fails for devel, 1.4.2

It is a kind of regression because of error-prone macros(So `testament` is preferred). (fixed)

> without parens, it fails for devel, 1.4.0, 1.2.0

It is indeed a bug. (fixed)

> with an intermediate typedef it works, but then the check error message on check fail is not as informative because it doesn't show the expression being asserted:

I'm not sure whether it is worth giving more informative messages. (I won't fix this)

**Comment by xflywind** [comment] 2020-12-27 01:13
Fortunately, the codes below don't work before.
```nim
when true:
  import unittest
  check 1i64 is float
```

**Closed as completed** 2020-12-27 08:16 UTC
Labels: Standard Library, Regression
