### ISSUE TITLE
CAS on windows seems to be incorrect

### ISSUE THREAD

**Issue by nsf** [nim-lang/Nim#3704] opened 2016-01-10 09:25 UTC
https://github.com/nim-lang/Nim/blob/master/lib/system/atomics.nim#L198

On windows CAS returns initial value of the Destination, not some arbitrary zero/non-zero number: https://msdn.microsoft.com/ru-ru/library/windows/desktop/ms683560(v=vs.85).aspx

**Comment by Araq** [comment] 2016-04-04 13:53
Duplicate of #3279

**Closed by Araq** 2016-04-04 13:53 UTC
