### ISSUE TITLE
cpp + arc causing  error: cannot jump from this goto statement to its label

### ISSUE THREAD

**Issue by jmgomez** [nim-lang/Nim#21862] opened 2023-05-18 13:51 UTC
### Description

This code:

```nim
import std/[asyncdispatch]

proc main()  =
  proc callMe() {.async.} =
    echo "hello"
    await sleepAsync(1000)
    echo "world"
  waitFor callMe()


main()
```

Fails when compiling with arc and cpp with the error below.

However, when compiling it with `refc` or `c` it works fine

I have seen this error before without using async but couldnt reproduce it anymore but I dont think it's async-related.

### Nim Version

```
Nim Compiler Version 1.9.3 [MacOSX: amd64]
Compiled at 2023-05-18
Copyright (c) 2006-2023 by Andreas Rumpf

git hash: b03ea373a2c8b3d189aad88a12e0735081157d5e
```

### Current Output

```
CC: helloworld.nim
/Volumes/Store/Dropbox/Code/Projects/nimlab/lab/nimcache/helloworld/@m..@s..@s..@s..@s..@sNim@slib@spure@sasyncfutures.nim.cpp:714:31: error: cannot jump from this goto statement to its label
                if (NIM_UNLIKELY(*nimErr_)) goto LA5_;
                                            ^
/Volumes/Store/Dropbox/Code/Projects/nimlab/lab/nimcache/helloworld/@m..@s..@s..@s..@s..@sNim@slib@spure@sasyncfutures.nim.cpp:716:49: note: jump bypasses variable initialization
                tyObject_FutureError__KNjPKOMkVazrylBrW4Vdnw* blitTmp_2 = err;
                                                              ^
/Volumes/Store/Dropbox/Code/Projects/nimlab/lab/nimcache/helloworld/@m..@s..@s..@s..@s..@sNim@slib@spure@sasyncfutures.nim.cpp:692:31: error: cannot jump from this goto statement to its label
                if (NIM_UNLIKELY(*nimErr_)) goto LA5_;
                                    /Volumes/Store/Dropbox/Code/Projects/nimlab/lab/nimcache/helloworld/@m..@s..@s..@s..@s..@sNim@slib@spure@scollections@sheapqueue.nim.cpp:292:152: error: cannot jump from this goto statement to its label
                        if ((parentpos) < ((NI)0) || (parentpos) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI(parentpos, ((NI)0), ((NI)IL64(9223372036854775807))); goto LA5_;
                                                                                                                                                                            ^
/Volumes/Store/Dropbox/Code/Projects/nimlab/lab/nimcache/helloworld/@m..@s..@s..@s..@s..@sNim@slib@spure@scollections@sheapqueue.nim.cpp:294:37: note: jump bypasses variable initialization
                        tyTuple__o0bBbmYdV2dERI6OV5Sxaw* T6_ = X5BX5D___pureZasyncdispatch_u179((&heap_p0), ((NI) (parentpos)));
                                                         ^
/Volumes/Store/Dropbox/Code/Projects/nimlab/lab/nimcache/helloworld/@m..@s..@s..@s..@s..@sNim@slib@spure@scollections@sheapqueue.nim.cpp:287:83: error: cannot jump from this goto statement to its label
                        if (nimSubInt(pos, ((NI)1), &TM__f2bNHCHm2LvO7iSrwQtdiQ_9)) { raiseOverflow(); goto LA5_;
                                                                                                       ^
/Volumes/Store/Dropbox/Code/Projects/nimlab/lab/nimcache/helloworld/@m..@s..@s..@s..@s..@sNim@slib@spure@scollections@sheapqueue.nim.cpp:294:37: note: jump bypasses variable initialization
                        tyTuple__o0bBbmYdV2dERI6OV5Sxaw* T6_ = X5BX5D___pureZasyncdispatch_u179((&heap_p0), ((NI) (parentpos)));
                                                         ^
/Volumes/Store/Dropbox/Code/Projects/nimlab/lab/nimcache/helloworld/@m..@s..@s..@s..@s..@sNim@slib@spure@scollections@sheapqueue.nim.cpp:289:7: note: jump bypasses variable initialization
                        NI parentpos = (NI)((NI64)((NI)(TM__f2bNHCHm2LvO7iSrwQtdiQ_9)) >> (NU64)(((NI)1)));
                           ^
/Volumes/Store/Dropbox/Code/Projects/nimlab/lab/nimcache/helloworld/@m..@s..@s..@s..@s..@sNim@slib@spure@scollections@sheapqueue.nim.cpp:273:132: error: cannot jump from this goto statement to its label
        if ((pos) < ((NI)0) || (pos) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI(pos, ((NI)0), ((NI)IL64(9223372036854775807))); goto LA1_;
                                                                                                                                          ^
/Volumes/Store/Dropbox/Code/Projects/nimlab/lab/nimcache/helloworld/@m..@s..@s..@s..@s..@sNim@slib@spure@scollections@sheapqueue.nim.cpp:275:35: note: jump bypasses variable initialization
        tyTuple__o0bBbmYdV2dERI6OV5Sxaw* T2_ = X5BX5D___pureZasyncdispatch_u179((&heap_p0), ((NI) (pos)));
                                         ^
3 errors generated.
        ^
Error: execution of an external compiler program 'clang++ -c -std=gnu++17 -funsigned-char  -pthread   -I/Volumes/Store/Nim/lib -I/Volumes/Store/Dropbox/Code/Projects/nimlab/lab -o /Volumes/Store/Dropbox/Code/Projects/nimlab/lab/nimcache/helloworld/@m..@s..@s..@s..@s..@sNim@slib@spure@scollections@sheapqueue.nim.cpp.o /Volumes/Store/Dropbox/Code/Projects/nimlab/lab/nimcache/helloworld/@m..@s..@s..@s..@s..@sNim@slib@spure@scollections@sheapqueue.nim.cpp' failed with exit code: 1


/Volumes/Store/Dropbox/Code/Projects/nimlab/lab/nimcache/helloworld/@m..@s..@s..@s..@s..@sNim@slib@spure@sasyncfutures.nim.cpp:716:49: note: jump bypasses variable initialization
                tyObject_FutureError__KNjPKOMkVazrylBrW4Vdnw* blitTmp_2 = err;
                                                              ^
/Volumes/Store/Dropbox/Code/Projects/nimlab/lab/nimcache/helloworld/@m..@s..@s..@s..@s..@sNim@slib@spure@sasyncfutures.nim.cpp:690:31: error: cannot jump from this goto statement to its label
                if (NIM_UNLIKELY(*nimErr_)) goto LA5_;
                                            ^
/Volumes/Store/Dropbox/Code/Projects/nimlab/lab/nimcache/helloworld/@m..@s..@s..@s..@s..@sNim@slib@spure@sasyncfutures.nim.cpp:716:49: note: jump bypasses variable initialization
                tyObject_FutureError__KNjPKOMkVazrylBrW4Vdnw* blitTmp_2 = err;
                                                              ^
/Volumes/Store/Dropbox/Code/Projects/nimlab/lab/nimcache/helloworld/@m..@s..@s..@s..@s..@sNim@slib@spure@sasyncfutures.nim.cpp:676:31: error: cannot jump from this goto statement to its label
                if (NIM_UNLIKELY(*nimErr_)) goto LA5_;
                                            ^
/Volumes/Store/Dropbox/Code/Projects/nimlab/lab/nimcache/helloworld/@m..@s..@s..@s..@s..@sNim@slib@spure@sasyncfutures.nim.cpp:716:49: note: jump bypasses variable initialization
                tyObject_FutureError__KNjPKOMkVazrylBrW4Vdnw* blitTmp_2 = err;
                                                              ^
/Volumes/Store/Dropbox/Code/Projects/nimlab/lab/nimcache/helloworld/@m..@s..@s..@s..@s..@sNim@slib@spure@sasyncfutures.nim.cpp:674:31: error: cannot jump from this goto statement to its label
                if (NIM_UNLIKELY(*nimErr_)) goto LA5_;
                                            ^
/Volumes/Store/Dropbox/Code/Projects/nimlab/lab/nimcache/helloworld/@m..@s..@s..@s..@s..@sNim@slib@spure@sasyncfutures.nim.cpp:716:49: note: jump bypasses variable initialization
                tyObject_FutureError__KNjPKOMkVazrylBrW4Vdnw* blitTmp_2 = err;
                                                              ^
/Volumes/Store/Dropbox/Code/Projects/nimlab/lab/nimcache/helloworld/@m..@s..@s..@s..@s..@sNim@slib@spure@sasyncfutures.nim.cpp:672:31: error: cannot jump from this goto statement to its label
                if (NIM/Volumes/Store/Dropbox/Code/Projects/nimlab/lab/nimcache/helloworld/@mhelloworld.nim.cpp:649:30: error: cannot jump from this goto statement to its label
        if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
                                    ^
/Volumes/Store/Dropbox/Code/Projects/nimlab/lab/nimcache/helloworld/@mhelloworld.nim.cpp:650:82: note: jump bypasses variable initialization
        tyObject_Env_asyncmacrodotnim_callMeX20X28AsyncX29___AY9bkjC9b9bvoV0KM3Lo2giow* blitTmp = colonenv__2;
                                                                                        ^
/Volumes/Store/Dropbox/Code/Projects/nimlab/lab/nimcache/helloworld/@mhelloworld.nim.cpp:643:30: error: cannot jump from this goto statement to its label
        if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
                                    ^
/Volumes/Store/Dropbox/Code/Projects/nimlab/lab/nimcache/helloworld/@_UNLIKELY(*nimErr_)) goto LA5_;
                                            ^
/Volumes/Store/Dropbox/Code/Projects/nimlab/lab/nimcache/helloworld/@m..@s..@s..@s..@s..@sNim@slib@spure@sasyncfutures.nim.cpp:716:49: note: jump bypasses variable initialization
                tyObject_FutureError__KNjPKOMkVazrylBrW4Vdnw* blitTmp_2 = err;
                                                              ^
/Volumes/Store/Dropbox/Code/Projects/nimlab/lab/nimcache/helloworld/@m..@s..@s..@s..@s..@sNim@slib@spure@sasyncfutures.nim.cpp:651:31: error: cannot jump from this goto statement to its label
                if (NIM_UNLIKELY(*nimErr_)) goto LA5_;
                                            ^
/Volumes/Store/Dropbox/Code/Projects/nimlab/lab/nimcache/helloworld/@m..@s..@s..@s..@s..@sNim@slib@spure@sasyncfutures.nim.cpp:716:49: note: jump bypasses variable initialization
                tyObject_FutureError__KNjPKOMkVazrylBrW4Vdnw* blitTmp_2 = err;
```

### Possible Solution

Use `inc p.splitDecls` in the scenario that triggers this? Doenst feel like a good solution though

**Comment by jmgomez** [comment] 2023-05-18 14:15
Just calling `pol(0)` reproduces it

**Comment by jmgomez** [comment] 2023-05-18 14:32
It's seems to happen when pulling* `selectors.nim`. When adding: `--exceptions:cpp` it doesnt fail so may it be a recent change on the default exceptions? Anyways, it seems like there is an underlaying issue

**Comment by ghost** [comment] 2023-05-18 20:10
@jmgomez are you compiling like `nim cpp file.nim` or `nim c --backend:cpp file.nim`? Right now the latter doesn't set the exceptions to C++ by default

**Comment by ghost** [comment] 2023-05-18 20:10
Also yeah, probably a duplicate of https://github.com/nim-lang/Nim/issues/21579

**Comment by jmgomez** [comment] 2023-05-18 21:49
Ouch, yes. Do you know if there is an issue opened for the `backend:cpp`?

If that's the case the `inc p.splitDecls` solution doesnt sound that bad. At least, it probably would work. Im not sure how (probably using backend:cpp?) but when doing 'virtual' at some point I hit it and that fixed it. Got rid of it because wasnt able to reproduce it anymore 

If is there a way in the compiler to know if a proc uses exceptions (probably there is a flag somewhere?) maybe it will worth it.

**Comment by metagn** [comment] 2023-05-19 12:43
Does this work with `--exceptions:cpp`? If so, is there a reason ARC doesn't use C++ exceptions by default?

> a way in the compiler to know if a proc uses exceptions 

There is `sfNeverRaises` I think

**Comment by ghost** [comment] 2023-05-19 13:00
@metagn as I said in my issue, it's a (bug?) with `--backend:cpp` - it doesn't change exceptions to cpp unlike doing `nim cpp`.

**Comment by heterodoxic** [comment] 2023-05-19 13:50
@jmgomez I think you're on the right track with increasing `splitDecls` of the current proc/func! Yet, I suspect checking the `nimErrorFlagAccessed` flag might be what we're looking for in order to avoid violating [ISO C++'s rule §6.7.3](https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2011/n3242.pdf) (p. 136), as it's only set for goto based exception handling.

Let me see if I can arrange a PR for a potential fix...

**Comment by jmgomez** [comment] 2023-05-19 16:50
@heterodoxic just saw your fix, thanks!
Does `nimErrorFlagAccessed` only used by goto? Otherwise everyone else will be paying the price.

**Closed as completed** 2023-05-19 19:24 UTC

**Comment by Araq** [comment] 2023-05-21 02:56
> Does nimErrorFlagAccessed only used by goto? Otherwise everyone else will be paying the price.

It is only used by exceptions:goto.

**Comment by heterodoxic** [comment] 2023-05-22 10:22
> @heterodoxic just saw your fix, thanks! Does `nimErrorFlagAccessed` only used by goto? Otherwise everyone else will be paying the price.

Sorry for my rather latish reply: the question I am pondering is, what do we mean by "price" here: I figure one could split this threefold to explicate different aspects:

- does my solution involve **runtime** performance costs? It's the same as if splitDecls were > 0, so there might occur some tiiiiny overhead in debug mode, but by ISO C++ standard rule, I see no other way around, but it will only be applied to those procs that need goto exception handling. 
- does my solution involve **compile time** costs? Sure, we pay for an additional set lookup here, but this is mostly due to
- the "**cognitive**/**architectural**" cost of keeping goto exceptions as an option around

I hope this helps levelling what we might understand under "paying a price" here.

**Comment by jmgomez** [comment] 2023-05-22 12:13
Thanks, my only concern was if it's `goto`'s specific.
