### ISSUE TITLE
tuple unpacking doesn't work with const (works with var,let)

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/Nim#9885] opened 2018-12-07 05:36 UTC
```nim
#[
KEY tuple
tuple unpacking doesn't work with const (works with var,let)
]#

proc fun(): auto=
  result = (a1:"foo1", a2: "foo2")

proc main()=
  block:
    let (a1,a2) = fun()
  block:
    var (a1,a2) = fun()
  block:
    # Error: identifier expected, but got '('
    const (a1,a2) = fun()

main()

```

**Comment by GULPF** [comment] 2018-12-07 06:18
Duplicate of #6355

**Closed by GULPF** 2018-12-07 06:18 UTC
Labels: const, tuple
