### ISSUE TITLE
--stacktrace:off does not disable stacktrace

### ISSUE THREAD

**Issue by alaviss** [nim-lang/Nim#11619] opened 2019-06-29 04:54 UTC
In #9480, the switch `--stacktrace:off` has been implemented to have a minimal stacktrace. This, however, go against what `--stacktrace:off` means (stacktrace disabled).

### Example
```nim
raise newException(Exception, "test")
```

### Current Output
```
test.nim(1)              test
Error: unhandled exception: test [Exception]
```

### Expected Output
```
Error: unhandled exception: test [Exception]
```

### Possible Solution
Change the current `--stacktrace:off` to `--stacktrace:minimal`, and set it as the default in `config/nim.cfg` for release mode to preserve the current behavior.

If accepted, I could implement this.

### Additional Information
```
$ nim -v
Nim Compiler Version 0.20.99 [Linux: amd64]
Compiled at 2019-06-29
Copyright (c) 2006-2019 by Andreas Rumpf

git hash: 3606e035f5f4d688876a83f824f7e7b3ac4ff083
active boot switches: -d:release -d:useLinenoise -d:nativeStackTrace
```

**Comment by Araq** [comment] 2019-06-29 19:35
I don't understand this, ``--stacktrace:off`` should mean "stacktrace off". Please fix this bug.

**Comment by cooldome** [comment] 2019-06-30 13:16
This is not a bug, just for raise Exception these is one level of line info in release m ode. It is not using stacktrace.
See feature description. https://github.com/nim-lang/Nim/issues/9434

**Comment by cooldome** [comment] 2019-06-30 13:16
Closed as not a bug

**Closed by cooldome** 2019-06-30 13:16 UTC
