### ISSUE TITLE
Range types + generic container: matching issue

### ISSUE THREAD

**Issue by mratsim** [nim-lang/Nim#7872] opened 2018-05-24 13:35 UTC
Potentially related to https://github.com/nim-lang/Nim/issues/7447.

Range types do not match with the base type when assigning to a generic container.

```Nim
type
  PriceKind = enum
    pkLow, pkHigh

  Price = range[0'i64 .. high(int64)]

  PriceTable = array[PriceKind, Price]

  PriceTable_no_range = array[PriceKind, int64]


# Works
const a: Price = 10'i64

# Works
const priceTable_norange: PriceTable_no_range = [
  pkLow: 10'i64,
  pkHigh: 10000
]

# Doesn't work - Error: type mismatch: got <array[0..1, int64]> but expected 'PriceTable = array[PriceKind, Price]'
const priceTable: PriceTable = [
  pkLow: 10'i64,
  pkHigh: 10000
]
```

**Comment by Araq** [comment] 2018-05-25 07:14
Duplicate of #7447.

**Closed by Araq** 2018-05-25 07:14 UTC
Labels: Generics, Range
