### ISSUE TITLE
export doesn't export intermediate explicit exports

### ISSUE THREAD

**Issue by gradha** [nim-lang/Nim#1054] opened 2014-03-30 11:31 UTC
The following set of files doesn't compile. Contents of `supernake.nim`:

``` nimrod
import nake
export nake

proc say_hello*() =
  echo "Hi!"
```

Contents of `nake.nim`:

``` nimrod
import supernake

task "hello", "Says hello":
  say_hello()
```

Compilation:

```
$ nake
/Users/gradha/.babel/pkgs/nake-1.2/nake.nim(89, 7) Error: type mismatch: got (TTable[string, PTask], string, PTask)
but expected one of: 
system.[]=(a: var array[Idx, T], x: TSlice[Idx], b: openarray[T])
system.[]=(a: var array[Idx, T], x: TSlice[int], b: openarray[T])
system.[]=(s: var string, x: TSlice[int], b: string)
system.[]=(s: var seq[T], x: TSlice[int], b: openarray[T])
```

The problem is that `nake.nim` exports some modules itself for the templates to work. One solution to this problem is to reimport and reexport those, modifying the `supernake.nim` file to:

``` nimrod
import nake
export nake
# Propagate exports
import strutils, parseopt, tables, os, rdstdin
export strutils, parseopt, tables, os, rdstdin

proc say_hello*() =
  echo "Hi!"
```

Should `export` automatically propagate explicit intermediate exports too?

**Comment by andreaferretti** [comment] 2018-06-26 08:20
I am not sure where the issue is. Without the `task` template, the example works fine for me, i.e.

```nim
#supernake.nim
import nake
export nake

proc say_hello*() =
  echo "Hi!"
```

```nim
#nake.nim
import supernake

say_hello()
```

Now, it seems that the problem is related to something that happens with the actual [nake](https://github.com/fowlmouth/nake), in particular the `task` template, but the code here is not enough to reproduce the issue and I cannot figure out what it is.

Is this issue still present?

**Comment by andreaferretti** [comment] 2018-10-10 08:28
As far as I can reproduce, this is fixed by now. As I mentioned above, the example given works just fine, apart from the `task` template.

I don't know whether the original example was intended to involve the actual nake - in this case, the example file should be called `nakefile.nim` and should `import nake`. Modifiying the example like this

```nim
#nakefile.nim
import nake
import supernake

task "hello", "Says hello":
  say_hello()
```

**also** works.

I am closing, but feel free to reopen if I missed something

**Closed by andreaferretti** 2018-10-10 08:28 UTC
Labels: Feature, Low Priority
