### ISSUE TITLE
rand(T.low .. T.high) only works for integers of type uint8 and uint16

### ISSUE THREAD

**Issue by mjoud** [nim-lang/Nim#10258] opened 2019-01-10 11:02 UTC
I get various errors trying to get a random integer of a specific integer type. Only `rand(uint8.low .. uint8.high)` and `rand(uint16.low .. uint16.high)` works.

### Example

```nim
import random, typetraits

proc test[T](n: int = 100) =
  echo T
  for i in 0..<n:
    echo rand(T.low .. T.high)

test[uint8]()  # works
test[uint16]()  # works

# uint32:
#     test.nim(10)             test
#     test.nim(6)              test
#     random.nim(156)          rand
#     random.nim(152)          rand
#     system.nim(2922)         sysFatal
#     Error: unhandled exception: value out of range: -1 [RangeError]

# uint64, uint:
#     test.nim(18, 5) template/generic instantiation from here
#     test.nim(6, 16) Error: type mismatch: got <type uint>
#     but expected one of:
#     proc low(T: typedesc[SomeFloat]): T:type
#     ...

# int8, int16, int32, int64, int:
#     test.nim(14)             test
#     test.nim(6)              test
#     random.nim(156)          rand
#     random.nim(152)          rand
#     system.nim(2916)         sysFatal
#     Error: unhandled exception: over- or underflow [OverflowError]
```

### Expected Output
A random integer of type T.

### Additional Information
Nim 0.19.2, Windows i386

**Comment by krux02** [comment] 2019-01-10 11:17
On 64 bit system `test[uint32]()` works, too. But that is not the point. It is pretty tough to get it correct for unsigned integers. And if you just want random bits, then `proc next*(r: var Rand): uint64` is the procedure of choice for you.

I suggest to expose a function ``proc next*(): uint64`` that uses the global random state (maybe with a different name), for you use case, and restrict the `rand` procedure to signed integer types only. Then it is clear that unsigend isn't supported properly.

**Comment by mjoud** [comment] 2019-01-10 11:31
Sure thing, but I think something like `rand[T](): T` or `rand(T): T` would be convenient.

**Comment by krux02** [comment] 2019-01-10 11:35
@mjound. That might be the simpler solution. `proc rand[T : SomeInteger](t: typedesc[T]): T` just for random bits of all integer kinds.

**Comment by mratsim** [comment] 2019-01-10 16:13
This is not random related, it's actually a duplicate of https://github.com/nim-lang/Nim/issues/725 and https://github.com/nim-lang/Nim/issues/6620: no high/low for the biggest unsigned int

**Comment by krux02** [comment] 2019-01-10 17:56
@mratsim well I would say this is a symptom of the issues you just listed.

**Closed** 2019-01-14 08:20 UTC
Labels: unsigned

**Comment by Araq** [comment] 2019-01-14 08:21
The more general issue is a language spec/implementation problem that will also be addressed but it's also been reported.
