### ISSUE TITLE
Get rid of all the prefixed (TFoo) types in the stdlib

### ISSUE THREAD

**Issue by reactormonk** [nim-lang/Nim#2773] opened 2015-05-21 17:24 UTC
Don't forget to add a type alias via

```
type Foo = ... 
type Bar = ...
{.deprecated: [TFoo: Foo, TBar: Bar].}
```

**Comment by Perelandric** [comment] 2015-05-21 21:13
I'll work on this if no one else is on it.

**Comment by reactormonk** [comment] 2015-05-22 04:59
Sure, go for it.

**Comment by dom96** [comment] 2015-05-22 13:37
@Perelandric That would be incredibly helpful, thanks!

**Comment by Perelandric** [comment] 2015-06-06 16:21
*Notes from merged PR:*

Wasn't able to change `TGenericSeq`, `TNimType`, `TSafePaint` or `TFrame` successfully.

Some files contain types that cause conflict if the `T` is dropped:

-    lib/posix/posix.nim
-    lib/wrappers/expat.nim
-    lib/wrappers/libuv.nim
-    lib/wrappers/odbcsql.nim
-    lib/wrappers/zzip.nim
-    lib/windows/windows.nim
- lib/wrappers/sdl/sdl.nim

Search for the word "conflict" in each file to find the conflicting types.

**Comment by dom96** [comment] 2015-06-08 00:26
Perhaps the conflicting ones should be changed to ``FooObj``?

**Comment by Perelandric** [comment] 2015-06-08 03:05
@dom96: Some (maybe most?) of the conflicts are with enum variants that don't have a prefix as required by the code style guidelines. Maybe it's worth changing those names.

**Comment by dom96** [comment] 2015-06-20 10:53
@Perelandric I would say so, yeah.

**Comment by Perelandric** [comment] 2015-06-22 01:19
@dom96 Only one existing file had naming conflicts due to unprefixed enum variants. That file has been updated with the old types deprecated. I can't deprecate the usage of the old variants, so those constitute a breaking change. (I updated `news.txt`.)

Other files had conflicts that need a decision and some files no longer exist. (See below.)

I'll submit the PR in a day or less.

**EXISTING FILES**

lib/wrappers/libuv.nim
 - [x] `enum HandleType` variants have been changed to use `ht` prefix.

lib/wrappers/odbcsql.nim
 - [ ] `type TSqlChar*` conflicts with `const SQL_CHAR*`
 - [ ] `type TSqlSmallInt*` conflicts with `const SQL_SMALLINT*`
 - [ ] `type TSqlInteger*` conflicts with `const SQL_INTEGER*`
 - [ ] `type TSqlReal*` conflicts with `const SQL_REAL*`
 - [ ] `type TSqlDouble*` conflicts with `const SQL_DOUBLE*`
 - [ ] `type TSqlFloat*` conflicts with `const SQL_FLOAT*`

lib/posix/posix.nim
 - [ ] `type Tflock*` conflicts with `var F_LOCK*`
 - [ ] `type TFdSet*` conflicts with `proc FD_SET*`

**NON-EXISTENT FILES**

 - lib/wrappers/expat.nim
 - lib/wrappers/zip/zzip.nim
 - lib/windows/windows.nim
 - lib/wrappers/sdl/sdl.nim

**Comment by dom96** [comment] 2015-06-22 20:46
> type TFdSet* conflicts with proc FD_SET*

This one is simple. Procedure names should all begin with a lower case letter.

**Comment by Perelandric** [comment] 2015-06-22 20:52
@dom96 That's fine, but then do we change the other procs with the same sort of naming as well to be consistent?

In the immediate area, there are `FD_CLR`, `FD_ISSET`, and `FD_ZERO` but there are several others as well. If so, I'll update them all at once.

**Comment by dom96** [comment] 2015-06-22 20:54
Yes. You might want to double check with @Araq, but this is something we should definitely start enforcing in the standard library. There should be no procedures that begin with a capital letter.

**Comment by Perelandric** [comment] 2015-06-22 21:04
I'll wait for the alls-clear from one of you. 

Thought maybe we could make all the `SQL_CHAR` consts into enums, but now it seems there's some overlap in their values. :-(

**Comment by Perelandric** [comment] 2015-06-22 23:50
@dom96 @Araq 

When I tried renaming and deprecating all the ALL_CAPS procs in `posix.nim`, I was unable to build. I'd get a bunch of lines like this:
```
compiler_koch.c:(.text+0x343b): undefined reference to `s_islnk'
```
and then a:
```
collect2: error: ld returned 1 exit status
```

Seems like the new names given in the `deprecated` pragma aren't picked up. I'll leave it alone for now unless you have any advice.

**Comment by dom96** [comment] 2015-06-23 18:48
@Perelandric Can you reproduce this and give us a short code sample? It's a bug if the C compiler fails.

**Comment by Perelandric** [comment] 2015-06-23 19:46
@dom96 Yes. I'll do that before anything else. Hopefully today.

**Comment by dom96** [comment] 2016-04-04 20:30
What's the status of this issue?

**Comment by Varriount** [comment] 2016-04-13 18:38
Aside from the compiler internals, it's pretty much done.

**Comment by dom96** [comment] 2016-06-09 17:20
There are also some "official" nimble packages which use prefixes, for example https://github.com/nim-lang/x11

**Comment by dom96** [comment] 2017-11-28 15:32
Marking high priority because it's about time we resolve this.

**Comment by Araq** [comment] 2018-02-11 13:58
Open issues in the nimble packages' issue trackers instead.

**Closed by Araq** 2018-02-11 13:58 UTC
Labels: Easy, High Priority, Stdlib

**Comment by GULPF** [comment] 2018-02-23 20:58
I don't think this was finished. I did a regex search in the stdlib using `\b[PT][A-Z][a-z]\w+\*` and it looks like there are still a lot of types that should be renamed. There's also a few error types that still use the `EName` style of naming instead of the newer `NameError`.

**Comment by Yardanico** [comment] 2018-02-23 20:59
@GULPF this issue is about TFoo types in stdlib, not in the compiler, and if you found these - make a PR :)
