### ISSUE TITLE
homebrew nim HEAD broken: Error: invalid command line option: '--hint'

### ISSUE THREAD

**Issue by anta40** [nim-lang/Nim#18117] opened 2021-05-28 13:34 UTC
I have nim on macOS Big Sur installed via Homebrew (the HEAD version).

When running `brew update`, I got these:
```
nim HEAD-22e06ee -> HEAD-22e06ee
==> Upgrading nim HEAD-22e06ee -> HEAD-22e06ee 
==> Cloning https://github.com/nim-lang/csources.git
Updating /Users/anta40/Library/Caches/Homebrew/nim--csources--git
==> Checking out branch master
Already on 'master'
Your branch is up to date with 'origin/master'.
HEAD is now at 64e34778 Update readme.markdown
==> Cloning https://github.com/nim-lang/Nim.git
Updating /Users/anta40/Library/Caches/Homebrew/nim--git
==> Checking out branch devel
Already on 'devel'
Your branch is up to date with 'origin/devel'.
HEAD is now at d62a298a2 fix typo in ci/funs.sh (#18115)
...
...
...
/private/tmp/nim-20210528-7165-seu30s/config/nim.cfg(16, 1) Error: invalid command line option: '--hint'
```

Not sure how this relates with this commit:
https://github.com/nim-lang/Nim/pull/18085

**Comment by timotheecour** [comment] 2021-05-29 02:49
> Not sure how this relates with this commit:

no, the problem is that csources shouldn't be used anymore for newer nim versions and the brew formula for HEAD needs to be updated (for stable it still works)

HEAD should install via `sh build_all.sh` (forward compatible), PR against homebrew welcome, see https://github.com/Homebrew/homebrew-core/blob/master/Formula/nim.rb; happy to help review whoever wants to write a PR against homebrew

we should keep this issue opened until that PR is merged though

**Comment by timotheecour** [comment] 2021-05-29 03:34
@anta40 can you try this? https://github.com/Homebrew/homebrew-core/pull/78297

**Comment by anta40** [comment] 2021-05-29 17:37
> @anta40 can you try this? [Homebrew/homebrew-core#78297](https://github.com/Homebrew/homebrew-core/pull/78297)

Sure. I read that a few times, but still not sure what to do.
I assume it's not merely running `brew upgrade`... yes?

**Comment by timotheecour** [comment] 2021-05-29 18:07
no you'd have to try the formula directly; or just wait for that PR to be merged.

**Comment by timotheecour** [comment] 2021-05-29 19:00
fixed via https://github.com/Homebrew/homebrew-core/pull/78297

**Closed as completed by timotheecour** 2021-05-29 19:00 UTC
Labels: Installation

**Comment by anta40** [comment] 2021-05-31 03:30
Got it. I ran `brew upgrade` again, now it compiles nim fine.
