### ISSUE TITLE
Missing bracket results in complier giving indentation error but does not mention the bracket

### ISSUE THREAD

**Issue by HeliumEnd** [nim-lang/Nim#16232] opened 2020-12-02 15:22 UTC
Compiling the example below

```
proc tuple_fib_internal(n: int, mem: (int, int)): (int, (int, int)) =
  ((n-1), (mem[1], mem[0] + mem[1])
```

Results in the error

```
example.nim(2, 1) Error: invalid indentation
```

The error does not help solve the problem.

Changing the example to

```
proc tuple_fib_internal(n: int, mem: (int, int)): (int, (int, int)) = ((n-1), (mem[1], mem[0] + mem[1])
```

gives an error that does help solve the problem

```
example.nim(2, 104) Error: expected: ')', but got: '[EOF]'
```

In all the brackets, I did not realise I was missing one. If getting the indentation error is intended, I believe it would be better if it mentioned that the a bracket is missing.

```
$ nim -v
Nim Compiler Version 1.4.2 [MacOSX: amd64]
Compiled at 2020-12-02
Copyright (c) 2006-2020 by Andreas Rumpf

active boot switches: -d:release

**Comment by timotheecour** [comment] 2020-12-03 02:57
duplicate of https://github.com/nim-lang/Nim/issues/15667; we really need to fix this since it keeps tripping people over

**Closed as completed by timotheecour** 2020-12-03 02:57 UTC
