### ISSUE TITLE
[ARC] Crash when adding openArray proc argument to a local seq

### ISSUE THREAD

**Issue by ghost** [nim-lang/Nim#15511] opened 2020-10-07 12:10 UTC
Found in https://github.com/paranim/pararules. Seems to be caused by the fact that system.add uses move here?

### Example
```nim
type
  Position = object
    data: seq[float]

proc test(data: openArray[float]) = 
  var pos = Position()
  pos.data.add(data)

test([1.5, 1.6])
```

### Current Output
```
Traceback (most recent call last)
/home/dian/Projects/stuff/a.nim(9) a
/home/dian/Projects/stuff/a.nim(7) test
/home/dian/Things/Nim/lib/system.nim(1242) add
SIGSEGV: Illegal storage access. (Attempt to read from nil?)
```

### Expected Output
Nothing

```
$ nim -v
Nim Compiler Version 1.3.7 [Linux: amd64]
Compiled at 2020-10-07
Copyright (c) 2006-2020 by Andreas Rumpf

git hash: acbe27b082c202895df1b78a82951389b4a232a0
active boot switches: -d:release -d:danger
```

**Comment by ghost** [comment] 2020-10-08 21:20
@Araq is it correct that after this PR the compiler fails on this line https://github.com/paranim/paranim/blob/master/src/paranim/gl/entities.nim#L111 with an error
"/home/dian/.nimble/pkgs/paranim-0.9.0/paranim/gl/entities.nim(110, 23) Error: cannot create an implicit openArray copy to be passed to a sink parameter" ?

EDIT: Noticed that the test case gives the same error :)

**Comment by ghost** [comment] 2020-10-08 21:20
so it means that arc/orc is a bit incompatible with refc in this case?

**Comment by Araq** [comment] 2020-10-09 06:51
For now. Working on a better fix.

**Comment by timotheecour** [comment] 2020-10-31 15:57
an error is better than SIGSEGV but this is still something that should be fixed, it makes nim-regex pkg unusable with --gc:arc
see https://github.com/nitely/nim-regex/issues/81
and who knows what other code

further reduced:
```nim
when true: # D20201031T170455
  proc fn(a: openArray[int]) =
    var b: seq[int]
    b.add a
  fn(@[1,2])
```
gives `Error: cannot create an implicit openArray copy to be passed to a sink parameter` (since the above PR that removes the SIGSEGV), but this should work

## proposal
* reopen/re-consider https://github.com/nim-lang/Nim/pull/12048
this is a general solution that allows adding overloads using arbitrary conditions, which would solve this issue without compromising performance:
```nim
# in system.nim
proc add*[T](x: var seq[T], y: sink openArray[T]) {.noSideEffect.} {.enableIf: canSink(y)).} =
  ...
  x[xl+i] = move y[i]
proc add*[T](x: var seq[T], y: openArray[T]) {.noSideEffect.} {.enableIf: not canSink(y).} =
  ...
  x[xl+i] = y[i]
```
`canSink` can be implemented in different ways, for eg:
```nim
proc canSinkImpl[T](y: sink openArray[T]) = discard
template canSink(a): untyped = compiles(canSinkImpl(y))
```
or without `compiles` using `overloadExists`, which is cheaper, via https://github.com/nim-lang/Nim/pull/12076

**Comment by Araq** [comment] 2020-11-02 11:06
The fix that I have in mind is to implement the alias analysis to prevent the bug and keep the system.nim's add a non-sink parameter as ``sink openArray[T]`` is a misguided construct, an openArray is a view-type, it never owns and ``sink`` always owns. A contradiction.

**Comment by timotheecour** [comment] 2020-11-02 11:34
> sink openArray[T] is a misguided construct, an openArray is a view-type, it never owns

but then you'll have to duplicate each proc accepting a sink parameter with `y: openArray[T]`, `y: sink seq[T]` overload to avoid copies when the whole container can be sinked, eg a seq or array;

Also, it's not clear how that'd work with array's (we don't want to generate code bloat by being generic on array size), eg:

```nim
var s = @[A(1), A(2)]
s.add [A(3), A(4)] # I want to move, not copy, A(3), A(4)
```

The problem is that `openArray` loses some type information: whether original container can be passed to a sink.
There must be a better way.

**Comment by Araq** [comment] 2020-11-02 11:58
Well yes, it's complex.

**Comment by cooldome** [comment] 2020-11-05 21:05
Possibly we need:
```nim
proc add*[T](x: var seq[T], y: sink (seq[T] | array[any, T]))
```

We can have a common type name alias for `seq[T] | array[any, T])`
I know `array[any, T]` doesn't work for now, but we can make it work.

P.S.
`varargs` remains one question

**Comment by cooldome** [comment] 2020-11-05 21:25
Actually this may work, 2 procs:
```nim
proc add*[T](x: var seq[T], y: sink (seq[T] | array[any, T]))
proc add*[T](x: var seq[T], y: openarray[T])
```
and make sink to match better.
 Copy to opennarray/varargs to seq  sounds easier though.

**Comment by timotheecour** [comment] 2020-11-05 21:41
`proc add*[T](x: var seq[T], y: sink (seq[T] | array[any, T]))` generates code bloat (1 instantiation per array size)

the solution I suggested in https://github.com/nim-lang/Nim/issues/15511#issuecomment-719952709 doesn't have this problem.

**Comment by Araq** [comment] 2021-02-24 15:29
Has been fixed.

**Closed as completed by Araq** 2021-02-24 15:29 UTC
Labels: ARC/ORC Memory Management

**Comment by ringabout** [comment] 2023-07-05 05:54
!nim c --gc:arc
```nim
type
  Position = object
    data: seq[float]

proc test(data: openArray[float]) = 
  var pos = Position()
  pos.data.add(data)

test([1.5, 1.6])
```
