### ISSUE TITLE
asm.js and WebAssembly

### ISSUE THREAD

**Issue by kirbyfan64** [nim-lang/Nim#2960] opened 2015-06-19 16:57 UTC
The vibe I got is that Nim currently outputs normal JS code. What about emitting asm.js code for functions that don't use the `asm` keyword? asm.js tends to be much faster than normal JS.

In addition, now there's WebAssembly, which could potentially make the code even faster.

**Comment by reactormonk** [comment] 2015-06-19 18:51
Ohh, more binary blobs via WebAssembly. Eh. Anyway, duplicate of https://github.com/nim-lang/Nim/issues/371

**Closed by reactormonk** 2015-06-19 18:51 UTC
