### ISSUE TITLE
Lint/style error reported for explicit module name when there's a type collision

### ISSUE THREAD

**Issue by snluu** [nim-lang/Nim#12955] opened 2019-12-23 23:24 UTC
### Example

```nim
# fileinfo.nim
type FileInfo* = object
```

```nim
# main.nim
import os
import fileinfo

# This next line has name collision
# var xs: seq[FileInfo]

# This next line causes the linter to bark
var xs: seq[fileinfo.FileInfo]
```
### Current Output
```
main.nim(9, 21) Hint: 'fileinfo' should be: 'FileInfo'
```

### Possible Solution

Alias the module to something else that the linter won't bark at (such as `fi`)

### Version:
```
$ nim -v
Nim Compiler Version 1.0.4 [MacOSX: amd64]
```

**Comment by ringabout** [comment] 2021-03-29 12:02
I can't reproduce this issue on Linux and Windows with `nim check`,

**Comment by timotheecour** [comment] 2021-03-29 18:38
@xflywind problem is still there, you need to pass `--stylecheck:hint` or `--stylecheck:error`


as of 861c42c258ee81ff20630fdaa49813de5311881d 1.5.1

**Comment by ringabout** [comment] 2022-08-14 14:31
Works on devel, it is probably fixed by https://github.com/nim-lang/Nim/pull/19356

**Closed** 2022-08-15 10:50 UTC
Labels: Error messages
