### ISSUE TITLE
Declaring a Channel as a threadvar will cause the program to instantly crash.

### ISSUE THREAD

**Issue by kayabaNerve** [nim-lang/Nim#9314] opened 2018-10-11 13:25 UTC
```
echo 1
proc a() =
    var channel {.threadvar.}: Channel[string]
a()
echo 2
```

Of course, a Channel should never be a threadvar. That said, the program should not instantly crash. I did it by accident while setting a bunch of things to threadvar.

**Comment by LemonBoy** [comment] 2018-10-11 18:47
Cannot reproduce this with both the "real" and the emulated TLS

**Comment by kayabaNerve** [comment] 2018-10-11 23:08
I used Nim 19.0 on Windows. It may be platform specific. `nim c --threads:on -r test.nim`

**Comment by Araq** [comment] 2018-10-13 18:01
I think this error message should use ``rawWrite`` or similar. We know threading is not yet available when this TLS-check fails.

**Comment by kayabaNerve** [comment] 2018-10-24 18:58
When you compile it and run it, it crashes with `too large thread local storage size requested (26528/16008). Use -d:"nimTlsSize=26528" to preallocate sufficient storage.`

If you compile it with `-d:"nimTlsSize=26528"`, it works fine. That said, the Channel is unusable since it's a threadvar and it never should be a threadvar. That said, we can chalk that up to the user being the idiot, and not an issue with the compiler itself.

**Comment by narimiran** [comment] 2019-09-13 09:28
> I used Nim 19.0 on Windows. It may be platform specific.

I cannot reproduce it on Linux. @kayabaNerve can you please check if the problem is still there with the latest Nim?

**Comment by kayabaNerve** [comment] 2019-09-13 21:16
Unfortunately, I don't have a Windows dev environment as of right now. Sorry.

**Comment by narimiran** [comment] 2020-07-09 12:47
Nobody confirmed this is still problem on Windows in last 10 months. Closing.

(We can reopen if somebody reproduces)

**Closed by narimiran** 2020-07-09 12:47 UTC
Labels: Threads

**Comment by ringabout** [comment] 2020-07-09 12:56
In win10:
```
nim c -r --threads:on t_day.nim
```

```
too large thread local storage size requested,
use -d:\"nimTlsSize=X\" to setup even more or stop using unittest.nimError: execution of an external program failed: 'D:\QQPCmgr\Desktop\iNim\cookbook\t_day.exe 
```

```
D:\QQPCmgr\Desktop\iNim\cookbook>nim -v
Nim Compiler Version 1.3.5 [Windows: amd64]
Compiled at 2020-07-01
Copyright (c) 2006-2020 by Andreas Rumpf
```

**Comment by ringabout** [comment] 2020-07-09 12:58
It works in gc:arc.
```
nim c -r --gc:arc --threads:on t_day.nim
```
Output:
```
1
2
```
