### ISSUE TITLE
Segfault in popFrame()

### ISSUE THREAD

**Issue by Parashurama** [nim-lang/Nim#4205] opened 2016-05-22 21:07 UTC
Using the tcc compiler in debug mode, I get a segfault consistently in the same place inside  popFrame()
using gdb I can see the framepointer variable appear to be NULL.
EDIT: the problem is only triggered if using --stackTrace:on with tcc . (--stackTrace:off on debug mode doesn't crash)
*No segfaults using gcc or clang at all, in any mode.*
It was initially triggered by adding a single call to this function inside an unrelated proc. 
```nim
proc split*(x: xAnchor): tuple[valign:xValign, halign:xHalign] =
    ## split anchor into its components (valign, halign)
    result[0] = xValign(x.uint and ANCHOR_Y_COMPONENT.uint)
    result[1] = xHalign(x.uint and ANCHOR_X_COMPONENT.uint)
```
It may be due to a difference in tcc specific code somewhere or even a bug inside tcc. Although I did try their latest devel and got the same error but in a different place.

I can't seems to reproduce the issue in a smaller testfile, even at depth dangerously closed to the hardcoded limit in the compiler proc ``nimFrame``.

here is the gdb traceback.
```gdb
#0  0x000000000053984f in popFrame ()
#1  0x0000000000532834 in Dialogonupdateuntyped_977405_3298800013 ()
    at /.../NimGui/examples/nimcache/NimGui_dialog.c:4732
#2  0x00000000005328f5 in onupdate_977401_3298800013 ()
    at /.../NimGui/examples/nimcache/NimGui_dialog.c:4747
#3  0x000000000073d110 in onupdate_937847_4076800905 ()
    at /.../NimGui/examples/nimcache/NimGui_test_gui.c:8314
#4  0x0000000000521f13 in updategui_966236_1513908488 ()
    at /.../NimGui/examples/nimcache/NimGui_manager.c:1057
#5  0x0000000000522393 in renderunbuffered_966265_1513908488 ()
    at /.../NimGui/examples/nimcache/NimGui_manager.c:1138
#6  0x000000000072c879 in render_1029680_1916730547 ()
    at /.../NimGui/examples/nimcache/NimGui_test_gui.c:3827
#7  0x000000000073dcc1 in render_944052_2648699161 ()
    at /.../NimGui/examples/nimcache/NimGui_test_gui.c:8479
#8  0x00000000005ad66e in run_944054_2648699161 ()
    at /.../NimGui/examples/nimcache/NimGui_base_window.c:1445
#9  0x000000000073ddb8 in run_944059_2648699161 ()
    at /.../NimGui/examples/nimcache/NimGui_test_gui.c:8496
#10 0x00000000007473b8 in test_guiInit000 ()
    at /.../NimGui/examples/nimcache/NimGui_test_gui.c:10902
#11 0x0000000000746edb in NimMainInner ()
    at /.../NimGui/examples/nimcache/NimGui_test_gui.c:10835
#12 0x0000000000746f22 in NimMain ()
    at /.../NimGui/examples/nimcache/NimGui_test_gui.c:10843
#13 0x0000000000746f6e in main ()
    at /.../NimGui/examples/nimcache/NimGui_test_gui.c:10850
```

**Comment by Parashurama** [comment] 2016-05-25 10:58
see C code for split
``` C
typedef NU8 xvalign885010;
typedef NU8 xhalign885008;
struct TY885077 {
xvalign885010 Field0;
xhalign885008 Field1;
};

N_NIMCALL(TY885077, split_885074_2801727210)(xanchor885012 x0) {
	TY885077 result0;
	nimfr("split", "constants.nim")
	memset((void*)(&result0), 0, sizeof(result0));
	nimln(70, "constants.nim");
	result0.Field0 = ((xvalign885010) ((NU)(((NU) (x0)) & Componentsecond_885057_2801727210)));
	nimln(71, "constants.nim");
	result0.Field1 = ((xhalign885008) ((NU)(((NU) (x0)) & Componentfirst_885058_2801727210)));
	popFrame();
	return result0;
}
```

**Comment by Parashurama** [comment] 2016-05-25 11:43
the split proc is called from this function
```nim
proc SetMinMaxDialogOffsets(anchor: xAnchor, screen: Widget, group, m_group: Widget) : (int, int, int, int) =
    let width = screen.width
    let height = screen.height
    let kanchor = anchor.split()

    var min_y, max_y, min_x, max_x: int

    if   kanchor[0] == VALIGN_TOP:
        min_y = -height + group.height
        max_y = 0

    elif kanchor[0] == VALIGN_CENTER:
        min_y = -height div 2 + group.height div 2
        max_y =  height div 2 - m_group.height div 2
    else: # VALIGN_BOTTOM
        min_y = 0
        max_y = height - group.height

    if   kanchor[1] == HALIGN_LEFT:
        min_x = 0
        max_x = width-group.width
    elif kanchor[1] == HALIGN_CENTER:
        min_x = -width div 2 + group.width div 2
        max_x =  width div 2 - m_group.width div 2
    else: # HALIGN_RIGHT
        min_x = -width + group.width
        max_x = 0

    return (min_x, min_y, max_x, max_y)
```
which generate this code
```C

N_NIMCALL(TY772077, Setminmaxdialogoffsets_971201_3298800013)(xanchor885012 anchor0, WidgetHEX3Aobjecttype934003* screen0, WidgetHEX3Aobjecttype934003* group0, WidgetHEX3Aobjecttype934003* mgroup0) {
	TY772077 result0;
	NI width0;
	NI height0;
	TY885077 kanchor0;
	NI miny0;
	NI maxy0;
	NI minx0;
	NI maxx0;
	nimfr("SetMinMaxDialogOffsets", "dialog.nim")
{	memset((void*)(&result0), 0, sizeof(result0));
	nimln(1164, "dialog.nim");
	width0 = (*screen0).width;
	nimln(1165, "dialog.nim");
	height0 = (*screen0).height;
	nimln(1168, "dialog.nim");
	kanchor0 = split_885074_2801727210(anchor0);
	miny0 = (NI)0;
	maxy0 = (NI)0;
	minx0 = (NI)0;
	maxx0 = (NI)0;
	nimln(1172, "dialog.nim");
	{
		NI TMP4335;
		if (!(kanchor0.Field0 == ((xvalign885010) 12))) goto LA3;
		nimln(1173, "dialog.nim");
		if (height0 == (IL64(-9223372036854775807) - IL64(1))) raiseOverflow();
		TMP4335 = addInt(((NI64)-(height0)), (*group0).height);
		miny0 = (NI)(TMP4335);
		nimln(1174, "dialog.nim");
		maxy0 = ((NI) 0);
	}
	goto LA1;
	LA3: ;
	{
		NI TMP4336;
		NI TMP4337;
		NI TMP4338;
		NI TMP4339;
		NI TMP4340;
		NI TMP4341;
		nimln(1176, "dialog.nim");
		if (!(kanchor0.Field0 == ((xvalign885010) 8))) goto LA6;
		nimln(1177, "dialog.nim");
		if (height0 == (IL64(-9223372036854775807) - IL64(1))) raiseOverflow();
		TMP4336 = divInt(((NI64)-(height0)), ((NI) 2));
		TMP4337 = divInt((*group0).height, ((NI) 2));
		TMP4338 = addInt((NI)(TMP4336), (NI)(TMP4337));
		miny0 = (NI)(TMP4338);
		nimln(1178, "dialog.nim");
		TMP4339 = divInt(height0, ((NI) 2));
		TMP4340 = divInt((*mgroup0).height, ((NI) 2));
		TMP4341 = subInt((NI)(TMP4339), (NI)(TMP4340));
		maxy0 = (NI)(TMP4341);
	}
	goto LA1;
	LA6: ;
	{
		NI TMP4342;
		nimln(1180, "dialog.nim");
		miny0 = ((NI) 0);
		nimln(1181, "dialog.nim");
		TMP4342 = subInt(height0, (*group0).height);
		maxy0 = (NI)(TMP4342);
	}
	LA1: ;
	nimln(1183, "dialog.nim");
	{
		NI TMP4343;
		if (!(kanchor0.Field1 == ((xhalign885008) 1))) goto LA11;
		nimln(1184, "dialog.nim");
		minx0 = ((NI) 0);
		nimln(1185, "dialog.nim");
		TMP4343 = subInt(width0, (*group0).width);
		maxx0 = (NI)(TMP4343);
	}
	goto LA9;
	LA11: ;
	{
		NI TMP4344;
		NI TMP4345;
		NI TMP4346;
		NI TMP4347;
		NI TMP4348;
		NI TMP4349;
		nimln(1186, "dialog.nim");
		if (!(kanchor0.Field1 == ((xhalign885008) 2))) goto LA14;
		nimln(1187, "dialog.nim");
		if (width0 == (IL64(-9223372036854775807) - IL64(1))) raiseOverflow();
		TMP4344 = divInt(((NI64)-(width0)), ((NI) 2));
		TMP4345 = divInt((*group0).width, ((NI) 2));
		TMP4346 = addInt((NI)(TMP4344), (NI)(TMP4345));
		minx0 = (NI)(TMP4346);
		nimln(1188, "dialog.nim");
		TMP4347 = divInt(width0, ((NI) 2));
		TMP4348 = divInt((*mgroup0).width, ((NI) 2));
		TMP4349 = subInt((NI)(TMP4347), (NI)(TMP4348));
		maxx0 = (NI)(TMP4349);
	}
	goto LA9;
	LA14: ;
	{
		NI TMP4350;
		nimln(1190, "dialog.nim");
		if (width0 == (IL64(-9223372036854775807) - IL64(1))) raiseOverflow();
		TMP4350 = addInt(((NI64)-(width0)), (*group0).width);
		minx0 = (NI)(TMP4350);
		nimln(1191, "dialog.nim");
		maxx0 = ((NI) 0);
	}
	LA9: ;
	nimln(1193, "dialog.nim");
	result0.Field0 = minx0;
	result0.Field1 = miny0;
	result0.Field2 = maxx0;
	result0.Field3 = maxy0;
	goto BeforeRet;
	}BeforeRet: ;
	popFrame();
	return result0;
}
```

**Comment by Parashurama** [comment] 2016-05-25 11:50
There is something clearly wrong.
```nim

when true:
    # something like this crashes
    proc split*(x: xAnchor): tuple[valign:xValign, halign:xHalign] =
        ## split anchor into its components (valign, halign)
        let k0 = xValign(x.uint and COMPONENT_SECOND.uint)
        let k1 = xHalign(x.uint and COMPONENT_FIRST.uint)
        result = (k0, k1)

    # called in SetMinMaxDialogOffsets
    let kanchor = anchor.split()

when true:
    # but this doesn't
    proc split*(x: xAnchor): tuple[valign:xValign, halign:xHalign] =
        ## split anchor into its components (valign, halign)
        let k0 = xValign(x.uint and COMPONENT_SECOND.uint)
        let k1 = xHalign(x.uint and COMPONENT_FIRST.uint)
        result = (k0, k1)

    # called in SetMinMaxDialogOffsets
    var kanchor: tuple[valign:xValign, halign:xHalign]
    anchor.split(kanchor)


    # it doesn't either
    proc split*(x: xAnchor; k0: var xValign; k1: var xHalign)  =
        ## split anchor into its components (valign, halign)
        k0 = xValign(x.uint and COMPONENT_SECOND.uint)
        k1 = xHalign(x.uint and COMPONENT_FIRST.uint)

    # called in SetMinMaxDialogOffsets
    var kanchor: tuple[valign:xValign, halign:xHalign]
    anchor.split(kanchor.valign, kanchor.halign)

```

**Comment by Parashurama** [comment] 2016-05-25 13:49
The issue seems to be with the TinyCC compiler.
Here is a pure C file mimicking Nim frame system in debug mode which crash when using TCC, but not gcc or clang. [see gist](https://gist.github.com/Parashurama/77db05d4969d28c5eb36db9d4f648384)

I will try to resolve the problem with the tinycc-devel mailing list.

**Comment by cheatfate** [comment] 2016-05-25 15:25
@Parashurama looks like TCC (for some reason) could not obtain proper size of your structure. In assembly code i see it wants to memcpy for only 2 bytes...

**Comment by cheatfate** [comment] 2016-05-25 15:34
@Parashurama looks like this commit already patched your issue
[http://repo.or.cz/tinycc.git/commit/50899e30abf3cbd71a09ecc03b2e172f6ba5d4f4](http://repo.or.cz/tinycc.git/commit/50899e30abf3cbd71a09ecc03b2e172f6ba5d4f4)

**Comment by Parashurama** [comment] 2016-05-25 17:11
I think it does, but it triggers a far more annoying crash.
Somehow the 
STRING_LITERAL(TMP5430, "", 0); 
is corrupted and its length become  something like -552100758919673012,
triggering a crash in memcpy.

**Comment by Araq** [comment] 2016-05-31 10:25
Duplicate of #3719.

**Closed by Araq** 2016-05-31 10:25 UTC
