### ISSUE TITLE
Get rid of the "pragmas are only allowed in the header of a proc" error

### ISSUE THREAD

**Issue by dom96** [nim-lang/Nim#3182] opened 2015-08-03 19:58 UTC
This error stops me from forward declaring async procedures.

Workaround for async procs:

```nim
proc forward(): Future[T] = ...

async:
  proc forward() = 
    await foobar()
```

**Comment by Araq** [comment] 2015-08-03 20:11
Already reported by you.

**Comment by dom96** [comment] 2015-08-03 20:25
Where?

**Comment by dom96** [comment] 2015-08-03 20:27
I'm going to keep this open until you or I can find where else I reported this.

**Comment by Araq** [comment] 2015-08-05 17:35
duplicate of #1970.

**Closed by Araq** 2015-08-05 17:35 UTC
