### ISSUE TITLE
winlean.nim: DWORD* = int32; should be uint32

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/Nim#9848] opened 2018-12-03 22:06 UTC
/cc @dom96 
reference: https://msdn.microsoft.com/en-us/library/cc230318.aspx
> A DWORD is a 32-bit unsigned integer (range: 0 through 4294967295 decimal). Because a DWORD is unsigned, its first bit (Most Significant Bit (MSB)) is not reserved for signing.

originally reported here https://github.com/nim-lang/Nim/pull/9846#discussion_r238438075 by @data-man

**Comment by data-man** [comment] 2018-12-04 12:49
From MinGW:
```C
/* Target specific macro replacement for type "long".  In the Windows API,
   the type long is always 32 bit, even if the target is 64 bit (LLP64).
   On 64 bit Cygwin, the type long is 64 bit (LP64).  So, to get the right
   sized definitions and declarations, all usage of type long in the Windows
   headers have to be replaced by the below defined macro __LONG32. */
#ifndef __LP64__	/* 32 bit target, 64 bit Mingw target */
#define __LONG32 long
#else			/* 64 bit Cygwin target */
#define __LONG32 int
#endif
```
```C
typedef unsigned __LONG32 DWORD;
```

**Comment by ringabout** [comment] 2021-03-29 05:10
Duplicate of #12327

**Closed by ringabout** 2021-03-29 05:10 UTC
Labels: OS/Arch specific
