### ISSUE TITLE
Parallel statement: distinct generic conversion compiler crash

### ISSUE THREAD

**Issue by mratsim** [nim-lang/Nim#9497] opened 2018-10-24 21:03 UTC
For some reason distinct generic conversion crashes the compiler in a parallel statement.
using distinctBase works though (maybe due to it generating fresh nim idents)

Test case:

```Nim
# Compute PI in an inefficient way
import strutils, math, threadpool, sugar
{.experimental: "parallel".}

type Foo[T] = distinct ptr T

proc term(k: float): float = 4 * math.pow(-1, k) / (2*k + 1)

proc pi[T: SomeNumber](n: T): float =
  var ch = newSeq[float](n+1)
  var foo: Foo[int]
  parallel:
    for k in 0..ch.high:
      let bar = (ptr int)(foo) # internal error: invalid kind for firstOrd(tyGenericBody)
      let baz = distinctBase(Foo[int])(foo) # Works

      ch[k] = spawn term(float(k))
  for k in 0..ch.high:
    result += ch[k]

echo formatFloat(pi(5000))
```

**Comment by krux02** [comment] 2018-11-08 11:08
I can't reproduce the crash. Can you verify it still exists on devel branch.

**Comment by mratsim** [comment] 2018-11-08 17:47
No it doesn't exist anymore. I'm not too sure how to add parallel tests to testament otherwise we can close this.

**Comment by krux02** [comment] 2018-11-08 18:03
I close it, because the issue doesn't exist anymore. I am sorry I can't help you with the test right now, if you find a way a PR for crucial functionality is always welcome. Maybe @Araq can help you more.

**Closed** 2018-11-12 08:41 UTC
Labels: Crash, Distinct Types, Generics, Not reproduced, Threads
