### ISSUE TITLE
Exit code 139 during compilation

### ISSUE THREAD

**Issue by donaldcallen** [nim-lang/Nim#10565] opened 2019-02-05 14:43 UTC
Compiling the example, excerpted from a program I was attempting to develop in nim, causes an exit code 139 during compilation, which I believe indicates a seg-fault.

### Example

```
type
    Account = ref tuple
        name, guid:string
        value:float
        combined_flags:int
        children:seq[Account]

var root:Account

```

### Current Output
```
dca@franz:/tmp$ nim compile testit.nim
Hint: used config file '/home/dca/.choosenim/toolchains/nim-0.19.4/config/nim.cfg' [Conf]
Hint: system [Processing]
Hint: testit [Processing]
dca@franz:/tmp$ echo $?
139
```
No executable is produced.

### Expected Output

```
Normal completion of compilation, generating an executable.
```

### Additional Information

```
dca@franz:/tmp$ nim -v
Nim Compiler Version 0.19.4 [Linux: amd64]
Compiled at 2019-02-01
Copyright (c) 2006-2018 by Andreas Rumpf

git hash: b6d96cafc8bcad1f3d32f2910b25cd11a93f7751
active boot switches: -d:release
dca@franz:/tmp$
$ 
```
I also saw this problem with 19.2.
The system is up-to-date Arch Linux.

**Comment by Yardanico** [comment] 2019-02-05 16:32
That's an internal compiler error.
<details>
  <summary>`./koch temp c` traceback:</summary>

```
Traceback (most recent call last)
nim.nim(109)             nim
nim.nim(73)              handleCmdLine
cmdlinehelper.nim(92)    loadConfigsAndRunMainCommand
main.nim(174)            mainCommand
main.nim(78)             commandCompileToC
modules.nim(134)         compileProject
modules.nim(79)          compileModule
passes.nim(194)          processModule
passes.nim(86)           processTopLevelStmt
cgen.nim(1575)           myProcess
ccgstmts.nim(1187)       genStmts
ccgexprs.nim(2405)       expr
ccgexprs.nim(2198)       genStmtList
ccgstmts.nim(1187)       genStmts
ccgexprs.nim(2427)       expr
ccgstmts.nim(324)        genVarStmt
ccgstmts.nim(252)        genSingleVar
cgen.nim(462)            assignGlobalVar
ccgtypes.nim(857)        getTypeDesc
ccgtypes.nim(629)        getTypeDescAux
sighashes.nim(287)       hashType
sighashes.nim(217)       hashType
sighashes.nim(233)       hashType
sighashes.nim(267)       hashType
sighashes.nim(217)       hashType
sighashes.nim(233)       hashType
sighashes.nim(267)       hashType
sighashes.nim(217)       hashType
sighashes.nim(233)       hashType
sighashes.nim(267)       hashType
sighashes.nim(217)       hashType
(1874 calls omitted) ...
sighashes.nim(217)       hashType
sighashes.nim(233)       hashType
sighashes.nim(267)       hashType
sighashes.nim(217)       hashType
sighashes.nim(233)       hashType
sighashes.nim(267)       hashType
sighashes.nim(217)       hashType
sighashes.nim(233)       hashType
sighashes.nim(267)       hashType
sighashes.nim(217)       hashType
sighashes.nim(233)       hashType
sighashes.nim(267)       hashType
sighashes.nim(217)       hashType
sighashes.nim(233)       hashType
sighashes.nim(267)       hashType
sighashes.nim(217)       hashType
sighashes.nim(233)       hashType
sighashes.nim(267)       hashType
sighashes.nim(217)       hashType
sighashes.nim(233)       hashType
sighashes.nim(267)       hashType
sighashes.nim(217)       hashType
sighashes.nim(233)       hashType
sighashes.nim(267)       hashType
sighashes.nim(217)       hashType
sighashes.nim(233)       hashType
sighashes.nim(267)       hashType
sighashes.nim(217)       hashType
sighashes.nim(233)       hashType
sighashes.nim(267)       hashType
sighashes.nim(217)       hashType
sighashes.nim(233)       hashType
sighashes.nim(267)       hashType
sighashes.nim(217)       hashType
sighashes.nim(233)       hashType
sighashes.nim(267)       hashType
sighashes.nim(217)       hashType
sighashes.nim(233)       hashType
sighashes.nim(267)       hashType
sighashes.nim(217)       hashType
sighashes.nim(233)       hashType
sighashes.nim(267)       hashType
sighashes.nim(217)       hashType
sighashes.nim(233)       hashType
sighashes.nim(267)       hashType
sighashes.nim(217)       hashType
sighashes.nim(233)       hashType
sighashes.nim(267)       hashType
sighashes.nim(217)       hashType
sighashes.nim(233)       hashType
sighashes.nim(267)       hashType
sighashes.nim(217)       hashType
sighashes.nim(233)       hashType
sighashes.nim(267)       hashType
sighashes.nim(217)       hashType
sighashes.nim(233)       hashType
sighashes.nim(267)       hashType
sighashes.nim(217)       hashType
sighashes.nim(233)       hashType
sighashes.nim(267)       hashType
sighashes.nim(217)       hashType
sighashes.nim(233)       hashType
sighashes.nim(267)       hashType
sighashes.nim(217)       hashType
sighashes.nim(233)       hashType
sighashes.nim(267)       hashType
sighashes.nim(217)       hashType
sighashes.nim(233)       hashType
sighashes.nim(267)       hashType
sighashes.nim(217)       hashType
sighashes.nim(233)       hashType
sighashes.nim(267)       hashType
sighashes.nim(217)       hashType
sighashes.nim(233)       hashType
sighashes.nim(267)       hashType
sighashes.nim(217)       hashType
sighashes.nim(233)       hashType
sighashes.nim(267)       hashType
sighashes.nim(217)       hashType
sighashes.nim(233)       hashType
sighashes.nim(267)       hashType
sighashes.nim(217)       hashType
sighashes.nim(233)       hashType
sighashes.nim(267)       hashType
sighashes.nim(217)       hashType
sighashes.nim(233)       hashType
sighashes.nim(267)       hashType
sighashes.nim(217)       hashType
sighashes.nim(233)       hashType
sighashes.nim(267)       hashType
sighashes.nim(217)       hashType
sighashes.nim(233)       hashType
sighashes.nim(267)       hashType
sighashes.nim(173)       hashType
sighashes.nim(70)        &=
md5.nim                  md5Update
Error: call depth limit reached in a debug build (2000 function calls). You can change it with -d:nimCallDepthLimit=<int> but really try to avoid deep recursions instead.
FAILURE
```
</details>

**Comment by Yardanico** [comment] 2019-02-05 16:34
Ah, sorry, this is actually a duplicate of https://github.com/nim-lang/Nim/issues/5891

**Comment by Yardanico** [comment] 2019-02-05 16:36
I thought that this is a duplicate of https://github.com/nim-lang/Nim/issues/5891 at first, but 5891 seems to be fixed.

**Comment by Araq** [comment] 2019-02-06 08:18
That is invalid code that the compiler doesn't refuse properly, Instead use this code please:

```nim

type
    Account = ref object
        name, guid: string
        value: float
        combined_flags: int
        children: seq[Account]

var root :Account
```

**Comment by donaldcallen** [comment] 2019-02-06 14:04
Thank you for the response. 

Besides the compiler bug, an issue here is the whitespace before or after the colons (you do it both ways in your suggested code). 

There is a thread in the Nim forums called "Nim needs better documentation", asking for suggestions more specific than "the documentation needs to be better". 

One of the most common issues I find with the documentation is that it too often doesn't tell you what you need to know in the places you'd expect to find the information, turning writing Nim code into an unwanted research project. This issue is an example, I think. I have never seen anything that discusses the whitespace in tuple field definitions is not optional. It's possible that it's there and I've missed it, but I did make a real effort to find it, in the Tutorial, the Language Manual and Dominik Pacheta's book. And without the benefit of documentation, I would argue that most experienced programmers would guess that the colon is sufficient to separate the field-name from the type. That would be wrong, apparently, in the case of Nim, which makes the lack of documentation of this issue (assuming I am correct about this) all the more important.

**Comment by nc-x** [comment] 2019-02-06 14:35
@donaldcallen 
> whitespace in tuple field definitions is not optional
What are you referring to?
  
The difference between your code and Araq's code is that you are trying to use a tuple whereas you are supposed to be using an object as shown in Araq's code.

**Comment by donaldcallen** [comment] 2019-02-06 14:41
My error. I missed the key difference between my code and his. Thanks for pointing it out. But without spending more time researching this, where does it say in the documentation that tuples can't be self-referential, which I presume is the issue?

**Comment by nc-x** [comment] 2019-02-06 14:46
@donaldcallen 
https://nim-lang.org/docs/manual.html
Search for `In order to simplify structural type checking, recursive tuples are not valid:`

**Comment by narimiran** [comment] 2019-06-06 14:17
> That is invalid code that the compiler doesn't refuse properly

Compiler now refuses it properly: `Error: illegal recursion in type 'tuple[name: string, guid: string, value: float, combined_flags: int, children: seq[Account]]'`

**Closed by narimiran** 2019-06-06 14:17 UTC
Labels: Crash, Type sections, accepts invalid
