### ISSUE TITLE
from `module` import `function` as `othername`

### ISSUE THREAD

**Issue by toshikiohnogi** [nim-lang/Nim#8933] opened 2018-09-10 04:08 UTC
I always saying thank you for all developers.

This time, it is proposal for Nim usage improvement.
For me, at Python, I always use below writing method.
```
from rootmodule.childmodule import (
  function1 as othername_f1,
  function2 as othername_f2,
)
```

But at Nim, this writing method is not able to use.
Especially, to name other to function using `as` is not supported.

I wish this feature will be enable soon.

Thank you.

**Comment by narimiran** [comment] 2018-10-06 12:18
I would personally like to have this, but in some recent discussion (I can't find the link, sorry) @Araq said he doesn't like the idea to have a possibility to rename imported function.

In other words, this limitation is by design, and your proposal won't be implemented.

**Comment by Araq** [comment] 2018-10-09 13:18
And even worse, it would break several invariants in the compiler, producing hard-to-detect bugs.

**Closed by Araq** 2018-10-09 13:18 UTC
Labels: Feature
