### ISSUE TITLE
Casting from function returning a tuple fails

### ISSUE THREAD

**Issue by edubart** [nim-lang/Nim#4345] opened 2016-06-16 01:25 UTC
The following sample file fails when compiling:

```nim
proc f(): tuple[a, b: uint8] = (1'u8, 2'u8)

let a, b = f()
let c = cast[int](b)
```

Compile error:
> Error: execution of an external compiler program 'gcc -c  -w -Os  -I/opt/nim/lib -o /tmp/nim/nimcache/hello.o /tmp/nim/nimcache/hello.c' failed with exit code: 256
/tmp/nimcache/hello.c: In function ‘helloInit000’:
/tmp/nimcache/hello.c:77:2: error: aggregate value used where an integer was expected
  c_94012_617288324 = ((NI) (b_94011_617288324));

Nim version:
> Nim Compiler Version 0.14.2 (2016-06-11) [Linux: amd64]
Copyright (c) 2006-2016 by Andreas Rumpf
git hash: abf4e204c2f1a8a6915a8d32c970b5ce64f58e10
active boot switches: -d:release

**Comment by edubart** [comment] 2016-06-16 01:47
I've just noted that the code was missing parenthesis to correctly unpack the tuple, anyway I think nim must show a syntax error before trying to compile in gcc.

**Comment by Parashurama** [comment] 2016-06-16 07:41
The problem is that
```nim
let a, b = dummy()
```
is completely valid code. It means assign to *a* as well as *b*. 
It can be surprising considering that dummy() is called for each variable a, b, c...

**Comment by Araq** [comment] 2016-06-16 14:11
The compiler does check for 'cast' and the codegen emits a ``union``. Apparently it's not covering every case yet. but the code is perfectly fine and should produce nice garbage at runtime.

**Closed** 2016-07-19 13:40 UTC
Labels: Codegen, High Priority
