### ISSUE TITLE
koch: please bundle tests when building zip/installers

### ISSUE THREAD

**Issue by infinity0** [nim-lang/Nim#2129] opened 2015-02-14 19:09 UTC
I think this was just an oversight, but it would be nice to be able to run tests using just the "zip" bundle too.

**Comment by Araq** [comment] 2015-02-19 08:06
No, I left them out to save space. Failing tests are our problem, not our users' problem. What do you do when 10 out of 500 tests fail on your machine? Report them to us? Well thanks either we 

a) already know about failing tests, thank you very much.
b) cannot reproduce them since they are specific to your machine.

Seems a lose-lose situation which eats up all of our time.

**Comment by def-** [comment] 2015-02-19 11:02
Once the tests it could be a good idea to ship them to users. This could help discover problems with operating systems, C libraries, etc.

**Comment by infinity0** [comment] 2015-02-19 12:26
Why is (b) a lose-lose situation? Don't you want your code to be tested on machines you don't have access to? Even if you can't reproduce them personally, at least "the world" now knows there is a problem. Perhaps someone else will be able to fix them, possibly even the user that experienced the failure.

**Comment by Varriount** [comment] 2015-02-19 13:32
First off, it's not like files included in the zip generated by 'koch zip' are hardcoded - Look at 'compiler/installer.ini' to see a mapping of what files are included. If you need to repurpose the tool for your own use, just change that file.

Second, though including the test files in the zip may allow end-users to run the tests, any test results received are only really valid to development of Nim if the generated zip contains the latest code in the 'devel' branch of the repository (it does no good reporting errors for older code versions, when those errors may have been fixed in the 'devel' branch).  
Since 'koch zip' is primarily used to generate zipped distributions for a *stable* version of Nim, any test results generated from such a distribution would be invalid (or to be succint, if you want to help develop Nim, use a development version *of* Nim).

When we get snapshot builds of devel again, then there may be a case for this, but even then it's just a matter of manually applying a patch to 'compiler/installer.ini' to include the test files.

**Comment by infinity0** [comment] 2015-02-19 13:40
Including test code with stable code releases is a very standard thing and expected of good FOSS projects.

It is definitely not "useless" - there is **no guarantee** that it is fixed upstream, and even if it is, it is useful knowledge for everyone to know that bug X affects stable version Y, which is easier if the test code is included in the release. Also, the test code in the HEAD may not be applicable to the stable release - maybe APIs have changed, maybe even the contract of certain behaviours have changed (e.g. been fixed, even), etc etc etc...

**Comment by infinity0** [comment] 2015-02-19 13:48
Further, test code is not *merely* for the developers to improve the latest version of the project. It's useful documentation for users, to indicate what is *supposed* to work, to act as example code, to define behaviours, etc.

**Comment by Varriount** [comment] 2015-02-19 14:48
(Just a heads up, I changed the issue title to add Windows installers, since this affects them too)

> Including test code with stable code releases is a very standard thing and expected of good FOSS projects.
And why is this exactly? It seems like circular reasoning to me...

Anyway, I see the merit in your last 2 points. Since one of the original arguments against including the test suite was size, do you have any size comparisons of 'koch zip' with the test suite, vs 'koch zip' without?

At least with the Windows installer, depending on the size of the test suites, we can simply relegate them to an optional external package. Doing the same may or may not be acceptable for those who use the end-result of 'koch zip'.

**Comment by Araq** [comment] 2015-02-19 15:38
*Shrug* so make a PR that our precious tests are included in the zip, I don't care enough to fight it but it makes no sense whatsoever and when I install GCC it surely doesn't run its extensive test suite saving me energy and thus money.

**Comment by Araq** [comment] 2016-10-20 23:59
The zip ships with all the tests since quite some time now.

**Closed by Araq** 2016-10-20 23:59 UTC
Labels: Easy, Installation, Low Priority
