### ISSUE TITLE
type A = distinct A makes compiler enter infinite loop

### ISSUE THREAD

**Issue by ghost** [nim-lang/Nim#13008] opened 2020-01-01 11:35 UTC
```nim
type string = distinct string
# or: type int = distinct int
```

or more general:

```nim
# a.nim
type T = int
```

```nim
# b.nim
import a
type T = distinct T
```

tested on
```
Nim Compiler Version 1.1.1 [Windows: amd64]
Compiled at 2019-12-30
Copyright (c) 2006-2019 by Andreas Rumpf

git hash: defaf3b5a55381f15da8e8e5c976cc18d9ce18ac
active boot switches: -d:release
```

**Comment by ee7** [comment] 2020-12-19 08:19
The minimal case (reported in https://github.com/nim-lang/Nim/issues/16393):
```Nim
type
  A = distinct A
```

So we should edit the title of this issue - the problem isn't restricted to an "imported type".

**Comment by metagn** [comment] 2022-01-03 18:03
Duplicate of #5282?

**Closed** 2022-08-23 17:58 UTC
Labels: Type Sections, Regression, Crash, Distinct Types
