### ISSUE TITLE
strutils.toHex doesn't work with bytes

### ISSUE THREAD

**Issue by endragor** [nim-lang/Nim#4599] opened 2016-08-10 14:35 UTC
I'd expect the sample below to work, but it doesn't, because `toHex` accepts `BiggestInt` which is not compatible with `byte` type.

``` nim
import strutils

echo 23.byte.toHex(2)
# Error: type mismatch: got (byte, int literal(2))
# but expected one of:
# proc toHex(x: BiggestInt; len: Positive): string
# proc toHex[T](x: T): string
```

**Comment by krux02** [comment] 2016-08-11 11:39
Ths is not a bug. Byte is intentionally not automatically convertable to other integer types, it's purpose is to be used for untyped data. For one byte int use the `int8` type. With int8 your example will work.

**Comment by endragor** [comment] 2016-08-11 11:58
@krux02 
`byte` is an alias for `uint8`. I think it makes a lot of sense to expect `toHex` procedure to work with unsigned integers.

**Comment by krux02** [comment] 2016-08-11 14:20
https://github.com/nim-lang/Nim/issues/936

**Comment by mratsim** [comment] 2018-03-13 16:42
From an usage point of view, hex representation is often used when working with bytes.

I do not mind that there is no automatic converter between uint8/byte/char however a proc
```Nim
proc toHex*(s: openarray[byte]): string
```
is very useful anywhere you need to hash data.

**Comment by narimiran** [comment] 2019-05-22 12:03
> I'd expect the sample below to work, but it doesn't

> I think it makes a lot of sense to expect `toHex` procedure to work with unsigned integers.

You can use the other variant of `toHex` where you don't specify the length and it accepts any integer, both signed and unsigned:

```nim
import strutils

echo 23.byte.toHex()
```

> Byte is intentionally not automatically convertable to other integer types, it's purpose is to be used for untyped data.

Note that the original example will *not* work for any unsigned integer, not just `byte`.

----

Since `toHex` works with unsigned ints, I'm closing this.

**Closed by narimiran** 2019-05-22 12:03 UTC
Labels: Stdlib
