### ISSUE TITLE
Combined type class ignores first type when first type is object or tuple

### ISSUE THREAD

**Issue by Wh1teDuke** [nim-lang/Nim#19060] opened 2021-10-27 08:49 UTC
**Test**
```nim
# tuple here is ignored
type TupleOrObject = tuple or object
doAssert (1,2) is TupleOrObject       # false
doAssert RootObj() is TupleOrObject   # true

# object here is ignored
type ObjectOrTuple = object or tuple
doAssert (1,2) is ObjectOrTuple       # true
doAssert RootObj() is ObjectOrTuple   # false
```
**Workaround**
```nim
type TupleOrObject = tuple or tuple or object
```
- Seems to be an old bug.
- No issues for other types: `type SetOrSeq = set or seq` works as expected
***
```nim
>nim -v
Nim Compiler Version 1.7.1 [Linux: amd64]
Compiled at 2021-10-24
Copyright (c) 2006-2021 by Andreas Rumpf

git hash: 62701cd3b92677c2014cf70b1cf5a5ba6e0468bf
active boot switches: -d:release -d:danger
```

**Comment by shirleyquirk** [comment] 2022-08-01 23:31
duplicate of #8846

**Closed as completed** 2022-08-02 02:20 UTC
