### ISSUE TITLE
template invoked without () from template is not expanded

### ISSUE THREAD

**Issue by jibal** [nim-lang/Nim#14898] opened 2020-07-04 07:21 UTC
nim 1.2.0 on Windows 10

### Example
```nim
template t1: int = 0
template t2 = echo t1
t2
```

### Current Output
```
argh.nim(3, 1) Error: type mismatch: got <template (): int>
but expected one of:
proc echo(x: varargs[typed, `$`])
  first type mismatch at position: 1
  required type for x: varargs[typed]
  but expression 't1' is of type: template (): int
```

### Expected Output
```
0
```

### workaround
```nim
template t1: int = 0
template t2 = echo t1()
t2
```

### note
It doesn't have anything to do with `echo`. Anything that tries to use `t1` as a value within `t2` fails, e.g.

```nim
template t1: int = 0
template t2 = discard -t1
t2
```

**Comment by metagn** [comment] 2020-07-05 03:49
Duplicate of #13515

**Closed as completed** 2020-07-05 07:52 UTC
