### ISSUE TITLE
Error: nil dereference is not allowed

### ISSUE THREAD

**Issue by StefanSalewski** [nim-lang/Nim#17485] opened 2021-03-23 21:18 UTC
```nim
type
  O = ref object
    i: int

iterator t(o: O): int =
  if o != nil:
    yield o.i
  yield 0

proc m =
  for i in t(nil):
    echo i

m()
```

```
$ nim c t.nim 
Hint: used config file '/home/salewski/Nim/config/nim.cfg' [Conf]
Hint: used config file '/home/salewski/Nim/config/config.nims' [Conf]
....
/tmp/hhh/t.nim(11, 7) template/generic instantiation from here
/tmp/hhh/t.nim(7, 11) Error: nil dereference is not allowed
```

Unfortunately this blocks my current code from compiling. Well maybe a var with value nil will work tomorrow...

**Comment by ghost** [comment] 2021-03-23 21:41
Duplicate of https://github.com/nim-lang/Nim/issues/16076

**Closed as completed by ghost** 2021-03-23 21:41 UTC
