### ISSUE TITLE
Auto params behavior when grouped together should be documented

### ISSUE THREAD

**Issue by hlaaftana** [nim-lang/Nim#7728] opened 2018-04-29 14:33 UTC
```nim
proc concat(x, y: auto): auto = x & y

echo concat("abc", 'd') # abcd

proc addLens(x, y: seq[auto]): auto = x.len + y.len

when false: echo addLens(@[1, 2, 3], @["abc", "def"]) # doesn't work
echo addLens(@[1, 2, 3], @[4, 5, 6]) # 6

proc addLens2(x: seq[auto], y: seq[auto]): auto = x.len + y.len

echo addLens2(@[1, 2, 3], @["abc", "def"]) # 5
```

`x, y: auto` not being `x, y: T` and being `x: T, y: U` here should be documented, as it is easy to assume the first from how other types behave, and assuming so can cause unintended behavior.

**Comment by data-man** [comment] 2018-04-29 14:50
Auto is evil.

**Comment by metagn** [comment] 2020-04-20 13:34
To clarify the problems here:

1. `proc foo(x, y: auto)` should preferably become `proc foo[T](x, y: T)`, but instead it becomes `proc foo[T, U](x: T, y: U)`. On the contrary, `proc foo(x, y: seq[auto])` correctly becomes `proc foo[T](x, y: seq[T])`.
2. ~~`proc foo(x: seq, y: seq)` acts like `proc foo[T](x, y: seq[T])`, it should act like `proc foo[T, U](x: seq[T], y: seq[U])`.~~ This is intended behavior, [mostly meant for concepts](https://nim-lang.org/docs/manual.html#generics-implicit-generics). The solution is this:

```nim
proc addLens2(x: distinct seq, y: distinct seq): auto = x.len + y.len

echo addLens2(@[1, 2, 3], @["abc", "def"])
```

**Comment by metagn** [comment] 2021-02-10 18:05
Now that I see this, I don't think there's a good solution to this, nor that it's very unintuitive that `x, y: auto` becomes `x: T, y:  U`. I would say it's just a matter of documentation now, that `auto` does this when used directly for a parameter type.

**Comment by timotheecour** [comment] 2021-02-10 23:30
it is documented:

https://nim-lang.github.io/Nim/manual.html#types-auto-type
```
For parameters it currently creates implicitly generic routines:

proc foo(a, b: auto) = discard
Is the same as:

proc foo[T1, T2](a: T1, b: T2) = discard
```
(aka bind many, not bind once)

closing but feel free to re-open if you disagree

**Closed by timotheecour** 2021-02-10 23:30 UTC
Labels: Generics, Semcheck
