### ISSUE TITLE
let statement doesn't copy `seq` when refc is used

### ISSUE THREAD

**Issue by demotomohiro** [nim-lang/Nim#20108] opened 2022-07-29 04:18 UTC
### Example
```nim
proc test =
  var a = @[1]
  let b = a # a is not copied to b
  a[0] = 7
  doAssert a == @[7]
  doAssert b == @[1]  # Fails when `--mm:refc` is used

  var c = a # a is copied to c
  a[0] = 11
  doAssert a == @[11]
  doAssert c == @[7]

test()
```

### Current Output
```
$ ./seqcopy
/tmp/tmp/testnim/seqcopy.nim(13) seqcopy
/tmp/tmp/testnim/seqcopy.nim(6) test
/tmp/tmp/Nim/lib/std/assertions.nim(44) failedAssertImpl
/tmp/tmp/Nim/lib/std/assertions.nim(34) raiseAssert
/tmp/tmp/Nim/lib/system/fatal.nim(53) sysFatal
Error: unhandled exception: /tmp/tmp/testnim/seqcopy.nim(6, 12) `b == @[1]`  [AssertionDefect]
```

### Expected Output
All `doAssert` in the example code passes

### Additional Information
`seq` is copied in var statement.
`seq` is copied in let statement when `--mm:arc` or `--mm:orc` is used.

```
$ nim -v
Nim Compiler Version 1.7.1 [Linux: amd64]
Compiled at 2022-07-29
Copyright (c) 2006-2022 by Andreas Rumpf

git hash: 528b6d1c3f001944a7a7754c8884178e365e6871
active boot switches: -d:release
```

**Comment by ringabout** [comment] 2022-07-29 04:27
Duplicate of https://github.com/nim-lang/Nim/issues/2314

**Closed as completed** 2022-07-29 04:28 UTC

**Comment by demotomohiro** [comment] 2022-07-29 05:10
I'm sorry.
I tried to search existing issues before posting this issue but I couldn't find it.
That issue is the last entry of the result of searching open issue with "seq copy".

**Comment by ringabout** [comment] 2022-07-29 05:17
@demotomohiro No worries. I would not have found the existing issue if I didn't encounter the issue before.
