### ISSUE TITLE
cpp code gen bug in nim-glm

### ISSUE THREAD

**Issue by dom96** [nim-lang/Nim#6455] opened 2017-09-30 12:07 UTC
https://github.com/stavenko/nim-glm/blob/master/tests/quaternion.nim

```
nim cpp tests/quaternion.nim
```

```
CC: glm_mat
Error: execution of an external compiler program 'clang++ -c  -w  -I/Users/dom/projects/nim/lib -o /Users/dom/other_projects/nim-glm/tests/nimcache/glm_vec.o /Users/dom/other_projects/nim-glm/tests/nimcache/glm_vec.cpp' failed with exit code: 1

/Users/dom/other_projects/nim-glm/tests/nimcache/glm_vec.cpp:399:13: error: declaration of reference variable 'c' requires an initializer
                NIM_CHAR& c;
                          ^
/Users/dom/other_projects/nim-glm/tests/nimcache/glm_vec.cpp:400:7: error: C-style cast from rvalue to reference type 'NIM_CHAR &' (aka 'char &')
                c = (NIM_CHAR&)0;
                    ^~~~~~~~~~~~
2 errors generated.
```

**Comment by mratsim** [comment] 2017-10-07 10:05
Same issue in Arraymancer https://github.com/mratsim/Arraymancer/issues/91.

In Arraymancer, the codegen issue was introduced by replacing higher-order functions that accepts closures by templates that uses {.inject.}

**Comment by mratsim** [comment] 2017-10-07 11:19
Reproduced with a small test case

```Nim
import sequtils

import future


type CustomSeq[T] = object
  data: seq[T]


iterator mitems[T](cs: var CustomSeq[T]): var T {.inline,noSideEffect.} =
  for val in cs.data.mitems:
    yield val

template map[T](cs: CustomSeq[T], op:untyped): untyped =
  var dest = cs

  for x {.inject.} in dest.mitems:
    x = op
  dest

let a = CustomSeq[int](data: toSeq(1..10))

let b = a.map(x * 2)

echo b
```

Error:
```
Error: execution of an external compiler program 'clang++ -c  -w  -I/Users/tesuji/.choosenim/toolchains/nim-0.17.2/lib -o ./nimcache/arraymancer_issue_6455.o ./nimcache/arraymancer_issue_6455.cpp' failed with exit code: 1

./nimcache/arraymancer_issue_6455.cpp:260:5: error: declaration of reference variable 'x_AFjtzFoe8mPqwuVFjBw4hg_2' requires an initializer
NI& x_AFjtzFoe8mPqwuVFjBw4hg_2;
    ^~~~~~~~~~~~~~~~~~~~~~~~~~
./nimcache/arraymancer_issue_6455.cpp:538:8: error: declaration of reference variable 'val' requires an initializer
                        NI& val;
                            ^~~
./nimcache/arraymancer_issue_6455.cpp:540:10: error: C-style cast from rvalue to reference type 'NI &' (aka 'long long &')
                        val = (NI&)0;
                              ^~~~~~
3 errors generated.
```

There is no issue with the C backend

**Comment by mratsim** [comment] 2017-10-07 12:57
Probably duplicate of https://github.com/nim-lang/Nim/issues/4910 and https://github.com/nim-lang/Nim/issues/4048 "mitems doesn't work with C++"

**Comment by krux02** [comment] 2019-02-26 15:24
Just tested it. It works now.

**Closed by krux02** 2019-02-26 15:24 UTC
Labels: C++ codegen
