### ISSUE TITLE
instantiationInfo returns "???" when called outside of a template

### ISSUE THREAD

**Issue by lhupfeldt** [nim-lang/Nim#17482] opened 2021-03-23 20:02 UTC
```nim
echo instantiationInfo().filename


proc fn2(): string =
  instantiationInfo().filename

echo fn2()


template fn3(): string =
  instantiationInfo().filename

echo fn3()
```

shows:

    ???
    ???
    ppp.nim

I would expect, in order of most desirable:

1. instantiationInfo working outside of a template
2. a compilation error
3. an exception

Returning "???" does not make sense to me.

**Comment by ringabout** [comment] 2021-03-29 02:45
Duplicate of #11689

**Closed as completed** 2021-03-29 02:46 UTC
