### ISSUE TITLE
collect(newString) : cannot instantiate

### ISSUE THREAD

**Issue by HJarausch** [nim-lang/Nim#16372] opened 2020-12-16 15:37 UTC
collect_string_bug.nim(3, 17) template/generic instantiation of `collect` from here
/usr/lib/nim/pure/sugar.nim(185, 21) Error: cannot instantiate: 
```
  for i in 0 .. 2:
    "this does not work"
  ]'; got 1 typeof(s) but expected 0
```

when trying to compile
```
import sugar

var st = collect(newString) :
  for i in 0..2 :  "this does not work"
  
echo st
```
*```
$ nim -v
Nim Compiler Version 1.5.1 [Linux: amd64]
Compiled at 2020-12-16
Copyright (c) 2006-2020 by Andreas Rumpf

git hash: 9ef7c0182058141b81a41e32b699be8f2e42f3e9
active boot switches: -d:release

```

**Comment by timotheecour** [comment] 2020-12-17 04:45
duplicate of https://github.com/nim-lang/Nim/issues/16078 ?

**Comment by Araq** [comment] 2020-12-17 10:06
duplicate of #16078

**Closed as completed by Araq** 2020-12-17 10:06 UTC
Labels: Standard Library
