### ISSUE TITLE
Mutually recursive types involving proc arguments fail to compile

### ISSUE THREAD

**Issue by rbehrends** [nim-lang/Nim#2920] opened 2015-06-14 08:33 UTC
The following code fails to compile because C types aren't generated in the correct order. Using `var x: B` instead works, as well as introducing references in the cycle (e.g. by making `B` a `{.byref.}` type, making the `b` argument a `var` parameter, or using `ref object` instead of `object`).

```nim
type
  A = object
    p: proc(b: B)
  B = object
    a: A

var x: A
```

**Comment by yglukhov** [comment] 2015-06-18 10:51
Duplicate of #2823?

**Comment by Araq** [comment] 2015-07-01 01:56
Duplicate of #2823.

**Closed by Araq** 2015-07-01 01:56 UTC
Labels: Codegen
