### ISSUE TITLE
`ProveInit` warning for `result` does not account for `noreturn` calls

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/Nim#16735] opened 2021-01-16 07:07 UTC
Note: both examples in this issue are not good, see examples in the comments.

### Example 1: `while true` not
reduced from fusion/btreetable `[]` which gives lots of `ProveInit` warnings in CI:
```nim
proc `[]`*[A, B](t: var Table[A, B]; x: A): var B =
  var a =
    if t.root.isNil: Node[A,B](m: 0, p0: nil)
    else: t.root
  while true:
    var r = binarySearch(x, a)
    if (r < a.m) and eq(x, a.e[r].key):
      return a.e[r].val
    a = if r == 0: a.p0 else: a.e[r-1].p
    if a.isNil:
      when compiles($key): raise newException(KeyError, "key not found: " & $key)
      else: raise newException(KeyError, "key not found")
```

reduced:
```nim
when true:
  proc fn(a: var int): var int =
    while true:
      if true:
        return a
```

### Current Output
Warning: Cannot prove that 'result' is initialized

### Expected Output
no warning, the only way out of this proc initializes result

### workaround
there's no simple workarounds in complex cases (and workarounds make the code uglier / obfuscated, potentially increasing code size).
The simplest workaround would be:
```nim
when defined case10:
  proc fn(a: var int): var int =
    while true:
      if true:
        return a
    doAssert false
```
but it doesn't work, because of Example 2 below

### Example 2
this gives a `ProveInit` warning but shouldn't because doAssert is `noreturn`:
```nim
when true:
  proc fn(a: var int): var int =
    if a > 0: return a
    doAssert false
```

likewise with this, more explicit:
```nim
when true:
  proc abort() {.noreturn.} = doAssert false
  proc fn(a: var int): var int =
    if a > 0: return a
    abort()
```

### Additional Information
devel 1.5.1 78a99587a4ad8ad17a179a7992fcda8a6e10f25a

**Comment by metagn** [comment] 2022-08-18 06:44
Just encountered this, with the noreturn/raise case.

```nim
type Foo = object
  x: int

proc bar(foos: seq[Foo]): lent Foo =
  for f in foos:
    if f.x == 3:
      return f
  raise newException(ValueError, "foo with 3 not found")
```

**Comment by metagn** [comment] 2023-08-29 00:53
Simplest case (no relation to `if` or `while`):

```nim
type Foo = object
  x: int

proc bar(f: Foo): lent Foo = # or (f: var Foo): var Foo
  raise newException(ValueError, "error")
```

`strictDefs` equivalent:

```nim
{.experimental: "strictDefs".}

proc bar(): int =
  raise newException(ValueError, "error")
```

Also, the examples in the original issue are incorrect.

"Example 1" should give a warning, the noreturn parts are conditional, the proc should throw a final `KeyError` at the end.

For "Example 2", the `proc abort {.noreturn.} = doAssert false` version is correct, but in general `doAssert` is not `noreturn`, it should use `raiseAssert`.

**Comment by ringabout** [comment] 2023-08-29 01:37
Duplicate of https://github.com/nim-lang/Nim/issues/21615 ?

**Comment by metagn** [comment] 2023-08-29 01:44
Yes but this covers the `var T` case which might affect more code than `requiresInit` or `strictDefs`, should be the same parts of the compiler though

**Closed as completed** 2023-09-18 06:28 UTC
Labels: Effect Tracking
