### ISSUE TITLE
Downloading Nim 1.4.8 fails because a virus is detected

### ISSUE THREAD

**Issue by TheSimpleZ** [nim-lang/Nim#18156] opened 2021-06-02 17:09 UTC
Downloading nim from https://nim-lang.org/install_windows.html fails because Chrome detects a virus:
![image](https://user-images.githubusercontent.com/2884929/120522299-726b0a00-c3d5-11eb-924d-52c91788adf3.png)

I also tried using Scoop to install Nim. However, Windows Defender immediately detected a trojan when first running nimble. 
![image](https://user-images.githubusercontent.com/2884929/120523211-ef967f00-c3d5-11eb-8da2-9399743bebe2.png)

I'm running:
![image](https://user-images.githubusercontent.com/2884929/120523439-2bc9df80-c3d6-11eb-9651-0080e7daa6eb.png)
![image](https://user-images.githubusercontent.com/2884929/120523544-4e5bf880-c3d6-11eb-92be-2aaa847cd28c.png)

**Comment by timotheecour** [comment] 2021-06-02 17:52
close as duplicate of https://github.com/nim-lang/Nim/issues/17820?

**Closed as completed** 2021-06-03 11:38 UTC
