### ISSUE TITLE
nimsuggest: go to proc sometimes goes to signature although proc is implemented

### ISSUE THREAD

**Issue by tim-st** [nim-lang/Nim#7237] opened 2018-02-20 11:31 UTC
For scenarios when a signature of a proc is defined without implementation and additionally the implemented proc is defined too, and the order of the code is like the following
```
proc test(i: var int)

proc test2(i: var int) =
  i.test() # <-- click here on goto goes to line 1; more interesting would be line 6

proc test(i: var int) =
  i.inc(i)
```

`nimsuggest` will go to the signature definiton of the unimplemented proc although the implementation is defined below.
Especially for a bigger source code it's a bit annoying to manually search for the place where it's implemented.

Araq mentioned this can be changed in `semProcAux`.

**Comment by andreaferretti** [comment] 2018-02-20 12:45
Please, can you post this on https://github.com/nim-lang/nimsuggest/issues ?

**Comment by nc-x** [comment] 2018-02-20 13:36
duplicate of https://github.com/nim-lang/Nim/issues/6867 ?

**Comment by tim-st** [comment] 2018-02-20 15:17
Ok, sorry. Than it can get closed, I think. Thanks for finding this!

**Comment by andreaferretti** [comment] 2018-02-20 16:15
@tim-st Please, can you post this on https://github.com/nim-lang/nimsuggest/issues ? Nimsuggest has its own separate issue tracker - then we could close both issues here

**Comment by tim-st** [comment] 2018-02-20 18:41
@andreaferretti Ok, I've done it. Sry, that I didn't make this earlier, I thought the other one was the main one.

**Closed** 2018-02-20 18:56 UTC
