### ISSUE TITLE
ranges aren't checked when used as arguments for generic types

### ISSUE THREAD

**Issue by Tarmean** [nim-lang/Nim#4655] opened 2016-08-24 23:30 UTC
Sample:

``` nim
type Test[C: static[Natural]] = object
var a: Test[-1]
assert a.C == -1
```

Which I think should produce a compile time error...?

**Comment by ringabout** [comment] 2021-04-01 11:05
Duplicate of #16969

close in favour of #16969

**Closed by ringabout** 2021-04-01 11:05 UTC
Labels: Static[T]
