### ISSUE TITLE
Unable to generate destructor for generic type with ARC/ORC

### ISSUE THREAD

**Issue by dadadani** [nim-lang/Nim#17319] opened 2021-03-10 11:11 UTC
The Nim compiler is unable to compile code if ARC or ORC are used, but works fine with the default one.

### Example
```nim

type 
  BrokenObject = ref object
    brokenType: seq[int]

proc use(obj: BrokenObject) =
  discard

method testMethod(self: BrokenObject) {.base.} =
  iterator testMethodIter() {.closure.} =
    use(self)

  var nameIterVar = testMethodIter

let a = BrokenObject()
a.testMethod()
```

### Current Output
The program fails to compile
```
reproduce.nim(12, 21) Error: cannot generate destructor for generic type: seq[int]
```

### Expected Output
Should compile

### Additional Information
Tested on the latest nightly
```
Nim Compiler Version 1.5.1 [Linux: amd64]
Compiled at 2021-03-10
Copyright (c) 2006-2021 by Andreas Rumpf

git hash: 2f213db7eed7fb715b803559b38af4148cff02e1
active boot switches: -d:release
```

**Comment by cooldome** [comment] 2021-03-10 18:50
I had a look. The issue is that type BrokenObject first requires copy/destruction in the closure iterator, hence type bound operations are generated in lift lambda pass and lift lambda pass can't instantiate generics.

There is no easy fix for this one, large changes in compiler required.
I would say that we need to move detection pass of lambda lafiting into sempass2 and store it result in proc sym. Actual lamnda lifting should stay in transformation phase.
@Araq what is your opinion on how this should work in the future?

**Comment by Araq** [comment] 2021-03-10 18:51
> I would say that we need to move detection pass of lambda lafiting into sempass2 and store it result in proc sym.

We do this already, to some extend as a similar bug was recently fixed.

**Closed as completed** 2021-10-01 08:19 UTC
Labels: ARC/ORC Memory Management
