### ISSUE TITLE
Implicit conversion error int -> float

### ISSUE THREAD

**Issue by al6x** [nim-lang/Nim#18962] opened 2021-10-06 07:38 UTC
Code below produce wrong result. It should not compile as implicit int -> float conversion is not allowed.

### Example
```nim
import std/[sugar, sequtils]

func sum*[T](values: openarray[T], op: (T) -> float): float =
  for v in values: result += op(v)

echo @[@[1]].sum(l => l.len) # => 0.0, wrong, should not compile
```

```
nim -v
Nim Compiler Version 1.4.6 [MacOSX: amd64]
Compiled at 2021-05-06
Copyright (c) 2006-2020 by Andreas Rumpf

active boot switches: -d:release
```

**Comment by Araq** [comment] 2021-10-06 11:58
Duplicate of some other "severe" bug.

**Comment by ringabout** [comment] 2021-11-07 14:25
Duplicate of https://github.com/nim-lang/Nim/issues/15836

**Closed as completed by ringabout** 2021-11-07 14:25 UTC
