### ISSUE TITLE
Compiler has problems with source files longer than 65535 lines (16 bit line number)Think about the title, twice.

### ISSUE THREAD

**Issue by ggb-sw** [nim-lang/Nim#21535] opened 2023-03-17 01:31 UTC
### Description

I have an autogenerated source file (generated from a Perl script) that is over 151000 lines long, and while it compiles OK, whenever it does get a compile error the line number it reports is constantly line 65535.  This is an irritant since it makes debugging more complex but it is not a show stopper since the file does compile and executes correctly.

I am not going to try and post a 151000 line source file here as an example.

### Nim Version

Nim Compiler Version 1.4.2 [Linux: amd64]
Compiled at 2021-05-13
Copyright (c) 2006-2020 by Andreas Rumpf

**Comment by beef331** [comment] 2023-03-17 02:39
It's an optimization, file columns and line count are limited to 16bit integers.
Does make me wonder if there is any merit in changing it into a bitfield so that the first 21 bits are for line number and the remaining 10 are for column, given files are longer than they are wide typically.

**Comment by ghost** [comment] 2023-03-17 04:10
Closing as a duplicate of https://github.com/nim-lang/Nim/issues/15165 (also see https://github.com/nim-lang/Nim/issues/16652)

**Closed as not planned by ghost** 2023-03-17 04:10 UTC
