### ISSUE TITLE
getOccupiedMem() always returns 0 with threads:on and gc:arc on Linux

### ISSUE THREAD

**Issue by olliNiinivaara** [nim-lang/Nim#16210] opened 2020-12-01 16:27 UTC
getOccupiedMem() always returns 0 with gc:arc on Linux.

### Example
nim c -r --gc:orc memfail.nim

```nim
echo getOccupiedMem()
```

### Current Output
```
0
```

### Expected Output
```
61440
```
(without --gc:arc or --gc:orc switch)

### Additional Information

```bash
Nim Compiler Version 1.4.2 [Linux: amd64]
Operating System: Ubuntu 20.04.1 LTS
Kernel: Linux 5.4.0-54-generic
```

**Comment by Clyybber** [comment] 2020-12-01 19:04
Its correct and tested. Try
```nim
var s = @[1, 2, 3]
echo getOccupiedMem()
echo s
```
and you will see it output something other than zero. `0` is actually the expected output for your snippet :)

**Comment by olliNiinivaara** [comment] 2020-12-04 12:01
Indeed - the real culprit is that getOccupiedMem() does not work with gc:arc **and threads:on**. For example. the snippet above outputs 0.

I have modified the title of this issue accordingly.

**Comment by ringabout** [comment] 2022-01-25 11:49
Duplicate of https://github.com/nim-lang/Nim/issues/18494

Fixed by https://github.com/nim-lang/Nim/pull/18783

**Closed as completed by ringabout** 2022-01-25 11:49 UTC
Labels: ARC/ORC Memory Management
