### ISSUE TITLE
A combination trailing colon in proc definition and case expression crashes compiler

### ISSUE THREAD

**Issue by alaviss** [nim-lang/Nim#10677] opened 2019-02-15 01:28 UTC
I can't think of any meaningful title, sorry.

### Example (run with `nim check`)
```nim
proc a(b: int, c:) =
  var f: uint
  f = (case b
```

### Current Output
```
t.nim(1, 18) Error: expression expected, but found ')'
t.nim(2, 9) Error: expected: ')', but got: ':'
t.nim(3, 3) Error: invalid indentation
t.nim(2, 7) Error: undeclared identifier: 'f'
t.nim(3, 3) Error: invalid indentation
t.nim(4, 1) Error: expected: ')', but got: '[EOF]'
t.nim(3, 3) Error: 'f' cannot be assigned to
SIGSEGV: Illegal storage access. (Attempt to read from nil?)
```

### Expected Output
Not crashing

### Additional Information
```
Nim Compiler Version 0.19.9 [Linux: amd64]
Compiled at 2019-02-14
Copyright (c) 2006-2018 by Andreas Rumpf

git hash: 3520253a09cb8f32df834e619c7435092a370e9d
active boot switches: -d:release -d:useLinenoise
```

**Comment by krux02** [comment] 2019-02-15 10:50
The cause of this crash is here:

https://github.com/nim-lang/Nim/blob/b3ffbac93c1485ca9b7fd5f5d7ddd3fb9461d8e4/compiler/parser.nim#L697

That is the line that I would delete to fix it. This skip of the ``)`` token causes the second error ``t.nim(2, 9) Error: expected: ')', but got: ':'``, even though the closing ``)`` is clearly there. Then the compiler just goes wild to interpret that syntax somehow.

**Comment by Araq** [comment] 2019-02-15 11:03
But it crashes somewhere else, not in the parser and this line in the parser even has a comment explaining why it is required in the general case.

**Comment by krux02** [comment] 2019-02-15 11:13
yes it crashes in the sem checker because the parser passen an illegal AST to the sem checker.

**Comment by ghost** [comment] 2020-06-25 00:10
Current `nim check` output:
```
/home/dian/Things/Nim/ah.nim(1, 18) Error: expression expected, but found ')'
/home/dian/Things/Nim/ah.nim(2, 9) Error: expected: ')', but got: ':'
/home/dian/Things/Nim/ah.nim(3, 3) Error: invalid indentation
/home/dian/Things/Nim/ah.nim(2, 7) Error: undeclared identifier: 'f'
/home/dian/Things/Nim/ah.nim(3, 3) Error: invalid indentation
/home/dian/Things/Nim/ah.nim(3, 14) Error: expected: ')', but got: '[EOF]'
/home/dian/Things/Nim/ah.nim(3, 3) Error: 'f' cannot be assigned to
/home/dian/Things/Nim/ah.nim(1, 6) Error: implementation of 'ah.a(b: int, c: typedesc) [declared in /home/dian/Things/Nim/ah.nim(1, 6)]' expected
```

**Comment by ringabout** [comment] 2021-01-12 06:13
It works now.

I also made two PRs in case of regression
https://github.com/nim-lang/Nim/pull/16692
https://github.com/nim-lang/Nim/pull/16690

**Closed by ringabout** 2021-01-12 06:13 UTC
Labels: Nim check
