### ISSUE TITLE
--out option in .nimble file changes to --var at runtime

### ISSUE THREAD

**Issue by OldhamMade** [nim-lang/Nim#9172] opened 2018-10-03 18:41 UTC
Given a nimble file containing the following:
```
task release, "Build an optimised release":
  --hints:off
  --define:release
  --opt:speed
  --nilseqs: on
  --path:"src"
  --out:"mybinary"
  setCommand "c", "src/main.nim"
```
When I run `nimble release`
I see the following error:
```
command line(1, 2) Error: invalid command line option: '--var'
       Tip: 12 messages have been suppressed, use --verbose to show them.
     Error: nimble.nim(1106)         nimble
        ... nimble.nim(1092)         doAction
        ... nimble.nim(1066)         doAction
        ... nimble.nim(544)          execBackend
        ... tools.nim(28)            doCmd
        ... Execution failed with exit code 256
        ... Command: "/path/to/nim" c --noNimblePath --path:"~/.nimble/pkgs/tempfile-0.1.5" "--define:release" "--opt:speed" "--nilseqs:on" "--hints:off" "--var:"mybinary"" "--path:"src""  "src/main.nim"
```
This is with `v0.19.0`.

**Comment by OldhamMade** [comment] 2018-10-03 18:52
Ah, this seems to be a duplicate of #6011, apologies.

**Comment by kaushalmodi** [comment] 2018-10-04 01:29
Also, `--define:release` does not work in NimScript (only that specific define). I'd assume the same applies to .nimble too.

**Comment by alaviss** [comment] 2018-10-04 02:13
> `--define:release` does not work in NimScript (only that specific define)

It doesn't work when the script is run by the Nim compiler specifically (probably since `-d:release` logic is in [`nim.cfg`][0], which is parsed before the NimScript can define anything). Since `nimble` calls the `nim` compiler directly, I don't see why it wouldn't work.

[0]: https://github.com/nim-lang/Nim/blob/5ea0bf1940637bf9b29c6e85033dcdf1c7c79cad/config/nim.cfg#L55

**Comment by dom96** [comment] 2018-10-04 03:35
Duplicate of https://github.com/nim-lang/Nim/issues/6011

**Closed by dom96** 2018-10-04 03:35 UTC

**Comment by OldhamMade** [comment] 2018-10-04 06:45
@kaushalmodi please note that, in this case, it _is_ correct since we're using the C compiler. The result (when omitting `--out`) is as expected. However, happy for this ticket to be closed since the issue is the same regardless of backend.
