### ISSUE TITLE
JS: Bad codegen on passing var result call to call

### ISSUE THREAD

**Issue by yglukhov** [nim-lang/Nim#5275] opened 2017-01-24 09:02 UTC
```nim
var g = 0
proc a(): var int =
    return g

proc c(s: var int) =
    echo s # Prints undefined

c(a())
```
```
nim js -r test.nim
undefined
```

**Comment by andreaferretti** [comment] 2017-06-26 12:27
This may be related https://github.com/nim-lang/Nim/issues/5972

**Comment by Araq** [comment] 2017-06-29 20:52
That's not idiomatic Nim though, so low priority.

**Comment by Araq** [comment] 2017-07-09 05:06
This turned out to be a duplicate of #5608

**Closed by Araq** 2017-07-09 05:06 UTC
Labels: JS, Low Priority
