### ISSUE TITLE
Can't call local procs using dot syntax in a template from another module

### ISSUE THREAD

**Issue by dawkot** [nim-lang/Nim#14894] opened 2020-07-03 22:12 UTC
### Example

y.nim:
```nim
proc myProc(s: string) = discard

template myTemplate* =
  "".myProc
```

x.nim:
```nim
import y

myTemplate()
```

### Current Output

```
/home/user/programming/nim/x.nim(3, 11) template/generic instantiation of `myTemplate` from here
/home/user/programming/nim/y.nim(4, 13) Error: attempting to call undeclared routine: 'myProc'
```

### Possible Solution

* Change `"".myProc()` to `myProc("")`

### Additional Information

Tested with 1.2.4 and 4f6acf24ffde4c43ea9f8c954265d23312453b31

**Comment by alaviss** [comment] 2020-07-03 22:45
Possible duplicate of: #11733

**Comment by timotheecour** [comment] 2020-07-04 18:24
if we close this as duplicate we should add it as test case in top post of https://github.com/nim-lang/Nim/issues/11733

**Comment by metagn** [comment] 2024-09-23 13:08
Works since #22076 same as #11733 which had a test case added

**Closed as completed** 2024-12-09 07:11 UTC
Labels: works_but_needs_test_case
