### ISSUE TITLE
Add support for redirecting stdin,stdout, and stderr in osproc.startProcess

### ISSUE THREAD

**Issue by chrisheller** [nim-lang/Nim#6001] opened 2017-06-19 08:37 UTC
This is to match the functionality that Python's subprocess module supports; being able to supply alternate handles for stdin, stdout, and stderr when starting a child process.

**Comment by chrisheller** [comment] 2017-06-19 19:46
I used ``getRealHandle`` as the name to match what os.nim uses internally for the ``getFileInfo`` proc,  but sort of implies that the C level file handles are not "real".

**Comment by timotheecour** [comment] 2019-08-01 19:11
we should close as duplicate of https://github.com/nim-lang/Nim/issues/7999

**Comment by timotheecour** [comment] 2020-11-07 06:01
closing as duplicate of https://github.com/nim-lang/Nim/issues/7999

**Closed by timotheecour** 2020-11-07 06:01 UTC
Labels: Feature, Stdlib
