### ISSUE TITLE
Changes in typedesc reforms

### ISSUE THREAD

**Issue by andreaferretti** [nim-lang/Nim#8126] opened 2018-06-27 08:03 UTC
It seems that [this recent pull request](https://github.com/nim-lang/Nim/pull/7681) has introduced some breaking changes. In particular, I see a lot errors in my [emmy](https://github.com/unicredit/emmy) library, which uses concepts heavily.

A minimal example is the following. This used to pass:

```nim
type AdditiveMonoid* = concept x, y, type T
  x + y is T

assert(1 is AdditiveMonoid)
```

With the latest changes, the above fails, and has to be replaced with

```nim
type AdditiveMonoid* = concept x, y
  x + y is type(x)

assert(1 is AdditiveMonoid)
```

I am not sure whether this is intentional, and more generally what is the expected behaviour of `type T` inside a concept, but I think in case this breaking change should be documented

**Comment by kaushalmodi** [comment] 2018-06-27 18:21
`koch web` also failed for me while running this example from manual:

```nim
template typedef(name: untyped, typ: type) =
  type
    `T name`* {.inject.} = typ
    `P name`* {.inject.} = ref `T name`

typedef(myint, int)
var x: PMyInt
```

> Error: type expected

I think this is related.

**Comment by Vindaar** [comment] 2018-06-27 18:34
@kaushalmodi Hm, on https://github.com/nim-lang/Nim/commit/19ea3a70d2d6d404235e0f5250d6b681d56903a5 your example works fine for me.

**Comment by kaushalmodi** [comment] 2018-06-27 18:37
@Vindaar OK, I skipped the `koch web` from my custom build script. Now I am on bb23d903b6741c1697ac55f8ee54ff30a9b2cc49 and that same snippet works.. I think the problem is that `koch web` uses the `nim` binary in my PATH and not from the nim build directory.. Sorry for the false alarm related to that example.. looks like it failed build on d08b9eb, but at some point it got fixed.

**Comment by zah** [comment] 2018-06-27 20:37
The regression is not an intentional design change. I'll fix it next week.

**Comment by zah** [comment] 2018-06-27 20:59
A slightly less impactful workaround is the following:

``` nim
type AdditiveMonoid* = concept x, y
  type T = type(x)
  x + y is T
```

**Comment by Araq** [comment] 2018-08-06 09:45
It's blocking the 0.19 release, will be fixed "real soon now (TM)".

**Closed** 2018-08-21 20:14 UTC
Labels: Concepts, High Priority, Regression, Showstopper

**Comment by ryukoposting** [comment] 2019-01-16 01:30
Found something odd in 0.19 that might be related to this:
```nim
import macros

# this fails with 'error "not string!"'
macro appendBar(text: untyped, T: typedesc): untyped =
  if T is string:
    return nnkStmtList.newTree(
      nnkInfix.newTree(
        newIdentNode("&"),
        text,
        newLit("bar")
      )
    )
  else:
    error "not string!"

# this successfully appends "bar" to "foo"
macro appendBar2(text: untyped, T: typedesc): untyped =
  if getType(T).repr == "typeDesc[string]":
    return nnkStmtList.newTree(
      nnkInfix.newTree(
        newIdentNode("&"),
        text,
        newLit("bar")
      )
    )
  else:
    error "not string part 2!"

discard appendBar("foo", string)  #error "not string!"
discard appendBar2("foo", string) #works just fine
```
the `if T is ...` thing in `appendBar` worked as expected in 0.18.0, and stopped working as of 0.19.0.
0.19.2 shows the same behavior as 0.19.0. I am pretty new to Nim, so I'm not sure if this is intended or not, but it seems wrong to me.

**Comment by bluenote10** [comment] 2019-01-16 12:21
@ryukoposting Looks like you mean this issue: https://github.com/nim-lang/Nim/issues/10136

Should have been fixed a few days ago.
