### ISSUE TITLE
lent is unsafe: after #14447 you can modify variables with "items" loop for sequences

### ISSUE THREAD

**Issue by ghost** [nim-lang/Nim#14498] opened 2020-05-29 22:10 UTC
This code should fail at compile-time because you shouldn't be able to modify loop variables with ``items``

### Example
```nim
var a = @['a', 'b', 'c', 'd', 'e', 'f']

for x in items(a):
  x = 'c'

echo a
```

### Current Output
```
@['c', 'c', 'c', 'c', 'c', 'c']
```

### Expected Output
```
Error: 'x' cannot be assigned to
```

```
$ nim -v
Nim Compiler Version 1.3.5 [Linux: amd64]
Compiled at 2020-05-30
Copyright (c) 2006-2020 by Andreas Rumpf

git hash: 3105909f887f2240c2a7a7071b37e1253a70e3e2
active boot switches: -d:release
```

**Comment by timotheecour** [comment] 2020-05-29 23:18
I'm fine with reverting https://github.com/nim-lang/Nim/pull/14447, but the root cause is that lent is buggy; so users using their own iterators with `lent` would still be affected.

And it's not just for iterators: here's an example that doesn't use `iterator`

```nim
when true: # D20200529T162305
  type Foo = object
    v: int
    when defined(caseFooBig):
      z: array[3, int]

  proc bar(a: Foo): lent Foo = a
  # proc bar(a: Foo): Foo = a # ok, this will give errors

  proc fn(a: Foo) =
    bar(a) = Foo(v:100) # BUG: should give: Error: 'bar(a)' cannot be assigned to
    bar(a).v = bar(a).v + 10 # BUG: should give: Error: 'bar(a).v' cannot be assigned to
    # bar(a).v += 7 # ok: gives Error 'bar(a).v' is immutable, not 'var'
    echo a

  var a = Foo(v:1)
  fn(a)
  echo a # with -d:caseFooBig, gives: (v: 110, z: [0, 0, 0])
```

output:
```
(v: 10)
(v: 1)
```

with -d:caseFooBig
```
(v: 10, z: [0, 0, 0])
(v: 10, z: [0, 0, 0])
```

* presumably, compiler optimizes the `lent T` into a pass by value for small sizeof; that is probably fine, but it should follow the "as-if" rule and here it clearly fails
* `bar(a).v = 10` should not be legal: it should give ` 'bar(a).v' cannot be assigned to`

the bug is not the optimization `pass by value for small sizeof`, the bug is the 2nd point.
Interestingly, the compiler correctly catches this case: `bar(a).v += 7`

**Closed as completed** 2020-05-30 13:32 UTC
Labels: Showstopper
