### ISSUE TITLE
NimVM reuses default-value sequences, differing from Nim and from NimVM with explicit defaults

### ISSUE THREAD

**Issue by jrfondren** [nim-lang/Nim#20985] opened 2022-12-01 06:24 UTC
### Description

The following program with identical code blocks (but for `let` v. `const`) results in `a != b`. This isn't the case when the `group` and `groups` variables are explicitly initialized to `@[]`.

```nim
let a = block:
  var groups: seq[seq[int]]
  for i in 0 ..< 3:
    var group: seq[int]
    for j in 0 ..< 3:
      group.add j
    groups.add group
  groups

const b = block:
  var groups: seq[seq[int]]
  for i in 0 ..< 3:
    var group: seq[int]
    for j in 0 ..< 3:
      group.add j
    groups.add group
  groups

echo a
echo b
```

### Nim Version

Nim Compiler Version 1.6.10 [Linux: amd64]

and:

Nim Compiler Version 1.7.3 [Linux: amd64]
Compiled at 2022-12-01
Copyright (c) 2006-2022 by Andreas Rumpf

git hash: b36f5119ae3e4f450960a86ff77eaae4e9b05fcd

### Current Output

```text
@[@[0, 1, 2], @[0, 1, 2], @[0, 1, 2]]
@[@[0, 1, 2], @[0, 1, 2, 0, 1, 2], @[0, 1, 2, 0, 1, 2, 0, 1, 2]]
```

### Expected Output

```text
@[@[0, 1, 2], @[0, 1, 2], @[0, 1, 2]]
@[@[0, 1, 2], @[0, 1, 2], @[0, 1, 2]]
```

### Additional Information

Workaround: don't trust https://nim-lang.org/docs/manual.html#statements-and-expressions-var-statement in const blocks:

```nim
let a = block:
  var groups: seq[seq[int]] = @[]
  for i in 0 ..< 3:
    var group: seq[int] = @[]
    for j in 0 ..< 3:
      group.add j
    groups.add group
  groups

const b = block:
  var groups: seq[seq[int]] = @[]
  for i in 0 ..< 3:
    var group: seq[int] = @[]
    for j in 0 ..< 3:
      group.add j
    groups.add group
  groups

echo a
echo b
```

**Comment by metagn** [comment] 2022-12-01 07:08
Related/same https://github.com/nim-lang/Nim/issues/10938

**Comment by ringabout** [comment] 2022-12-14 12:10
Duplicate of https://github.com/nim-lang/Nim/issues/10938

**Closed as completed** 2022-12-14 12:10 UTC
