### ISSUE TITLE
Command invocation syntax not working with array literal / table constructor

### ISSUE THREAD

**Issue by jboy** [nim-lang/Nim#4482] opened 2016-07-13 08:55 UTC
I encountered the problem below, when I attempted to use [command invocation syntax](http://nim-lang.org/docs/manual.html#procedures-command-invocation-syntax) with [table constructor](http://nim-lang.org/docs/manual.html#statements-and-expressions-table-constructor)s.

```Nim
import tables

var t1_works = {1:2}.toTable
echo $t1_works

var t2_works = [(1,2)].toTable
echo $t2_works

var t3_works = toTable([(1,2)])
echo $t3_works

var t4_works = toTable({1:2})
echo $t4_works

var t5_fails = toTable [(1,2)]
echo $t5_fails
# totable.nim(15, 16) Error: expression 'totable' has no type (or is ambiguous)

var t6_fails = toTable {1:2}
echo $t6_fails
# totable.nim(19, 24) Error: undeclared identifier: '{}'
```

This test below demonstrates a few more failure cases that occur, even when the generic type has been specified precisely in the "command".  Is this a bug in Nim, or am I trying to do something invalid?

```Nim
proc tostring(arg: int): string = $arg
proc tostring(arg: openArray[int]): string = $ @arg
proc tostring(arg: openArray[(int, int)]): string = $ @arg

echo tostring(1)  # Success!
echo tostring 1  # Success!
echo 1.tostring  # Success!

echo tostring([1])  # Success!
echo tostring [1]  # Fail: tabcon.nim(10, 16) Error: type expected
echo [1].tostring  # Fail: tabcon.nim(11, 7) Error: type expected

echo tostring([(1,2)])  # Success!
echo tostring [(1,2)]  # Fail: tabcon.nim(14, 17) Error: type expected
echo [(1,2)].tostring  # Fail: tabcon.nim(15, 8) Error: type expected

echo tostring({1:2})  # Success!
echo tostring {1:2}  # Fail: tabcon.nim(18, 15) Error: undeclared identifier: '{}'
echo {1:2}.tostring  # Fail: tabcon.nim(19, 6) Error: undeclared identifier: '{}'
```

**Comment by Araq** [comment] 2016-07-15 09:26
Duplicate of https://github.com/nim-lang/Nim/issues/3898

**Closed by Araq** 2016-07-15 09:26 UTC
