### ISSUE TITLE
SIGSEGV when converting `lines` to closure iterator, most likely caused by defer

### ISSUE THREAD

**Issue by bluenote10** [nim-lang/Nim#5321] opened 2017-02-02 07:39 UTC
I was trying to convert the (inline) `lines` operator into a closure iterator like so:

    proc lineIter*(filename: string): iterator(): string =
      result = iterator(): string {.closure.} =
        for line in lines(filename):
          yield line

    var count = 0
    let iter = lineIter("/tmp/test_file")
    for line in iter():
      count += 1

This crashes with: `SIGSEGV: Illegal storage access. (Attempt to read from nil?)`

The same goes for rewriting the `lines` iterator directly as a closure iterator:

    iterator lineIter*(filename: string): string {.closure.} =
      var f = open(filename, bufSize=8000)
      defer: close(f)   # <-- commenting defer "solves" the problem
      var res = TaintedString(newStringOfCap(80))
      while f.readLine(res): yield res

    var count = 0
    for line in lineIter("/tmp/test_file"):
      count += 1
    echo count

Commenting out the `defer` avoids the crash, but probably leaves the file open.

Might be related to #4966

**Comment by Araq** [comment] 2017-02-02 11:43
Seems to be a duplicate of https://github.com/nim-lang/Nim/issues/4966 indeed.

**Closed** 2018-10-18 15:00 UTC
Labels: Crash
