### ISSUE TITLE
Compiler crash (because of json import?)

### ISSUE THREAD

**Issue by TiberiumN** [nim-lang/Nim#5757] opened 2017-04-25 19:32 UTC
This snippet fails to compile:
```nim
import json, marshal

type
  something = object
var data = "hello"
let rr = to[something](data)
```
Error:
```python
Hint: intsets [Processing]                                                                                                   
Traceback (most recent call last)                                                                                            
nim.nim(121)             nim
nim.nim(77)              handleCmdLine
main.nim(163)            mainCommand
main.nim(74)             commandCompileToC
modules.nim(240)         compileProject
modules.nim(180)         compileModule
passes.nim(215)          processModule
passes.nim(135)          processTopLevelStmt
sem.nim(536)             myProcess
sem.nim(508)             semStmtAndGenerateGenerics
semstmts.nim(1679)       semStmt
semexprs.nim(828)        semExprNoType
semexprs.nim(2365)       semExpr
semstmts.nim(486)        semVarOrLet
semexprs.nim(44)         semExprWithType
semexprs.nim(2281)       semExpr
semexprs.nim(747)        semIndirectOp
semexprs.nim(702)        semBracketedMacro
sem.nim(410)             semMacroExpr
vm.nim(1654)             evalMacroCall
system.nim(2637)         sysFatal
Error: unhandled exception: index out of bounds [IndexError]
FAILURE
```
However, if I remove `json` import, it doesn't fail

**Comment by dom96** [comment] 2017-04-25 19:41
Likely duplicate of https://github.com/nim-lang/Nim/issues/5751

**Closed** 2017-05-17 20:14 UTC
