### ISSUE TITLE
Passing tuple with proc leads to confusing errors

### ISSUE THREAD

**Issue by dom96** [nim-lang/Nim#7808] opened 2018-05-10 17:07 UTC
```nim
proc foo(x: (string, proc ())) =
  x[1]()

foo(
  ("foobar", proc () = echo("Hello!"))
)
```

```
/private/tmp/aporia/a8.nim(4, 4) Error: type mismatch: got <tuple of (string, proc (){.gcsafe, locks: 0.})>
but expected one of:
proc foo(x: (string, proc ()))
expression: foo(("foobar", proc () = echo(["Hello!"])))
```

Adding ``{.closure.}`` to the proc fixes it but there is no way you can figure that out from this error.

In addition, this {.closure.} isn't a problem when the procedure isn't in a tuple so it's doubly confusing. I guess there is some rules here to implicitly add the {.closure.} which do not apply when the proc is in a tuple. It would be nice if they did (as adding ``{.closure.}`` to ``=>`` isn't easy, I suppose alternatively we could add that pragma to all ``=>`` procedures).

**Comment by mratsim** [comment] 2018-05-11 10:42
This works for me:

```Nim
proc foo(x: (string, proc () {.nimcall.})) =
  x[1]()

foo(
  ("foobar", proc () {.nimcall.}= echo("Hello!"))
)
```

**Comment by PMunch** [comment] 2018-09-17 10:34
Why is it forcing `closure` anyways? I tried to declare a sequence of tuples with a procedure and pass it procedures declared in my module. But it failed since they aren't closures. Using @mratsims trick fixed the issue, but it's such a strange issue.

**Comment by mratsim** [comment] 2018-10-10 09:17
This might be related to https://github.com/nim-lang/Nim/issues/5647#issuecomment-310679862: type inference in unnamed tuples.

**Comment by timotheecour** [comment] 2019-07-05 22:42
should be closed as duplicate of https://github.com/nim-lang/Nim/issues/8305  ; as explained in #8305 the issue occurs when there's only 1 argument; it has nothing to do with passing a tuple or not.

with 1 arg you get:

```
 Error: type mismatch: got <tuple of (string, proc (){.gcsafe, locks: 0.})>
but expected one of:
proc foo(x: (string, proc ()))

expression: foo(("foobar", proc () = echo(["Hello!"])))
    foo(
```



if you add 1 more arg you get a more informative error message:
```nim
  proc foo(x: (string, proc ()), y: int) =
    x[1]()

  foo(
    ("foobar", proc () = echo("Hello!")), 12
  )
```

```
Error: type mismatch: got <tuple of (string, proc (){.gcsafe, locks: 0.}), int literal(12)>
but expected one of:
proc foo(x: (string, proc ()); y: int)
  first type mismatch at position: 1
  required type: tuple of (string, proc (){.closure.})
  but expression '("foobar", proc () = echo(["Hello!"]))' is of type: tuple of (string, proc (){.gcsafe, locks: 0.})

expression: foo(("foobar", proc () = echo(["Hello!"])), 12)
    foo(
```

**Comment by bluenote10** [comment] 2019-07-06 07:53
Related issue when the proc is wrapped in an array/seq instead of tuple: https://github.com/nim-lang/Nim/issues/10285

**Comment by timotheecour** [comment] 2019-07-06 18:03
correct, and I have a fix for it in the pipeline

**Closed** 2019-07-17 14:01 UTC
Labels: Error messages
