### ISSUE TITLE
yield invokes a call argument redundantly and confuses its tuple result

### ISSUE THREAD

**Issue by disruptek** [nim-lang/Nim#18761] opened 2021-08-27 18:20 UTC
### Example
```nim
var visits = 0

proc bar(): (int, int) =
  inc visits
  (visits, visits)

iterator foo(): (int, int) =
  yield bar()

for a, b in foo():
  assert a == b
```

### Current Output
`AssertionDefect: 1 != 2`

### Expected Output
```
```

### Possible Solution

Switch to Rust.

### Additional Information
Exists in 1.5, 1.4, 1.2, 1.0, 0.20, etc.

**Comment by ringabout** [comment] 2021-08-28 06:11
# Workaround
```nim
var visits = 0

proc bar(): (int, int) =
  inc visits
  (visits, visits)

iterator foo(): (int, int) =
  let tmp = bar()
  yield tmp

for a, b in foo():
  assert a == b
```

# Possible solution
Introduces a temp variable for routines kinds

## Before
```nim
a = bar()[0]
b = bar()[1]
```
## After
```nim
var :tmp_452984856 = bar()
a = :tmp_452984856[0]
b = :tmp_452984856[1]
```

**Comment by ringabout** [comment] 2021-08-28 09:07
Duplicate of https://github.com/nim-lang/Nim/issues/18347
Duplicate of #9778

**Comment by ringabout** [comment] 2021-08-28 09:10
So the workaround from #18347 still applies to this issue.

```nim
var visits = 0

proc bar(): (int, int) =
  inc visits
  (visits, visits)

iterator foo(): (int, int) =
  yield bar()

for t in foo():
  let (a, b) = t
  assert a == b
```

**Closed as completed by ringabout** 2021-08-28 09:10 UTC
Labels: Iterators

**Comment by hasanyasin** [comment] 2021-08-28 18:20
@xflywind The other issue (#18347) was closed because it was a duplicate of this. However, I don't understand why this one is closed? 

Isn't this a serious bug that would go silently and very hard to find in any application? @disruptek obviously caught a very good one here.  Is there any suggestion in the language manual that I missed regarding this issue and a workaround? Wouldn't you agree that this issue should stay open until addressed?
