### ISSUE TITLE
Incorrect possible `CatchableError` error reported when adding procedure to table

### ISSUE THREAD

**Issue by KonradStaniec** [nim-lang/Nim#18376] opened 2021-06-28 14:23 UTC
### Example
```nim
{.push raises: [Defect].}
type Call = proc (x: int): int {.gcsafe, raises: [Defect, CatchableError].}

type Bar* = object
  foo*: Table[string, Call]

proc barCal(b: var Bar, s: string, s1: Call) =
  #compiler complains that his line can throw CatchableError
  b.foo.add(s, s1)
```

### Current Output
```
Error: can raise an unlisted exception: CatchableError
```

### Expected Output
Compiles successfully

Removing `CatchableError` from raises list of `Call` makes everything compiling again so it is definitely not the the fact that `table.add(...) ` can throw.

###  Additional Information

```
$ nim -v
Nim Compiler Version 1.2.10 [MacOSX: amd64]
Compiled at 2021-06-22
Copyright (c) 2006-2020 by Andreas Rumpf

git hash: af69b3ceae16281efd45cbee4ce1bedd14282304

```

and

```
$ nim -v
Nim Compiler Version 1.4.8 [MacOSX: amd64]
Compiled at 2021-05-25
Copyright (c) 2006-2021 by Andreas Rumpf
```

**Comment by arnetheduck** [comment] 2021-06-28 18:38
same as https://github.com/nim-lang/Nim/issues/17382 ?

**Comment by Araq** [comment] 2021-06-28 18:43
Duplicate of #17382 and #17382 works as by Nim's spec. (Yes, yes, I know the spec is weird.) Will see what we can do here.

**Comment by arnetheduck** [comment] 2021-06-28 19:00
> works as by Nim's spec. (Yes, yes, I know the spec is weird.) 

ok, that's .. unusually weird, even by Nim standards ;) what's going on? ie there's no actuall call involved so why is the effect infectious?

**Comment by Araq** [comment] 2021-06-28 19:07
Quoting: https://nim-lang.org/docs/manual.html#effect-system-exception-tracking

1. Every indirect call via some proc type T is assumed to raise system.Exception (the base type of the exception hierarchy) and thus any exception unless T has an explicit raises list. However, if the call is of the form f(...) where f is a parameter of the currently analyzed routine it is ignored. The call is optimistically assumed to have no effect. Rule 2 compensates for this case.

2. Every expression of some proc type within a call that is not a call itself (and not nil) is assumed to be called indirectly somehow and thus its raises list is added to p's raises list.

Rules 1-2 ensure the following works:

```nim

proc noRaise(x: proc()) {.raises: [].} =
  # unknown call that might raise anything, but valid:
  x()

proc doRaise() {.raises: [IOError].} =
  raise newException(IOError, "IO")

proc use() {.raises: [].} =
  # doesn't compile! Can raise IOError!
  noRaise(doRaise)
```

So in many cases a callback does not cause the compiler to be overly conservative in its effect analysis.

**Comment by Araq** [comment] 2021-06-28 19:11
The idea here is to give us a form of "raises parametrization" for e.g. map and filter. I think we can easily do better when we use something like:

```nim

proc map[Elist](f: proc () {.raises: Elist.}) {.raises: Elist.}
# map raises what 'f' raises (if anything)

```

**Comment by arnetheduck** [comment] 2021-06-28 20:25
Sure, I understand why `noRaise` raises - because `x` is treated as a worst-case - but why does the example in #17382 not work? there's no actual call there, so what does `2` solve? in `map` and `filter` there are actual, real calls.

**Comment by Araq** [comment] 2021-06-29 05:47
Without rule 2 there would be a loophole in the effect analysis:

```nim

proc use() {.raises: [].} =
  # doesn't compile! Can raise IOError!
  noRaise(doRaise) # <-- the price of the flexibility is that we need to 
  # assume that `doRaise` will be called immediately
```

**Comment by arnetheduck** [comment] 2021-06-29 10:09
> Without rule 2 there would be a loophole in the effect analysis:

I don't see why - ie:

```
proc noRaise(x: proc()) {.raises: [].} =
  x() # This is already invalid: x _might_ raise so the compile error is _here_
```

The correct way would be:
```
proc noRaise(x: proc() {.raises: [].}) {.raises: [].} =
  x() # this works
```

**Comment by arnetheduck** [comment] 2021-06-29 10:12
conversely, this should work:

```
var glob: proc()
proc noRaise(x: proc()) {.raises: [].} =
  glob = x # this should work, no call, so no effect

```

**Comment by arnetheduck** [comment] 2021-06-29 10:15
more importantly, this is what doesn't make sense:

```
var glob: proc()
proc noRaise(x: proc()) {.raises: [].} =
  glob = x # this should work, no call, so no effect


import tables
var tbl: Table[string, proc()]

proc noRaise2(x: proc()) {.raises: [].} =
  tbl["test"] = x # this should work, no call, so no effect, but gives error

```

the two assignments are conceptually the same - there are no exceptions involved

**Comment by Araq** [comment] 2021-06-29 10:29
```nim

proc noRaise(x: proc()) {.raises: [].} =
  x() # This is already invalid: x _might_ raise so the compile error is _here_

```

Yet the spec allows this case (!) and then uses rule (2) to compensate for the unsoundness. 

> more importantly, this is what doesn't make sense

Yeah, well, when you design an effect system, "don't be smart".

**Comment by timotheecour** [comment] 2021-07-30 21:03
here's my analysis of this bug via successive reductions:

```nim
when defined case7a:
  # Error: add(b.foo, s, s1) can raise an unlisted exception: CatchableError
  import tables
  {.push raises: [Defect].}
  type Call = proc (x: int): int {.gcsafe, raises: [Defect, CatchableError].}

  type Bar* = object
    foo*: Table[string, Call]

  proc barCal(b: var Bar, s: string, s1: Call) =
    b.foo.add(s, s1)

when defined case7b:
  # ditto: unlisted exception
  import tables
  type Call = proc (x: int): int {.raises: [CatchableError].}
  type Bar* = object
    foo*: Table[string, Call]
  proc barCal(b: var Bar, s: string, s1: Call) {.raises: [].} =
    b.foo.add(s, s1)

when defined case7c:
  # ditto: unlisted exception
  import tables
  type Call = proc () {.raises: [ValueError].}
  type Bar* = object
    foo*: Table[string, Call]
  proc fn() = discard
  proc barCal(b: var Bar) {.raises: [].} =
    b.foo[""] = fn

when defined case7d:
  # ditto
  type Call = proc () {.raises: [ValueError].}
  type Bar* = object
    foo*: Call
  proc add2[T](a: T) = discard
  proc barCal(b: Bar) {.raises: [].} =
    b.foo.add2()

when defined case7e:
  # ditto
  type Call = proc () {.raises: [ValueError].}
  proc add2[T](a: T) = discard
  proc barCal(b: Call) {.raises: [].} =
    add2(b)

when defined case7f:
  # ditto
  type Call = proc () {.raises: [ValueError].}
  proc barCal(b: Call) {.raises: [].} =
    b()

when defined case7g:
  type Call1 = proc() # can raise anything, including ValueError
  type Call2 = proc() {.raises: [ValueError].} # can raise at most ValueError
  proc barCal(b1: Call1, b2: Call2) {.raises: [].} =
    b1() # ok
    b2() # BUG: compiler rejects with: Error: b2() can raise an unlisted exception: ValueError
```

as you can see in the final step, the problem is that calling a parameter of type "raise anything" is considered ok but calling a parameter of type "raises: [ValueError]" is considered not ok.

**Comment by Araq** [comment] 2021-07-31 04:47
> as you can see in the final step, the problem is that calling a parameter of type "raise anything" is considered ok but calling a parameter of type "raises: [ValueError]" is considered not ok.

That's one problem yes, and your proposal solves it. It's not the only problem, however.

**Closed as completed** 2021-09-02 10:10 UTC
Labels: Showstopper, Language Design, Effect Tracking
