### ISSUE TITLE
Recursive functions don't get marked as `XDeclaredButNotUsed` even if nothing external calls them

### ISSUE THREAD

**Issue by tersec** [nim-lang/Nim#22274] opened 2023-07-12 19:23 UTC
### Description

```nim
proc f(n: int) =
  if n == 0: f(1)
```

It's on the one hand true that there's a call to `f`, but that call is only from `f` itself -- that is, removing `f` entirely would have no effect on the rest of the code (assuming there's not an open/closed symbol/function overloading question, et cetera). `f` is, in fact, unused, unless something external calls it.

### Nim Version

```
Nim Compiler Version 1.6.14 [Linux: amd64]
Compiled at 2023-06-29
Copyright (c) 2006-2023 by Andreas Rumpf

active boot switches: -d:release
```

```
Nim Compiler Version 2.0.0 [Linux: amd64]
Compiled at 2023-07-12
Copyright (c) 2006-2023 by Andreas Rumpf

git hash: a9cf99270765dc806568aca93d0f2d59afda3491
active boot switches: -d:release
```

```
Nim Compiler Version 1.9.5 [Linux: amd64]
Compiled at 2023-07-12
Copyright (c) 2006-2023 by Andreas Rumpf

git hash: 9471b5f964395f9b4f4f673239d4375e1910bfaa
active boot switches: -d:release
```

### Current Output

```text
No XDeclaredButNotUsed hint
```

### Expected Output

```text
s.nim(1, 6) Hint: 'f' is declared but not used [XDeclaredButNotUsed]
```

**Comment by juancarlospaco** [comment] 2023-07-12 19:32
!nim c --hintAsError[XDeclaredButNotUsed]:on

```nim
proc f(n: int) = (if n == 0: f(1))
```

**Comment by Araq** [comment] 2023-07-16 05:24
It's not defined what "not used" means.

**Comment by usernameisnotavailablewhy** [comment] 2023-07-16 05:26
duplicate of https://github.com/nim-lang/Nim/issues/20264

**Comment by ringabout** [comment] 2023-07-17 01:29
Duplicate of https://github.com/nim-lang/Nim/issues/20264

**Closed as completed by ringabout** 2023-07-17 01:29 UTC
Labels: Low Priority
