### ISSUE TITLE
Error messages are misleading when filename is bad

### ISSUE THREAD

**Issue by def-** [nim-lang/Nim#2678] opened 2015-05-07 23:39 UTC
With this example code: http://nim-lang.org/docs/manual.html#parallel-spawn-spawn-statement

``` nimrod
import threadpool

proc processLine(line: string) =
  discard "do some heavy lifting here"

for x in lines("myinput.txt"):
  spawn processLine(x)
sync()
```

When you call the file `spawn.nim` (which happened at least to me and someone else), you will be greeted by a confusing error:

```
spawn.nim(7, 20) Error: expression 'processLine(x)' has no type (or is ambiguous)
```

Instead it would be great if the error could say something about `spawn` also being the filename.

**Comment by def-** [comment] 2017-07-15 21:45
No longer throws an error. If you rename the file to another dangerous name like `string.nim` you get another error:
```
string.nim(3, 24) Error: Error: ambiguous identifier: 'string' --use unknown.string or system.string
```
At least it suggests a fix, but not the explanation that `unknown.string` comes from the file being called `string.nim`.

**Comment by dom96** [comment] 2017-08-12 10:37
Duplicate of #4796.

**Closed by dom96** 2017-08-12 10:37 UTC
Labels: Error messages
