### ISSUE TITLE
False positive in duplicate import hint / DuplicateModuleImport

### ISSUE THREAD

**Issue by arnetheduck** [nim-lang/Nim#20907] opened 2022-11-24 09:47 UTC
### What happened?

```nim
from system/ansi_c import c_memcpy
from system/ansi_c import c_memchr
```

```
testit.nim(2, 1) Hint: duplicate import of 'ansi_c'; previous import here: testit.nim(1, 12) [DuplicateModuleImport]
```

these are two legitimately distinct imports - of course, if they imported the same function they should give a hint

### Nim Version

1.6.8

**Comment by Araq** [comment] 2022-11-24 16:13
True but the style we are after is:

```nim

from system/ansi_c import c_memcpy, c_memchr
```

**Comment by arnetheduck** [comment] 2022-11-24 16:15
> True but the style we are after is:

this is somewhat difficult to maintain, because often we do this style of imports in `when` sections - given that each import indeed contributes new symbols and not just repeats the same thing, it seems reasonable to want to keep them separate, sometimes.

**Comment by ringabout** [comment] 2023-03-11 03:40
Duplicate of https://github.com/nim-lang/Nim/issues/18762

**Closed as completed by ringabout** 2023-03-11 03:40 UTC
